function plotPyrNeuStimUpDownAlone_LongShortTr(pathAnal0, FRProfileMean1, timeStepRun, avgFRProfileNorm1, avgFRProfileNorm2,...
    avgFRProfile1, avgFRProfile2,title1)

    %% normalized
    %% order pyramidal neurons based on the peak firing rate after 0
    % and compare good non-stim with stim trials
    plotIndFRProfileCmp(timeStepRun,...
            avgFRProfileNorm1,...
            avgFRProfileNorm2,['Neuron no.'],...
            [title1 '_IndFRProfileNormFR0to1VsBefRunNeu_LS'],...
            pathAnal0,[],4,FRProfileMean1.indFRBefRun,...
            FRProfileMean1.indFR0to1)
         
    %% average profile 
    plotAvgFRProfileCmp(timeStepRun,...
            avgFRProfile1,...
            avgFRProfile2,...
            [title1 'FR Long/Short'],...
            [title1 '_FRProfileLongShort'],...
            pathAnal0,[0 3.5],'Time (s)');
        
end