function PyrRisedownBurst(taskSel,methodKMean)
% bursting probability for PyrUp and PyrDown neurons
    
    if(taskSel == 1) % including all the neurons
        pathAnal = 'Z:\Yingxue\Draft\PV\PyramidalIntInitPeak\';
    elseif(taskSel == 2) % including AL and PL neurons
        pathAnal = 'Z:\Yingxue\Draft\PV\PyramidalIntInitPeakALPL\';
    else
        pathAnal = 'Z:\Yingxue\Draft\PV\PyramidalIntInitPeakAL\';
    end
    if(exist([pathAnal 'initPeakPyrIntAllRec.mat']))
        load([pathAnal 'initPeakPyrIntAllRec.mat']);
    end
    
    if(taskSel == 1) % including all the neurons
        pathAnal0 = ['Z:\Yingxue\Draft\PV\PyramidalAlignedCtrlTr\' num2str(methodKMean) '\'];
    elseif(taskSel == 2) % including AL and PL neurons
        pathAnal0 = ['Z:\Yingxue\Draft\PV\PyramidalAlignedCtrlTrALPL\' num2str(methodKMean) '\'];
    else % AL neurons only
        pathAnal0 = ['Z:\Yingxue\Draft\PV\PyramidalAlignedCtrlTrAL\' num2str(methodKMean) '\'];
    end
    load([pathAnal0 'pyrAlignedAllRec_CtrlTr.mat']);
    
    PyrRiseBurst.idx = [];
    for i = 1:length(PyrRise.idxRise)
        idx = find(mod_CtrlTr1.task == PyrRise.task(i) &...
            mod_CtrlTr1.indRec == PyrRise.indRec(i) &...
            mod_CtrlTr1.indNeu == PyrRise.indNeu(i));
        PyrRiseBurst.idx = [PyrRiseBurst.idx idx];
    end
    PyrRiseBurst.fractBurst = mod_CtrlTr1.fractBurst(PyrRiseBurst.idx);
    PyrRiseBurst.numSpPerBurstMean = mod_CtrlTr1.numSpPerBurstMean(PyrRiseBurst.idx);
    PyrRiseBurst.burstMeanDire = mod_CtrlTr1.burstMeanDire(PyrRiseBurst.idx);
    PyrRiseBurst.burstMeanResultantLen = mod_CtrlTr1.burstMeanResultantLen(PyrRiseBurst.idx);
    PyrRiseBurst.phaseMeanDire = mod_CtrlTr1.phaseMeanDire(PyrRiseBurst.idx);
    PyrRiseBurst.phaseMeanDireH = mod_CtrlTr1.phaseMeanDireH(PyrRiseBurst.idx);
    PyrRiseBurst.phaseMeanResultantLen = mod_CtrlTr1.phaseMeanResultantLen(PyrRiseBurst.idx);
    
    PyrDownBurst.idx = [];
    for i = 1:length(PyrDown.idxDown)
        idx = find(mod_CtrlTr1.task == PyrDown.task(i) &...
            mod_CtrlTr1.indRec == PyrDown.indRec(i) &...
            mod_CtrlTr1.indNeu == PyrDown.indNeu(i));
        PyrDownBurst.idx = [PyrDownBurst.idx idx];
    end
    PyrDownBurst.fractBurst = mod_CtrlTr1.fractBurst(PyrDownBurst.idx);
    PyrDownBurst.numSpPerBurstMean = mod_CtrlTr1.numSpPerBurstMean(PyrDownBurst.idx);
    PyrDownBurst.burstMeanDire = mod_CtrlTr1.burstMeanDire(PyrDownBurst.idx);
    PyrDownBurst.burstMeanResultantLen = mod_CtrlTr1.burstMeanResultantLen(PyrDownBurst.idx);
    PyrDownBurst.phaseMeanDire = mod_CtrlTr1.phaseMeanDire(PyrDownBurst.idx);
    PyrDownBurst.phaseMeanDireH = mod_CtrlTr1.phaseMeanDireH(PyrDownBurst.idx);
    PyrDownBurst.phaseMeanResultantLen = mod_CtrlTr1.phaseMeanResultantLen(PyrDownBurst.idx);
    
    PyrRiseDownBurst.pRSFractBurst = ranksum(PyrRiseBurst.fractBurst,...
        PyrDownBurst.fractBurst);
    PyrRiseDownBurst.pRSNumSpPerBurstMean = ranksum(PyrRiseBurst.numSpPerBurstMean,...
        PyrDownBurst.numSpPerBurstMean);
    PyrRiseDownBurst.pRSBurstMeanDire = ranksum(PyrRiseBurst.burstMeanDire,...
        PyrDownBurst.burstMeanDire);
    PyrRiseDownBurst.pRSBurstMeanResultantLen = ranksum(PyrRiseBurst.burstMeanResultantLen,...
        PyrDownBurst.burstMeanResultantLen);
    PyrRiseDownBurst.pRSPhaseMeanDire = ranksum(PyrRiseBurst.phaseMeanDire,...
        PyrDownBurst.phaseMeanDire);
    PyrRiseDownBurst.pRSPhaseMeanDireH = ranksum(PyrRiseBurst.phaseMeanDireH,...
        PyrDownBurst.phaseMeanDireH);
    PyrRiseDownBurst.pRSPhaseMeanResultantLen = ranksum(PyrRiseBurst.phaseMeanResultantLen,...
        PyrDownBurst.phaseMeanResultantLen);
    
    PyrRiseDownBurst.meanFractBurst = [mean(PyrRiseBurst.fractBurst),...
        mean(PyrDownBurst.fractBurst)];
    PyrRiseDownBurst.meanNumSpPerBurstMean = [mean(PyrRiseBurst.numSpPerBurstMean),...
        mean(PyrDownBurst.numSpPerBurstMean)];
    PyrRiseDownBurst.meanBurstMeanDire = [mean(PyrRiseBurst.burstMeanDire),...
        mean(PyrDownBurst.burstMeanDire)];
    PyrRiseDownBurst.meanBurstMeanResultantLen = [mean(PyrRiseBurst.burstMeanResultantLen),...
        mean(PyrDownBurst.burstMeanResultantLen)];
    PyrRiseDownBurst.meanPhaseMeanDire = [mean(PyrRiseBurst.phaseMeanDire),...
        mean(PyrDownBurst.phaseMeanDire)];
    PyrRiseDownBurst.meanPhaseMeanDireH = [mean(PyrRiseBurst.phaseMeanDireH),...
        mean(PyrDownBurst.phaseMeanDireH)];
    PyrRiseDownBurst.meanPhaseMeanResultantLen = [mean(PyrRiseBurst.phaseMeanResultantLen),...
        mean(PyrDownBurst.phaseMeanResultantLen)];
    
    PyrRiseDownBurst.semFractBurst = [std(PyrRiseBurst.fractBurst)/sqrt(length(PyrRise.idxRise)),...
        std(PyrDownBurst.fractBurst)/sqrt(length(PyrDown.idxDown))];
    PyrRiseDownBurst.semNumSpPerBurststd = [std(PyrRiseBurst.numSpPerBurstMean)/sqrt(length(PyrRise.idxRise)),...
        std(PyrDownBurst.numSpPerBurstMean)/sqrt(length(PyrDown.idxDown))];
    PyrRiseDownBurst.semBurstMeanDire = [std(PyrRiseBurst.burstMeanDire)/sqrt(length(PyrRise.idxRise)),...
        std(PyrDownBurst.burstMeanDire)/sqrt(length(PyrDown.idxDown))];
    PyrRiseDownBurst.semBurstMeanResultantLen = [std(PyrRiseBurst.burstMeanResultantLen)/sqrt(length(PyrRise.idxRise)),...
        std(PyrDownBurst.burstMeanResultantLen)/sqrt(length(PyrDown.idxDown))];
    PyrRiseDownBurst.semPhaseMeanDire = [std(PyrRiseBurst.phaseMeanDire)/sqrt(length(PyrRise.idxRise)),...
        std(PyrDownBurst.phaseMeanDire)/sqrt(length(PyrDown.idxDown))];
    PyrRiseDownBurst.semPhaseMeanDireH = [std(PyrRiseBurst.phaseMeanDireH)/sqrt(length(PyrRise.idxRise)),...
        std(PyrDownBurst.phaseMeanDireH)/sqrt(length(PyrDown.idxDown))];
    PyrRiseDownBurst.semPhaseMeanResultantLen = [std(PyrRiseBurst.phaseMeanResultantLen)/sqrt(length(PyrRise.idxRise)),...
        std(PyrDownBurst.phaseMeanResultantLen)/sqrt(length(PyrDown.idxDown))];
    
    save([pathAnal 'PyrRiseDownBurst.mat'],'PyrRiseBurst','PyrDownBurst','PyrRiseDownBurst');
    
    colorSel = 0;
    plotBoxPlot(PyrRiseBurst.fractBurst,...
        PyrDownBurst.fractBurst,'Fract. burst',...
        'PyrRiseDown_FractBurst',pathAnal,[],PyrRiseDownBurst.pRSFractBurst,colorSel,[{'Rise'} {'Down'}]);
    
    plotBoxPlot(PyrRiseBurst.numSpPerBurstMean,...
        PyrDownBurst.numSpPerBurstMean,'Num. spikes per burst',...
        'PyrRiseDown_NumSpPerBurst',pathAnal,[1.5 3.5],PyrRiseDownBurst.pRSNumSpPerBurstMean,colorSel,[{'Rise'} {'Down'}]);
    
    plotBoxPlot(PyrRiseBurst.burstMeanDire/pi*180,...
        PyrDownBurst.burstMeanDire/pi*180,'Burst mean dire.',...
        'PyrRiseDown_BurstMeanDire',pathAnal,[],PyrRiseDownBurst.pRSBurstMeanDire,colorSel,[{'Rise'} {'Down'}]);
    
    plotBoxPlot(PyrRiseBurst.burstMeanResultantLen,...
        PyrDownBurst.burstMeanResultantLen,'Burst mean resultant length',...
        'PyrRiseDown_BurstMeanResultantLen',pathAnal,[],PyrRiseDownBurst.pRSBurstMeanResultantLen,colorSel,[{'Rise'} {'Down'}]);
    
    plotBoxPlot(PyrRiseBurst.phaseMeanDire/pi*180,...
        PyrDownBurst.phaseMeanDire/pi*180,'Theta mean dire.',...
        'PyrRiseDown_PhaseMeanDire',pathAnal,[],PyrRiseDownBurst.pRSPhaseMeanDire,colorSel,[{'Rise'} {'Down'}]);
    
    plotBoxPlot(PyrRiseBurst.phaseMeanDireH/pi*180,...
        PyrDownBurst.phaseMeanDireH/pi*180,'Theta mean dire. H',...
        'PyrRiseDown_PhaseMeanDireH',pathAnal,[],PyrRiseDownBurst.pRSPhaseMeanDireH,colorSel,[{'Rise'} {'Down'}]);
    
    plotBoxPlot(PyrRiseBurst.phaseMeanResultantLen,...
        PyrDownBurst.phaseMeanResultantLen,'Theta mean resultant length',...
        'PyrRiseDown_PhaseMeanResultantLen',pathAnal,[],PyrRiseDownBurst.pRSPhaseMeanResultantLen,colorSel,[{'Rise'} {'Down'}]);