function CompPyrModAlignedGoodVsBadTrALPL()
%% compare No cue vs ALPL recordings for good trials over time
%% run this after running PyrModAlignedAllRec_GoodTr()

    pathAnal0 = 'Z:\Yingxue\Draft\PV\Pyramidal\';
    if(exist([pathAnal0 'autoCorrPyrAlignedAllRec_GoodTr.mat']))
        load([pathAnal0 'autoCorrPyrAlignedAllRec_GoodTr.mat']);
    end
    
    goodVsBadALPL.ALPLIsNeuWithField = [modPyr1AL_GoodTr.isNeuWithField, modPyr1PL_GoodTr.isNeuWithField];
    
    goodVsBadALPL.goodMeanCorrTRunNZ = [modPyr1AL_GoodTr.meanCorrTRunNZ,modPyr1PL_GoodTr.meanCorrTRunNZ];
    goodVsBadALPL.goodMeanCorrTRunNZ1 = goodVsBadALPL.goodMeanCorrTRunNZ...
        (~isnan(goodVsBadALPL.goodMeanCorrTRunNZ));
    goodVsBadALPL.badMeanCorrTRunNZ = [modPyr1AL_BadTr.meanCorrTRunNZ, modPyr1PL_BadTr.meanCorrTRunNZ];
    goodVsBadALPL.badMeanCorrTRunNZ1 = goodVsBadALPL.badMeanCorrTRunNZ...
        (~isnan(goodVsBadALPL.badMeanCorrTRunNZ));
    goodVsBadALPL.pRSMeanCorrTRunNZ = ranksum(goodVsBadALPL.goodMeanCorrTRunNZ,...
        goodVsBadALPL.badMeanCorrTRunNZ); 
    
    goodVsBadALPL.goodMeanCorrTRunNZField = goodVsBadALPL.goodMeanCorrTRunNZ(goodVsBadALPL.ALPLIsNeuWithField == 1);
    goodVsBadALPL.goodMeanCorrTRunNZField1 = goodVsBadALPL.goodMeanCorrTRunNZField...
        (~isnan(goodVsBadALPL.goodMeanCorrTRunNZField));
    goodVsBadALPL.badMeanCorrTRunNZField = goodVsBadALPL.badMeanCorrTRunNZ(goodVsBadALPL.ALPLIsNeuWithField == 1);
    goodVsBadALPL.badMeanCorrTRunNZField1 = goodVsBadALPL.badMeanCorrTRunNZField...
        (~isnan(goodVsBadALPL.badMeanCorrTRunNZField));
    goodVsBadALPL.pRSMeanCorrTRunNZField = ranksum(goodVsBadALPL.goodMeanCorrTRunNZField,...
        goodVsBadALPL.badMeanCorrTRunNZField); 
    
    goodVsBadALPL.goodMeanCorrTRewNZ = [modPyr1AL_GoodTr.meanCorrTRewNZ, modPyr1PL_GoodTr.meanCorrTRewNZ];
    goodVsBadALPL.goodMeanCorrTRewNZ1 = goodVsBadALPL.goodMeanCorrTRewNZ...
        (~isnan(goodVsBadALPL.goodMeanCorrTRewNZ));
    goodVsBadALPL.badMeanCorrTRewNZ = [modPyr1AL_BadTr.meanCorrTRewNZ, modPyr1PL_BadTr.meanCorrTRewNZ];
    goodVsBadALPL.badMeanCorrTRewNZ1 = goodVsBadALPL.badMeanCorrTRewNZ...
        (~isnan(goodVsBadALPL.badMeanCorrTRewNZ));
    goodVsBadALPL.pRSMeanCorrTRewNZ = ranksum(goodVsBadALPL.goodMeanCorrTRewNZ,...
        goodVsBadALPL.badMeanCorrTRewNZ);
    
    goodVsBadALPL.goodMeanCorrTRewNZField = goodVsBadALPL.goodMeanCorrTRewNZ(goodVsBadALPL.ALPLIsNeuWithField == 1);
    goodVsBadALPL.goodMeanCorrTRewNZField1 = goodVsBadALPL.goodMeanCorrTRewNZField...
        (~isnan(goodVsBadALPL.goodMeanCorrTRewNZField));
    goodVsBadALPL.badMeanCorrTRewNZField = goodVsBadALPL.badMeanCorrTRewNZ(goodVsBadALPL.ALPLIsNeuWithField == 1);
    goodVsBadALPL.badMeanCorrTRewNZField1 = goodVsBadALPL.badMeanCorrTRewNZField...
        (~isnan(goodVsBadALPL.badMeanCorrTRewNZField));
    goodVsBadALPL.pRSMeanCorrTRewNZField = ranksum(goodVsBadALPL.goodMeanCorrTRewNZField,...
        goodVsBadALPL.badMeanCorrTRewNZField); 
    
    goodVsBadALPL.goodMeanCorrTCueNZ = [modPyr1AL_GoodTr.meanCorrTCueNZ, modPyr1PL_GoodTr.meanCorrTCueNZ];
    goodVsBadALPL.goodMeanCorrTCueNZ1 = goodVsBadALPL.goodMeanCorrTCueNZ...
        (~isnan(goodVsBadALPL.goodMeanCorrTCueNZ));
    goodVsBadALPL.badMeanCorrTCueNZ = [modPyr1AL_BadTr.meanCorrTCueNZ, modPyr1PL_BadTr.meanCorrTCueNZ];
    goodVsBadALPL.badMeanCorrTCueNZ1 = goodVsBadALPL.badMeanCorrTCueNZ...
        (~isnan(goodVsBadALPL.badMeanCorrTCueNZ));
    goodVsBadALPL.pRSMeanCorrTCueNZ = ranksum(goodVsBadALPL.goodMeanCorrTCueNZ,...
        goodVsBadALPL.badMeanCorrTCueNZ);
    
    goodVsBadALPL.goodMeanCorrTCueNZField = goodVsBadALPL.goodMeanCorrTCueNZ(goodVsBadALPL.ALPLIsNeuWithField == 1);
    goodVsBadALPL.goodMeanCorrTCueNZField1 = goodVsBadALPL.goodMeanCorrTCueNZField...
        (~isnan(goodVsBadALPL.goodMeanCorrTCueNZField));
    goodVsBadALPL.badMeanCorrTCueNZField = goodVsBadALPL.badMeanCorrTCueNZ(goodVsBadALPL.ALPLIsNeuWithField == 1);
    goodVsBadALPL.badMeanCorrTCueNZField1 = goodVsBadALPL.badMeanCorrTCueNZField...
        (~isnan(goodVsBadALPL.badMeanCorrTCueNZField));
    goodVsBadALPL.pRSMeanCorrTCueNZField = ranksum(goodVsBadALPL.goodMeanCorrTCueNZField,...
        goodVsBadALPL.badMeanCorrTCueNZField); 
    
    goodVsBadALPL.pRSGoodMeanCorrTRunRewNZ = ranksum(goodVsBadALPL.goodMeanCorrTRunNZ,...
        goodVsBadALPL.goodMeanCorrTRewNZ);
    goodVsBadALPL.pRSGoodMeanCorrTRunCueNZ = ranksum(goodVsBadALPL.goodMeanCorrTRunNZ,...
        goodVsBadALPL.goodMeanCorrTCueNZ);
    
    goodVsBadALPL.pRSGoodMeanCorrTRunRewNZField = ranksum(goodVsBadALPL.goodMeanCorrTRunNZField,...
        goodVsBadALPL.goodMeanCorrTRewNZField);
    goodVsBadALPL.pRSGoodMeanCorrTRunCueNZField = ranksum(goodVsBadALPL.goodMeanCorrTRunNZField,...
        goodVsBadALPL.goodMeanCorrTCueNZField);
    
    
    goodVsBadALPL.goodAdaptSpatialInfo = [modPyr1AL_GoodTr.adaptSpatialInfo, modPyr1PL_GoodTr.adaptSpatialInfo];
    goodVsBadALPL.goodAdaptSpatialInfo1 = goodVsBadALPL.goodAdaptSpatialInfo...
        (~isnan(goodVsBadALPL.goodAdaptSpatialInfo));
    goodVsBadALPL.badAdaptSpatialInfo = [modPyr1AL_BadTr.adaptSpatialInfo, modPyr1PL_BadTr.adaptSpatialInfo];
    goodVsBadALPL.badAdaptSpatialInfo1 = goodVsBadALPL.badAdaptSpatialInfo...
        (~isnan(goodVsBadALPL.badAdaptSpatialInfo));
    goodVsBadALPL.pRSAdaptSpatialInfo = ranksum(goodVsBadALPL.goodAdaptSpatialInfo,...
        goodVsBadALPL.badAdaptSpatialInfo);
    
    goodVsBadALPL.goodAdaptSpatialInfoField = goodVsBadALPL.goodAdaptSpatialInfo(goodVsBadALPL.ALPLIsNeuWithField == 1);
    goodVsBadALPL.goodAdaptSpatialInfoField1 = goodVsBadALPL.goodAdaptSpatialInfoField...
        (~isnan(goodVsBadALPL.goodAdaptSpatialInfoField));
    goodVsBadALPL.badAdaptSpatialInfoField = goodVsBadALPL.badAdaptSpatialInfo(goodVsBadALPL.ALPLIsNeuWithField == 1);
    goodVsBadALPL.badAdaptSpatialInfoField1 = goodVsBadALPL.badAdaptSpatialInfoField...
        (~isnan(goodVsBadALPL.badAdaptSpatialInfoField));
    goodVsBadALPL.pRSAdaptSpatialInfoField = ranksum(goodVsBadALPL.goodAdaptSpatialInfoField,...
        goodVsBadALPL.badAdaptSpatialInfoField); 
    
    goodVsBadALPL.goodSpatialInfo = [modPyr1AL_GoodTr.spatialInfo, modPyr1PL_GoodTr.spatialInfo];
    goodVsBadALPL.goodSpatialInfo1 = goodVsBadALPL.goodSpatialInfo...
        (~isnan(goodVsBadALPL.goodSpatialInfo));
    goodVsBadALPL.badSpatialInfo = [modPyr1AL_BadTr.spatialInfo, modPyr1PL_BadTr.spatialInfo];
    goodVsBadALPL.badSpatialInfo1 = goodVsBadALPL.badSpatialInfo...
        (~isnan(goodVsBadALPL.badSpatialInfo));
    goodVsBadALPL.pRSSpatialInfo = ranksum(goodVsBadALPL.goodSpatialInfo,...
        goodVsBadALPL.badSpatialInfo);
    
    goodVsBadALPL.goodSpatialInfoField = goodVsBadALPL.goodSpatialInfo(goodVsBadALPL.ALPLIsNeuWithField == 1);
    goodVsBadALPL.goodSpatialInfoField1 = goodVsBadALPL.goodSpatialInfoField...
        (~isnan(goodVsBadALPL.goodSpatialInfoField));
    goodVsBadALPL.badSpatialInfoField = goodVsBadALPL.badSpatialInfo(goodVsBadALPL.ALPLIsNeuWithField == 1);
    goodVsBadALPL.badSpatialInfoField1 = goodVsBadALPL.badSpatialInfoField...
        (~isnan(goodVsBadALPL.badSpatialInfoField));
    goodVsBadALPL.pRSSpatialInfoField = ranksum(goodVsBadALPL.goodSpatialInfoField,...
        goodVsBadALPL.badSpatialInfoField); 
    
    goodVsBadALPL.goodSparsity = [modPyr1AL_GoodTr.sparsity, modPyr1PL_GoodTr.sparsity];
    goodVsBadALPL.goodSparsity1 = goodVsBadALPL.goodSparsity...
        (~isnan(goodVsBadALPL.goodSparsity));
    goodVsBadALPL.badSparsity = [modPyr1AL_BadTr.sparsity, modPyr1PL_BadTr.sparsity];
    goodVsBadALPL.badSparsity1 = goodVsBadALPL.badSparsity...
        (~isnan(goodVsBadALPL.badSparsity));
    goodVsBadALPL.pRSSparsity = ranksum(goodVsBadALPL.goodSparsity,...
        goodVsBadALPL.badSparsity);
    
    goodVsBadALPL.goodSparsityField = goodVsBadALPL.goodSparsity(goodVsBadALPL.ALPLIsNeuWithField == 1);
    goodVsBadALPL.goodSparsityField1 = goodVsBadALPL.goodSparsityField...
        (~isnan(goodVsBadALPL.goodSparsityField));
    goodVsBadALPL.badSparsityField = goodVsBadALPL.badSparsity(goodVsBadALPL.ALPLIsNeuWithField == 1);
    goodVsBadALPL.badSparsityField1 = goodVsBadALPL.badSparsityField...
        (~isnan(goodVsBadALPL.badSparsityField));
    goodVsBadALPL.pRSSparsityField = ranksum(goodVsBadALPL.goodSparsityField,...
        goodVsBadALPL.badSparsityField); 
  
    
    colorSel = 1;
    
    % mean corr
    plotBarsOnly(...
        [mean(goodVsBadALPL.goodMeanCorrTRunNZ1),mean(goodVsBadALPL.badMeanCorrTRunNZ1)],...
            [std(goodVsBadALPL.goodMeanCorrTRunNZ1)/sqrt(length(goodVsBadALPL.goodMeanCorrTRunNZ1)),...
            std(goodVsBadALPL.badMeanCorrTRunNZ1)/sqrt(length(goodVsBadALPL.badMeanCorrTRunNZ1))],...
            '','Mean corr. T NZ (Run) G/B', ['p=' num2str(goodVsBadALPL.pRSMeanCorrTRunNZ)],...
            pathAnal0,'MeanCorrRunTNZGoodVsBadALPLBar')
        
    plotBarsOnly(...
        [mean(goodVsBadALPL.goodMeanCorrTRewNZ1),mean(goodVsBadALPL.badMeanCorrTRewNZ1)],...
            [std(goodVsBadALPL.goodMeanCorrTRewNZ1)/sqrt(length(goodVsBadALPL.goodMeanCorrTRewNZ1)),...
            std(goodVsBadALPL.badMeanCorrTRewNZ1)/sqrt(length(goodVsBadALPL.badMeanCorrTRewNZ1))],...
            '','Mean corr. T NZ (Rew) G/B', ['p=' num2str(goodVsBadALPL.pRSMeanCorrTRewNZ)],...
            pathAnal0,'MeanCorrRewTNZGoodVsBadALPLBar')
        
    plotBarsOnly(...
        [mean(goodVsBadALPL.goodMeanCorrTCueNZ1),mean(goodVsBadALPL.badMeanCorrTCueNZ1)],...
            [std(goodVsBadALPL.goodMeanCorrTCueNZ1)/sqrt(length(goodVsBadALPL.goodMeanCorrTCueNZ1)),...
            std(goodVsBadALPL.badMeanCorrTCueNZ1)/sqrt(length(goodVsBadALPL.badMeanCorrTCueNZ1))],...
            '','Mean corr. T NZ (Cue) G/B', ['p=' num2str(goodVsBadALPL.pRSMeanCorrTCueNZ)],...
            pathAnal0,'MeanCorrCueTNZGoodVsBadALPLBar')
        
    plotBarsOnly(...
        [mean(goodVsBadALPL.goodMeanCorrTRunNZ1),mean(goodVsBadALPL.goodMeanCorrTRewNZ1)],...
            [std(goodVsBadALPL.goodMeanCorrTRunNZ1)/sqrt(length(goodVsBadALPL.goodMeanCorrTRunNZ1)),...
            std(goodVsBadALPL.goodMeanCorrTRewNZ1)/sqrt(length(goodVsBadALPL.goodMeanCorrTRewNZ1))],...
            '','Mean corr. T NZ (Run vs Rew) good', ['p=' num2str(goodVsBadALPL.pRSGoodMeanCorrTRunRewNZ)],...
            pathAnal0,'GoodMeanCorrTNZRunVsRewALPLBar')
        
    plotBarsOnly(...
        [mean(goodVsBadALPL.goodMeanCorrTRunNZ1),mean(goodVsBadALPL.goodMeanCorrTCueNZ1)],...
            [std(goodVsBadALPL.goodMeanCorrTRunNZ1)/sqrt(length(goodVsBadALPL.goodMeanCorrTRunNZ1)),...
            std(goodVsBadALPL.goodMeanCorrTCueNZ1)/sqrt(length(goodVsBadALPL.goodMeanCorrTCueNZ1))],...
            '','Mean corr. T NZ (Run vs Cue) good', ['p=' num2str(goodVsBadALPL.pRSGoodMeanCorrTRunCueNZ)],...
            pathAnal0,'GoodMeanCorrTNZRunVsCueALPLBar')
        
    % mean corr field
    plotBarsOnly(...
        [mean(goodVsBadALPL.goodMeanCorrTRunNZField1),mean(goodVsBadALPL.badMeanCorrTRunNZField1)],...
            [std(goodVsBadALPL.goodMeanCorrTRunNZField1)/sqrt(length(goodVsBadALPL.goodMeanCorrTRunNZField1)),...
            std(goodVsBadALPL.badMeanCorrTRunNZField1)/sqrt(length(goodVsBadALPL.badMeanCorrTRunNZField1))],...
            '','Mean corr. T NZ (Run) G/B Field', ['p=' num2str(goodVsBadALPL.pRSMeanCorrTRunNZField)],...
            pathAnal0,'MeanCorrRunTNZGoodVsBadFieldALPLBar')
        
    plotBarsOnly(...
        [mean(goodVsBadALPL.goodMeanCorrTRewNZField1),mean(goodVsBadALPL.badMeanCorrTRewNZField1)],...
            [std(goodVsBadALPL.goodMeanCorrTRewNZField1)/sqrt(length(goodVsBadALPL.goodMeanCorrTRewNZField1)),...
            std(goodVsBadALPL.badMeanCorrTRewNZField1)/sqrt(length(goodVsBadALPL.badMeanCorrTRewNZField1))],...
            '','Mean corr. T NZ (Rew) G/B Field', ['p=' num2str(goodVsBadALPL.pRSMeanCorrTRewNZField)],...
            pathAnal0,'MeanCorrRewTNZGoodVsBadFieldALPLBar')
        
    plotBarsOnly(...
        [mean(goodVsBadALPL.goodMeanCorrTCueNZField1),mean(goodVsBadALPL.badMeanCorrTCueNZField1)],...
            [std(goodVsBadALPL.goodMeanCorrTCueNZField1)/sqrt(length(goodVsBadALPL.goodMeanCorrTCueNZField1)),...
            std(goodVsBadALPL.badMeanCorrTCueNZField1)/sqrt(length(goodVsBadALPL.badMeanCorrTCueNZField1))],...
            '','Mean corr. T NZ (Cue) G/B Field', ['p=' num2str(goodVsBadALPL.pRSMeanCorrTCueNZField)],...
            pathAnal0,'MeanCorrCueTNZGoodVsBadFieldALPLBar')
        
    plotBarsOnly(...
        [mean(goodVsBadALPL.goodMeanCorrTRunNZField1),mean(goodVsBadALPL.goodMeanCorrTRewNZField1)],...
            [std(goodVsBadALPL.goodMeanCorrTRunNZField1)/sqrt(length(goodVsBadALPL.goodMeanCorrTRunNZField1)),...
            std(goodVsBadALPL.goodMeanCorrTRewNZField1)/sqrt(length(goodVsBadALPL.goodMeanCorrTRewNZField1))],...
            '','Mean corr. T NZ Field (Run vs Rew)', ['p=' num2str(goodVsBadALPL.pRSGoodMeanCorrTRunRewNZField)],...
            pathAnal0,'GoodMeanCorrTNZFieldRunVsRewALPLBar')
        
    plotBarsOnly(...
        [mean(goodVsBadALPL.goodMeanCorrTRunNZField1),mean(goodVsBadALPL.goodMeanCorrTCueNZField1)],...
            [std(goodVsBadALPL.goodMeanCorrTRunNZField1)/sqrt(length(goodVsBadALPL.goodMeanCorrTRunNZField1)),...
            std(goodVsBadALPL.goodMeanCorrTCueNZField1)/sqrt(length(goodVsBadALPL.goodMeanCorrTCueNZField1))],...
            '','Mean corr. T NZ Field (Run vs Cue)', ['p=' num2str(goodVsBadALPL.pRSGoodMeanCorrTRunCueNZField)],...
            pathAnal0,'GoodMeanCorrTNZFieldRunVsCueALPLBar')
                
    %% adapted spatial information (the difference in the number of trials in good and bad trials might have skewed the results)
    plotBarsOnly(...
        [mean(goodVsBadALPL.goodAdaptSpatialInfo1),mean(goodVsBadALPL.badAdaptSpatialInfo1)],...
            [std(goodVsBadALPL.goodAdaptSpatialInfo1)/sqrt(length(goodVsBadALPL.goodAdaptSpatialInfo1)),...
            std(goodVsBadALPL.badAdaptSpatialInfo1)/sqrt(length(goodVsBadALPL.badAdaptSpatialInfo1))],...
            '','Adapted Spatial Info (Run) G/B', ['p=' num2str(goodVsBadALPL.pRSAdaptSpatialInfo)],...
            pathAnal0,'AdaptSpatialInfoRunGoodVsBadALPLBar')
        
    plotBarsOnly(...
        [mean(goodVsBadALPL.goodAdaptSpatialInfoField1),mean(goodVsBadALPL.badAdaptSpatialInfoField1)],...
            [std(goodVsBadALPL.goodAdaptSpatialInfoField1)/sqrt(length(goodVsBadALPL.goodAdaptSpatialInfoField1)),...
            std(goodVsBadALPL.badAdaptSpatialInfoField1)/sqrt(length(goodVsBadALPL.badAdaptSpatialInfoField1))],...
            '','Adapt Spatial Info Field (Run) G/B', ['p=' num2str(goodVsBadALPL.pRSAdaptSpatialInfoField)],...
            pathAnal0,'AdaptSpatialInfoRunFieldGoodVsBadALPLBar')
        
    %% spatial information, added on 7/21/2022
    plotBarsOnly(...
        [mean(goodVsBadALPL.goodSpatialInfo1),mean(goodVsBadALPL.badSpatialInfo1)],...
            [std(goodVsBadALPL.goodSpatialInfo1)/sqrt(length(goodVsBadALPL.goodSpatialInfo1)),...
            std(goodVsBadALPL.badSpatialInfo1)/sqrt(length(goodVsBadALPL.badSpatialInfo1))],...
            '','Spatial Info (Run) G/B', ['p=' num2str(goodVsBadALPL.pRSSpatialInfo)],...
            pathAnal0,'SpatialInfoRunGoodVsBadALPLBar')
    
    plotBarsOnly(...
        [mean(goodVsBadALPL.goodSpatialInfoField1),mean(goodVsBadALPL.badSpatialInfoField1)],...
            [std(goodVsBadALPL.goodSpatialInfoField1)/sqrt(length(goodVsBadALPL.goodSpatialInfoField1)),...
            std(goodVsBadALPL.badSpatialInfoField1)/sqrt(length(goodVsBadALPL.badSpatialInfoField1))],...
            '','Spatial Info Field (Run) G/B', ['p=' num2str(goodVsBadALPL.pRSSpatialInfoField)],...
            pathAnal0,'SpatialInfoRunFieldGoodVsBadALPLBar')
        
    %% sparsity
    plotBarsOnly(...
        [mean(goodVsBadALPL.goodSparsity1),mean(goodVsBadALPL.badSparsity1)],...
            [std(goodVsBadALPL.goodSparsity1)/sqrt(length(goodVsBadALPL.goodSparsity1)),...
            std(goodVsBadALPL.badSparsity1)/sqrt(length(goodVsBadALPL.badSparsity1))],...
            '','Sparsity (Run) G/B', ['p=' num2str(goodVsBadALPL.pRSSparsity)],...
            pathAnal0,'SparsityRunGoodVsBadALPLBar')
        
    plotBarsOnly(...
        [mean(goodVsBadALPL.goodSparsityField1),mean(goodVsBadALPL.badSparsityField1)],...
            [std(goodVsBadALPL.goodSparsityField1)/sqrt(length(goodVsBadALPL.goodSparsityField1)),...
            std(goodVsBadALPL.badSparsityField1)/sqrt(length(goodVsBadALPL.badSparsityField1))],...
            '','Sparsity Field (Run) G/B', ['p=' num2str(goodVsBadALPL.pRSSparsityField)],...
            pathAnal0,'SparsityFieldRunGoodVsBadALPLBar')
        
    save([pathAnal0 'autoCorrPyrAlignedAllRec_GoodTr.mat'], 'goodVsBadALPL', '-append');
end