function CompPyrModAlignedDistGoodVsBadTrALPL()
%% compare No cue vs ALPL recordings for good trials over distance
%% run this after running PyrModAlignedDistAllRec_GoodTr()

    pathAnal0 = 'Z:\Yingxue\Draft\PV\Pyramidal\';
    if(exist([pathAnal0 'autoCorrPyrAlignedDistAllRec_GoodTr.mat']))
        load([pathAnal0 'autoCorrPyrAlignedDistAllRec_GoodTr.mat']);
    end
    
    if(exist([pathAnal0 'autoCorrPyrAlignedAllRec_GoodTr.mat']))
        load([pathAnal0 'autoCorrPyrAlignedAllRec_GoodTr.mat'],'goodVsBadALPL');
    end
    
    goodVsBadALPL.goodMeanCorrDistRunNZ = [modPyr1AL_GoodTr.meanCorrDistRunNZ,modPyr1PL_GoodTr.meanCorrDistRunNZ];
    goodVsBadALPL.goodMeanCorrDistRunNZ1 = goodVsBadALPL.goodMeanCorrDistRunNZ...
        (~isnan(goodVsBadALPL.goodMeanCorrDistRunNZ));
    goodVsBadALPL.badMeanCorrDistRunNZ = [modPyr1AL_BadTr.meanCorrDistRunNZ, modPyr1PL_BadTr.meanCorrDistRunNZ];
    goodVsBadALPL.badMeanCorrDistRunNZ1 = goodVsBadALPL.badMeanCorrDistRunNZ...
        (~isnan(goodVsBadALPL.badMeanCorrDistRunNZ));
    goodVsBadALPL.pRSMeanCorrDistRunNZ = ranksum(goodVsBadALPL.goodMeanCorrDistRunNZ,...
        goodVsBadALPL.badMeanCorrDistRunNZ); 
    
    goodVsBadALPL.goodMeanCorrDistRunNZField = goodVsBadALPL.goodMeanCorrDistRunNZ(goodVsBadALPL.ALPLIsNeuWithField == 1);
    goodVsBadALPL.goodMeanCorrDistRunNZField1 = goodVsBadALPL.goodMeanCorrDistRunNZField...
        (~isnan(goodVsBadALPL.goodMeanCorrDistRunNZField));
    goodVsBadALPL.badMeanCorrDistRunNZField = goodVsBadALPL.badMeanCorrDistRunNZ(goodVsBadALPL.ALPLIsNeuWithField == 1);
    goodVsBadALPL.badMeanCorrDistRunNZField1 = goodVsBadALPL.badMeanCorrDistRunNZField...
        (~isnan(goodVsBadALPL.badMeanCorrDistRunNZField));
    goodVsBadALPL.pRSMeanCorrDistRunNZField = ranksum(goodVsBadALPL.goodMeanCorrDistRunNZField,...
        goodVsBadALPL.badMeanCorrDistRunNZField); 
    
    goodVsBadALPL.goodMeanCorrDistRewNZ = [modPyr1AL_GoodTr.meanCorrDistRewNZ, modPyr1PL_GoodTr.meanCorrDistRewNZ];
    goodVsBadALPL.goodMeanCorrDistRewNZ1 = goodVsBadALPL.goodMeanCorrDistRewNZ...
        (~isnan(goodVsBadALPL.goodMeanCorrDistRewNZ));
    goodVsBadALPL.badMeanCorrDistRewNZ = [modPyr1AL_BadTr.meanCorrDistRewNZ, modPyr1PL_BadTr.meanCorrDistRewNZ];
    goodVsBadALPL.badMeanCorrDistRewNZ1 = goodVsBadALPL.badMeanCorrDistRewNZ...
        (~isnan(goodVsBadALPL.badMeanCorrDistRewNZ));
    goodVsBadALPL.pRSMeanCorrDistRewNZ = ranksum(goodVsBadALPL.goodMeanCorrDistRewNZ,...
        goodVsBadALPL.badMeanCorrDistRewNZ);
    
    goodVsBadALPL.goodMeanCorrDistRewNZField = goodVsBadALPL.goodMeanCorrDistRewNZ(goodVsBadALPL.ALPLIsNeuWithField == 1);
    goodVsBadALPL.goodMeanCorrDistRewNZField1 = goodVsBadALPL.goodMeanCorrDistRewNZField...
        (~isnan(goodVsBadALPL.goodMeanCorrDistRewNZField));
    goodVsBadALPL.badMeanCorrDistRewNZField = goodVsBadALPL.badMeanCorrDistRewNZ(goodVsBadALPL.ALPLIsNeuWithField == 1);
    goodVsBadALPL.badMeanCorrDistRewNZField1 = goodVsBadALPL.badMeanCorrDistRewNZField...
        (~isnan(goodVsBadALPL.badMeanCorrDistRewNZField));
    goodVsBadALPL.pRSMeanCorrDistRewNZField = ranksum(goodVsBadALPL.goodMeanCorrDistRewNZField,...
        goodVsBadALPL.badMeanCorrDistRewNZField); 
    
    goodVsBadALPL.goodMeanCorrDistCueNZ = [modPyr1AL_GoodTr.meanCorrDistCueNZ, modPyr1PL_GoodTr.meanCorrDistCueNZ];
    goodVsBadALPL.goodMeanCorrDistCueNZ1 = goodVsBadALPL.goodMeanCorrDistCueNZ...
        (~isnan(goodVsBadALPL.goodMeanCorrDistCueNZ));
    goodVsBadALPL.badMeanCorrDistCueNZ = [modPyr1AL_BadTr.meanCorrDistCueNZ, modPyr1PL_BadTr.meanCorrDistCueNZ];
    goodVsBadALPL.badMeanCorrDistCueNZ1 = goodVsBadALPL.badMeanCorrDistCueNZ...
        (~isnan(goodVsBadALPL.badMeanCorrDistCueNZ));
    goodVsBadALPL.pRSMeanCorrDistCueNZ = ranksum(goodVsBadALPL.goodMeanCorrDistCueNZ,...
        goodVsBadALPL.badMeanCorrDistCueNZ);
    
    goodVsBadALPL.goodMeanCorrDistCueNZField = goodVsBadALPL.goodMeanCorrDistCueNZ(goodVsBadALPL.ALPLIsNeuWithField == 1);
    goodVsBadALPL.goodMeanCorrDistCueNZField1 = goodVsBadALPL.goodMeanCorrDistCueNZField...
        (~isnan(goodVsBadALPL.goodMeanCorrDistCueNZField));
    goodVsBadALPL.badMeanCorrDistCueNZField = goodVsBadALPL.badMeanCorrDistCueNZ(goodVsBadALPL.ALPLIsNeuWithField == 1);
    goodVsBadALPL.badMeanCorrDistCueNZField1 = goodVsBadALPL.badMeanCorrDistCueNZField...
        (~isnan(goodVsBadALPL.badMeanCorrDistCueNZField));
    goodVsBadALPL.pRSMeanCorrDistCueNZField = ranksum(goodVsBadALPL.goodMeanCorrDistCueNZField,...
        goodVsBadALPL.badMeanCorrDistCueNZField); 
    
    goodVsBadALPL.pRSGoodMeanCorrDistRunRewNZ = ranksum(goodVsBadALPL.goodMeanCorrDistRunNZ,...
        goodVsBadALPL.goodMeanCorrDistRewNZ);
    goodVsBadALPL.pRSGoodMeanCorrDistRunCueNZ = ranksum(goodVsBadALPL.goodMeanCorrDistRunNZ,...
        goodVsBadALPL.goodMeanCorrDistCueNZ);
    
    goodVsBadALPL.pRSGoodMeanCorrDistRunRewNZField = ranksum(goodVsBadALPL.goodMeanCorrDistRunNZField,...
        goodVsBadALPL.goodMeanCorrDistRewNZField);
    goodVsBadALPL.pRSGoodMeanCorrDistRunCueNZField = ranksum(goodVsBadALPL.goodMeanCorrDistRunNZField,...
        goodVsBadALPL.goodMeanCorrDistCueNZField);
    
    colorSel = 1;
    
    % mean corr
    plotBarsOnly(...
        [mean(goodVsBadALPL.goodMeanCorrDistRunNZ1),mean(goodVsBadALPL.badMeanCorrDistRunNZ1)],...
            [std(goodVsBadALPL.goodMeanCorrDistRunNZ1)/sqrt(length(goodVsBadALPL.goodMeanCorrDistRunNZ1)),...
            std(goodVsBadALPL.badMeanCorrDistRunNZ1)/sqrt(length(goodVsBadALPL.badMeanCorrDistRunNZ1))],...
            '','Mean corr. T NZ (Run) G/B', ['p=' num2str(goodVsBadALPL.pRSMeanCorrDistRunNZ)],...
            pathAnal0,'MeanCorrDistRunNZGoodVsBadALPLBar')
        
    plotBarsOnly(...
        [mean(goodVsBadALPL.goodMeanCorrDistRewNZ1),mean(goodVsBadALPL.badMeanCorrDistRewNZ1)],...
            [std(goodVsBadALPL.goodMeanCorrDistRewNZ1)/sqrt(length(goodVsBadALPL.goodMeanCorrDistRewNZ1)),...
            std(goodVsBadALPL.badMeanCorrDistRewNZ1)/sqrt(length(goodVsBadALPL.badMeanCorrDistRewNZ1))],...
            '','Mean corr. T NZ (Rew) G/B', ['p=' num2str(goodVsBadALPL.pRSMeanCorrDistRewNZ)],...
            pathAnal0,'MeanCorrDistRewNZGoodVsBadALPLBar')
        
    plotBarsOnly(...
        [mean(goodVsBadALPL.goodMeanCorrDistCueNZ1),mean(goodVsBadALPL.badMeanCorrDistCueNZ1)],...
            [std(goodVsBadALPL.goodMeanCorrDistCueNZ1)/sqrt(length(goodVsBadALPL.goodMeanCorrDistCueNZ1)),...
            std(goodVsBadALPL.badMeanCorrDistCueNZ1)/sqrt(length(goodVsBadALPL.badMeanCorrDistCueNZ1))],...
            '','Mean corr. T NZ (Cue) G/B', ['p=' num2str(goodVsBadALPL.pRSMeanCorrDistCueNZ)],...
            pathAnal0,'MeanCorrDistCueNZGoodVsBadALPLBar')
        
    plotBarsOnly(...
        [mean(goodVsBadALPL.goodMeanCorrDistRunNZ1),mean(goodVsBadALPL.goodMeanCorrDistRewNZ1)],...
            [std(goodVsBadALPL.goodMeanCorrDistRunNZ1)/sqrt(length(goodVsBadALPL.goodMeanCorrDistRunNZ1)),...
            std(goodVsBadALPL.goodMeanCorrDistRewNZ1)/sqrt(length(goodVsBadALPL.goodMeanCorrDistRewNZ1))],...
            '','Mean corr. T NZ (Run vs Rew) good', ['p=' num2str(goodVsBadALPL.pRSGoodMeanCorrDistRunRewNZ)],...
            pathAnal0,'GoodMeanCorrDistNZRunVsRewALPLBar')
        
    plotBarsOnly(...
        [mean(goodVsBadALPL.goodMeanCorrDistRunNZ1),mean(goodVsBadALPL.goodMeanCorrDistCueNZ1)],...
            [std(goodVsBadALPL.goodMeanCorrDistRunNZ1)/sqrt(length(goodVsBadALPL.goodMeanCorrDistRunNZ1)),...
            std(goodVsBadALPL.goodMeanCorrDistCueNZ1)/sqrt(length(goodVsBadALPL.goodMeanCorrDistCueNZ1))],...
            '','Mean corr. T NZ (Run vs Cue) good', ['p=' num2str(goodVsBadALPL.pRSGoodMeanCorrDistRunCueNZ)],...
            pathAnal0,'GoodMeanCorrDistNZRunVsCueALPLBar')
        
    % mean corr field
    plotBarsOnly(...
        [mean(goodVsBadALPL.goodMeanCorrDistRunNZField1),mean(goodVsBadALPL.badMeanCorrDistRunNZField1)],...
            [std(goodVsBadALPL.goodMeanCorrDistRunNZField1)/sqrt(length(goodVsBadALPL.goodMeanCorrDistRunNZField1)),...
            std(goodVsBadALPL.badMeanCorrDistRunNZField1)/sqrt(length(goodVsBadALPL.badMeanCorrDistRunNZField1))],...
            '','Mean corr. T NZ (Run) G/B Field', ['p=' num2str(goodVsBadALPL.pRSMeanCorrDistRunNZField)],...
            pathAnal0,'MeanCorrDistRunNZGoodVsBadFieldALPLBar')
        
    plotBarsOnly(...
        [mean(goodVsBadALPL.goodMeanCorrDistRewNZField1),mean(goodVsBadALPL.badMeanCorrDistRewNZField1)],...
            [std(goodVsBadALPL.goodMeanCorrDistRewNZField1)/sqrt(length(goodVsBadALPL.goodMeanCorrDistRewNZField1)),...
            std(goodVsBadALPL.badMeanCorrDistRewNZField1)/sqrt(length(goodVsBadALPL.badMeanCorrDistRewNZField1))],...
            '','Mean corr. T NZ (Rew) G/B Field', ['p=' num2str(goodVsBadALPL.pRSMeanCorrDistRewNZField)],...
            pathAnal0,'MeanCorrDistRewNZGoodVsBadFieldALPLBar')
        
    plotBarsOnly(...
        [mean(goodVsBadALPL.goodMeanCorrDistCueNZField1),mean(goodVsBadALPL.badMeanCorrDistCueNZField1)],...
            [std(goodVsBadALPL.goodMeanCorrDistCueNZField1)/sqrt(length(goodVsBadALPL.goodMeanCorrDistCueNZField1)),...
            std(goodVsBadALPL.badMeanCorrDistCueNZField1)/sqrt(length(goodVsBadALPL.badMeanCorrDistCueNZField1))],...
            '','Mean corr. T NZ (Cue) G/B Field', ['p=' num2str(goodVsBadALPL.pRSMeanCorrDistCueNZField)],...
            pathAnal0,'MeanCorrDistCueNZGoodVsBadFieldALPLBar')
        
    plotBarsOnly(...
        [mean(goodVsBadALPL.goodMeanCorrDistRunNZField1),mean(goodVsBadALPL.goodMeanCorrDistRewNZField1)],...
            [std(goodVsBadALPL.goodMeanCorrDistRunNZField1)/sqrt(length(goodVsBadALPL.goodMeanCorrDistRunNZField1)),...
            std(goodVsBadALPL.goodMeanCorrDistRewNZField1)/sqrt(length(goodVsBadALPL.goodMeanCorrDistRewNZField1))],...
            '','Mean corr. T NZ Field (Run vs Rew)', ['p=' num2str(goodVsBadALPL.pRSGoodMeanCorrDistRunRewNZField)],...
            pathAnal0,'GoodMeanCorrDistNZFieldRunVsRewALPLBar')
        
    plotBarsOnly(...
        [mean(goodVsBadALPL.goodMeanCorrDistRunNZField1),mean(goodVsBadALPL.goodMeanCorrDistCueNZField1)],...
            [std(goodVsBadALPL.goodMeanCorrDistRunNZField1)/sqrt(length(goodVsBadALPL.goodMeanCorrDistRunNZField1)),...
            std(goodVsBadALPL.goodMeanCorrDistCueNZField1)/sqrt(length(goodVsBadALPL.goodMeanCorrDistCueNZField1))],...
            '','Mean corr. T NZ Field (Run vs Cue)', ['p=' num2str(goodVsBadALPL.pRSGoodMeanCorrDistRunCueNZField)],...
            pathAnal0,'GoodMeanCorrDistNZFieldRunVsCueALPLBar')
    
    save([pathAnal0 'autoCorrPyrAlignedDistAllRec_GoodTr.mat'], 'goodVsBadALPL', '-append');
end