function CompPyrModCtrlTrNoCueVsALPL()
%% compare No cue vs ALPL recordings for good trials over distance
%% run this after running PyrModAllRec_GoodTr()

    pathAnal0 = 'Z:\Yingxue\Draft\PV\Pyramidal\';
    if(exist([pathAnal0 'autoCorrPyrAllRec_CtrlTr.mat']))
        load([pathAnal0 'autoCorrPyrAllRec_CtrlTr.mat']);
    end
    
    noCueVsALPL.noCueMeanCorrDistNZ = modPyrNoCue_CtrlTr.meanCorrDistNZ;
    noCueVsALPL.noCueMeanCorrDistNZ1 = noCueVsALPL.noCueMeanCorrDistNZ(...
        ~isnan(noCueVsALPL.noCueMeanCorrDistNZ));
    noCueVsALPL.ALPLMeanCorrDistNZ = [modPyrAL_CtrlTr.meanCorrDistNZ, modPyrPL_CtrlTr.meanCorrDistNZ];
    noCueVsALPL.ALPLMeanCorrDistNZ1 = noCueVsALPL.ALPLMeanCorrDistNZ(...
        ~isnan(noCueVsALPL.ALPLMeanCorrDistNZ));
    noCueVsALPL.pRSMeanCorrDistNZ = ranksum(noCueVsALPL.noCueMeanCorrDistNZ,...
        noCueVsALPL.ALPLMeanCorrDistNZ);
    
    noCueVsALPL.meanNoCueMeanCorrDistNZ = mean(noCueVsALPL.noCueMeanCorrDistNZ1);
    noCueVsALPL.semNoCueMeanCorrDistNZ = std(noCueVsALPL.noCueMeanCorrDistNZ1)...
            /sqrt(length(noCueVsALPL.noCueMeanCorrDistNZ1)); 
    noCueVsALPL.meanALPLMeanCorrDistNZ = mean(noCueVsALPL.ALPLMeanCorrDistNZ1);
    noCueVsALPL.semALPLMeanCorrDistNZ = std(noCueVsALPL.ALPLMeanCorrDistNZ1)...
            /sqrt(length(noCueVsALPL.ALPLMeanCorrDistNZ1)); 
    
    noCueVsALPL.noCueAdaptSpatialInfo = modPyrNoCue_CtrlTr.adaptSpatialInfo;
    noCueVsALPL.noCueAdaptSpatialInfo1 = modPyrNoCue_CtrlTr.adaptSpatialInfo...
        (~isnan(modPyrNoCue_CtrlTr.adaptSpatialInfo));
    noCueVsALPL.ALPLAdaptSpatialInfo = [modPyrAL_CtrlTr.adaptSpatialInfo, modPyrPL_CtrlTr.adaptSpatialInfo];
    noCueVsALPL.ALPLAdaptSpatialInfo1 = noCueVsALPL.ALPLAdaptSpatialInfo...
        (~isnan(noCueVsALPL.ALPLAdaptSpatialInfo));
    noCueVsALPL.pRSAdaptSpatialInfo = ranksum(noCueVsALPL.noCueAdaptSpatialInfo,...
        noCueVsALPL.ALPLAdaptSpatialInfo);
    
    % added on 7/21/2022
    noCueVsALPL.noCueSpatialInfo = modPyrNoCue_CtrlTr.spatialInfo;
    noCueVsALPL.noCueSpatialInfo1 = modPyrNoCue_CtrlTr.spatialInfo...
        (~isnan(modPyrNoCue_CtrlTr.spatialInfo));
    noCueVsALPL.ALPLSpatialInfo = [modPyrAL_CtrlTr.spatialInfo, modPyrPL_CtrlTr.spatialInfo];
    noCueVsALPL.ALPLSpatialInfo1 = noCueVsALPL.ALPLSpatialInfo...
        (~isnan(noCueVsALPL.ALPLSpatialInfo));
    noCueVsALPL.pRSSpatialInfo = ranksum(noCueVsALPL.noCueSpatialInfo,...
        noCueVsALPL.ALPLSpatialInfo);
    
    noCueVsALPL.noCueSparsity = modPyrNoCue_CtrlTr.sparsity;
    noCueVsALPL.noCueSparsity1 = noCueVsALPL.noCueSparsity(~isnan(noCueVsALPL.noCueSparsity)); 
    noCueVsALPL.ALPLSparsity = [modPyrAL_CtrlTr.sparsity, modPyrPL_CtrlTr.sparsity];
    noCueVsALPL.ALPLSparsity1 = noCueVsALPL.ALPLSparsity(~isnan(noCueVsALPL.ALPLSparsity));
    noCueVsALPL.pRSSparsity = ranksum(noCueVsALPL.noCueSparsity,...
        noCueVsALPL.ALPLSparsity);
    
    colorSel = 1;
    plotBoxPlot(noCueVsALPL.noCueMeanCorrDistNZ,...
            noCueVsALPL.ALPLMeanCorrDistNZ,...
            ['Mean corr. dist NZ'],...
            ['MeanCorrDistNZNoCueVsALPLBox'],...
            pathAnal0,[-0.1 0.15],noCueVsALPL.pRSMeanCorrDistNZ,colorSel,[{'NoCue'} {'ALPL'}]);
        
    plotDistri(noCueVsALPL.noCueMeanCorrDistNZ,...
        noCueVsALPL.ALPLMeanCorrDistNZ,...
        -1:0.01:1,...
        'Mean corr. dist NZ',[{'NoCue'} {'ALPL'}],pathAnal0,...
        'MeanCorrDistNZNoCueVsALPLDistr',[-0.1 0.25],['p = ' num2str(noCueVsALPL.pRSMeanCorrDistNZ)]);
    
    plotBarsOnly(...
        [mean(noCueVsALPL.noCueMeanCorrDistNZ1),mean(noCueVsALPL.ALPLMeanCorrDistNZ1)],...
            [std(noCueVsALPL.noCueMeanCorrDistNZ1)/sqrt(length(noCueVsALPL.noCueMeanCorrDistNZ1)),...
            std(noCueVsALPL.ALPLMeanCorrDistNZ1)/sqrt(length(noCueVsALPL.ALPLMeanCorrDistNZ1))],...
            '','Mean corr. dist NZ', ['p=' num2str(noCueVsALPL.pRSMeanCorrDistNZ)],...
            pathAnal0,'MeanCorrDistNZNoCueVsALPLBar')
        
    plotBarsOnly(...
        [mean(noCueVsALPL.noCueAdaptSpatialInfo1),mean(noCueVsALPL.ALPLAdaptSpatialInfo1)],...
            [std(noCueVsALPL.noCueAdaptSpatialInfo1)/sqrt(length(noCueVsALPL.noCueAdaptSpatialInfo1)),...
            std(noCueVsALPL.ALPLAdaptSpatialInfo1)/sqrt(length(noCueVsALPL.ALPLAdaptSpatialInfo1))],...
            '','Adapt spatial info. (bit)', ['p=' num2str(noCueVsALPL.pRSAdaptSpatialInfo)],...
            pathAnal0,'AdaptSpatialInfoNoCueVsALPLBar')
        
    plotBarsOnly(...
        [mean(noCueVsALPL.noCueSpatialInfo1),mean(noCueVsALPL.ALPLSpatialInfo1)],...
            [std(noCueVsALPL.noCueSpatialInfo1)/sqrt(length(noCueVsALPL.noCueSpatialInfo1)),...
            std(noCueVsALPL.ALPLSpatialInfo1)/sqrt(length(noCueVsALPL.ALPLSpatialInfo1))],...
            '','Spatial info. (bit)', ['p=' num2str(noCueVsALPL.pRSSpatialInfo)],...
            pathAnal0,'SpatialInfoNoCueVsALPLBar')
        
    plotBarsOnly(...
        [mean(noCueVsALPL.noCueSparsity1),mean(noCueVsALPL.ALPLSparsity1)],...
            [std(noCueVsALPL.noCueSparsity1)/sqrt(length(noCueVsALPL.noCueSparsity1)),...
            std(noCueVsALPL.ALPLSparsity1)/sqrt(length(noCueVsALPL.ALPLSparsity1))],...
            '','Sparsity', ['p=' num2str(noCueVsALPL.pRSSparsity)],...
            pathAnal0,'SparsityNoCueVsALPLBar')
        
    save([pathAnal0 'autoCorrPyrAllRec_CtrlTr.mat'], 'noCueVsALPL', '-append');
end