function CompPyrModGoodTrNoCueVsALPL()
%% compare No cue vs ALPL recordings for good trials over distance
%% run this after running PyrModAllRec_GoodTr()

    pathAnal0 = 'Z:\Yingxue\Draft\PV\Pyramidal\';
    if(exist([pathAnal0 'autoCorrPyrAllRec_GoodTr.mat']))
        load([pathAnal0 'autoCorrPyrAllRec_GoodTr.mat']);
    end
    
    noCueVsALPL.noCueMeanCorrDistGoodNZ = modPyrNoCue_GoodTr.meanCorrDistNZ;
    noCueVsALPL.ALPLMeanCorrDistGoodNZ = [modPyrAL_GoodTr.meanCorrDistNZ, modPyrPL_GoodTr.meanCorrDistNZ];
    noCueVsALPL.pRSMeanCorrDistGoodNZ = ranksum(noCueVsALPL.noCueMeanCorrDistGoodNZ,...
        noCueVsALPL.ALPLMeanCorrDistGoodNZ);
    
    noCueVsALPL.noCueAdaptSpatialInfoGood = modPyrNoCue_GoodTr.adaptSpatialInfo;
    noCueVsALPL.ALPLAdaptSpatialInfoGood = [modPyrAL_GoodTr.adaptSpatialInfo, modPyrPL_GoodTr.adaptSpatialInfo];
    noCueVsALPL.pRSAdaptSpatialInfoGood = ranksum(noCueVsALPL.noCueAdaptSpatialInfoGood,...
        noCueVsALPL.ALPLAdaptSpatialInfoGood);
    
    noCueVsALPL.noCueSparsityGood = modPyrNoCue_GoodTr.sparsity;
    noCueVsALPL.ALPLSparsityGood = [modPyrAL_GoodTr.sparsity, modPyrPL_GoodTr.sparsity];
    noCueVsALPL.pRSSparsityGood = ranksum(noCueVsALPL.noCueSparsityGood,...
        noCueVsALPL.ALPLSparsityGood);
    
    plotBoxPlot(noCueVsALPL.noCueMeanCorrDistGoodNZ,...
            noCueVsALPL.ALPLMeanCorrDistGoodNZ,...
            ['Mean corr. dist goodNZ'],...
            ['MeanCorrDistGoodNZNoCueVsALPL'],...
            pathAnal0,[0 0.2],noCueVsALPL.pRSMeanCorrDistGoodNZ,colorSel,[{'BL'} {'0to1s'}]);
    
    plotBars(noCueVsALPL.noCueMeanCorrDistGoodNZ,noCueVsALPL.ALPLMeanCorrDistGoodNZ,...
        [mean(noCueVsALPL.noCueMeanCorrDistGoodNZ),mean(noCueVsALPL.ALPLMeanCorrDistGoodNZ)],...
            [std(noCueVsALPL.noCueMeanCorrDistGoodNZ)/sqrt(length(noCueVsALPL.noCueMeanCorrDistGoodNZ)),...
            std(noCueVsALPL.ALPLMeanCorrDistGoodNZ)/sqrt(length(noCueVsALPL.ALPLMeanCorrDistGoodNZ))],...
            '','Mean corr. dist goodNZ', ['p=' num2str(noCueVsALPL.pRSMeanCorrDistGoodNZ)],...
            pathAnal0,'MeanCorrDistGoodNZNoCueVsALPL')
        
    plotBars(noCueVsALPL.noCueAdaptSpatialInfoGood,noCueVsALPL.ALPLAdaptSpatialInfoGood,...
        [mean(noCueVsALPL.noCueAdaptSpatialInfoGood),mean(noCueVsALPL.ALPLAdaptSpatialInfoGood)],...
            [std(noCueVsALPL.noCueAdaptSpatialInfoGood)/sqrt(length(noCueVsALPL.noCueAdaptSpatialInfoGood)),...
            std(noCueVsALPL.ALPLAdaptSpatialInfoGood)/sqrt(length(noCueVsALPL.ALPLAdaptSpatialInfoGood))],...
            '','Adapt spatial info. (bit)', ['p=' num2str(noCueVsALPL.pRSAdaptSpatialInfoGood)],...
            pathAnal0,'AdaptSpatialInfoGoodNoCueVsALPL')
        
    plotBars(noCueVsALPL.noCueSparsityGood,noCueVsALPL.ALPLSparsityGood,...
        [mean(noCueVsALPL.noCueSparsityGood),mean(noCueVsALPL.ALPLSparsityGood)],...
            [std(noCueVsALPL.noCueSparsityGood)/sqrt(length(noCueVsALPL.noCueSparsityGood)),...
            std(noCueVsALPL.ALPLSparsityGood)/sqrt(length(noCueVsALPL.ALPLSparsityGood))],...
            '','Sparsity', ['p=' num2str(noCueVsALPL.pRSSparsityGood)],...
            pathAnal0,'SparsityGoodNoCueVsALPL')
        
    save([pathAnal0 'autoCorrPyrAllRec_GoodTr.mat'], 'noCueVsALPL', '-append');
end