function plotCompPyrClusters(pathAnal, mod, modPyrStatsC, colorSel, clu1, clu2, distTime)
% compare two pyramidal clusters
% This function is called by PyrModAllRec.m

    % colorSel = 0;
    idxC = mod.idxC;
    
    plotBoxPlot(mod.relDepthNeuHDefC{clu1},...
        mod.relDepthNeuHDefC{clu2},'Depth','relDepthNeuHDefCmpC1C2Box',...
        pathAnal,[-6 6],mod.pRSRelDepthNeuHDefC,colorSel,[{'deep'} {'sup'}]);
        
    plotBoxPlot(mod.phaseMeanDire(idxC == clu1)/pi*180,...
        mod.phaseMeanDire(idxC == clu2)/pi*180,'Mean theta phase (deg.)','Pyr_ThetaMeanC1C2Box',...
        pathAnal,[],modPyrStatsC.pWWPhaseMeanDireC,colorSel,[{'deep'} {'sup'}]);
    
    plotBoxPlot(mod.burstMeanDire(idxC == clu1)/pi*180,...
        mod.burstMeanDire(idxC == clu2)/pi*180,'Mean burst phase (deg.)','Pyr_BurstMeanGoodVsBadTrBox',...
        pathAnal,[],modPyrStatsC.pWWburstMeanDireC,colorSel,[{'deep'} {'sup'}]);
    
    plotBoxPlot(mod.phaseMeanResultantLen(idxC == clu1),...
        mod.phaseMeanResultantLen(idxC == clu2),'Theta phase resultant length','Pyr_PhaseMeanResultantLenC1C2Box',...
        pathAnal,[-0.1 0.6],modPyrStatsC.pRSPhaseMeanResultantLenC,colorSel,[{'deep'} {'sup'}]);
    
    plotBoxPlot(mod.burstMeanResultantLen(idxC == clu1),...
        mod.burstMeanResultantLen(idxC == clu2),'Burst phase resultant length','Pyr_BurstMeanResultantLenC1C2Box',...
        pathAnal,[-0.1 0.8],modPyrStatsC.pRSBurstMeanResultantLenC,colorSel,[{'deep'} {'sup'}]);
    
    plotBoxPlot(mod.thetaModHist(idxC == clu1),...
        mod.thetaModHist(idxC == clu2),'Theta modulation','Pyr_ThetaModHistC1C2Box',...
        pathAnal,[-0.1 1.2],modPyrStatsC.pRSThetaModHistC,colorSel,[{'deep'} {'sup'}]);
    
    plotBoxPlot(mod.burstThetaDiff(idxC == clu1 & mod.fractBurst > 0)/pi*180,...
        mod.burstThetaDiff(idxC == clu2 & mod.fractBurst > 0)/pi*180,'Burst phase - theta phase (deg.)','Pyr_BurstPhase-ThetaPhaseC1C2Box',...
        pathAnal,[],modPyrStatsC.pWWBurstThetaDiffC,colorSel,[{'deep'} {'sup'}]);
    
    plotBoxPlot(mod.fractBurst(idxC == clu1),...
        mod.fractBurst(idxC == clu2),'Fract burst','Pyr_FractBurstC1C2Box',...
        pathAnal,[],modPyrStatsC.pRSFractBurstC,colorSel,[{'deep'} {'sup'}]);
    
    plotBoxPlot(mod.numSpPerBurstMean(idxC == clu1),...
        mod.numSpPerBurstMean(idxC == clu2),'Num. spikes per burst','Pyr_NumSpPerBurstMeanC1C2Box',...
        pathAnal,[1.8 3.2],modPyrStatsC.pRSNumSpPerBurstMeanC,colorSel,[{'deep'} {'sup'}]);
    
    plotBoxPlot(mod.thetaModFreq3(idxC == clu1),...
        mod.thetaModFreq3(idxC == clu2),'Theta modulation frequency (Hz)','Pyr_ThetaModFreq3C1C2Box',...
        pathAnal,[],modPyrStatsC.pRSThetaModFreq3C,colorSel,[{'deep'} {'sup'}]);
    
    plotBoxPlot(mod.diffNeuronLFPFreq(idxC == clu1),...
        mod.diffNeuronLFPFreq(idxC == clu2),'Neuron mod freq. - LFP freq. (Hz)',...
        'Pyr_DiffNeuronLFPFreqC1C2Box',...
        pathAnal,[],modPyrStatsC.pRSDiffNeuronLFPFreq,colorSel,[{'deep'} {'sup'}]);
    
    plotBoxPlot(mod.thetaAsym3(idxC == clu1),...
        mod.thetaAsym3(idxC == clu2),'Theta asymmetry','Pyr_ThetaAsym3C1C2Box',...
        pathAnal,[0.15 0.85],modPyrStatsC.pRSThetaAsym3C,colorSel,[{'deep'} {'sup'}]);
        
    plotDistri(mod.relDepthNeuHDefC{clu1},...
        mod.relDepthNeuHDefC{clu2},...
        min(mod.relDepthNeuHDef):max(mod.relDepthNeuHDef),...
        'Depth',[{'deep'} {'sup'}],pathAnal,'relDepthNeuHDefCmpC1C2',[-5 5]);
    
    plotPolarPlot(mod.phaseMeanDire(idxC == clu1),...
        mod.phaseMeanDire(idxC == clu2),'Mean theta phase direction',...
        'Pyr_ThetaMeanC1C2Polar',pathAnal,modPyrStatsC.pWWPhaseMeanDireC);
    
    plotPolarPlot(mod.maxPhaseArr(idxC == clu1)/180*pi,...
        mod.maxPhaseArr(idxC == clu2)/180*pi,'Max theta phase',...
        'Pyr_MaxPhaseArrC1C2Polar',pathAnal,modPyrStatsC.pWWMaxPhaseC);
    
    plotPolarPlot(mod.minPhaseArr(idxC == clu1)/180*pi,...
        mod.minPhaseArr(idxC == clu2)/180*pi,'Min theta phase',...
        'Pyr_MinPhaseArrC1C2Polar',pathAnal,modPyrStatsC.pWWMinPhaseC);
    
    plotPolarPlot(mod.burstMeanDire(idxC == clu1 & mod.fractBurst > 0),...
        mod.burstMeanDire(idxC == clu2 & mod.fractBurst > 0),'Burst mean phase',...
        'Pyr_BurstMeanDireC1C2Polar',pathAnal,modPyrStatsC.pWWburstMeanDireC);
    
%     plotPolarPlot(mod.nonBurstMeanDire(idxC == clu1),...
%         mod.nonBurstMeanDire(idxC == clu2),'Non-burst mean phase',...
%         'Pyr_NonBurstMeanDireC1C2Polar',pathAnal,modPyrStatsC.pWWnonburstMeanDireC);
    
    plotPolarPlot(mod.burstMeanDireStart(idxC == clu1 & mod.fractBurst > 0),...
        mod.burstMeanDireStart(idxC == clu2 & mod.fractBurst > 0),'Burst start phase direction',...
        'Pyr_BurstMeanDireStartC1C2Polar',pathAnal,modPyrStatsC.pWWburstMeanDireStartC);
    
    if(distTime == 0)
        str = 'Field width (mm)';
        indhist = 0:10:max(mod.fieldWidth);
    else
        str = 'Field width (s)';
        indhist = 0:0.1:max(mod.fieldWidth);
    end
    plotDistri(mod.fieldWidth(idxC == clu1 & mod.isNeuWithField == 1),...
        mod.fieldWidth(idxC == clu2 & mod.isNeuWithField == 1),...
        indhist,...
        str,[{'deep'} {'sup'}],pathAnal,'fieldWidthCmpC1C2',[0 max(mod.fieldWidth)+0.1],...
        ['p = ' num2str(modPyrStatsC.pRFieldWidthC)]);
    
    if(distTime == 0)
        str = 'Field start (mm)';
        indhist = 0:10:max(mod.indStartField);
    else
        str = 'Field start (s)';
        indhist = 0:0.1:max(mod.indStartField);
    end
    plotDistri(mod.indStartField(idxC == clu1 & mod.isNeuWithField == 1),...
        mod.indStartField(idxC == clu2 & mod.isNeuWithField == 1),...
        indhist,...
        str,[{'deep'} {'sup'}],pathAnal,'indStartFieldCmpC1C2',[0 max(mod.indStartField)+0.1],...
        ['p = ' num2str(modPyrStatsC.pRIndStartFieldC)]);
    
    if(distTime == 0)
        str = 'Field peak (mm)';
        indhist = 0:10:max(mod.indPeakField);
    else
        str = 'Field peak (s)';
        indhist = 0:0.1:max(mod.indPeakField);
    end
    plotDistri(mod.indPeakField(idxC == clu1 & mod.isNeuWithField == 1),...
        mod.indPeakField(idxC == clu2 & mod.isNeuWithField == 1),...
        indhist,...
        str,[{'deep'} {'sup'}],pathAnal,'indPeakFieldCmpC1C2',[0 max(mod.indPeakField)+0.1],...
        ['p = ' num2str(modPyrStatsC.pRIndPeakFieldC)]);
    
    plotDistri(mod.percTrackStartField(idxC == clu1 & mod.isNeuWithField == 1),...
        mod.percTrackStartField(idxC == clu2 & mod.isNeuWithField == 1),...
        0:0.02:max(mod.percTrackStartField),...
        'Perc track field start',[{'deep'} {'sup'}],pathAnal,'percTrackStartFieldCmpC1C2',[0 max(mod.percTrackStartField)+0.02],...
        ['p = ' num2str(modPyrStatsC.pRPercTrackStartFieldC)]);
    
    plotDistri(mod.percTrackPeakField(idxC == clu1 & mod.isNeuWithField == 1),...
        mod.percTrackPeakField(idxC == clu2 & mod.isNeuWithField == 1),...
        0:0.02:max(mod.percTrackPeakField),...
        'Perc track field peak',[{'deep'} {'sup'}],pathAnal,'percTrackPeakFieldCmpC1C2',[0 max(mod.percTrackPeakField)+0.02],...
        ['p = ' num2str(modPyrStatsC.pRPercTrackPeakFieldC)]);
    
    plotDistri(mod.percTrackEndField(idxC == clu1 & mod.isNeuWithField == 1),...
        mod.percTrackEndField(idxC == clu2 & mod.isNeuWithField == 1),...
        0:0.02:max(mod.percTrackEndField),...
        'Perc track field end',[{'deep'} {'sup'}],pathAnal,'percTrackEndFieldCmpC1C2',[0 max(mod.percTrackEndField)+0.02],...
        ['p = ' num2str(modPyrStatsC.pRPercTrackEndFieldC)]);
end

