function plotCompPyrClu2RecFieldNoField(pathAnal, mod, modPyrStatsField, colorSel, clu2)
% compare neurons in the recordings with fields vs. in the recordings with no field in cluster 2
% This function is called by PryModAllrec.m

    plotBarPlot(mod.relDepthNeuHDef(modPyrStatsField.indCurCField{clu2}),...
        mod.relDepthNeuHDef(modPyrStatsField.indCurCNoField{clu2}),'Depth',...
        'Pyr_RelDepthNeuHDefCmpC2FieldRecBar',pathAnal,[-5 6],...
        modPyrStatsField.pKWRelDepthNeuHDef(clu2),colorSel);
        
    plotBoxPlot(mod.fractBurst(modPyrStatsField.indCurCField{clu2}),...
        mod.fractBurst(modPyrStatsField.indCurCNoField{clu2}),'Fract burst',...
        'Pyr_FractBurstC2FieldRecBox',pathAnal,[-0.1 0.85],...
        modPyrStatsField.pRSFractBurst(clu2),colorSel,[{'supF'} {'supNoF'}]);
    
    plotBoxPlot(mod.numSpPerBurstMean(modPyrStatsField.indCurCField{clu2}),...
        mod.numSpPerBurstMean(modPyrStatsField.indCurCNoField{clu2}),'Burst length',...
        'Pyr_NumSpPerBurstMeanC2FieldRecBox',pathAnal,[1.9 3.5],...
        modPyrStatsField.pRSNumSpPerBurstMean(clu2),colorSel,[{'supF'} {'supNoF'}]);
    
    plotBoxPlot(mod.thetaModHist(modPyrStatsField.indCurCField{clu2}),...
        mod.thetaModHist(modPyrStatsField.indCurCNoField{clu2}),'Theta modulation',...
        'Pyr_ThetaModHistC2FieldRecBox',pathAnal,[0 1.1],...
        modPyrStatsField.pRSThetaModHist(clu2),colorSel,[{'supF'} {'supNoF'}]);
    
    plotBoxPlot(mod.phaseMeanDire(modPyrStatsField.indCurCField{clu2})/pi*180,...
        mod.phaseMeanDire(modPyrStatsField.indCurCNoField{clu2})/pi*180,'Mean theta phase (deg.)',...
        'Pyr_ThetaMeanC2FieldRecBox',pathAnal,[-45 360],...
        modPyrStatsField.pWWPhaseMeanDire(clu2),colorSel,[{'supF'} {'supNoF'}]);
    
    plotBoxPlot(mod.burstMeanDire(modPyrStatsField.indCurCFieldBurst{clu2})/pi*180,...
        mod.burstMeanDire(modPyrStatsField.indCurCNoFieldBurst{clu2})/pi*180,'Burst mean phase (deg.)',...
        'Pyr_BurstMeanDirC2FieldRecBox',pathAnal,[],...
        modPyrStatsField.pWWBurstMeanDire(clu2),colorSel,[{'supF'} {'supNoF'}]);
    
    plotBoxPlot(mod.burstMeanDireStart(modPyrStatsField.indCurCFieldBurst{clu2})/pi*180,...
        mod.burstMeanDireStart(modPyrStatsField.indCurCNoFieldBurst{clu2})/pi*180,'Burst start phase (deg.)',...
        'Pyr_BurstMeanDirStartC2FieldRecBox',pathAnal,[],...
        modPyrStatsField.pWWBurstMeanDireStart(clu2),colorSel,[{'supF'} {'supNoF'}]);
    
    plotBoxPlot(mod.burstThetaDiff(modPyrStatsField.indCurCFieldBurst{clu2})/pi*180,...
        mod.burstThetaDiff(modPyrStatsField.indCurCNoFieldBurst{clu2})/pi*180,...
        'Burst phase - theta phase (deg.)','Pyr_BurstPhase-ThetaPhaseC2FieldRecBox',...
        pathAnal,[],modPyrStatsField.pWWBurstThetaDiff(clu2),colorSel,[{'supF'} {'supNoF'}]);
    
    plotBoxPlot(mod.thetaModFreq3(modPyrStatsField.indCurCField{clu2}),...
        mod.thetaModFreq3(modPyrStatsField.indCurCNoField{clu2}),'Theta modulation frequency (Hz)',...
        'Pyr_ThetaModFreqC2FieldRecBox',pathAnal,[4.5 10.5],...
        modPyrStatsField.pRSThetaModFreq3(clu2),colorSel,[{'supF'} {'supNoF'}]);
    
    plotBoxPlot(mod.diffNeuronLFPFreq(modPyrStatsField.indCurCField{clu2}),...
        mod.diffNeuronLFPFreq(modPyrStatsField.indCurCNoField{clu2}),'Neuron mod freq. - LFP freq. (Hz)',...
        'Pyr_DiffNeuronLFPFreqC2FieldRecBox',...
        pathAnal,[],modPyrStatsField.pRSDiffNeuronLFPFreq(clu2),colorSel,[{'supF'} {'supNoF'}]);
    
    plotBoxPlot(mod.thetaAsym3(modPyrStatsField.indCurCField{clu2}),...
        mod.thetaAsym3(modPyrStatsField.indCurCNoField{clu2}),'Theta asymmetry',...
        'Pyr_ThetaAsymC2FieldRecBox',pathAnal,[0.1 0.85],...
        modPyrStatsField.pRSThetaAsym3(clu2),colorSel,[{'supF'} {'supNoF'}]);
    