function plotCompPyrGoodBadTr(pathAnal, mod_GoodTr, mod_BadTr, modPyrStatsC, colorSel)
% compare good and bad trials
% This function is called by PyrModAllRec_GoodTr.m

    % colorSel = 0;
    plotBoxPlot(mod_GoodTr.meanInstFR,mod_BadTr.meanInstFR,...
         'Mean inst. FR (Hz)','Pyr_MeanInstFRGoodVsBadTrBox',...
        pathAnal,[],modPyrStatsC.pRSMeanInstFR,colorSel,[{'good'} {'bad'}]);
            
    plotBoxPlot(mod_GoodTr.phaseMeanDire/pi*180,...
        mod_BadTr.phaseMeanDire/pi*180,'Mean theta phase (deg.)','Pyr_ThetaMeanGoodVsBadTrBox',...
        pathAnal,[],modPyrStatsC.pWWPhaseMeanDire,colorSel,[{'good'} {'bad'}]);
    
    plotBoxPlot(mod_GoodTr.burstMeanDire/pi*180,...
        mod_BadTr.burstMeanDire/pi*180,'Mean burst phase (deg.)','Pyr_BurstMeanGoodVsBadTrBox',...
        pathAnal,[],modPyrStatsC.pWWBurstMeanDire,colorSel,[{'good'} {'bad'}]);
    
    plotBoxPlot(mod_GoodTr.phaseMeanResultantLen,...
        mod_BadTr.phaseMeanResultantLen,'Theta phase resultant length','Pyr_PhaseMeanResultantLenGoodVsBadBox',...
        pathAnal,[-0.1 0.6],modPyrStatsC.pRSPhaseMeanResultantLen,colorSel,[{'good'} {'bad'}]);
    
    plotBoxPlot(mod_GoodTr.burstMeanResultantLen,...
        mod_BadTr.burstMeanResultantLen,'Burst phase resultant length','Pyr_BurstMeanResultantLenGoodVsBadBox',...
        pathAnal,[-0.1 0.8],modPyrStatsC.pRSBurstMeanResultantLen,colorSel,[{'good'} {'bad'}]);
    
    plotBoxPlot(mod_GoodTr.thetaModHist,...
        mod_BadTr.thetaModHist,'Theta modulation','Pyr_ThetaModHistGoodVsBadBox',...
        pathAnal,[-0.1 1.2],modPyrStatsC.pRSThetaModHist,colorSel,[{'good'} {'bad'}]);
    
    plotBoxPlot(mod_GoodTr.burstThetaDiff(mod_GoodTr.fractBurst > 0)/pi*180,...
        mod_BadTr.burstThetaDiff(mod_BadTr.fractBurst > 0)/pi*180,'Burst phase - theta phase (deg.)','Pyr_BurstPhase-ThetaPhaseGoodVsBadBox',...
        pathAnal,[],modPyrStatsC.pWWBurstThetaDiff,colorSel,[{'good'} {'bad'}]);
    
    plotBoxPlot(mod_GoodTr.fractBurst,...
        mod_BadTr.fractBurst,'Fract burst','Pyr_FractBurstGoodVsBadBox',...
        pathAnal,[],modPyrStatsC.pRSFractBurst,colorSel,[{'good'} {'bad'}]);
    
    plotBoxPlot(mod_GoodTr.numSpPerBurstMean,...
        mod_BadTr.numSpPerBurstMean,'Num. spikes per burst','Pyr_NumSpPerBurstMeanGoodVsBadBox',...
        pathAnal,[1.8 3.2],modPyrStatsC.pRSNumSpPerBurstMean,colorSel,[{'good'} {'bad'}]);
    
    plotBoxPlot(mod_GoodTr.thetaModFreq3,...
        mod_BadTr.thetaModFreq3,'Theta modulation frequency (Hz)','Pyr_ThetaModFreq3GoodVsBadBox',...
        pathAnal,[],modPyrStatsC.pRSThetaModFreq3,colorSel,[{'good'} {'bad'}]);
    
    plotBoxPlot(mod_GoodTr.diffNeuronLFPFreq,...
        mod_BadTr.diffNeuronLFPFreq,'Neuron mod freq. - LFP freq. (Hz)',...
        'Pyr_DiffNeuronLFPFreqGoodVsBadBox',...
        pathAnal,[],modPyrStatsC.pRSDiffNeuronLFPFreq,colorSel,[{'good'} {'bad'}]);
    
    plotBoxPlot(mod_GoodTr.thetaAsym3,...
        mod_BadTr.thetaAsym3,'Theta asymmetry','Pyr_ThetaAsym3GoodVsBadBox',...
        pathAnal,[0.15 0.85],modPyrStatsC.pRSThetaAsym3,colorSel,[{'good'} {'bad'}]);
            
    plotPolarPlot(mod_GoodTr.phaseMeanDire(~isnan(mod_GoodTr.phaseMeanDire)),...
        mod_BadTr.phaseMeanDire(~isnan(mod_BadTr.phaseMeanDire)),'Mean theta phase direction',...
        'Pyr_ThetaMeanGoodVsBadPolar',pathAnal,modPyrStatsC.pWWPhaseMeanDire);
    
    plotPolarPlot(mod_GoodTr.maxPhaseArr(~isnan(mod_GoodTr.maxPhaseArr))/180*pi,...
        mod_BadTr.maxPhaseArr(~isnan(mod_BadTr.maxPhaseArr))/180*pi,'Max theta phase',...
        'Pyr_MaxPhaseArrGoodVsBadPolar',pathAnal,modPyrStatsC.pWWMaxPhase);
    
    plotPolarPlot(mod_GoodTr.minPhaseArr(~isnan(mod_GoodTr.minPhaseArr))/180*pi,...
        mod_BadTr.minPhaseArr(~isnan(mod_BadTr.minPhaseArr))/180*pi,'Min theta phase',...
        'Pyr_MinPhaseArrGoodVsBadPolar',pathAnal,modPyrStatsC.pWWMinPhase);
    
    plotPolarPlot(mod_GoodTr.burstMeanDire(mod_GoodTr.fractBurst > 0),...
        mod_BadTr.burstMeanDire(mod_BadTr.fractBurst > 0),'Burst mean phase',...
        'Pyr_BurstMeanDireGoodVsBadPolar',pathAnal,modPyrStatsC.pWWBurstMeanDire);
        
    plotPolarPlot(mod_GoodTr.burstMeanDireStart(mod_GoodTr.fractBurst > 0),...
        mod_BadTr.burstMeanDireStart(mod_BadTr.fractBurst > 0),'Burst start phase direction',...
        'Pyr_BurstMeanDireStartGoodVsBadPolar',pathAnal,modPyrStatsC.pWWBurstMeanDireStart);
    
    plotBoxPlot(mod_GoodTr.meanCorrDistNZ,...
        mod_BadTr.meanCorrDistNZ,'Mean corr. dist. NZ','Pyr_MeanCorrDistNZGoodVsBadTrBox',...
        pathAnal,[-0.1 0.2],modPyrStatsC.pRSMeanCorrDistNZ,colorSel,[{'good'} {'bad'}]);
    
    plotBoxPlot(mod_GoodTr.adaptSpatialInfo,...
        mod_BadTr.adaptSpatialInfo,'Adapt spatial info. (bit)','Pyr_AdaptSpInfoGoodVsBadTrBox',...
        pathAnal,[0 3],modPyrStatsC.pRSAdaptSpatialInfo,colorSel,[{'good'} {'bad'}]);
    
    plotBoxPlot(mod_GoodTr.sparsity,...
        mod_BadTr.sparsity,'Sparsity','Pyr_SparsityGoodVsBadTrBox',...
        pathAnal,[0 3],modPyrStatsC.pRSSparsity,colorSel,[{'good'} {'bad'}]);
    
    plotDistri(mod_GoodTr.fieldWidth(mod_GoodTr.isNeuWithField == 1),...
        mod_BadTr.fieldWidth(mod_BadTr.isNeuWithField == 1),...
        0:20:max([mod_GoodTr.fieldWidth mod_BadTr.fieldWidth]),...
        'Field width (mm)',[{'good'} {'bad'}],pathAnal,'fieldWidthCmpGoodVsBadTr',...
        [0 max([mod_GoodTr.fieldWidth mod_BadTr.fieldWidth])+10],...
        ['p = ' num2str(modPyrStatsC.pRFieldWidthC)]);
    
    plotDistri(mod_GoodTr.indStartField(mod_GoodTr.isNeuWithField == 1),...
        mod_BadTr.indStartField(mod_BadTr.isNeuWithField == 1),...
        0:20:max([mod_GoodTr.indStartField mod_BadTr.indStartField]),...
        'Field start (mm)',[{'good'} {'bad'}],pathAnal,'indStartFieldCmpGoodVsBadTr',...
        [0 max([mod_GoodTr.indStartField mod_BadTr.indStartField])+10],...
        ['p = ' num2str(modPyrStatsC.pRIndStartFieldC)]);
    
    plotDistri(mod_GoodTr.indPeakField(mod_GoodTr.isNeuWithField == 1),...
        mod_BadTr.indPeakField(mod_BadTr.isNeuWithField == 1),...
        0:20:max([mod_GoodTr.indPeakField mod_BadTr.indPeakField]),...
        'Field peak (mm)',[{'good'} {'bad'}],pathAnal,'indPeakFieldCmpGoodVsBadTr',...
        [0 max([mod_GoodTr.indPeakField mod_BadTr.indPeakField])+10],...
        ['p = ' num2str(modPyrStatsC.pRIndPeakFieldC)]);
    
    plotDistri(mod_GoodTr.percTrackStartField(mod_GoodTr.isNeuWithField == 1),...
        mod_BadTr.percTrackStartField(mod_BadTr.isNeuWithField == 1),...
        0:0.02:max([mod_GoodTr.percTrackStartField mod_BadTr.percTrackStartField]),...
        'Perc track field start',[{'good'} {'bad'}],pathAnal,'percTrackStartFieldCmpGoodVsBadTr',...
        [0 max([mod_GoodTr.percTrackStartField mod_BadTr.percTrackStartField])+0.02],...
        ['p = ' num2str(modPyrStatsC.pRPercTrackStartFieldC)]);
    
    plotDistri(mod_GoodTr.percTrackPeakField(mod_GoodTr.isNeuWithField == 1),...
        mod_BadTr.percTrackPeakField(mod_BadTr.isNeuWithField == 1),...
        0:0.02:max([mod_GoodTr.percTrackPeakField mod_BadTr.percTrackPeakField]),...
        'Perc track field peak',[{'good'} {'bad'}],pathAnal,'percTrackPeakFieldCmpGoodVsBadTr',...
        [0 max([mod_GoodTr.percTrackPeakField mod_BadTr.percTrackPeakField])+0.02],...
        ['p = ' num2str(modPyrStatsC.pRPercTrackPeakFieldC)]);
    
    plotDistri(mod_GoodTr.percTrackEndField(mod_GoodTr.isNeuWithField == 1),...
        mod_BadTr.percTrackEndField(mod_BadTr.isNeuWithField == 1),...
        0:0.02:max([mod_GoodTr.percTrackEndField mod_BadTr.percTrackEndField]),...
        'Perc track field peak',[{'good'} {'bad'}],pathAnal,'percTrackEndFieldCmpGoodVsBadTr',...
        [0 max([mod_GoodTr.percTrackEndField mod_BadTr.percTrackEndField])+0.02],...
        ['p = ' num2str(modPyrStatsC.pRPercTrackEndFieldC)]);
    
end