function plotCompPyrClu2FieldNoField(pathAnal, mod, modPyrStatsFNeuVsNoFNeu, colorSel, clu)
% compare field neurons vs. no field neuron in cluster 2
% This function is called by PryModAllrec.m

    plotBarPlot(mod.relDepthNeuHDef(modPyrStatsFNeuVsNoFNeu.indCurCField{clu}),...
        mod.relDepthNeuHDef(modPyrStatsFNeuVsNoFNeu.indCurCNoField{clu}),'Depth',...
        'Pyr_RelDepthNeuHDefCmpC2FieldBar',pathAnal,[-5 6],...
        modPyrStatsFNeuVsNoFNeu.pRSRelDepthNeuHDef(clu),colorSel);
    
    plotBoxPlot(mod.fractBurst(modPyrStatsFNeuVsNoFNeu.indCurCField{clu}),...
        mod.fractBurst(modPyrStatsFNeuVsNoFNeu.indCurCNoField{clu}),'Fract burst',...
        'Pyr_FractBurstC2FieldBox',pathAnal,[-0.1 0.85],...
        modPyrStatsFNeuVsNoFNeu.pRSMeanFractBurst(clu),colorSel,[{'supF'} {'supNoF'}]);
    
    plotBoxPlot(mod.numSpPerBurstMean(modPyrStatsFNeuVsNoFNeu.indCurCField{clu}),...
        mod.numSpPerBurstMean(modPyrStatsFNeuVsNoFNeu.indCurCNoField{clu}),'Burst length',...
        'Pyr_NumSpPerBurstMeanC2FieldBox',pathAnal,[1.9 3.5],...
        modPyrStatsFNeuVsNoFNeu.pRSNumSpPerBurstMean(clu),colorSel,[{'supF'} {'supNoF'}]);
    
    plotBoxPlot(mod.thetaModHist(modPyrStatsFNeuVsNoFNeu.indCurCField{clu}),...
        mod.thetaModHist(modPyrStatsFNeuVsNoFNeu.indCurCNoField{clu}),'Theta modulation',...
        'Pyr_ThetaModHistC2FieldBox',pathAnal,[0 1.1],...
        modPyrStatsFNeuVsNoFNeu.pRSThetaModHist(clu),colorSel,[{'supF'} {'supNoF'}]);
    
    plotBoxPlot(mod.phaseMeanDire(modPyrStatsFNeuVsNoFNeu.indCurCField{clu})/pi*180,...
        mod.phaseMeanDire(modPyrStatsFNeuVsNoFNeu.indCurCNoField{clu})/pi*180,'Mean theta phase (deg.)',...
        'Pyr_ThetaMeanC2FieldBox',pathAnal,[-45 360],...
        modPyrStatsFNeuVsNoFNeu.pWWPhaseMeanDire(clu),colorSel,[{'supF'} {'supNoF'}]);
    
    plotBoxPlot(mod.burstMeanDire(modPyrStatsFNeuVsNoFNeu.indCurCFieldBurst{clu})/pi*180,...
        mod.burstMeanDire(modPyrStatsFNeuVsNoFNeu.indCurCNoFieldBurst{clu})/pi*180,'Burst mean phase (deg.)',...
        'Pyr_BurstMeanDirC2FieldBox',pathAnal,[],...
        modPyrStatsFNeuVsNoFNeu.pWWBurstMeanDire(clu),colorSel,[{'supF'} {'supNoF'}]);
    
    plotBoxPlot(mod.burstThetaDiff(modPyrStatsFNeuVsNoFNeu.indCurCFieldBurst{clu})/pi*180,...
        mod.burstThetaDiff(modPyrStatsFNeuVsNoFNeu.indCurCNoFieldBurst{clu})/pi*180,...
        'Burst phase - theta phase (deg.)','Pyr_BurstPhase-ThetaPhaseC2FieldBox',...
        pathAnal,[],modPyrStatsFNeuVsNoFNeu.pWWBurstThetaDiff(clu),colorSel,[{'supF'} {'supNoF'}]);
    
    plotBoxPlot(mod.burstMeanDireStart(modPyrStatsFNeuVsNoFNeu.indCurCFieldBurst{clu})/pi*180,...
        mod.burstMeanDireStart(modPyrStatsFNeuVsNoFNeu.indCurCNoFieldBurst{clu})/pi*180,'Burst start phase (deg.)',...
        'Pyr_BurstMeanDirStartC2FieldBox',pathAnal,[],...
        modPyrStatsFNeuVsNoFNeu.pWWBurstMeanDireStart(clu),colorSel,[{'supF'} {'supNoF'}]);
    
    plotBoxPlot(mod.thetaModFreq3(modPyrStatsFNeuVsNoFNeu.indCurCField{clu}),...
        mod.thetaModFreq3(modPyrStatsFNeuVsNoFNeu.indCurCNoField{clu}),'Theta modulation frequency (Hz)',...
        'Pyr_ThetaModFreqC2FieldBox',pathAnal,[4.5 10],...
        modPyrStatsFNeuVsNoFNeu.pRSThetaModFreq3(clu),colorSel,[{'supF'} {'supNoF'}]);
    
    plotBoxPlot(mod.diffNeuronLFPFreq(modPyrStatsFNeuVsNoFNeu.indCurCField{clu}),...
        mod.diffNeuronLFPFreq(modPyrStatsFNeuVsNoFNeu.indCurCNoField{clu}),'Neuron mod freq. - LFP freq. (Hz)',...
        'Pyr_DiffNeuronLFPFreqC2FieldBox',...
        pathAnal,[],modPyrStatsFNeuVsNoFNeu.pRSDiffNeuronLFPFreq(clu),colorSel,[{'supF'} {'supNoF'}]);
    
    plotBoxPlot(mod.thetaAsym3(modPyrStatsFNeuVsNoFNeu.indCurCField{clu}),...
        mod.thetaAsym3(modPyrStatsFNeuVsNoFNeu.indCurCNoField{clu}),'Theta asymmetry',...
        'Pyr_ThetaAsymC2FieldBox',pathAnal,[0.1 0.85],...
        modPyrStatsFNeuVsNoFNeu.pRSThetaAsym3(clu),colorSel,[{'supF'} {'supNoF'}]);
    