function plotCompPyrClu1FieldNoField(pathAnal, mod, modPyrStatsFNeuVsNoFNeu, colorSel, clu)
% compare field neurons vs. no field neuron in cluster 1
% This function is called by PryModAllrec.m

    plotBarPlot(mod.relDepthNeuHDef(modPyrStatsFNeuVsNoFNeu.indCurCField{clu}),...
        mod.relDepthNeuHDef(modPyrStatsFNeuVsNoFNeu.indCurCNoField{clu}),'Depth',...
        'Pyr_RelDepthNeuHDefCmpC1FieldBar',pathAnal,[-5 6],...
        modPyrStatsFNeuVsNoFNeu.pKWRelDepthNeuHDef(clu),colorSel);
    
    plotBoxPlot(mod.fractBurst(modPyrStatsFNeuVsNoFNeu.indCurCField{clu}),...
        mod.fractBurst(modPyrStatsFNeuVsNoFNeu.indCurCNoField{clu}),'Fract burst',...
        'Pyr_FractBurstC1FieldBox',pathAnal,[-0.1 0.85],...
        modPyrStatsFNeuVsNoFNeu.pRSMeanFractBurst(clu),colorSel,[{'deepF'} {'deepNoF'}]);
    
    plotBoxPlot(mod.numSpPerBurstMean(modPyrStatsFNeuVsNoFNeu.indCurCField{clu}),...
        mod.numSpPerBurstMean(modPyrStatsFNeuVsNoFNeu.indCurCNoField{clu}),'Burst length',...
        'Pyr_NumSpPerBurstMeanC1FieldBox',pathAnal,[1.9 3.5],...
        modPyrStatsFNeuVsNoFNeu.pRSNumSpPerBurstMean(clu),colorSel,[{'deepF'} {'deepNoF'}]);
    
    plotBoxPlot(mod.thetaModHist(modPyrStatsFNeuVsNoFNeu.indCurCField{clu}),...
        mod.thetaModHist(modPyrStatsFNeuVsNoFNeu.indCurCNoField{clu}),'Theta modulation',...
        'Pyr_ThetaModHistC1FieldBox',pathAnal,[0 1.1],...
        modPyrStatsFNeuVsNoFNeu.pRSThetaModHist(clu),colorSel,[{'deepF'} {'deepNoF'}]);
    
    x = mod.phaseMeanDire;
    x(x > pi) = x(x > pi) - 2*pi;
    x = x/pi*180;
    plotBoxPlot(x(modPyrStatsFNeuVsNoFNeu.indCurCField{clu}),...
        x(modPyrStatsFNeuVsNoFNeu.indCurCNoField{clu}),'Mean theta phase (deg.)',...
        'Pyr_ThetaMeanC1FieldBox',pathAnal,[-180 180],...
        modPyrStatsFNeuVsNoFNeu.pWWPhaseMeanDire(clu),colorSel,[{'deepF'} {'deepNoF'}]);
    
    x = mod.burstMeanDire;
    x(x > pi) = x(x > pi) - 2*pi;
    x = x/pi*180;
    plotBoxPlot(x(modPyrStatsFNeuVsNoFNeu.indCurCFieldBurst{clu}),...
        x(modPyrStatsFNeuVsNoFNeu.indCurCNoFieldBurst{clu}),'Burst mean phase (deg.)',...
        'Pyr_BurstMeanDirC1FieldBox',pathAnal,[-180 180],...
        modPyrStatsFNeuVsNoFNeu.pWWBurstMeanDire(clu),colorSel,[{'deepF'} {'deepNoF'}]);
    
    plotBoxPlot(mod.burstThetaDiff(modPyrStatsFNeuVsNoFNeu.indCurCFieldBurst{clu})/pi*180,...
        mod.burstThetaDiff(modPyrStatsFNeuVsNoFNeu.indCurCNoFieldBurst{clu})/pi*180,...
        'Burst phase - theta phase (deg.)','Pyr_BurstPhase-ThetaPhaseC1FieldBox',...
        pathAnal,[],modPyrStatsFNeuVsNoFNeu.pWWBurstThetaDiff(clu),colorSel,[{'deepF'} {'deepNoF'}]);
    
    x = mod.burstMeanDireStart;
    x(x > pi) = x(x > pi) - 2*pi;
    x = x/pi*180;
    plotBoxPlot(x(modPyrStatsFNeuVsNoFNeu.indCurCFieldBurst{clu}),...
        x(modPyrStatsFNeuVsNoFNeu.indCurCNoFieldBurst{clu}),'Burst start phase (deg.)',...
        'Pyr_BurstMeanDirStartC1FieldBox',pathAnal,[-150 180],...
        modPyrStatsFNeuVsNoFNeu.pWWBurstMeanDireStart(clu),colorSel,[{'deepF'} {'deepNoF'}]);
    
    plotBoxPlot(mod.thetaModFreq3(modPyrStatsFNeuVsNoFNeu.indCurCField{clu}),...
        mod.thetaModFreq3(modPyrStatsFNeuVsNoFNeu.indCurCNoField{clu}),'Theta modulation frequency (Hz)',...
        'Pyr_ThetaModFreqC1FieldBox',pathAnal,[4 10.5],...
        modPyrStatsFNeuVsNoFNeu.pRSThetaModFreq3(clu),colorSel,[{'deepF'} {'deepNoF'}]);
    
    plotBoxPlot(mod.diffNeuronLFPFreq(modPyrStatsFNeuVsNoFNeu.indCurCField{clu}),...
        mod.diffNeuronLFPFreq(modPyrStatsFNeuVsNoFNeu.indCurCNoField{clu}),'Neuron mod freq. - LFP freq. (Hz)',...
        'Pyr_DiffNeuronLFPFreqC1FieldBox',...
        pathAnal,[],modPyrStatsFNeuVsNoFNeu.pRSDiffNeuronLFPFreq(clu),colorSel,[{'deepF'} {'deepNoF'}]);
    
    plotBoxPlot(mod.thetaAsym3(modPyrStatsFNeuVsNoFNeu.indCurCField{clu}),...
        mod.thetaAsym3(modPyrStatsFNeuVsNoFNeu.indCurCNoField{clu}),'Theta asymmetry',...
        'Pyr_ThetaAsymC1FieldBox',pathAnal,[0.1 0.85],...
        modPyrStatsFNeuVsNoFNeu.pRSThetaAsym3(clu),colorSel,[{'deepF'} {'deepNoF'}]);
    
    