function plotCompPyrClu1RecFieldNoField(pathAnal, mod, modPyrStatsField, colorSel, clu1)
% compare neurons in the recordings with fields vs. in the recordings with no field in cluster 1
% This function is called by PryModAllrec.m

    plotBarPlot(mod.relDepthNeuHDef(modPyrStatsField.indCurCField{clu1}),...
        mod.relDepthNeuHDef(modPyrStatsField.indCurCNoField{clu1}),'Depth',...
        'Pyr_RelDepthNeuHDefCmpC1FieldRecBar',pathAnal,[-5 6],...
        modPyrStatsField.pKWRelDepthNeuHDef(clu1),colorSel);
        
    plotBoxPlot(mod.fractBurst(modPyrStatsField.indCurCField{clu1}),...
        mod.fractBurst(modPyrStatsField.indCurCNoField{clu1}),'Fract burst',...
        'Pyr_FractBurstC1FieldRecBox',pathAnal,[-0.1 0.85],...
        modPyrStatsField.pRSFractBurst(clu1),colorSel,[{'deepF'} {'deepNoF'}]);
    
    plotBoxPlot(mod.numSpPerBurstMean(modPyrStatsField.indCurCField{clu1}),...
        mod.numSpPerBurstMean(modPyrStatsField.indCurCNoField{clu1}),'Burst length',...
        'Pyr_NumSpPerBurstMeanC1FieldRecBox',pathAnal,[1.9 3.5],...
        modPyrStatsField.pRSNumSpPerBurstMean(clu1),colorSel,[{'deepF'} {'deepNoF'}]);
    
    plotBoxPlot(mod.thetaModHist(modPyrStatsField.indCurCField{clu1}),...
        mod.thetaModHist(modPyrStatsField.indCurCNoField{clu1}),'Theta modulation',...
        'Pyr_ThetaModHistC1FieldRecBox',pathAnal,[0 1.2],...
        modPyrStatsField.pRSThetaModHist(clu1),colorSel,[{'deepF'} {'deepNoF'}]);
    
    x = mod.phaseMeanDire;
    x(x > pi) = x(x > pi) - 2*pi;
    x = x/pi*180;
    plotBoxPlot(x(modPyrStatsField.indCurCField{clu1}),...
        x(modPyrStatsField.indCurCNoField{clu1}),'Mean theta phase (deg.)',...
        'Pyr_ThetaMeanC1FieldRecBox',pathAnal,[-120 180],...
        modPyrStatsField.pWWPhaseMeanDire(clu1),colorSel,[{'deepF'} {'deepNoF'}]);
    
    x = mod.burstMeanDire;
    x(x > pi) = x(x > pi) - 2*pi;
    x = x/pi*180;
    plotBoxPlot(x(modPyrStatsField.indCurCFieldBurst{clu1}),...
        x(modPyrStatsField.indCurCNoFieldBurst{clu1}),'Burst mean phase (deg.)',...
        'Pyr_BurstMeanDirC1FieldRecBox',pathAnal,[-180 180],...
        modPyrStatsField.pWWBurstMeanDire(clu1),colorSel,[{'deepF'} {'deepNoF'}]);
    
    x = mod.burstMeanDireStart;
    x(x > pi) = x(x > pi) - 2*pi;
    x = x/pi*180;
    plotBoxPlot(x(modPyrStatsField.indCurCFieldBurst{clu1}),...
        x(modPyrStatsField.indCurCNoFieldBurst{clu1}),'Burst start phase (deg.)',...
        'Pyr_BurstMeanDirStartC1FieldRecBox',pathAnal,[-180 180],...
        modPyrStatsField.pWWBurstMeanDireStart(clu1),colorSel,[{'deepF'} {'deepNoF'}]);
    
    plotBoxPlot(mod.burstThetaDiff(modPyrStatsField.indCurCFieldBurst{clu1})/pi*180,...
        mod.burstThetaDiff(modPyrStatsField.indCurCNoFieldBurst{clu1})/pi*180,...
        'Burst phase - theta phase (deg.)','Pyr_BurstPhase-ThetaPhaseC1FieldRecBox',...
        pathAnal,[],modPyrStatsField.pWWBurstThetaDiff(clu1),colorSel,[{'deepF'} {'deepNoF'}]);
    
    plotBoxPlot(mod.thetaModFreq3(modPyrStatsField.indCurCField{clu1}),...
        mod.thetaModFreq3(modPyrStatsField.indCurCNoField{clu1}),'Theta modulation frequency (Hz)',...
        'Pyr_ThetaModFreqC1FieldRecBox',pathAnal,[4 10.5],...
        modPyrStatsField.pRSThetaModFreq3(clu1),colorSel,[{'deepF'} {'deepNoF'}]);
    
    plotBoxPlot(mod.diffNeuronLFPFreq(modPyrStatsField.indCurCField{clu1}),...
        mod.diffNeuronLFPFreq(modPyrStatsField.indCurCNoField{clu1}),'Neuron mod freq. - LFP freq. (Hz)',...
        'Pyr_DiffNeuronLFPFreqC1FieldRecBox',...
        pathAnal,[],modPyrStatsField.pRSDiffNeuronLFPFreq(clu1),colorSel,[{'deepF'} {'deepNoF'}]);
    
    plotBoxPlot(mod.thetaAsym3(modPyrStatsField.indCurCField{clu1}),...
        mod.thetaAsym3(modPyrStatsField.indCurCNoField{clu1}),'Theta asymmetry',...
        'Pyr_ThetaAsymC1FieldRecBox',pathAnal,[0.1 0.85],...
        modPyrStatsField.pRSThetaAsym3(clu1),colorSel,[{'deepF'} {'deepNoF'}]);
    