function plotIntNeuStimIndNeu(pathAnal0,FRProfileMean1, modInt1AL, IntStim, FRProfile1)

    %% all interneurons
    for i = 1:length(FRProfileMean1)
        %% normalized
        %% order interneurons based on the peak firing rate after 0
        % and compare good non-stim with stim trials
        plotIndFRProfileCmp(modInt1AL.timeStepRun,...
                IntStim.avgFRProfileNorm(FRProfile1{i}.ind,:),...
                IntStim.avgFRProfileNormStim(FRProfile1{i}.ind,:),['Neuron no.'],...
                ['Int_IndFRProfileNormFRPeakAftRunNeuCmpGoodNoStimVsStim_Cond' num2str(i)],...
                pathAnal0,[],5,[],[])
        
        %% order interneurons based on before and after run FR ratio 
        % and compare good non-stim with stim trials
        plotIndFRProfileCmp(modInt1AL.timeStepRun,...
                IntStim.avgFRProfileNorm(FRProfile1{i}.ind,:),...
                IntStim.avgFRProfileNormStim(FRProfile1{i}.ind,:),['Neuron no.'],...
                ['Int_IndFRProfileNormFR0to1VsBefRunNeuCmpGoodNoStimVsStim_Cond' num2str(i)],...
                pathAnal0,[],4,FRProfileMean1{i}.indFRBefRun,...
                FRProfileMean1{i}.indFR0to1)
    
        %% compare good non stim trials with stim trials, int rise
        plotAvgFRProfileCmp(modInt1AL.timeStepRun,...
                IntStim.avgFRProfileNorm(FRProfile1{i}.ind,:),...
                IntStim.avgFRProfileNormStim(FRProfile1{i}.ind,:),...
                ['FR IntRise Norm'],...
                ['Int_FRProfileNormIntNoStimGoodVsStim_Cond' num2str(i)],...
                pathAnal0,[0 0.6],[{'GoodNoStim'},{'Stim'}])
                    
        %% not normalized, fields from good non-stim trials
        %% compare good non stim trials with stim trials, int rise
        plotAvgFRProfileCmp(modInt1AL.timeStepRun,...
                IntStim.avgFRProfile(FRProfile1{i}.ind,:),...
                IntStim.avgFRProfileStim(FRProfile1{i}.ind,:),...
                ['FR IntRise'],...
                ['Int_FRProfileIntNoStimGoodVsStim_Cond' num2str(i)],...
                pathAnal0,[],[{'GoodNoStim'},{'Stim'}])
                   
        %% stimctrl vs stim    
        %% order interneurons based on the peak firing rate after 0
        % and compare stim Ctrl with stim trials
        plotIndFRProfileCmp(modInt1AL.timeStepRun,...
                IntStim.avgFRProfileNormStimCtrl(FRProfile1{i}.ind,:),...
                IntStim.avgFRProfileNormStim(FRProfile1{i}.ind,:),['Neuron no.'],...
                ['Int_IndFRProfileNormFRPeakAftRunNeuCmpStimCtrlVsStim_Cond' num2str(i)],...
                pathAnal0,[],5,[],[])
        
        %% order interneurons based on before and after run FR ratio 
        % and compare stim Ctrl with stim trials
        plotIndFRProfileCmp(modInt1AL.timeStepRun,...
                IntStim.avgFRProfileNormStimCtrl(FRProfile1{i}.ind,:),...
                IntStim.avgFRProfileNormStim(FRProfile1{i}.ind,:),['Neuron no.'],...
                ['Int_IndFRProfileNormFR0to1VsBefRunNeuCmpStimCtrlVsStim_Cond' num2str(i)],...
                pathAnal0,[],4,FRProfileMean1{i}.indFRBefRun,...
                FRProfileMean1{i}.indFR0to1)
    
        %% compare stim Ctrl trials with stim trials, int rise
        plotAvgFRProfileCmp(modInt1AL.timeStepRun,...
                IntStim.avgFRProfileNormStimCtrl(FRProfile1{i}.ind,:),...
                IntStim.avgFRProfileNormStim(FRProfile1{i}.ind,:),...
                ['FR IntRise Norm'],...
                ['Int_FRProfileNormIntStimCtrlVsStim_Cond' num2str(i)],...
                pathAnal0,[0 0.6],[{'StimCtrl'},{'Stim'}])
                     
        %% not normalized, fields from stim Ctrl trials
        %% compare stim Ctrl  trials with stim trials, int rise
        plotAvgFRProfileCmp(modInt1AL.timeStepRun,...
                IntStim.avgFRProfileStimCtrl(FRProfile1{i}.ind,:),...
                IntStim.avgFRProfileStim(FRProfile1{i}.ind,:),...
                ['FR IntRise'],...
                ['Int_FRProfileIntStimCtrlVsStim_Cond' num2str(i)],...
                pathAnal0,[],[{'StimCtrl'},{'Stim'}])

    end