function plotIntNeuStimUpDown(pathAnal0,FRProfileMean1, modInt1AL, IntStim, FRProfile1,clu)

    %% all interneurons
    for i = 1:length(FRProfileMean1)
        %% normalized
        %% order interneurons based on the peak firing rate after 0
        % and compare good non-stim with stim trials
        plotIndFRProfileCmp(modInt1AL.timeStepRun,...
                IntStim.avgFRProfileNorm(FRProfile1{i}.ind,:),...
                IntStim.avgFRProfileNormStim(FRProfile1{i}.ind,:),['Neuron no.'],...
                ['Int_IndFRProfileNormFRPeakAftRunNeuCmpGoodNoStimVsStim_Cond' num2str(i) 'C' num2str(clu)],...
                pathAnal0,[],5,[],[])
        
        %% order interneurons based on before and after run FR ratio 
        % and compare good non-stim with stim trials
        plotIndFRProfileCmp(modInt1AL.timeStepRun,...
                IntStim.avgFRProfileNorm(FRProfile1{i}.ind,:),...
                IntStim.avgFRProfileNormStim(FRProfile1{i}.ind,:),['Neuron no.'],...
                ['Int_IndFRProfileNormFR0to1VsBefRunNeuCmpGoodNoStimVsStim_Cond' num2str(i) 'C' num2str(clu)],...
                pathAnal0,[],4,FRProfileMean1{i}.indFRBefRun,...
                FRProfileMean1{i}.indFR0to1)
    
        %% compare good non stim trials with stim trials, int rise
        plotAvgFRProfileCmp(modInt1AL.timeStepRun,...
                IntStim.avgFRProfileNorm(FRProfile1{i}.indIntRise,:),...
                IntStim.avgFRProfileNormStim(FRProfile1{i}.indIntRise,:),...
                ['FR IntRise Norm C' num2str(clu)],...
                ['Int_FRProfileNormIntRiseNoStimGoodVsStim_Cond' num2str(i) 'C' num2str(clu)],...
                pathAnal0,[0 0.6],[{'GoodNoStim'},{'Stim'}])
        
%         %% compare good non stim trials with stim trials, int down
%         plotAvgFRProfileCmp(modInt1AL.timeStepRun,...
%                 IntStim.avgFRProfileNorm(FRProfile1{i}.indIntDown,:),...
%                 IntStim.avgFRProfileNormStim(FRProfile1{i}.indIntDown,:),...
%                 ['FR IntDown Norm C' num2str(clu)],...
%                 ['Int_FRProfileNormIntDownNoStimGoodVsStim_Cond' num2str(i) 'C' num2str(clu)],...
%                 pathAnal0,[0 0.6],[{'GoodNoStim'},{'Stim'}])
            
        %% not normalized, fields from good non-stim trials
        %% compare good non stim trials with stim trials, int rise
        plotAvgFRProfileCmp(modInt1AL.timeStepRun,...
                IntStim.avgFRProfile(FRProfile1{i}.indIntRise,:),...
                IntStim.avgFRProfileStim(FRProfile1{i}.indIntRise,:),...
                ['FR IntRise C' num2str(clu)],...
                ['Int_FRProfileIntRiseNoStimGoodVsStim_Cond' num2str(i) 'C' num2str(clu)],...
                pathAnal0,[],[{'GoodNoStim'},{'Stim'}])
        
%         %% compare good non stim trials with stim trials, int down
%         plotAvgFRProfileCmp(modInt1AL.timeStepRun,...
%                 IntStim.avgFRProfile(FRProfile1{i}.indIntDown,:),...
%                 IntStim.avgFRProfileStim(FRProfile1{i}.indIntDown,:),...
%                 ['FR IntDown C' num2str(clu)],...
%                 ['Int_FRProfileIntDownNoStimGoodVsStim_Cond' num2str(i) 'C' num2str(clu)],...
%                 pathAnal0,[],[{'GoodNoStim'},{'Stim'}])
%             
                   
        %% stimctrl vs stim    
        %% order interneurons based on the peak firing rate after 0
        % and compare stim Ctrl with stim trials
        plotIndFRProfileCmp(modInt1AL.timeStepRun,...
                IntStim.avgFRProfileNormStimCtrl(FRProfile1{i}.ind,:),...
                IntStim.avgFRProfileNormStim(FRProfile1{i}.ind,:),['Neuron no.'],...
                ['Int_IndFRProfileNormFRPeakAftRunNeuCmpStimCtrlVsStim_Cond' num2str(i) 'C' num2str(clu)],...
                pathAnal0,[],5,[],[])
        
        %% order interneurons based on before and after run FR ratio 
        % and compare stim Ctrl with stim trials
        plotIndFRProfileCmp(modInt1AL.timeStepRun,...
                IntStim.avgFRProfileNormStimCtrl(FRProfile1{i}.ind,:),...
                IntStim.avgFRProfileNormStim(FRProfile1{i}.ind,:),['Neuron no.'],...
                ['Int_IndFRProfileNormFR0to1VsBefRunNeuCmpStimCtrlVsStim_Cond' num2str(i) 'C' num2str(clu)],...
                pathAnal0,[],4,FRProfileMean1{i}.indFRBefRun,...
                FRProfileMean1{i}.indFR0to1)
    
        %% compare stim Ctrl trials with stim trials, int rise
        plotAvgFRProfileCmp(modInt1AL.timeStepRun,...
                IntStim.avgFRProfileNormStimCtrl(FRProfile1{i}.indIntRise,:),...
                IntStim.avgFRProfileNormStim(FRProfile1{i}.indIntRise,:),...
                ['FR IntRise Norm C' num2str(clu)],...
                ['Int_FRProfileNormIntRiseStimCtrlVsStim_Cond' num2str(i) 'C' num2str(clu)],...
                pathAnal0,[0 0.6],[{'StimCtrl'},{'Stim'}])
        
%         %% compare stim Ctrl trials with stim trials, int down
%         plotAvgFRProfileCmp(modInt1AL.timeStepRun,...
%                 IntStim.avgFRProfileNormStimCtrl(FRProfile1{i}.indIntDown,:),...
%                 IntStim.avgFRProfileNormStim(FRProfile1{i}.indIntDown,:),...
%                 ['FR IntDown Norm C' num2str(clu)],...
%                 ['Int_FRProfileNormIntDownStimCtrlVsStim_Cond' num2str(i) 'C' num2str(clu)],...
%                 pathAnal0,[0 0.6],[{'StimCtrl'},{'Stim'}])
             
        %% not normalized, fields from stim Ctrl trials
        %% compare stim Ctrl  trials with stim trials, int rise
        plotAvgFRProfileCmp(modInt1AL.timeStepRun,...
                IntStim.avgFRProfileStimCtrl(FRProfile1{i}.indIntRise,:),...
                IntStim.avgFRProfileStim(FRProfile1{i}.indIntRise,:),...
                ['FR IntRise C' num2str(clu)],...
                ['Int_FRProfileIntRiseStimCtrlVsStim_Cond' num2str(i) 'C' num2str(clu)],...
                pathAnal0,[],[{'StimCtrl'},{'Stim'}])
        
%         %% compare stim Ctrl trials with stim trials, int down
%         plotAvgFRProfileCmp(modInt1AL.timeStepRun,...
%                 IntStim.avgFRProfileStimCtrl(FRProfile1{i}.indIntDown,:),...
%                 IntStim.avgFRProfileStim(FRProfile1{i}.indIntDown,:),...
%                 ['FR IntDown C' num2str(clu)],...
%                 ['Int_FRProfileIntDownStimCtrlVsStim_Cond' num2str(i) 'C' num2str(clu)],...
%                 pathAnal0,[],[{'StimCtrl'},{'Stim'}])
            
    end