function FRProfileMeanStatC = accumMeanPVStimStatC(FRProfileMean,idxC,nNeuWithField,isNeuWithField)
    
    numC = max(idxC);
    for i = 1:numC
        idxCI = idxC == i;
        
        %% recordings with field vs without field
        indCurCField = idxC == i & nNeuWithField >= 2;
        indCurCNoField = idxC == i & nNeuWithField < 1;
        FRProfileMeanStatC.pRS0to1VsBL(i) = ranksum(FRProfileMean.meanAvgFRProfileBaseline(idxCI),...
                    FRProfileMean.meanAvgFRProfile0to1(idxCI));
        FRProfileMeanStatC.pRS0to1VsBLField(i) = ranksum(FRProfileMean.meanAvgFRProfileBaseline(indCurCField),...
                    FRProfileMean.meanAvgFRProfile0to1(indCurCField));
        FRProfileMeanStatC.pRS0to1VsBLNoField(i) = ranksum(FRProfileMean.meanAvgFRProfileBaseline(indCurCNoField),...
                    FRProfileMean.meanAvgFRProfile0to1(indCurCNoField));        
                            
        FRProfileMeanStatC.pRSBefRunVsBL(i) = ranksum(FRProfileMean.meanAvgFRProfileBaseline(idxCI),...
                    FRProfileMean.meanAvgFRProfileBefRun(idxCI));
        FRProfileMeanStatC.pRSBefRunVsBLField(i) = ranksum(FRProfileMean.meanAvgFRProfileBaseline(indCurCField),...
                    FRProfileMean.meanAvgFRProfileBefRun(indCurCField));
        FRProfileMeanStatC.pRSBefRunVsBLNoField(i) = ranksum(FRProfileMean.meanAvgFRProfileBaseline(indCurCNoField),...
                    FRProfileMean.meanAvgFRProfileBefRun(indCurCNoField));
                
        FRProfileMeanStatC.pRS3to5VsBL(i) = ranksum(FRProfileMean.meanAvgFRProfileBaseline(idxCI),...
                    FRProfileMean.meanAvgFRProfile3to5(idxCI));
        FRProfileMeanStatC.pRS3to5VsBLField(i) = ranksum(FRProfileMean.meanAvgFRProfileBaseline(indCurCField),...
                    FRProfileMean.meanAvgFRProfile3to5(indCurCField));
        FRProfileMeanStatC.pRS3to5VsBLNoField(i) = ranksum(FRProfileMean.meanAvgFRProfileBaseline(indCurCNoField),...
                    FRProfileMean.meanAvgFRProfile3to5(indCurCNoField));
                
        FRProfileMeanStatC.pRSBefRunVs0to1(i) = ranksum(FRProfileMean.meanAvgFRProfile0to1(idxCI),...
                    FRProfileMean.meanAvgFRProfileBefRun(idxCI));
        FRProfileMeanStatC.pRSBefRunVs0to1Field(i) = ranksum(FRProfileMean.meanAvgFRProfile0to1(indCurCField),...
                    FRProfileMean.meanAvgFRProfileBefRun(indCurCField));
        FRProfileMeanStatC.pRSBefRunVs0to1NoField(i) = ranksum(FRProfileMean.meanAvgFRProfile0to1(indCurCNoField),...
                    FRProfileMean.meanAvgFRProfileBefRun(indCurCNoField));
                
        FRProfileMeanStatC.pRS3to5Vs0to1(i) = ranksum(FRProfileMean.meanAvgFRProfile0to1(idxCI),...
                    FRProfileMean.meanAvgFRProfile3to5(idxCI));
        FRProfileMeanStatC.pRS3to5Vs0to1Field(i) = ranksum(FRProfileMean.meanAvgFRProfile0to1(indCurCField),...
                    FRProfileMean.meanAvgFRProfile3to5(indCurCField));
        FRProfileMeanStatC.pRS3to5Vs0to1NoField(i) = ranksum(FRProfileMean.meanAvgFRProfile0to1(indCurCNoField),...
                    FRProfileMean.meanAvgFRProfile3to5(indCurCNoField));
                
        FRProfileMeanStatC.pRS3to5VsBefRun(i) = ranksum(FRProfileMean.meanAvgFRProfileBefRun(idxCI),...
                    FRProfileMean.meanAvgFRProfile3to5(idxCI));
        FRProfileMeanStatC.pRS3to5VsBefRunField(i) = ranksum(FRProfileMean.meanAvgFRProfileBefRun(indCurCField),...
                    FRProfileMean.meanAvgFRProfile3to5(indCurCField));
        FRProfileMeanStatC.pRS3to5VsBefRunNoField(i) = ranksum(FRProfileMean.meanAvgFRProfileBefRun(indCurCNoField),...
                    FRProfileMean.meanAvgFRProfile3to5(indCurCNoField));
                
        FRProfileMeanStatC.pTTPercChange0to1VsBL(i) = ttest(FRProfileMean.percChange0to1VsBL(idxCI));
        FRProfileMeanStatC.pRSPercChange0to1VsBLFieldVsNoField(i) = ...
            ranksum(FRProfileMean.percChange0to1VsBL(indCurCField),...
            FRProfileMean.percChange0to1VsBL(indCurCNoField));
        
        FRProfileMeanStatC.pTTPercChangeBefRunVsBL(i) = ttest(FRProfileMean.percChangeBefRunVsBL(idxCI));
        FRProfileMeanStatC.pRSPercChangeBefRunVsBLFieldVsNoField(i) = ...
            ranksum(FRProfileMean.percChangeBefRunVsBL(indCurCField),...
            FRProfileMean.percChangeBefRunVsBL(indCurCNoField));
        
        FRProfileMeanStatC.pTTPercChangeBefRunVs0to1(i) = ttest(FRProfileMean.percChangeBefRunVs0to1(idxCI));
        FRProfileMeanStatC.pRSPercChangeBefRunVs0to1FieldVsNoField(i) = ...
            ranksum(FRProfileMean.percChangeBefRunVs0to1(indCurCField),...
            FRProfileMean.percChangeBefRunVs0to1(indCurCNoField));
        
        FRProfileMeanStatC.pTTPercChange0to1Vs3to5(i) = ttest(FRProfileMean.percChange0to1Vs3to5(idxCI));
        FRProfileMeanStatC.pRSPercChange0to1Vs3to5FieldVsNoField(i) = ...
            ranksum(FRProfileMean.percChange0to1Vs3to5(indCurCField),...
            FRProfileMean.percChange0to1Vs3to5(indCurCNoField));
        
        FRProfileMeanStatC.pTTPercChangeBefRunVs3to5(i) = ttest(FRProfileMean.percChangeBefRunVs3to5(idxCI));
        FRProfileMeanStatC.pRSPercChangeBefRunVs3to5FieldVsNoField(i) = ...
            ranksum(FRProfileMean.percChangeBefRunVs3to5(indCurCField),...
            FRProfileMean.percChangeBefRunVs3to5(indCurCNoField));
        
        %% neurons with field vs without field
        indCurCField = idxC == i & isNeuWithField == 1;
        indCurCNoField = idxC == i & isNeuWithField == 0;
        FRProfileMeanStatC.pRS0to1VsBLFieldNeu(i) = ranksum(FRProfileMean.meanAvgFRProfileBaseline(indCurCField),...
                    FRProfileMean.meanAvgFRProfile0to1(indCurCField));
        FRProfileMeanStatC.pRS0to1VsBLNoFieldNeu(i) = ranksum(FRProfileMean.meanAvgFRProfileBaseline(indCurCNoField),...
                    FRProfileMean.meanAvgFRProfile0to1(indCurCNoField));        
                            
        FRProfileMeanStatC.pRSBefRunVsBLFieldNeu(i) = ranksum(FRProfileMean.meanAvgFRProfileBaseline(indCurCField),...
                    FRProfileMean.meanAvgFRProfileBefRun(indCurCField));
        FRProfileMeanStatC.pRSBefRunVsBLNoFieldNeu(i) = ranksum(FRProfileMean.meanAvgFRProfileBaseline(indCurCNoField),...
                    FRProfileMean.meanAvgFRProfileBefRun(indCurCNoField));
                
        FRProfileMeanStatC.pRSBefRunVs0to1FieldNeu(i) = ranksum(FRProfileMean.meanAvgFRProfile0to1(indCurCField),...
                    FRProfileMean.meanAvgFRProfileBefRun(indCurCField));
        FRProfileMeanStatC.pRSBefRunVs0to1NoFieldNeu(i) = ranksum(FRProfileMean.meanAvgFRProfile0to1(indCurCNoField),...
                    FRProfileMean.meanAvgFRProfileBefRun(indCurCNoField));
                
        FRProfileMeanStatC.pRS3to5VsBLFieldNeu(i) = ranksum(FRProfileMean.meanAvgFRProfileBaseline(indCurCField),...
                    FRProfileMean.meanAvgFRProfile3to5(indCurCField));
        FRProfileMeanStatC.pRS3to5VsBLNoFieldNeu(i) = ranksum(FRProfileMean.meanAvgFRProfileBaseline(indCurCNoField),...
                    FRProfileMean.meanAvgFRProfile3to5(indCurCNoField));
                
        FRProfileMeanStatC.pRS3to5Vs0to1FieldNeu(i) = ranksum(FRProfileMean.meanAvgFRProfile0to1(indCurCField),...
                    FRProfileMean.meanAvgFRProfile3to5(indCurCField));
        FRProfileMeanStatC.pRS3to5Vs0to1NoFieldNeu(i) = ranksum(FRProfileMean.meanAvgFRProfile0to1(indCurCNoField),...
                    FRProfileMean.meanAvgFRProfile3to5(indCurCNoField));
                
        FRProfileMeanStatC.pRS3to5VsBefRunFieldNeu(i) = ranksum(FRProfileMean.meanAvgFRProfileBefRun(indCurCField),...
                    FRProfileMean.meanAvgFRProfile3to5(indCurCField));
        FRProfileMeanStatC.pRS3to5VsBefRunNoFieldNeu(i) = ranksum(FRProfileMean.meanAvgFRProfileBefRun(indCurCNoField),...
                    FRProfileMean.meanAvgFRProfile3to5(indCurCNoField));
                
        FRProfileMeanStatC.pRSPercChange0to1VsBLFieldNeuVsNoFieldNeu(i) = ...
            ranksum(FRProfileMean.percChange0to1VsBL(indCurCField),...
            FRProfileMean.percChange0to1VsBL(indCurCNoField));
        
        FRProfileMeanStatC.pRSPercChangeBefRunVsBLFieldNeuVsNoFieldNeu(i) = ...
            ranksum(FRProfileMean.percChangeBefRunVsBL(indCurCField),...
            FRProfileMean.percChangeBefRunVsBL(indCurCNoField));
        
        FRProfileMeanStatC.pRSPercChangeBefRunVs0to1FieldNeuVsNoFieldNeu(i) = ...
            ranksum(FRProfileMean.percChangeBefRunVs0to1(indCurCField),...
            FRProfileMean.percChangeBefRunVs0to1(indCurCNoField));
        
        FRProfileMeanStatC.pRSPercChange0to1Vs3to5FieldNeuVsNoFieldNeu(i) = ...
            ranksum(FRProfileMean.percChange0to1Vs3to5(indCurCField),...
            FRProfileMean.percChange0to1Vs3to5(indCurCNoField));
        
        FRProfileMeanStatC.pRSPercChangeBefRunVs3to5FieldNeuVsNoFieldNeu(i) = ...
            ranksum(FRProfileMean.percChangeBefRunVs3to5(indCurCField),...
            FRProfileMean.percChangeBefRunVs3to5(indCurCNoField));
    end
end