function numField = PyrInitPeakPVStimField(pathAnal,pulseMethod,modPyr1AL)

    actOrInActStr{1} = 'inact';
    actOrInActStr{2} = 'act';
    
    pm3StimLoc{1} = unique(modPyr1AL.stimLocPerRec(modPyr1AL.pulseMethPerRec == 3 ...
        & modPyr1AL.actOrInactPerRec == 1)); 
    pm3StimLoc{2} = unique(modPyr1AL.stimLocPerRec(modPyr1AL.pulseMethPerRec == 3 ...
        & modPyr1AL.actOrInactPerRec == 2));
    
    % activation or inactivation
    cond = 0;
    for i = 1: 2
        % different pulse methods
        for j = 1:length(pulseMethod{i})
            if(pulseMethod{i}(j) == 3)
                stimLocs = pm3StimLoc{i};
            else
                stimLocs = 0;
            end
            for m = 1:length(stimLocs)
                
                indRec = find(modPyr1AL.actOrInactPerRec == i & modPyr1AL.pulseMethPerRec == pulseMethod{i}(j) ...
                    & modPyr1AL.stimLocPerRec == stimLocs(m));
                if(isempty(indRec))
                    continue;
                end
                cond = cond + 1;
                numField{cond}.actOrInact = i;
                numField{cond}.pulseMethod = pulseMethod{i}(j);
                numField{cond}.stimLoc = stimLocs(m);
                numField{cond}.indRec = modPyr1AL.indRecPerRec(indRec);
                numField{cond}.nNeuWithFieldAlignedPerRec = modPyr1AL.nNeuWithFieldAlignedPerRec(indRec);
                numField{cond}.nNeuWithFieldAlignedPerRecGoodNonStim = modPyr1AL.nNeuWithFieldAlignedPerRecGoodNonStim(indRec);
                numField{cond}.nNeuWithFieldAlignedPerRecStim = modPyr1AL.nNeuWithFieldAlignedPerRecStim(indRec);
                numField{cond}.nNeuWithFieldAlignedPerRecStimCtrl = modPyr1AL.nNeuWithFieldAlignedPerRecStimCtrl(indRec);

                numField{cond}.percNeuWithFieldAlignedPerRec = modPyr1AL.nNeuWithFieldAlignedPerRec(indRec)...
                    ./modPyr1AL.nNeuPerRec(indRec);
                numField{cond}.percNeuWithFieldAlignedPerRecGoodNonStim = modPyr1AL.nNeuWithFieldAlignedPerRecGoodNonStim(indRec)...
                    ./modPyr1AL.nNeuPerRec(indRec);
                numField{cond}.percNeuWithFieldAlignedPerRecStim = modPyr1AL.nNeuWithFieldAlignedPerRecStim(indRec)...
                    ./modPyr1AL.nNeuPerRec(indRec);
                numField{cond}.percNeuWithFieldAlignedPerRecStimCtrl = modPyr1AL.nNeuWithFieldAlignedPerRecStimCtrl(indRec)...
                    ./modPyr1AL.nNeuPerRec(indRec);

                numField{cond}.pRSNumFieldGoodNonStimVsStim = ranksum(...
                    numField{cond}.nNeuWithFieldAlignedPerRecGoodNonStim, numField{cond}.nNeuWithFieldAlignedPerRecStim);
                numField{cond}.pRSNumFieldStimVsStimCtrl = ranksum(...
                    numField{cond}.nNeuWithFieldAlignedPerRecStim, numField{cond}.nNeuWithFieldAlignedPerRecStimCtrl);

                numField{cond}.pRSPercFieldGoodNonStimVsStim = ranksum(...
                    numField{cond}.percNeuWithFieldAlignedPerRecGoodNonStim,numField{cond}.percNeuWithFieldAlignedPerRecStim);
                numField{cond}.pRSPercFieldStimVsStimCtrl = ranksum(...
                    numField{cond}.percNeuWithFieldAlignedPerRecStim,numField{cond}.percNeuWithFieldAlignedPerRecStimCtrl);

                colorSel = 0;
                % field good non-stim vs. stim
                barPlotWithStat3(1:2,...
                    [mean(numField{cond}.nNeuWithFieldAlignedPerRecGoodNonStim),...
                    mean(numField{cond}.nNeuWithFieldAlignedPerRecStim)],...
                    [std(numField{cond}.nNeuWithFieldAlignedPerRecGoodNonStim)/sqrt(length(numField{cond}.nNeuWithFieldAlignedPerRecGoodNonStim)),...
                    std(numField{cond}.nNeuWithFieldAlignedPerRecStim)/sqrt(length(numField{cond}.nNeuWithFieldAlignedPerRecStim))],...
                    numField{cond}.nNeuWithFieldAlignedPerRecGoodNonStim,...
                    numField{cond}.nNeuWithFieldAlignedPerRecStim,...
                    ['No. fields ' actOrInActStr{i} '-' num2str(pulseMethod{i}(j)) '-' num2str(stimLocs(m))],...
                    '', numField{cond}.pRSNumFieldGoodNonStimVsStim,...
                    ['NumFieldAlignedGoodNoStimVsStim_' actOrInActStr{i} '_P' num2str(pulseMethod{i}(j)) '_sl' num2str(stimLocs(m))],...
                    pathAnal,colorSel,[{'Nonstim'} {'Stim'}]);

                % field stim ctrl vs stim
                barPlotWithStat3(1:2,...
                    [mean(numField{cond}.nNeuWithFieldAlignedPerRecStimCtrl),...
                    mean(numField{cond}.nNeuWithFieldAlignedPerRecStim)],...
                    [std(numField{cond}.nNeuWithFieldAlignedPerRecStimCtrl)/sqrt(length(numField{cond}.nNeuWithFieldAlignedPerRecStimCtrl)),...
                    std(numField{cond}.nNeuWithFieldAlignedPerRecStim)/sqrt(length(numField{cond}.nNeuWithFieldAlignedPerRecStim))],...
                    numField{cond}.nNeuWithFieldAlignedPerRecStimCtrl,...
                    numField{cond}.nNeuWithFieldAlignedPerRecStim,...
                    ['No. fields ' actOrInActStr{i} '-' num2str(pulseMethod{i}(j)) '-' num2str(stimLocs(m))],...
                    '',numField{cond}.pRSNumFieldStimVsStimCtrl,...
                    ['NumFieldAlignedStimCtrlVsStim_' actOrInActStr{i} '_P' num2str(pulseMethod{i}(j)) '_sl' num2str(stimLocs(m))],...
                    pathAnal,colorSel,[{'StimCtrl'} {'Stim'}]);

                % field good non-stim vs. stim
                barPlotWithStat3(1:2,...
                    [mean(numField{cond}.percNeuWithFieldAlignedPerRecGoodNonStim),...
                    mean(numField{cond}.percNeuWithFieldAlignedPerRecStim)],...
                    [std(numField{cond}.percNeuWithFieldAlignedPerRecGoodNonStim)/sqrt(length(numField{cond}.percNeuWithFieldAlignedPerRecGoodNonStim)),...
                    std(numField{cond}.percNeuWithFieldAlignedPerRecStim)/sqrt(length(numField{cond}.percNeuWithFieldAlignedPerRecStim))],...
                    numField{cond}.percNeuWithFieldAlignedPerRecGoodNonStim,...
                    numField{cond}.percNeuWithFieldAlignedPerRecStim,...
                    ['Perc. fields ' actOrInActStr{i} '-' num2str(pulseMethod{i}(j)) '-' num2str(stimLocs(m))],...
                    '',numField{cond}.pRSPercFieldGoodNonStimVsStim,...
                    ['PercFieldAlignedGoodNoStimVsStim_' actOrInActStr{i} '_P' num2str(pulseMethod{i}(j)) '_sl' num2str(stimLocs(m))],...
                    pathAnal,colorSel,[{'Nonstim'} {'Stim'}]);

                % field stim ctrl vs stim
                barPlotWithStat3(1:2,...
                    [mean(numField{cond}.percNeuWithFieldAlignedPerRecStimCtrl),...
                    mean(numField{cond}.percNeuWithFieldAlignedPerRecStim)],...
                    [std(numField{cond}.percNeuWithFieldAlignedPerRecStimCtrl)/sqrt(length(numField{cond}.percNeuWithFieldAlignedPerRecStimCtrl)),...
                    std(numField{cond}.percNeuWithFieldAlignedPerRecStim)/sqrt(length(numField{cond}.percNeuWithFieldAlignedPerRecStim))],...
                    numField{cond}.percNeuWithFieldAlignedPerRecStimCtrl,...
                    numField{cond}.percNeuWithFieldAlignedPerRecStim,...
                    ['Perc. fields ' actOrInActStr{i} '-' num2str(pulseMethod{i}(j)) '-' num2str(stimLocs(m))],...
                    '',numField{cond}.pRSPercFieldStimVsStimCtrl,...
                    ['PercFieldAlignedStimCtrlVsStim_' actOrInActStr{i} '_P' num2str(pulseMethod{i}(j)) '_sl' num2str(stimLocs(m))],...
                    pathAnal,colorSel,[{'StimCtrl'} {'Stim'}]);
            end
        end
    end
    
end