function plotIntNeuRiseDownTaggedAllPVNonPV(pathAnal,timeStepRun,...
            InitAll,FRProfileMean,cluPV)

        idxCTmp = find(InitAll.idxC2Int ~= cluPV(1));
        idxCTmp = intersect(idxCTmp,InitAll.goodNeuInt);
        
        %% order pyramidal neurons with field based on the peak firing rate after 0
        plotIndFRProfile(timeStepRun,...
                InitAll.avgFRProfileNormInt(idxCTmp,:),['FR (Hz)  No C' num2str(cluPV(1))],...
                ['Int_IndFRProfileNormFRPeakAftRunNeuNoPVC' num2str(cluPV(1))],...
                pathAnal,[],5,[],[])

        indTmp = timeStepRun > 0;
        [~,indMax] = max(InitAll.avgFRProfileNormInt(idxCTmp,indTmp)');
        [~,indOrd] = sort(indMax,'descend');
        plotIndFRProfileProvOrder(timeStepRun,...
                InitAll.avgFRProfileNormBadInt(idxCTmp,:),['FR (Hz) Bad No C' num2str(cluPV(1))],...
                ['Int_IndFRProfileNormFRPeakAftRunNeuNoPVBadC' num2str(cluPV(1))],...
                pathAnal,indOrd);

        %% order pyramidal neurons with field based on before and after run FR ratio  
        plotIndFRProfile(timeStepRun,...
                InitAll.avgFRProfileNormInt(idxCTmp,:),['FR (Hz) No C' num2str(cluPV(1))],...
                ['Int_IndFRProfileNormFR0to1VsBefRunNeuNoPVC' num2str(cluPV(1))],...
                pathAnal,[],4,FRProfileMean.indFRBefRun,...
                FRProfileMean.indFR0to1) % ordered based on -1to0 to 0to1 mean ratio

        indMax1 = mean(InitAll.avgFRProfileNormInt(idxCTmp,FRProfileMean.indFRBefRun)');
        indMax2 = mean(InitAll.avgFRProfileNormInt(idxCTmp,FRProfileMean.indFR0to1)');
        indMax = indMax1./indMax2;
        [~,indOrd] = sort(indMax,'descend');
        plotIndFRProfileProvOrder(timeStepRun,...
                InitAll.avgFRProfileNormBadInt(idxCTmp,:),['FR (Hz) Bad No C' num2str(cluPV(1))],...
                ['Int_IndFRProfileNormFR0to1VsBefRunNeuNoPVBadC' num2str(cluPV(1))],...
                pathAnal,indOrd); % ordered based on -1to0 to 0to1 mean ratio

       
end