function plotPyrNeuRiseDownFVsNoF(pathAnal,timeStepRun,...
            InitAll,PyrRiseF,PyrRiseNoF,PyrDownF,PyrDownNoF,...
            PyrOtherF,PyrOtherNoF,FRProfileMeanPyr,...
            FRProfileMeanPyrStat,colorSel,xlabels)

    
    %% average profile No cue vs AL
    plotAvgFRProfileCmp(timeStepRun,...
            InitAll.avgFRProfile(PyrRiseNoF.idxRise,:),...
            InitAll.avgFRProfile(PyrRiseF.idxRise,:),...
            ['FR PyrRise NoF/F'],...
            ['Pyr_FRProfilePyrRiseFNoF'],...
            pathAnal,[0 4],xlabels)
        
    plotAvgFRProfileCmp(timeStepRun,...
            InitAll.avgFRProfile(PyrDownNoF.idxDown,:),...
            InitAll.avgFRProfile(PyrDownF.idxDown,:),...
            ['FR PyrDown NoF/F'],...
            ['Pyr_FRProfilePyrDownFNoF'],...
            pathAnal,[0 4],xlabels)
        
    % add on 7/9/2022
    plotAvgFRProfileCmp(timeStepRun,...
            InitAll.avgFRProfile(PyrOtherNoF.idxOther,:),...
            InitAll.avgFRProfile(PyrOtherF.idxOther,:),...
            ['FR PyrOther NoF/F'],...
            ['Pyr_FRProfilePyrOtherFNoF'],...
            pathAnal,[0 2.6],xlabels)
        
    plotAvgFRProfileCmp(timeStepRun,...
            InitAll.avgFRProfileNorm(PyrRiseNoF.idxRise,:),...
            InitAll.avgFRProfileNorm(PyrRiseF.idxRise,:),...
            ['FR Norm PyrRise NoF/F'],...
            ['Pyr_FRProfileNormPyrRiseFNoF'],...
            pathAnal,[0 0.6],xlabels)
        
    plotAvgFRProfileCmp(timeStepRun,...
            InitAll.avgFRProfileNorm(PyrDownNoF.idxDown,:),...
            InitAll.avgFRProfileNorm(PyrDownF.idxDown,:),...
            ['FR Norm PyrDown NoF/F'],...
            ['Pyr_FRProfileNormPyrDownFNoF'],...
            pathAnal,[0 0.6],xlabels)

    % add on 7/9/2022
    plotAvgFRProfileCmp(timeStepRun,...
            InitAll.avgFRProfileNorm(PyrOtherNoF.idxOther,:),...
            InitAll.avgFRProfileNorm(PyrOtherF.idxOther,:),...
            ['FR Norm PyrOther NoF/F'],...
            ['Pyr_FRProfileNormPyrOtherFNoF'],...
            pathAnal,[0 0.6],xlabels)
        
    %% FR Change before run vs 0to1s
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyr.RiseNoF.percChangeBefRunVs0to1),...
            mean(FRProfileMeanPyr.RiseF.percChangeBefRunVs0to1)],...
            [std(FRProfileMeanPyr.RiseNoF.percChangeBefRunVs0to1)...
                /sqrt(length(FRProfileMeanPyr.RiseNoF.percChangeBefRunVs0to1)),...
            std(FRProfileMeanPyr.RiseF.percChangeBefRunVs0to1)...
                /sqrt(length(FRProfileMeanPyr.RiseF.percChangeBefRunVs0to1))],...
            [],...
            ['average FR change BefRun/0to1s NoF/F Rise'],...
            '', FRProfileMeanPyrStat.Rise.pRSPercChangeBefRunVs0to1All,...
            ['Pyr_FRChangeBefRun-0to1RiseFNoF'],...
            pathAnal,colorSel,xlabels);
        
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyr.DownNoF.percChangeBefRunVs0to1),...
            mean(FRProfileMeanPyr.DownF.percChangeBefRunVs0to1)],...
            [std(FRProfileMeanPyr.DownNoF.percChangeBefRunVs0to1)...
                /sqrt(length(FRProfileMeanPyr.DownNoF.percChangeBefRunVs0to1)),...
            std(FRProfileMeanPyr.DownF.percChangeBefRunVs0to1)...
                /sqrt(length(FRProfileMeanPyr.DownF.percChangeBefRunVs0to1))],...
            [],...
            ['average FR change BefRun/0to1s NoF/F Down'],...
            '', FRProfileMeanPyrStat.Down.pRSPercChangeBefRunVs0to1All,...
            ['Pyr_FRChangeBefRun-0to1DownFNoF'],...
            pathAnal,colorSel,xlabels);
        
    % add on 7/9/2022
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyr.OtherNoF.percChangeBefRunVs0to1),...
            mean(FRProfileMeanPyr.OtherF.percChangeBefRunVs0to1)],...
            [std(FRProfileMeanPyr.OtherNoF.percChangeBefRunVs0to1)...
                /sqrt(length(FRProfileMeanPyr.OtherNoF.percChangeBefRunVs0to1)),...
            std(FRProfileMeanPyr.OtherF.percChangeBefRunVs0to1)...
                /sqrt(length(FRProfileMeanPyr.OtherF.percChangeBefRunVs0to1))],...
            [],...
            ['average FR change BefRun/0to1s NoF/F Other'],...
            '', FRProfileMeanPyrStat.Other.pRSPercChangeBefRunVs0to1All,...
            ['Pyr_FRChangeBefRun-0to1OtherFNoF'],...
            pathAnal,colorSel,xlabels);
   
    %% FR rel Change before run vs 0to1s
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyr.RiseNoF.relChangeBefRunVs0to1),...
            mean(FRProfileMeanPyr.RiseF.relChangeBefRunVs0to1)],...
            [std(FRProfileMeanPyr.RiseNoF.relChangeBefRunVs0to1)...
                /sqrt(length(FRProfileMeanPyr.RiseNoF.relChangeBefRunVs0to1)),...
            std(FRProfileMeanPyr.RiseF.relChangeBefRunVs0to1)...
                /sqrt(length(FRProfileMeanPyr.RiseF.relChangeBefRunVs0to1))],...
            [],...
            ['rel. FR change BefRun/0to1s NoF/F Rise'],...
            '', FRProfileMeanPyrStat.Rise.pRSRelChangeBefRunVs0to1All,...
            ['Pyr_RelFRChangeBefRun-0to1RiseFNoF'],...
            pathAnal,colorSel,xlabels,[-0.65 0.65]);
        
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyr.DownNoF.relChangeBefRunVs0to1),...
            mean(FRProfileMeanPyr.DownF.relChangeBefRunVs0to1)],...
            [std(FRProfileMeanPyr.DownNoF.relChangeBefRunVs0to1)...
                /sqrt(length(FRProfileMeanPyr.DownNoF.relChangeBefRunVs0to1)),...
            std(FRProfileMeanPyr.DownF.relChangeBefRunVs0to1)...
                /sqrt(length(FRProfileMeanPyr.DownF.relChangeBefRunVs0to1))],...
            [],...
            ['rel. FR change BefRun/0to1s NoF/F Down'],...
            '', FRProfileMeanPyrStat.Down.pRSRelChangeBefRunVs0to1All,...
            ['Pyr_RelFRChangeBefRun-0to1DownFNoF'],...
            pathAnal,colorSel,xlabels,[-0.65 0.65]);
        
    % add on 7/9/2022
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyr.OtherNoF.relChangeBefRunVs0to1),...
            mean(FRProfileMeanPyr.OtherF.relChangeBefRunVs0to1)],...
            [std(FRProfileMeanPyr.OtherNoF.relChangeBefRunVs0to1)...
                /sqrt(length(FRProfileMeanPyr.OtherNoF.relChangeBefRunVs0to1)),...
            std(FRProfileMeanPyr.OtherF.relChangeBefRunVs0to1)...
                /sqrt(length(FRProfileMeanPyr.OtherF.relChangeBefRunVs0to1))],...
            [],...
            ['rel. FR change BefRun/0to1s NoF/F Other'],...
            '', FRProfileMeanPyrStat.Other.pRSRelChangeBefRunVs0to1All,...
            ['Pyr_RelFRChangeBefRun-0to1OtherFNoF'],...
            pathAnal,colorSel,xlabels,[-0.65 0.65]);
   
    %% FR between -1 to 4s    
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyr.RiseNoF.meanAvgFRProfileAll),...
            mean(FRProfileMeanPyr.RiseF.meanAvgFRProfileAll)],...
            [std(FRProfileMeanPyr.RiseNoF.meanAvgFRProfileAll)...
                /sqrt(length(FRProfileMeanPyr.RiseNoF.meanAvgFRProfileAll)),...
            std(FRProfileMeanPyr.RiseF.meanAvgFRProfileAll)...
                /sqrt(length(FRProfileMeanPyr.RiseF.meanAvgFRProfileAll))],...
            [],...
            ['average FR All NoF/F Rise'],...
            '', FRProfileMeanPyrStat.Rise.pRSAll,...
            ['Pyr_FRAllRiseFNoF'],...
            pathAnal,colorSel,xlabels,[0 4]);
        
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyr.DownNoF.meanAvgFRProfileAll),...
            mean(FRProfileMeanPyr.DownF.meanAvgFRProfileAll)],...
            [std(FRProfileMeanPyr.DownNoF.meanAvgFRProfileAll)...
                /sqrt(length(FRProfileMeanPyr.DownNoF.meanAvgFRProfileAll)),...
            std(FRProfileMeanPyr.DownF.meanAvgFRProfileAll)...
                /sqrt(length(FRProfileMeanPyr.DownF.meanAvgFRProfileAll))],...
            [],...
            ['average FR All NoF/F Down'],...
            '', FRProfileMeanPyrStat.Down.pRSAll,...
            ['Pyr_FRAllDownFNoF'],...
            pathAnal,colorSel,xlabels,[0 4]);
        
    % add on 7/9/2022
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyr.OtherNoF.meanAvgFRProfileAll),...
            mean(FRProfileMeanPyr.OtherF.meanAvgFRProfileAll)],...
            [std(FRProfileMeanPyr.OtherNoF.meanAvgFRProfileAll)...
                /sqrt(length(FRProfileMeanPyr.OtherNoF.meanAvgFRProfileAll)),...
            std(FRProfileMeanPyr.OtherF.meanAvgFRProfileAll)...
                /sqrt(length(FRProfileMeanPyr.OtherF.meanAvgFRProfileAll))],...
            [],...
            ['average FR All NoF/F Other'],...
            '', FRProfileMeanPyrStat.Other.pRSAll,...
            ['Pyr_FRAllOtherFNoF'],...
            pathAnal,colorSel,xlabels,[0 4]);
        
    %% FR before run    
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyr.RiseNoF.meanAvgFRProfileBefRun),...
            mean(FRProfileMeanPyr.RiseF.meanAvgFRProfileBefRun)],...
            [std(FRProfileMeanPyr.RiseNoF.meanAvgFRProfileBefRun)...
                /sqrt(length(FRProfileMeanPyr.RiseNoF.meanAvgFRProfileBefRun)),...
            std(FRProfileMeanPyr.RiseF.meanAvgFRProfileBefRun)...
                /sqrt(length(FRProfileMeanPyr.RiseF.meanAvgFRProfileBefRun))],...
            [],...
            ['average FR BefRun NoF/F Rise'],...
            '', FRProfileMeanPyrStat.Rise.pRSBefRunAll,...
            ['Pyr_FRBefRunRiseFNoF'],...
            pathAnal,colorSel,xlabels,[0 4]);
        
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyr.DownNoF.meanAvgFRProfileBefRun),...
            mean(FRProfileMeanPyr.DownF.meanAvgFRProfileBefRun)],...
            [std(FRProfileMeanPyr.DownNoF.meanAvgFRProfileBefRun)...
                /sqrt(length(FRProfileMeanPyr.DownNoF.meanAvgFRProfileBefRun)),...
            std(FRProfileMeanPyr.DownF.meanAvgFRProfileBefRun)...
                /sqrt(length(FRProfileMeanPyr.DownF.meanAvgFRProfileBefRun))],...
            [],...
            ['average FR BefRun NoF/F Down'],...
            '', FRProfileMeanPyrStat.Down.pRSBefRunAll,...
            ['Pyr_FRBefRunDownFNoF'],...
            pathAnal,colorSel,xlabels,[0 4]);
        
    % add on 7/9/2022
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyr.OtherNoF.meanAvgFRProfileBefRun),...
            mean(FRProfileMeanPyr.OtherF.meanAvgFRProfileBefRun)],...
            [std(FRProfileMeanPyr.OtherNoF.meanAvgFRProfileBefRun)...
                /sqrt(length(FRProfileMeanPyr.OtherNoF.meanAvgFRProfileBefRun)),...
            std(FRProfileMeanPyr.OtherF.meanAvgFRProfileBefRun)...
                /sqrt(length(FRProfileMeanPyr.OtherF.meanAvgFRProfileBefRun))],...
            [],...
            ['average FR BefRun NoF/F Other'],...
            '', FRProfileMeanPyrStat.Other.pRSBefRunAll,...
            ['Pyr_FRBefRunOtherFNoF'],...
            pathAnal,colorSel,xlabels,[0 4]);
    
    %% FR 0 to 1s
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyr.RiseNoF.meanAvgFRProfile0to1),...
            mean(FRProfileMeanPyr.RiseF.meanAvgFRProfile0to1)],...
            [std(FRProfileMeanPyr.RiseNoF.meanAvgFRProfile0to1)...
                /sqrt(length(FRProfileMeanPyr.RiseNoF.meanAvgFRProfile0to1)),...
            std(FRProfileMeanPyr.RiseF.meanAvgFRProfile0to1)...
                /sqrt(length(FRProfileMeanPyr.RiseF.meanAvgFRProfile0to1))],...
            [],...
            ['average FR 0to1s NoF/F Rise'],...
            '', FRProfileMeanPyrStat.Rise.pRS0to1All,...
            ['Pyr_FR0to1sRiseFNoF'],...
            pathAnal,colorSel,xlabels,[0 5]);
        
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyr.DownNoF.meanAvgFRProfile0to1),...
            mean(FRProfileMeanPyr.DownF.meanAvgFRProfile0to1)],...
            [std(FRProfileMeanPyr.DownNoF.meanAvgFRProfile0to1)...
                /sqrt(length(FRProfileMeanPyr.DownNoF.meanAvgFRProfile0to1)),...
            std(FRProfileMeanPyr.DownF.meanAvgFRProfile0to1)...
                /sqrt(length(FRProfileMeanPyr.DownF.meanAvgFRProfile0to1))],...
            [],...
            ['average FR 0to1s NoF/F Down'],...
            '', FRProfileMeanPyrStat.Down.pRS0to1All,...
            ['Pyr_FR0to1sDownFNoF'],...
            pathAnal,colorSel,xlabels,[0 4]);
        
    % add on 7/9/2022
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyr.OtherNoF.meanAvgFRProfile0to1),...
            mean(FRProfileMeanPyr.OtherF.meanAvgFRProfile0to1)],...
            [std(FRProfileMeanPyr.OtherNoF.meanAvgFRProfile0to1)...
                /sqrt(length(FRProfileMeanPyr.OtherNoF.meanAvgFRProfile0to1)),...
            std(FRProfileMeanPyr.OtherF.meanAvgFRProfile0to1)...
                /sqrt(length(FRProfileMeanPyr.OtherF.meanAvgFRProfile0to1))],...
            [],...
            ['average FR 0to1s NoF/F Other'],...
            '', FRProfileMeanPyrStat.Other.pRS0to1All,...
            ['Pyr_FR0to1sOtherFNoF'],...
            pathAnal,colorSel,xlabels,[0 4]);
end