function mod = IntModRunSegAllRecByType(autoCorrIntNoCue,autoCorrIntAL,autoCorrIntPL,...
    modIntNoCue,modIntAL,modIntPL,modSegIntNoCue,modSegIntAL,modSegIntPL,taskSel,methodKMean)

    if(taskSel == 1)
        mod.task = [autoCorrIntNoCue.task autoCorrIntAL.task autoCorrIntPL.task];
        mod.indRec = [autoCorrIntNoCue.indRec autoCorrIntAL.indRec autoCorrIntPL.indRec];
        mod.nNeuWithField = [modIntNoCue.nNeuWithField modIntAL.nNeuWithField modIntPL.nNeuWithField];

        mod.thetaModHistBefRun = [modSegIntNoCue.thetaModHistBefRun ...
            modSegIntAL.thetaModHistBefRun modSegIntPL.thetaModHistBefRun];
        mod.phaseMeanDireBefRun = [modSegIntNoCue.phaseMeanDireBefRun ...
            modSegIntAL.phaseMeanDireBefRun modSegIntPL.phaseMeanDireBefRun];
        mod.maxPhaseArrBefRun = [modSegIntNoCue.maxPhaseFilBefRun ...
            modSegIntAL.maxPhaseFilBefRun modSegIntPL.maxPhaseFilBefRun];
        mod.minPhaseArrBefRun = [modSegIntNoCue.minPhaseFilBefRun ...
            modSegIntAL.minPhaseFilBefRun modSegIntPL.minPhaseFilBefRun];
        mod.phaseMeanResultantLenBefRun = [modSegIntNoCue.phaseMeanResultantLenBefRun ...
            modSegIntAL.phaseMeanResultantLenBefRun modSegIntPL.phaseMeanResultantLenBefRun];

        mod.thetaModHist0to1 = [modSegIntNoCue.thetaModHist0to1 ...
            modSegIntAL.thetaModHist0to1 modSegIntPL.thetaModHist0to1];
        mod.thetaModHistH0to1 = [modSegIntNoCue.thetaModHistH0to1 ...
            modSegIntAL.thetaModHistH0to1 modSegIntPL.thetaModHistH0to1];
        mod.phaseMeanDire0to1 = [modSegIntNoCue.phaseMeanDire0to1 ...
            modSegIntAL.phaseMeanDire0to1 modSegIntPL.phaseMeanDire0to1];
        mod.phaseMeanDireH0to1 = [modSegIntNoCue.phaseMeanDireH0to1 ...
            modSegIntAL.phaseMeanDireH0to1 modSegIntPL.phaseMeanDireH0to1];
        mod.maxPhaseArr0to1 = [modSegIntNoCue.maxPhaseFil0to1 ...
            modSegIntAL.maxPhaseFil0to1 modSegIntPL.maxPhaseFil0to1];
        mod.maxPhaseArrH0to1 = [modSegIntNoCue.maxPhaseFilH0to1 ...
            modSegIntAL.maxPhaseFilH0to1 modSegIntPL.maxPhaseFilH0to1];
        mod.minPhaseArr0to1 = [modSegIntNoCue.minPhaseFil0to1 ...
            modSegIntAL.minPhaseFil0to1 modSegIntPL.minPhaseFil0to1];
        mod.minPhaseArrH0to1 = [modSegIntNoCue.minPhaseFilH0to1 ...
            modSegIntAL.minPhaseFilH0to1 modSegIntPL.minPhaseFilH0to1];
        mod.phaseMeanResultantLen0to1 = [modSegIntNoCue.phaseMeanResultantLen0to1 ...
            modSegIntAL.phaseMeanResultantLen0to1 modSegIntPL.phaseMeanResultantLen0to1];

        mod.thetaModHist3to5 = [modSegIntNoCue.thetaModHist3to5 ...
            modSegIntAL.thetaModHist3to5 modSegIntPL.thetaModHist3to5];
        mod.thetaModHistH3to5 = [modSegIntNoCue.thetaModHistH3to5 ...
            modSegIntAL.thetaModHistH3to5 modSegIntPL.thetaModHistH3to5];
        mod.phaseMeanDire3to5 = [modSegIntNoCue.phaseMeanDire3to5 ...
            modSegIntAL.phaseMeanDire3to5 modSegIntPL.phaseMeanDire3to5];
        mod.phaseMeanDireH3to5 = [modSegIntNoCue.phaseMeanDireH3to5 ...
            modSegIntAL.phaseMeanDireH3to5 modSegIntPL.phaseMeanDireH3to5];
        mod.maxPhaseArr3to5 = [modSegIntNoCue.maxPhaseFil3to5 ...
            modSegIntAL.maxPhaseFil3to5 modSegIntPL.maxPhaseFil3to5];
        mod.maxPhaseArrH3to5 = [modSegIntNoCue.maxPhaseFilH3to5 ...
            modSegIntAL.maxPhaseFilH3to5 modSegIntPL.maxPhaseFilH3to5];
        mod.minPhaseArr3to5 = [modSegIntNoCue.minPhaseFil3to5 ...
            modSegIntAL.minPhaseFil3to5 modSegIntPL.minPhaseFil3to5];
        mod.minPhaseArrH3to5 = [modSegIntNoCue.minPhaseFilH3to5 ...
            modSegIntAL.minPhaseFilH3to5 modSegIntPL.minPhaseFilH3to5];
        mod.phaseMeanResultantLen3to5 = [modSegIntNoCue.phaseMeanResultantLen3to5 ...
            modSegIntAL.phaseMeanResultantLen3to5 modSegIntPL.phaseMeanResultantLen3to5];

        mod.thetaModHist3to4 = [modSegIntNoCue.thetaModHist3to4 ...
            modSegIntAL.thetaModHist3to4 modSegIntPL.thetaModHist3to4];
        mod.thetaModHistH3to4 = [modSegIntNoCue.thetaModHistH3to4 ...
            modSegIntAL.thetaModHistH3to4 modSegIntPL.thetaModHistH3to4];
        mod.phaseMeanDire3to4 = [modSegIntNoCue.phaseMeanDire3to4 ...
            modSegIntAL.phaseMeanDire3to4 modSegIntPL.phaseMeanDire3to4];
        mod.phaseMeanDireH3to4 = [modSegIntNoCue.phaseMeanDireH3to4 ...
            modSegIntAL.phaseMeanDireH3to4 modSegIntPL.phaseMeanDireH3to4];
        mod.maxPhaseArr3to4 = [modSegIntNoCue.maxPhaseFil3to4 ...
            modSegIntAL.maxPhaseFil3to4 modSegIntPL.maxPhaseFil3to4];
        mod.maxPhaseArrH3to4 = [modSegIntNoCue.maxPhaseFilH3to4 ...
            modSegIntAL.maxPhaseFilH3to4 modSegIntPL.maxPhaseFilH3to4];
        mod.minPhaseArr3to4 = [modSegIntNoCue.minPhaseFil3to4 ...
            modSegIntAL.minPhaseFil3to4 modSegIntPL.minPhaseFil3to4];
        mod.minPhaseArrH3to4 = [modSegIntNoCue.minPhaseFilH3to4 ...
            modSegIntAL.minPhaseFilH3to4 modSegIntPL.minPhaseFilH3to4];
        mod.phaseMeanResultantLen3to4 = [modSegIntNoCue.phaseMeanResultantLen3to4 ...
            modSegIntAL.phaseMeanResultantLen3to4 modSegIntPL.phaseMeanResultantLen3to4];

        if(methodKMean == 1)
            mod.idxC = [autoCorrIntAll.idxC1(autoCorrIntAll.task == autoCorrIntNoCue.task(1))' ...
                autoCorrIntAll.idxC1(autoCorrIntAll.task == autoCorrIntAL.task(1))' ...
                autoCorrIntAll.idxC1(autoCorrIntAll.task == autoCorrIntPL.task(1))'];
        elseif(methodKMean == 2)
            mod.idxC = [autoCorrIntAll.idxC2(autoCorrIntAll.task == autoCorrIntNoCue.task(1))' ...
                autoCorrIntAll.idxC2(autoCorrIntAll.task == autoCorrIntAL.task(1))' ...
                autoCorrIntAll.idxC2(autoCorrIntAll.task == autoCorrIntPL.task(1))'];
        elseif(methodKMean == 3)
            mod.idxC = [autoCorrIntAll.idxC3(autoCorrIntAll.task == autoCorrIntNoCue.task(1))' ...
                autoCorrIntAll.idxC3(autoCorrIntAll.task == autoCorrIntAL.task(1))' ...
                autoCorrIntAll.idxC3(autoCorrIntAll.task == autoCorrIntPL.task(1))'];
        end
    elseif(taskSel == 2)
        mod.task = [autoCorrIntAL.task autoCorrIntPL.task];
        mod.indRec = [autoCorrIntAL.indRec autoCorrIntPL.indRec];
        mod.nNeuWithField = [modIntAL.nNeuWithField modIntPL.nNeuWithField];

        mod.thetaModHistBefRun = [...
            modSegIntAL.thetaModHistBefRun modSegIntPL.thetaModHistBefRun];
        mod.phaseMeanDireBefRun = [...
            modSegIntAL.phaseMeanDireBefRun modSegIntPL.phaseMeanDireBefRun];
        mod.maxPhaseArrBefRun = [...
            modSegIntAL.maxPhaseFilBefRun modSegIntPL.maxPhaseFilBefRun];
        mod.minPhaseArrBefRun = [...
            modSegIntAL.minPhaseFilBefRun modSegIntPL.minPhaseFilBefRun];
        mod.phaseMeanResultantLenBefRun = [...
            modSegIntAL.phaseMeanResultantLenBefRun modSegIntPL.phaseMeanResultantLenBefRun];

        mod.thetaModHist0to1 = [...
            modSegIntAL.thetaModHist0to1 modSegIntPL.thetaModHist0to1];
        mod.thetaModHistH0to1 = [...
            modSegIntAL.thetaModHistH0to1 modSegIntPL.thetaModHistH0to1];
        mod.phaseMeanDire0to1 = [...
            modSegIntAL.phaseMeanDire0to1 modSegIntPL.phaseMeanDire0to1];
        mod.phaseMeanDireH0to1 = [...
            modSegIntAL.phaseMeanDireH0to1 modSegIntPL.phaseMeanDireH0to1];
        mod.maxPhaseArr0to1 = [...
            modSegIntAL.maxPhaseFil0to1 modSegIntPL.maxPhaseFil0to1];
        mod.maxPhaseArrH0to1 = [...
            modSegIntAL.maxPhaseFilH0to1 modSegIntPL.maxPhaseFilH0to1];
        mod.minPhaseArr0to1 = [...
            modSegIntAL.minPhaseFil0to1 modSegIntPL.minPhaseFil0to1];
        mod.minPhaseArrH0to1 = [...
            modSegIntAL.minPhaseFilH0to1 modSegIntPL.minPhaseFilH0to1];
        mod.phaseMeanResultantLen0to1 = [...
            modSegIntAL.phaseMeanResultantLen0to1 modSegIntPL.phaseMeanResultantLen0to1];

        mod.thetaModHist3to5 = [...
            modSegIntAL.thetaModHist3to5 modSegIntPL.thetaModHist3to5];
        mod.thetaModHistH3to5 = [...
            modSegIntAL.thetaModHistH3to5 modSegIntPL.thetaModHistH3to5];
        mod.phaseMeanDire3to5 = [...
            modSegIntAL.phaseMeanDire3to5 modSegIntPL.phaseMeanDire3to5];
        mod.phaseMeanDireH3to5 = [...
            modSegIntAL.phaseMeanDireH3to5 modSegIntPL.phaseMeanDireH3to5];
        mod.maxPhaseArr3to5 = [...
            modSegIntAL.maxPhaseFil3to5 modSegIntPL.maxPhaseFil3to5];
        mod.maxPhaseArrH3to5 = [...
            modSegIntAL.maxPhaseFilH3to5 modSegIntPL.maxPhaseFilH3to5];
        mod.minPhaseArr3to5 = [...
            modSegIntAL.minPhaseFil3to5 modSegIntPL.minPhaseFil3to5];
        mod.minPhaseArrH3to5 = [...
            modSegIntAL.minPhaseFilH3to5 modSegIntPL.minPhaseFilH3to5];
        mod.phaseMeanResultantLen3to5 = [...
            modSegIntAL.phaseMeanResultantLen3to5 modSegIntPL.phaseMeanResultantLen3to5];

        mod.thetaModHist3to4 = [...
            modSegIntAL.thetaModHist3to4 modSegIntPL.thetaModHist3to4];
        mod.thetaModHistH3to4 = [...
            modSegIntAL.thetaModHistH3to4 modSegIntPL.thetaModHistH3to4];
        mod.phaseMeanDire3to4 = [...
            modSegIntAL.phaseMeanDire3to4 modSegIntPL.phaseMeanDire3to4];
        mod.phaseMeanDireH3to4 = [...
            modSegIntAL.phaseMeanDireH3to4 modSegIntPL.phaseMeanDireH3to4];
        mod.maxPhaseArr3to4 = [...
            modSegIntAL.maxPhaseFil3to4 modSegIntPL.maxPhaseFil3to4];
        mod.maxPhaseArrH3to4 = [...
            modSegIntAL.maxPhaseFilH3to4 modSegIntPL.maxPhaseFilH3to4];
        mod.minPhaseArr3to4 = [...
            modSegIntAL.minPhaseFil3to4 modSegIntPL.minPhaseFil3to4];
        mod.minPhaseArrH3to4 = [...
            modSegIntAL.minPhaseFilH3to4 modSegIntPL.minPhaseFilH3to4];
        mod.phaseMeanResultantLen3to4 = [...
            modSegIntAL.phaseMeanResultantLen3to4 modSegIntPL.phaseMeanResultantLen3to4];

        if(methodKMean == 1)
            mod.idxC = [...
                autoCorrIntAll.idxC1(autoCorrIntAll.task == autoCorrIntAL.task(1))' ...
                autoCorrIntAll.idxC1(autoCorrIntAll.task == autoCorrIntPL.task(1))'];
        elseif(methodKMean == 2)
            mod.idxC = [...
                autoCorrIntAll.idxC2(autoCorrIntAll.task == autoCorrIntAL.task(1))' ...
                autoCorrIntAll.idxC2(autoCorrIntAll.task == autoCorrIntPL.task(1))'];
        elseif(methodKMean == 3)
            mod.idxC = [...
                autoCorrIntAll.idxC3(autoCorrIntAll.task == autoCorrIntAL.task(1))' ...
                autoCorrIntAll.idxC3(autoCorrIntAll.task == autoCorrIntPL.task(1))'];
        end
    elseif(taskSel == 3)
        mod.task = [autoCorrIntAL.task];
        mod.indRec = [autoCorrIntAL.indRec];
        mod.nNeuWithField = [modIntAL.nNeuWithField];

        mod.thetaModHistBefRun = [...
            modSegIntAL.thetaModHistBefRun];
        mod.phaseMeanDireBefRun = [...
            modSegIntAL.phaseMeanDireBefRun];
        mod.maxPhaseArrBefRun = [...
            modSegIntAL.maxPhaseFilBefRun];
        mod.minPhaseArrBefRun = [...
            modSegIntAL.minPhaseFilBefRun];
        mod.phaseMeanResultantLenBefRun = [...
            modSegIntAL.phaseMeanResultantLenBefRun];

        mod.thetaModHist0to1 = [...
            modSegIntAL.thetaModHist0to1];
        mod.thetaModHistH0to1 = [...
            modSegIntAL.thetaModHistH0to1];
        mod.phaseMeanDire0to1 = [...
            modSegIntAL.phaseMeanDire0to1];
        mod.phaseMeanDireH0to1 = [...
            modSegIntAL.phaseMeanDireH0to1];
        mod.maxPhaseArr0to1 = [...
            modSegIntAL.maxPhaseFil0to1];
        mod.maxPhaseArrH0to1 = [...
            modSegIntAL.maxPhaseFilH0to1];
        mod.minPhaseArr0to1 = [...
            modSegIntAL.minPhaseFil0to1];
        mod.minPhaseArrH0to1 = [...
            modSegIntAL.minPhaseFilH0to1];
        mod.phaseMeanResultantLen0to1 = [...
            modSegIntAL.phaseMeanResultantLen0to1];

        mod.thetaModHist3to5 = [...
            modSegIntAL.thetaModHist3to5];
        mod.thetaModHistH3to5 = [...
            modSegIntAL.thetaModHistH3to5];
        mod.phaseMeanDire3to5 = [...
            modSegIntAL.phaseMeanDire3to5];
        mod.phaseMeanDireH3to5 = [...
            modSegIntAL.phaseMeanDireH3to5];
        mod.maxPhaseArr3to5 = [...
            modSegIntAL.maxPhaseFil3to5];
        mod.maxPhaseArrH3to5 = [...
            modSegIntAL.maxPhaseFilH3to5];
        mod.minPhaseArr3to5 = [...
            modSegIntAL.minPhaseFil3to5];
        mod.minPhaseArrH3to5 = [...
            modSegIntAL.minPhaseFilH3to5];
        mod.phaseMeanResultantLen3to5 = [...
            modSegIntAL.phaseMeanResultantLen3to5];

        mod.thetaModHist3to4 = [...
            modSegIntAL.thetaModHist3to4];
        mod.thetaModHistH3to4 = [...
            modSegIntAL.thetaModHistH3to4];
        mod.phaseMeanDire3to4 = [...
            modSegIntAL.phaseMeanDire3to4];
        mod.phaseMeanDireH3to4 = [...
            modSegIntAL.phaseMeanDireH3to4];
        mod.maxPhaseArr3to4 = [...
            modSegIntAL.maxPhaseFil3to4];
        mod.maxPhaseArrH3to4 = [...
            modSegIntAL.maxPhaseFilH3to4];
        mod.minPhaseArr3to4 = [...
            modSegIntAL.minPhaseFil3to4];
        mod.minPhaseArrH3to4 = [...
            modSegIntAL.minPhaseFilH3to4];
        mod.phaseMeanResultantLen3to4 = [...
            modSegIntAL.phaseMeanResultantLen3to4];

        if(methodKMean == 1)
            mod.idxC = [...
                autoCorrIntAll.idxC1(autoCorrIntAll.task == autoCorrIntAL.task(1))' ...
                ];
        elseif(methodKMean == 2)
            mod.idxC = [...
                autoCorrIntAll.idxC2(autoCorrIntAll.task == autoCorrIntAL.task(1))' ...
                ];
        elseif(methodKMean == 3)
            mod.idxC = [...
                autoCorrIntAll.idxC3(autoCorrIntAll.task == autoCorrIntAL.task(1))' ...
                ];
        end
    end
end