function plotModRunSeg(mod,modSegIntStatsField,modSegIntStatsSeg,colorSel,...
        cluster,indCurCField,indCurCNoField,pathAnal)
    idxC = mod.idxC;
    % before run, field vs no field 
    plotBoxPlot(mod.phaseMeanDireBefRun(indCurCField),...
        mod.phaseMeanDireBefRun(indCurCNoField),'Mean theta phase (bef run)',...
        ['Int_ThetaMeanC' num2str(cluster) 'BefRunField-NoFieldBox'],...
        pathAnal,[0 2*pi],modSegIntStatsField.pWWPhaseMeanDireBefRun(cluster),colorSel);
    
    plotBoxPlot(mod.phaseMeanResultantLenBefRun(indCurCField),...
        mod.phaseMeanResultantLenBefRun(indCurCNoField),'Theta phase resultant length (bef run)',...
        ['Int_PhaseMeanResultantLen' num2str(cluster) 'BefRunField-NoFieldBox'],...
        pathAnal,[-0.1 0.8],modSegIntStatsField.pRSPhaseMeanResultantLenBefRun(cluster),colorSel);
    
    plotBoxPlot(mod.thetaModHistBefRun(indCurCField),...
        mod.thetaModHistBefRun(indCurCNoField),'Theta modulation (bef run)',...
        ['Int_thetaModHist' num2str(cluster) 'BefRunField-NoFieldBox'],...
        pathAnal,[-0.1 1.2],modSegIntStatsField.pRSThetaModHistBefRun(cluster),colorSel);
    
    % 0-1s, field vs no field 
    plotBoxPlot(mod.phaseMeanDire0to1(indCurCField),...
        mod.phaseMeanDire0to1(indCurCNoField),'Mean theta phase (0to1s)',...
        ['Int_ThetaMeanC' num2str(cluster) '0to1sField-NoFieldBox'],...
        pathAnal,[0 2*pi],modSegIntStatsField.pWWPhaseMeanDire0to1(cluster),colorSel);
    
    plotBoxPlot(mod.phaseMeanResultantLen0to1(indCurCField),...
        mod.phaseMeanResultantLen0to1(indCurCNoField),'Theta phase resultant length (0to1s)',...
        ['Int_PhaseMeanResultantLen' num2str(cluster) '0to1sField-NoFieldBox'],...
        pathAnal,[-0.1 0.6],modSegIntStatsField.pRSPhaseMeanResultantLen0to1(cluster),colorSel);
    
    plotBoxPlot(mod.thetaModHist0to1(indCurCField),...
        mod.thetaModHist0to1(indCurCNoField),'Theta modulation (0to1s)',...
        ['Int_thetaModHist' num2str(cluster) '0to1sField-NoFieldBox'],...
        pathAnal,[-0.1 1.2],modSegIntStatsField.pRSThetaModHist0to1(cluster),colorSel);
    
    % 3-4s, field vs no field 
    plotBoxPlot(mod.phaseMeanDire3to4(indCurCField),...
        mod.phaseMeanDire3to4(indCurCNoField),'Mean theta phase (3to4s)',...
        ['Int_ThetaMeanC' num2str(cluster) '3to4sField-NoFieldBox'],...
        pathAnal,[0 2*pi],modSegIntStatsField.pWWPhaseMeanDire3to4(cluster),colorSel);
    
    plotBoxPlot(mod.phaseMeanResultantLen3to4(indCurCField),...
        mod.phaseMeanResultantLen3to4(indCurCNoField),'Theta phase resultant length (3to4s)',...
        ['Int_PhaseMeanResultantLen' num2str(cluster) '3to4sField-NoFieldBox'],...
        pathAnal,[-0.1 0.6],modSegIntStatsField.pRSPhaseMeanResultantLen3to4(cluster),colorSel);
    
    plotBoxPlot(mod.thetaModHist3to4(indCurCField),...
        mod.thetaModHist3to4(indCurCNoField),'Theta modulation (3to4s)',...
        ['Int_thetaModHist' num2str(cluster) '3to4sField-NoFieldBox'],...
        pathAnal,[-0.1 1.2],modSegIntStatsField.pRSThetaModHist3to4(cluster),colorSel);
   
    % 0-1s vs 3-4s 
    plotBoxPlot(mod.phaseMeanDire0to1(idxC == cluster),...
        mod.phaseMeanDire3to4(idxC == cluster),'Mean theta phase (0to1 vs 3to4)',...
        ['Int_ThetaMeanC' num2str(cluster) '0to1sVs3to4sBox'],...
        pathAnal,[0 2*pi],modSegIntStatsSeg.pWWPhaseMeanDireC0to1vs3to4(cluster),colorSel);
    
    plotBoxPlot(mod.phaseMeanResultantLen0to1(idxC == cluster),...
        mod.phaseMeanResultantLen3to4(idxC == cluster),'Theta phase resultant length (0to1 vs 3to4)',...
        ['Int_PhaseMeanResultantLen' num2str(cluster) '0to1sVs3to4sBox'],...
        pathAnal,[-0.1 0.6],modSegIntStatsSeg.pRSPhaseMeanResultantLenC0to1vs3to4(cluster),colorSel);
    
    plotBoxPlot(mod.thetaModHist0to1(idxC == cluster),...
        mod.thetaModHist3to4(idxC == cluster),'Theta modulation (0to1 vs 3to4)',...
        ['Int_thetaModHist' num2str(cluster) '0to1sVs3to4sBox'],...
        pathAnal,[-0.1 1.2],modSegIntStatsSeg.pRSThetaModHistC0to1vs3to4(cluster),colorSel);
    
    % 0-1s vs 3-4s no field
    plotBoxPlot(mod.phaseMeanDire0to1(indCurCNoField),...
        mod.phaseMeanDire3to4(indCurCNoField),'Mean theta phase (0to1 vs 3to4 no field)',...
        ['Int_ThetaMeanC' num2str(cluster) '0to1sVs3to4sNoFieldBox'],...
        pathAnal,[0 2*pi],modSegIntStatsSeg.pWWPhaseMeanDireCNoField0to1vs3to4(cluster),colorSel);
    
    plotBoxPlot(mod.phaseMeanResultantLen0to1(indCurCNoField),...
        mod.phaseMeanResultantLen3to4(indCurCNoField),'Theta phase resultant length (0to1 vs 3to4 no field)',...
        ['Int_PhaseMeanResultantLen' num2str(cluster) '0to1sVs3to4sNoFieldBox'],...
        pathAnal,[-0.1 0.8],modSegIntStatsSeg.pRSPhaseMeanResultantLenCNoField0to1vs3to4(cluster),colorSel);
    
    plotBoxPlot(mod.thetaModHist0to1(indCurCNoField),...
        mod.thetaModHist3to4(indCurCNoField),'Theta modulation (0to1 vs 3to4 no field)',...
        ['Int_thetaModHist' num2str(cluster) '0to1sVs3to4sNoFieldBox'],...
        pathAnal,[-0.1 1.2],modSegIntStatsSeg.pRSThetaModHistCNoField0to1vs3to4(cluster),colorSel);
   
    % 0-1s vs 3-4s field    
    plotBoxPlot(mod.phaseMeanDire0to1(indCurCField),...
        mod.phaseMeanDire3to4(indCurCField),'Mean theta phase (0to1 vs 3to4 field)',...
        ['Int_ThetaMeanC' num2str(cluster) '0to1sVs3to4sFieldBox'],...
        pathAnal,[0 2*pi],modSegIntStatsSeg.pWWPhaseMeanDireCField0to1vs3to4(cluster),colorSel);
    
    plotBoxPlot(mod.phaseMeanResultantLen0to1(indCurCField),...
        mod.phaseMeanResultantLen3to4(indCurCField),'Theta phase resultant length (0to1 vs 3to4 field)',...
        ['Int_PhaseMeanResultantLen' num2str(cluster) '0to1sVs3to4sFieldBox'],...
        pathAnal,[-0.1 0.8],modSegIntStatsSeg.pRSPhaseMeanResultantLenCField0to1vs3to4(cluster),colorSel);
    
    plotBoxPlot(mod.thetaModHist0to1(indCurCField),...
        mod.thetaModHist3to4(indCurCField),'Theta modulation (0to1 vs 3to4 field)',...
        ['Int_thetaModHist' num2str(cluster) '0to1sVs3to4sFieldBox'],...
        pathAnal,[-0.1 1.2],modSegIntStatsSeg.pRSThetaModHistCField0to1vs3to4(cluster),colorSel);
    
    % 0-1s vs 3-5s field
    plotBoxPlot(mod.phaseMeanDire0to1(indCurCField),...
        mod.phaseMeanDire3to5(indCurCField),'Mean theta phase (0to1 vs 3to5 field)',...
        ['Int_ThetaMeanC' num2str(cluster) '0to1sVs3to5sFieldBox'],...
        pathAnal,[0 2*pi],modSegIntStatsSeg.pWWPhaseMeanDireCField0to1vs3to5(cluster),colorSel);
    
    plotBoxPlot(mod.phaseMeanResultantLen0to1(indCurCField),...
        mod.phaseMeanResultantLen3to5(indCurCField),'Theta phase resultant length (0to1 vs 3to5 field)',...
        ['Int_PhaseMeanResultantLen' num2str(cluster) '0to1sVs3to5sFieldBox'],...
        pathAnal,[-0.1 0.8],modSegIntStatsSeg.pRSPhaseMeanResultantLenCField0to1vs3to5(cluster),colorSel);
    
    plotBoxPlot(mod.thetaModHist0to1(indCurCField),...
        mod.thetaModHist3to5(indCurCField),'Theta modulation (0to1 vs 3to5 field)',...
        ['Int_thetaModHist' num2str(cluster) '0to1sVs3to5sFieldBox'],...
        pathAnal,[-0.1 1.2],modSegIntStatsSeg.pRSThetaModHistCField0to1vs3to5(cluster),colorSel);
    
    % bef run vs 3-4s field
    plotBoxPlot(mod.phaseMeanDireBefRun(indCurCField),...
        mod.phaseMeanDire3to4(indCurCField),'Mean theta phase (bef run vs 3to4 field)',...
        ['Int_ThetaMeanC' num2str(cluster) 'BefRunVs3to4sFieldBox'],...
        pathAnal,[0 2*pi],modSegIntStatsSeg.pWWPhaseMeanDireCFieldBefRunvs3to4(cluster),colorSel);
    
    plotBoxPlot(mod.phaseMeanResultantLenBefRun(indCurCField),...
        mod.phaseMeanResultantLen3to4(indCurCField),'Theta phase resultant length (bef run vs 3to4 field)',...
        ['Int_PhaseMeanResultantLen' num2str(cluster) 'BefRunVs3to4sFieldBox'],...
        pathAnal,[-0.1 0.8],modSegIntStatsSeg.pRSPhaseMeanResultantLenCFieldBefRunvs3to4(cluster),colorSel);
    
    plotBoxPlot(mod.thetaModHistBefRun(indCurCField),...
        mod.thetaModHist3to4(indCurCField),'Theta modulation (bef run vs 3to4 field)',...
        ['Int_thetaModHist' num2str(cluster) 'BefRunVs3to4sFieldBox'],...
        pathAnal,[-0.1 1.2],modSegIntStatsSeg.pRSThetaModHistCFieldBefRunvs3to4(cluster),colorSel);
    
    % bef run vs 3-4s no field
    plotBoxPlot(mod.phaseMeanDireBefRun(indCurCNoField),...
        mod.phaseMeanDire3to4(indCurCNoField),'Mean theta phase (bef run vs 3to4 no field)',...
        ['Int_ThetaMeanC' num2str(cluster) 'BefRunVs3to4sNoFieldBox'],...
        pathAnal,[0 2*pi],modSegIntStatsSeg.pWWPhaseMeanDireCNoFieldBefRunvs3to4(cluster),colorSel);
    
    plotBoxPlot(mod.phaseMeanResultantLenBefRun(indCurCNoField),...
        mod.phaseMeanResultantLen3to4(indCurCNoField),'Theta phase resultant length (bef run vs 3to4 no field)',...
        ['Int_PhaseMeanResultantLen' num2str(cluster) 'BefRunVs3to4sNoFieldBox'],...
        pathAnal,[-0.1 0.8],modSegIntStatsSeg.pRSPhaseMeanResultantLenCNoFieldBefRunvs3to4(cluster),colorSel);
    
    plotBoxPlot(mod.thetaModHistBefRun(indCurCNoField),...
        mod.thetaModHist3to4(indCurCNoField),'Theta modulation (bef run vs 3to4 no field)',...
        ['Int_thetaModHist' num2str(cluster) 'BefRunVs3to4sNoFieldBox'],...
        pathAnal,[-0.1 1.2],modSegIntStatsSeg.pRSThetaModHistCNoFieldBefRunvs3to4(cluster),colorSel);
end