function FRProfileMeanStatC = accumMeanPVStimStatGoodBad_1stStimCtrl(FRProfileMean,FRProfileMeanBad)
       
    FRProfileMeanStatC.pRSAll = ranksum(FRProfileMean.meanAvgFRProfileAll,...
                    FRProfileMeanBad.meanAvgFRProfileAll); % added on 10/28/2023
                
    FRProfileMeanStatC.pRSBLAll = ranksum(FRProfileMean.meanAvgFRProfileBaseline,...
                    FRProfileMeanBad.meanAvgFRProfileBaseline);
                                
    FRProfileMeanStatC.pRSBefRunAll = ranksum(FRProfileMean.meanAvgFRProfileBefRun,...
                FRProfileMeanBad.meanAvgFRProfileBefRun);

    FRProfileMeanStatC.pRS3to5All = ranksum(FRProfileMean.meanAvgFRProfile3to5,...
                FRProfileMeanBad.meanAvgFRProfile3to5);
            
    FRProfileMeanStatC.pRS3to4All = ranksum(FRProfileMean.meanAvgFRProfile3to4,...
                FRProfileMeanBad.meanAvgFRProfile3to4);

    FRProfileMeanStatC.pRS0to1All = ranksum(FRProfileMean.meanAvgFRProfile0to1,...
                FRProfileMeanBad.meanAvgFRProfile0to1);
            
    FRProfileMeanStatC.pRS0to1stAll = ranksum(FRProfileMean.meanAvgFRProfile0to1st,...
                FRProfileMeanBad.meanAvgFRProfile0to1st);

    FRProfileMeanStatC.pRS1to3All = ranksum(FRProfileMean.meanAvgFRProfile1to3,...
                FRProfileMeanBad.meanAvgFRProfile1to3);
            
    FRProfileMeanStatC.pRS0to3All = ranksum(FRProfileMean.meanAvgFRProfile0to3,...
                FRProfileMeanBad.meanAvgFRProfile0to3);
            
    FRProfileMeanStatC.pSignRAll = signrank(FRProfileMean.meanAvgFRProfileAll,...
                    FRProfileMeanBad.meanAvgFRProfileAll); % added on 10/28/2023
                
    FRProfileMeanStatC.pSignRBLAll = signrank(FRProfileMean.meanAvgFRProfileBaseline,...
                    FRProfileMeanBad.meanAvgFRProfileBaseline);
                                
    FRProfileMeanStatC.pSignRBefRunAll = signrank(FRProfileMean.meanAvgFRProfileBefRun,...
                FRProfileMeanBad.meanAvgFRProfileBefRun);

    FRProfileMeanStatC.pSignR3to5All = signrank(FRProfileMean.meanAvgFRProfile3to5,...
                FRProfileMeanBad.meanAvgFRProfile3to5);
            
    FRProfileMeanStatC.pSignR3to4All = signrank(FRProfileMean.meanAvgFRProfile3to4,...
                FRProfileMeanBad.meanAvgFRProfile3to4);

    FRProfileMeanStatC.pSignR0to1All = signrank(FRProfileMean.meanAvgFRProfile0to1,...
                FRProfileMeanBad.meanAvgFRProfile0to1);
            
    FRProfileMeanStatC.pSignR0to1stAll = signrank(FRProfileMean.meanAvgFRProfile0to1st,...
                FRProfileMeanBad.meanAvgFRProfile0to1st);

    FRProfileMeanStatC.pSignR1to3All = signrank(FRProfileMean.meanAvgFRProfile1to3,...
                FRProfileMeanBad.meanAvgFRProfile1to3);
            
    FRProfileMeanStatC.pSignR0to3All = signrank(FRProfileMean.meanAvgFRProfile0to3,...
                FRProfileMeanBad.meanAvgFRProfile0to3);

    
end