function plotPyrNeuWithFieldStim(pathAnal0,FRProfileMean1, modPyr1AL, PyrStim, FRProfile1)

%% pyramidal neurons with fields
    for i = 1:length(FRProfileMean1)
        %% normalized, fields from good non-stim trials
        %% order pyramidal neurons with field based on the peak firing rate after 0
%         plotIndFRProfile(modPyr1AL.timeStepRun,...
%                 PyrStim.avgFRProfileNorm(FRProfile1{i}.indField,:),['Neuron no.'],...
%                 ['Pyr_IndFRProfileNormFRPeakAftRunNeuField_Cond' num2str(i)],...
%                 pathAnal0,[],5,[],[])
%           
        %% order pyramidal neurons with field based on the peak firing rate after 0
        % and compare good non-stim with stim trials
        plotIndFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileNorm(FRProfile1{i}.indField,:),...
                PyrStim.avgFRProfileNormStim(FRProfile1{i}.indField,:),['Neuron no. cond ' num2str(i)],...
                ['Pyr_IndFRProfileNormFRPeakAftRunNeuFieldCmpGoodNoStimVsStim_Cond' num2str(i)],...
                pathAnal0,[],5,[],[])
            
        
        %% order pyramidal neurons with field based on before and after run FR ratio  
%         plotIndFRProfile(modPyr1AL.timeStepRun,...
%                 PyrStim.avgFRProfileNorm(FRProfile1{i}.indField,:),['Neuron no.'],...
%                 ['Pyr_IndFRProfileNormFR0to1VsBefRunNeuField_Cond' num2str(i)],...
%                 pathAnal0,[],4,FRProfileMean1{i}.indFRBefRun,...
%                 FRProfileMean1{i}.indFR0to1) % ordered based on -1to0 to 0to1 mean ratio
            
        %% order pyramidal neurons with field based on before and after run FR ratio 
        % and compare good non-stim with stim trials
        plotIndFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileNorm(FRProfile1{i}.indField,:),...
                PyrStim.avgFRProfileNormStim(FRProfile1{i}.indField,:),['Neuron no. cond ' num2str(i)],...
                ['Pyr_IndFRProfileNormFR0to1VsBefRunNeuFieldCmpGoodNoStimVsStim_Cond' num2str(i)],...
                pathAnal0,[],4,FRProfileMean1{i}.indFRBefRun,...
                FRProfileMean1{i}.indFR0to1)
    end
    
        