function plotPyrNeuStimUpDownAlone0(pathAnal0, FRProfileMean1, modPyr1AL, PyrStim, FRProfile1)

    %% all pyramidal up or down neurons
    for i = 1:length(FRProfile1)
        %% normalized
        %% order pyramidal neurons based on the peak firing rate after 0
        % and compare good non-stim with stim trials
        plotIndFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileNorm(FRProfile1{i}.indPyrRise,:),...
                PyrStim.avgFRProfileNormStim(FRProfile1{i}.indPyrRise,:),['Neuron no.'],...
                ['PyrRise_IndFRProfileNormFR0to1VsBefRunNeuCmpGoodNoStimVsStim_Cond' num2str(i)],...
                pathAnal0,[],4,FRProfileMean1{i}.indFRBefRun,...
                FRProfileMean1{i}.indFR0to1)
        
        %% order pyramidal neurons based on before and after run FR ratio 
        % and compare good non-stim with stim trials
        plotIndFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileNorm(FRProfile1{i}.indPyrDown,:),...
                PyrStim.avgFRProfileNormStim(FRProfile1{i}.indPyrDown,:),['Neuron no.'],...
                ['PyrDown_IndFRProfileNormFR0to1VsBefRunNeuCmpGoodNoStimVsStim_Cond' num2str(i)],...
                pathAnal0,[],4,FRProfileMean1{i}.indFRBefRun,...
                FRProfileMean1{i}.indFR0to1)
         
    end