function plotPyrNeuWithFieldStimUpDown(pathAnal0,FRProfileMean1, modPyr1AL, PyrStim, FRProfile1,...
    isNeuWithFieldAlignedRise,isNeuWithFieldAlignedDown,isNeuWithFieldAlignedOther)

    for i = 1:length(FRProfileMean1)
        %% compare good non stim trials with stim trials, pyr rise
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileNorm(isNeuWithFieldAlignedRise{i}.idxRise,:),...
                PyrStim.avgFRProfileNormStim(isNeuWithFieldAlignedRise{i}.idxRise,:),...
                ['FR PyrRise GoodNStim/Stim Field Cond' num2str(i)],...
                ['Pyr_FRProfileNormPyrRiseFieldNoStimGoodVsStim_Cond' num2str(i)],...
                pathAnal0,[0 0.6],[{'GoodNoStim'},{'Stim'}])

        %% compare good non stim trials with stim trials, pyr down
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileNorm(isNeuWithFieldAlignedDown{i}.idxDown,:),...
                PyrStim.avgFRProfileNormStim(isNeuWithFieldAlignedDown{i}.idxDown,:),...
                ['FR PyrDown GoodNStim/Stim Field Cond' num2str(i)],...
                ['Pyr_FRProfileNormPyrDownFieldNoStimGoodVsStim_Cond' num2str(i)],...
                pathAnal0,[0 0.6],[{'GoodNoStim'},{'Stim'}])
         
        % added on 7/8/2022    
        %% compare good non stim trials with stim trials, pyr other
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileNorm(isNeuWithFieldAlignedOther{i}.idxOther,:),...
                PyrStim.avgFRProfileNormStim(isNeuWithFieldAlignedOther{i}.idxOther,:),...
                ['FR PyrOther GoodNStim/Stim Field Cond' num2str(i)],...
                ['Pyr_FRProfileNormPyrOtherFieldNoStimGoodVsStim_Cond' num2str(i)],...
                pathAnal0,[0 0.6],[{'GoodNoStim'},{'Stim'}])

        %% normalized, fields from both good non-stim trials and stim trials
        %% order pyramidal neurons with field based on the peak firing rate after 0
    %         plotIndFRProfile(modPyr1AL.timeStepRun,...
    %                 PyrStim.avgFRProfileNorm(FRProfile1{i}.indFieldComb,:),['Neuron no.'],...
    %                 ['Pyr_IndFRProfileNormFRPeakAftRunNeuFieldComb_Cond' num2str(i)],...
    %                 pathAnal0,[],5,[],[])

        %% order pyramidal neurons with field based on the peak firing rate after 0
        % and compare good non-stim with stim trials
        plotIndFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileNorm(FRProfile1{i}.indFieldComb,:),...
                PyrStim.avgFRProfileNormStim(FRProfile1{i}.indFieldComb,:),['Neuron no. Cond' num2str(i)],...
                ['Pyr_IndFRProfileNormFRPeakAftRunNeuFieldCombCmpGoodNoStimVsStim_Cond' num2str(i)],...
                pathAnal0,[],5,[],[])


        %% order pyramidal neurons with field based on before and after run FR ratio  
    %         plotIndFRProfile(modPyr1AL.timeStepRun,...
    %                 PyrStim.avgFRProfileNorm(FRProfile1{i}.indFieldComb,:),['Neuron no.'],...
    %                 ['Pyr_IndFRProfileNormFR0to1VsBefRunNeuFieldComb_Cond' num2str(i)],...
    %                 pathAnal0,[],4,FRProfileMean1{i}.indFRBefRun,...
    %                 FRProfileMean1{i}.indFR0to1) % ordered based on -1to0 to 0to1 mean ratio

        %% order pyramidal neurons with field based on before and after run FR ratio 
        % and compare good non-stim with stim trials
        plotIndFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileNorm(FRProfile1{i}.indFieldComb,:),...
                PyrStim.avgFRProfileNormStim(FRProfile1{i}.indFieldComb,:),['Neuron no. Cond' num2str(i)],...
                ['Pyr_IndFRProfileNormFR0to1VsBefRunNeuFieldCombCmpGoodNoStimVsStim_Cond' num2str(i)],...
                pathAnal0,[],4,FRProfileMean1{i}.indFRBefRun,...
                FRProfileMean1{i}.indFR0to1)

        %% compare good non stim trials with stim trials, pyr rise
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileNorm(isNeuWithFieldAlignedRise{i}.idxRiseComb,:),...
                PyrStim.avgFRProfileNormStim(isNeuWithFieldAlignedRise{i}.idxRiseComb,:),...
                ['FR PyrRise GoodNStim/Stim Field Com Cond' num2str(i)],...
                ['Pyr_FRProfileNormPyrRiseFieldCombNoStimGoodVsStim_Cond' num2str(i)],...
                pathAnal0,[0 0.6],[{'GoodNoStim'},{'Stim'}])

        %% compare good non stim trials with stim trials, pyr down
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileNorm(isNeuWithFieldAlignedDown{i}.idxDownComb,:),...
                PyrStim.avgFRProfileNormStim(isNeuWithFieldAlignedDown{i}.idxDownComb,:),...
                ['FR PyrDown GoodNStim/Stim Field Comb Cond' num2str(i)],...
                ['Pyr_FRProfileNormPyrDownFieldCombNoStimGoodVsStim_Cond' num2str(i)],...
                pathAnal0,[0 0.6],[{'GoodNoStim'},{'Stim'}])
         
        % added on 7/8/2022
        %% compare good non stim trials with stim trials, pyr other
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileNorm(isNeuWithFieldAlignedOther{i}.idxOtherComb,:),...
                PyrStim.avgFRProfileNormStim(isNeuWithFieldAlignedOther{i}.idxOtherComb,:),...
                ['FR PyrOther GoodNStim/Stim Field Comb Cond' num2str(i)],...
                ['Pyr_FRProfileNormPyrOtherFieldCombNoStimGoodVsStim_Cond' num2str(i)],...
                pathAnal0,[0 0.6],[{'GoodNoStim'},{'Stim'}])

        %% not normalized, fields from good non-stim trials
        %% compare good non stim trials with stim trials, pyr rise
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfile(isNeuWithFieldAlignedRise{i}.idxRise,:),...
                PyrStim.avgFRProfileStim(isNeuWithFieldAlignedRise{i}.idxRise,:),...
                ['FR PyrRise GoodNStim/Stim Field Cond' num2str(i)],...
                ['Pyr_FRProfilePyrRiseFieldNoStimGoodVsStim_Cond' num2str(i)],...
                pathAnal0,[],[{'GoodNoStim'},{'Stim'}])

        %% compare good non stim trials with stim trials, pyr down
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfile(isNeuWithFieldAlignedDown{i}.idxDown,:),...
                PyrStim.avgFRProfileStim(isNeuWithFieldAlignedDown{i}.idxDown,:),...
                ['FR PyrDown GoodNStim/Stim Field Cond' num2str(i)],...
                ['Pyr_FRProfilePyrDownFieldNoStimGoodVsStim_Cond' num2str(i)],...
                pathAnal0,[],[{'GoodNoStim'},{'Stim'}])
            
        % added on 7/8/2022
        %% compare good non stim trials with stim trials, pyr other
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfile(isNeuWithFieldAlignedOther{i}.idxOther,:),...
                PyrStim.avgFRProfileStim(isNeuWithFieldAlignedOther{i}.idxOther,:),...
                ['FR PyrOther GoodNStim/Stim Field Cond' num2str(i)],...
                ['Pyr_FRProfilePyrOtherFieldNoStimGoodVsStim_Cond' num2str(i)],...
                pathAnal0,[],[{'GoodNoStim'},{'Stim'}])

        %% not  normalized, fields from both good non-stim trials and stim trials
        %% compare good non stim trials with stim trials, pyr rise
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfile(isNeuWithFieldAlignedRise{i}.idxRiseComb,:),...
                PyrStim.avgFRProfileStim(isNeuWithFieldAlignedRise{i}.idxRiseComb,:),...
                ['FR PyrRise GoodNStim/Stim Field Cond' num2str(i)],...
                ['Pyr_FRProfilePyrRiseFieldCombNoStimGoodVsStim_Cond' num2str(i)],...
                pathAnal0,[],[{'GoodNoStim'},{'Stim'}])

        %% compare good non stim trials with stim trials, pyr down
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfile(isNeuWithFieldAlignedDown{i}.idxDownComb,:),...
                PyrStim.avgFRProfileStim(isNeuWithFieldAlignedDown{i}.idxDownComb,:),...
                ['FR PyrDown GoodNStim/Stim Field Comb'],...
                ['Pyr_FRProfilePyrDownFieldCombNoStimGoodVsStim_Cond' num2str(i)],...
                pathAnal0,[],[{'GoodNoStim'},{'Stim'}])
            
        % added on 7/8/2022
        %% compare good non stim trials with stim trials, pyr other
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfile(isNeuWithFieldAlignedOther{i}.idxOtherComb,:),...
                PyrStim.avgFRProfileStim(isNeuWithFieldAlignedOther{i}.idxOtherComb,:),...
                ['FR PyrOther GoodNStim/Stim Field Comb'],...
                ['Pyr_FRProfilePyrOtherFieldCombNoStimGoodVsStim_Cond' num2str(i)],...
                pathAnal0,[],[{'GoodNoStim'},{'Stim'}])
            
        %%%    
        %% compare stim ctrl trials with stim trials, pyr rise
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileNormStimCtrl(isNeuWithFieldAlignedRise{i}.idxRise,:),...
                PyrStim.avgFRProfileNormStim(isNeuWithFieldAlignedRise{i}.idxRise,:),...
                ['FR PyrRise StimCtrl/Stim Field Cond' num2str(i)],...
                ['Pyr_FRProfileNormPyrRiseFieldStimCtrlVsStim_Cond' num2str(i)],...
                pathAnal0,[0 0.6],[{'StimCtrl'},{'Stim'}])

        %% compare stim ctrl trials with stim trials, pyr down
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileNormStimCtrl(isNeuWithFieldAlignedDown{i}.idxDown,:),...
                PyrStim.avgFRProfileNormStim(isNeuWithFieldAlignedDown{i}.idxDown,:),...
                ['FR PyrDown StimCtrl/Stim Field Cond' num2str(i)],...
                ['Pyr_FRProfileNormPyrDownFieldStimCtrlVsStim_Cond' num2str(i)],...
                pathAnal0,[0 0.6],[{'StimCtrl'},{'Stim'}])
            
        % added on 7/8/2022
        %% compare stim ctrl trials with stim trials, pyr other
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileNormStimCtrl(isNeuWithFieldAlignedOther{i}.idxOther,:),...
                PyrStim.avgFRProfileNormStim(isNeuWithFieldAlignedOther{i}.idxOther,:),...
                ['FR PyrOther StimCtrl/Stim Field Cond' num2str(i)],...
                ['Pyr_FRProfileNormPyrOtherFieldStimCtrlVsStim_Cond' num2str(i)],...
                pathAnal0,[0 0.6],[{'StimCtrl'},{'Stim'}])

        %% order pyramidal neurons with field based on the peak firing rate after 0
        % and compare stim ctrl with stim trials
        plotIndFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileNormStimCtrl(FRProfile1{i}.indFieldComb,:),...
                PyrStim.avgFRProfileNormStim(FRProfile1{i}.indFieldComb,:),['Neuron no. Cond' num2str(i)],...
                ['Pyr_IndFRProfileNormFRPeakAftRunNeuFieldCombCmpStimCtrlVsStim_Cond' num2str(i)],...
                pathAnal0,[],5,[],[])

        %% order pyramidal neurons with field based on before and after run FR ratio 
        % and compare stim ctrl with stim trials
        plotIndFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileNormStimCtrl(FRProfile1{i}.indFieldComb,:),...
                PyrStim.avgFRProfileNormStim(FRProfile1{i}.indFieldComb,:),['Neuron no. Cond' num2str(i)],...
                ['Pyr_IndFRProfileNormFR0to1VsBefRunNeuFieldCombCmpStimCtrlVsStim_Cond' num2str(i)],...
                pathAnal0,[],4,FRProfileMean1{i}.indFRBefRun,...
                FRProfileMean1{i}.indFR0to1)

        %% compare stim ctrl trials with stim trials, pyr rise
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileNormStimCtrl(isNeuWithFieldAlignedRise{i}.idxRiseComb,:),...
                PyrStim.avgFRProfileNormStim(isNeuWithFieldAlignedRise{i}.idxRiseComb,:),...
                ['FR PyrRise StimCtrl/Stim Field Cond' num2str(i)],...
                ['Pyr_FRProfileNormPyrRiseFieldCombStimCtrlVsStim_Cond' num2str(i)],...
                pathAnal0,[0 0.6],[{'StimCtrl'},{'Stim'}])

        %% compare stim ctrl trials with stim trials, pyr down
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileNormStimCtrl(isNeuWithFieldAlignedDown{i}.idxDownComb,:),...
                PyrStim.avgFRProfileNormStim(isNeuWithFieldAlignedDown{i}.idxDownComb,:),...
                ['FR PyrDown StimCtrl/Stim Field Comb Cond' num2str(i)],...
                ['Pyr_FRProfileNormPyrDownFieldCombStimCtrlVsStim_Cond' num2str(i)],...
                pathAnal0,[0 0.6],[{'StimCtrl'},{'Stim'}])
            
        % added on 7/8/2022    
        %% compare stim ctrl trials with stim trials, pyr other
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileNormStimCtrl(isNeuWithFieldAlignedOther{i}.idxOtherComb,:),...
                PyrStim.avgFRProfileNormStim(isNeuWithFieldAlignedOther{i}.idxOtherComb,:),...
                ['FR PyrOther StimCtrl/Stim Field Comb Cond' num2str(i)],...
                ['Pyr_FRProfileNormPyrOtherFieldCombStimCtrlVsStim_Cond' num2str(i)],...
                pathAnal0,[0 0.6],[{'StimCtrl'},{'Stim'}])

        %% not normalized, fields from good non-stim trials
        %% compare stim ctrl trials with stim trials, pyr rise
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileStimCtrl(isNeuWithFieldAlignedRise{i}.idxRise,:),...
                PyrStim.avgFRProfileStim(isNeuWithFieldAlignedRise{i}.idxRise,:),...
                ['FR PyrRise StimCtrl/Stim Field Cond' num2str(i)],...
                ['Pyr_FRProfilePyrRiseFieldStimCtrlVsStim_Cond' num2str(i)],...
                pathAnal0,[],[{'StimCtrl'},{'Stim'}])

        %% compare stim ctrl trials with stim trials, pyr down
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileStimCtrl(isNeuWithFieldAlignedDown{i}.idxDown,:),...
                PyrStim.avgFRProfileStim(isNeuWithFieldAlignedDown{i}.idxDown,:),...
                ['FR PyrDown StimCtrl/Stim Field Cond' num2str(i)],...
                ['Pyr_FRProfilePyrDownFieldStimCtrlVsStim_Cond' num2str(i)],...
                pathAnal0,[],[{'StimCtrl'},{'Stim'}])
            
        % added on 7/8/2022
        %% compare stim ctrl trials with stim trials, pyr other
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileStimCtrl(isNeuWithFieldAlignedOther{i}.idxOther,:),...
                PyrStim.avgFRProfileStim(isNeuWithFieldAlignedOther{i}.idxOther,:),...
                ['FR PyrOther StimCtrl/Stim Field Cond' num2str(i)],...
                ['Pyr_FRProfilePyrOtherFieldStimCtrlVsStim_Cond' num2str(i)],...
                pathAnal0,[],[{'StimCtrl'},{'Stim'}])

        %% not  normalized, fields from both good non-stim trials and stim trials
        %% compare stim ctrl trials with stim trials, pyr rise
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileStimCtrl(isNeuWithFieldAlignedRise{i}.idxRiseComb,:),...
                PyrStim.avgFRProfileStim(isNeuWithFieldAlignedRise{i}.idxRiseComb,:),...
                ['FR PyrRise StimCtrl/Stim Field Cond' num2str(i)],...
                ['Pyr_FRProfilePyrRiseFieldCombStimCtrlVsStim_Cond' num2str(i)],...
                pathAnal0,[],[{'StimCtrl'},{'Stim'}])

        %% compare stim ctrl trials with stim trials, pyr down
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileStimCtrl(isNeuWithFieldAlignedDown{i}.idxDownComb,:),...
                PyrStim.avgFRProfileStim(isNeuWithFieldAlignedDown{i}.idxDownComb,:),...
                ['FR PyrDown StimCtrl/Stim Field Comb'],...
                ['Pyr_FRProfilePyrDownFieldCombStimCtrlVsStim_Cond' num2str(i)],...
                pathAnal0,[],[{'StimCtrl'},{'Stim'}])
            
        % added on 7/8/2022    
        %% compare stim ctrl trials with stim trials, pyr other
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileStimCtrl(isNeuWithFieldAlignedOther{i}.idxOtherComb,:),...
                PyrStim.avgFRProfileStim(isNeuWithFieldAlignedOther{i}.idxOtherComb,:),...
                ['FR PyrOther StimCtrl/Stim Field Comb'],...
                ['Pyr_FRProfilePyrOtherFieldCombStimCtrlVsStim_Cond' num2str(i)],...
                pathAnal0,[],[{'StimCtrl'},{'Stim'}])
    end