function plotPyrNeuWithFieldStimStats(pathAnal0,FRProfileMean,FRProfileMeanStim,FRProfileMeanStats,xlabels,fnstr,isField)

    colorSel = 0;
    if(isField)
        xLimTmp = [0 4];
    else
        xLimTmp = [0 3.1];
    end
    for i = 1:length(FRProfileMean)
        
        %% added pm 10/26/2023
        barPlotWithStat1(1:2,...
            [mean(FRProfileMean{i}.meanAvgFRProfileAll),...
            mean(FRProfileMeanStim{i}.meanAvgFRProfileAll)],...
            [std(FRProfileMean{i}.meanAvgFRProfileAll)...
                /sqrt(length(FRProfileMean{i}.meanAvgFRProfileAll)),...
            std(FRProfileMeanStim{i}.meanAvgFRProfileAll)...
                /sqrt(length(FRProfileMeanStim{i}.meanAvgFRProfileAll))],...
            [FRProfileMean{i}.meanAvgFRProfileAll,...
            FRProfileMeanStim{i}.meanAvgFRProfileAll],...
            ['FRMean All cond ' num2str(i)],...
            '', [FRProfileMeanStats{i}.pRSAll,FRProfileMeanStats{i}.pSignRAll],...
            ['FRMeanAllGoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,colorSel,xlabels,xLimTmp);
        
        %% FR mean of each segment
        barPlotWithStat1(1:2,...
            [mean(FRProfileMean{i}.meanAvgFRProfileBaseline),...
            mean(FRProfileMeanStim{i}.meanAvgFRProfileBaseline)],...
            [std(FRProfileMean{i}.meanAvgFRProfileBaseline)...
                /sqrt(length(FRProfileMean{i}.meanAvgFRProfileBaseline)),...
            std(FRProfileMeanStim{i}.meanAvgFRProfileBaseline)...
                /sqrt(length(FRProfileMeanStim{i}.meanAvgFRProfileBaseline))],...
            [FRProfileMean{i}.meanAvgFRProfileBaseline,...
            FRProfileMeanStim{i}.meanAvgFRProfileBaseline],...
            ['FRMean Baseline cond ' num2str(i)],...
            '', [FRProfileMeanStats{i}.pRSBLAll,FRProfileMeanStats{i}.pSignRBLAll],...
            ['FRMeanBLGoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,colorSel,xlabels,xLimTmp); %pathAnal0,colorSel,xlabels,[0 4]);
        
        barPlotWithStat1(1:2,...
            [mean(FRProfileMean{i}.meanAvgFRProfileBefRun),...
            mean(FRProfileMeanStim{i}.meanAvgFRProfileBefRun)],...
            [std(FRProfileMean{i}.meanAvgFRProfileBefRun)...
                /sqrt(length(FRProfileMean{i}.meanAvgFRProfileBefRun)),...
            std(FRProfileMeanStim{i}.meanAvgFRProfileBefRun)...
                /sqrt(length(FRProfileMeanStim{i}.meanAvgFRProfileBefRun))],...
            [FRProfileMean{i}.meanAvgFRProfileBefRun,...
            FRProfileMeanStim{i}.meanAvgFRProfileBefRun],...
            ['FRMean Befrun cond ' num2str(i)],...
            '', [FRProfileMeanStats{i}.pRSBefRunAll,FRProfileMeanStats{i}.pSignRBefRunAll],...
            ['FRMeanBefRunGoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,colorSel,xlabels,xLimTmp); %pathAnal0,colorSel,xlabels,[0 4]); %
        
        barPlotWithStat1(1:2,...
            [mean(FRProfileMean{i}.meanAvgFRProfile0to1),...
            mean(FRProfileMeanStim{i}.meanAvgFRProfile0to1)],...
            [std(FRProfileMean{i}.meanAvgFRProfile0to1)...
                /sqrt(length(FRProfileMean{i}.meanAvgFRProfile0to1)),...
            std(FRProfileMeanStim{i}.meanAvgFRProfile0to1)...
                /sqrt(length(FRProfileMeanStim{i}.meanAvgFRProfile0to1))],...
            [FRProfileMean{i}.meanAvgFRProfile0to1,...
            FRProfileMeanStim{i}.meanAvgFRProfile0to1],...
            ['FRMean 0to1s cond ' num2str(i)],...
            '', [FRProfileMeanStats{i}.pRS0to1All,FRProfileMeanStats{i}.pSignR0to1All],...
            ['FRMean0to1sGoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,colorSel,xlabels,xLimTmp); %pathAnal0,colorSel,xlabels,[0 4]); %
        
        barPlotWithStat1(1:2,...
            [mean(FRProfileMean{i}.meanAvgFRProfile0to1st),...
            mean(FRProfileMeanStim{i}.meanAvgFRProfile0to1st)],...
            [std(FRProfileMean{i}.meanAvgFRProfile0to1st)...
                /sqrt(length(FRProfileMean{i}.meanAvgFRProfile0to1st)),...
            std(FRProfileMeanStim{i}.meanAvgFRProfile0to1st)...
                /sqrt(length(FRProfileMeanStim{i}.meanAvgFRProfile0to1st))],...
            [FRProfileMean{i}.meanAvgFRProfile0to1st,...
            FRProfileMeanStim{i}.meanAvgFRProfile0to1st],...
            ['FRMean 0to1s-st cond ' num2str(i)],...
            '', [FRProfileMeanStats{i}.pRS0to1stAll,FRProfileMeanStats{i}.pSignR0to1stAll],...
            ['FRMean0to1sStGoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,colorSel,xlabels,xLimTmp); %pathAnal0,colorSel,xlabels,[0 4]); %
        
        barPlotWithStat1(1:2,...
            [mean(FRProfileMean{i}.meanAvgFRProfile0to3),...
            mean(FRProfileMeanStim{i}.meanAvgFRProfile0to3)],...
            [std(FRProfileMean{i}.meanAvgFRProfile0to3)...
                /sqrt(length(FRProfileMean{i}.meanAvgFRProfile0to3)),...
            std(FRProfileMeanStim{i}.meanAvgFRProfile0to3)...
                /sqrt(length(FRProfileMeanStim{i}.meanAvgFRProfile0to3))],...
            [FRProfileMean{i}.meanAvgFRProfile0to3,...
            FRProfileMeanStim{i}.meanAvgFRProfile0to3],...
            ['FRMean 0to3s cond ' num2str(i)],...
            '', [FRProfileMeanStats{i}.pRS0to3All,FRProfileMeanStats{i}.pSignR0to3All],...
            ['FRMean0to3sGoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,colorSel,xlabels,xLimTmp); %pathAnal0,colorSel,xlabels,[0 4]); %
        
         barPlotWithStat1(1:2,...
            [mean(FRProfileMean{i}.meanAvgFRProfile0to2),...
            mean(FRProfileMeanStim{i}.meanAvgFRProfile0to2)],...
            [std(FRProfileMean{i}.meanAvgFRProfile0to2)...
                /sqrt(length(FRProfileMean{i}.meanAvgFRProfile0to2)),...
            std(FRProfileMeanStim{i}.meanAvgFRProfile0to2)...
                /sqrt(length(FRProfileMeanStim{i}.meanAvgFRProfile0to2))],...
            [FRProfileMean{i}.meanAvgFRProfile0to2,...
            FRProfileMeanStim{i}.meanAvgFRProfile0to2],...
            ['FRMean 0to2s cond ' num2str(i)],...
            '', [FRProfileMeanStats{i}.pRS0to2All,FRProfileMeanStats{i}.pSignR0to2All],...
            ['FRMean0to2sGoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,colorSel,xlabels,xLimTmp); %pathAnal0,colorSel,xlabels,[0 4]); % added on 1/6/2024
        
        barPlotWithStat1(1:2,...
            [mean(FRProfileMean{i}.meanAvgFRProfile3to4),...
            mean(FRProfileMeanStim{i}.meanAvgFRProfile3to4)],...
            [std(FRProfileMean{i}.meanAvgFRProfile3to4)...
                /sqrt(length(FRProfileMean{i}.meanAvgFRProfile3to4)),...
            std(FRProfileMeanStim{i}.meanAvgFRProfile3to4)...
                /sqrt(length(FRProfileMeanStim{i}.meanAvgFRProfile3to4))],...
            [FRProfileMean{i}.meanAvgFRProfile3to4,...
            FRProfileMeanStim{i}.meanAvgFRProfile3to4],...
            ['FRMean 3to4s cond ' num2str(i)],...
            '', [FRProfileMeanStats{i}.pRS3to4All,FRProfileMeanStats{i}.pSignR3to4All],...
            ['FRMean3to4sGoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,colorSel,xlabels,xLimTmp); %pathAnal0,colorSel,xlabels,[0 4]); %
        
        barPlotWithStat1(1:2,...
            [mean(FRProfileMean{i}.meanAvgFRProfile3to5),...
            mean(FRProfileMeanStim{i}.meanAvgFRProfile3to5)],...
            [std(FRProfileMean{i}.meanAvgFRProfile3to5)...
                /sqrt(length(FRProfileMean{i}.meanAvgFRProfile3to5)),...
            std(FRProfileMeanStim{i}.meanAvgFRProfile3to5)...
                /sqrt(length(FRProfileMeanStim{i}.meanAvgFRProfile3to5))],...
            [FRProfileMean{i}.meanAvgFRProfile3to5,...
            FRProfileMeanStim{i}.meanAvgFRProfile3to5],...
            ['FRMean 3to5s cond ' num2str(i)],...
            '', [FRProfileMeanStats{i}.pRS3to5All,FRProfileMeanStats{i}.pSignR3to5All],...
            ['FRMean3to5sGoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,colorSel,xlabels,xLimTmp); %pathAnal0,colorSel,xlabels,[0 4]); %
        
        %% FR mean change between segments
        
        meanIsNan = ~isnan(FRProfileMean{i}.percChangeBefRunVsBL) & ...
            ~isinf(FRProfileMean{i}.percChangeBefRunVsBL);
        meanStimIsNan = ~isnan(FRProfileMeanStim{i}.percChangeBefRunVsBL) & ...
            ~isinf(FRProfileMeanStim{i}.percChangeBefRunVsBL);
        barPlotWithStat1(1:2,...
            [mean(FRProfileMean{i}.percChangeBefRunVsBL(meanIsNan)),...
            mean(FRProfileMeanStim{i}.percChangeBefRunVsBL(meanStimIsNan))],...
            [std(FRProfileMean{i}.percChangeBefRunVsBL(meanIsNan))...
                /sqrt(length(FRProfileMean{i}.percChangeBefRunVsBL(meanIsNan))),...
            std(FRProfileMeanStim{i}.percChangeBefRunVsBL(meanStimIsNan))...
                /sqrt(length(FRProfileMeanStim{i}.percChangeBefRunVsBL(meanStimIsNan)))],...
            [FRProfileMean{i}.percChangeBefRunVsBL,...
            FRProfileMeanStim{i}.percChangeBefRunVsBL],...
            ['BefRunVsBL cond ' num2str(i)],...
            '', FRProfileMeanStats{i}.pRSPercChangeBefRunVsBLAll,...
            ['FRMeanBefRunVsBLGoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,colorSel,xlabels);
        
        meanIsNan = ~isnan(FRProfileMean{i}.percChange0to1VsBL) & ...
            ~isinf(FRProfileMean{i}.percChange0to1VsBL);
        meanStimIsNan = ~isnan(FRProfileMeanStim{i}.percChange0to1VsBL) & ...
            ~isinf(FRProfileMeanStim{i}.percChange0to1VsBL);
        barPlotWithStat1(1:2,...
            [mean(FRProfileMean{i}.percChange0to1VsBL(meanIsNan)),...
            mean(FRProfileMeanStim{i}.percChange0to1VsBL(meanStimIsNan))],...
            [std(FRProfileMean{i}.percChange0to1VsBL(meanIsNan))...
                /sqrt(length(FRProfileMean{i}.percChange0to1VsBL(meanIsNan))),...
            std(FRProfileMeanStim{i}.percChange0to1VsBL(meanStimIsNan))...
                /sqrt(length(FRProfileMeanStim{i}.percChange0to1VsBL(meanStimIsNan)))],...
            [FRProfileMean{i}.percChange0to1VsBL,...
            FRProfileMeanStim{i}.percChange0to1VsBL],...
            ['0to1VsBL cond ' num2str(i)],...
            '', FRProfileMeanStats{i}.pRSPercChange0to1VsBLAll,...
            ['FRMean0to1VsBLGoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,colorSel,xlabels);
        
        meanIsNan = ~isnan(FRProfileMean{i}.percChangeBefRunVs0to1) & ...
            ~isinf(FRProfileMean{i}.percChangeBefRunVs0to1);
        meanStimIsNan = ~isnan(FRProfileMeanStim{i}.percChangeBefRunVs0to1) & ...
            ~isinf(FRProfileMeanStim{i}.percChangeBefRunVs0to1);
        barPlotWithStat1(1:2,...
            [mean(FRProfileMean{i}.percChangeBefRunVs0to1(meanIsNan)),...
            mean(FRProfileMeanStim{i}.percChangeBefRunVs0to1(meanStimIsNan))],...
            [std(FRProfileMean{i}.percChangeBefRunVs0to1(meanIsNan))...
                /sqrt(length(FRProfileMean{i}.percChangeBefRunVs0to1(meanIsNan))),...
            std(FRProfileMeanStim{i}.percChangeBefRunVs0to1(meanStimIsNan))...
                /sqrt(length(FRProfileMeanStim{i}.percChangeBefRunVs0to1(meanStimIsNan)))],...
            [FRProfileMean{i}.percChangeBefRunVs0to1,...
            FRProfileMeanStim{i}.percChangeBefRunVs0to1],...
            ['BefRunVs0to1 cond ' num2str(i)],...
            '', FRProfileMeanStats{i}.pRSPercChangeBefRunVs0to1All,...
            ['FRMeanBefRunVs0to1GoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,colorSel,xlabels);
        
        meanIsNan = ~isnan(FRProfileMean{i}.percChangeBefRunVs1to3) & ...
            ~isinf(FRProfileMean{i}.percChangeBefRunVs1to3);
        meanStimIsNan = ~isnan(FRProfileMeanStim{i}.percChangeBefRunVs1to3) & ...
            ~isinf(FRProfileMeanStim{i}.percChangeBefRunVs1to3);
        barPlotWithStat1(1:2,...
            [mean(FRProfileMean{i}.percChangeBefRunVs1to3(meanIsNan)),...
            mean(FRProfileMeanStim{i}.percChangeBefRunVs1to3(meanStimIsNan))],...
            [std(FRProfileMean{i}.percChangeBefRunVs1to3(meanIsNan))...
                /sqrt(length(FRProfileMean{i}.percChangeBefRunVs1to3(meanIsNan))),...
            std(FRProfileMeanStim{i}.percChangeBefRunVs1to3(meanStimIsNan))...
                /sqrt(length(FRProfileMeanStim{i}.percChangeBefRunVs1to3(meanStimIsNan)))],...
            [FRProfileMean{i}.percChangeBefRunVs1to3,...
            FRProfileMeanStim{i}.percChangeBefRunVs1to3],...
            ['BefRunVs1to3 cond ' num2str(i)],...
            '', FRProfileMeanStats{i}.pRSPercChangeBefRunVs1to3All,...
            ['FRMeanBefRunVs1to3GoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,colorSel,xlabels);
        
         meanIsNan = ~isnan(FRProfileMean{i}.percChangeBefRunVs3to5) & ...
            ~isinf(FRProfileMean{i}.percChangeBefRunVs3to5);
        meanStimIsNan = ~isnan(FRProfileMeanStim{i}.percChangeBefRunVs3to5) & ...
            ~isinf(FRProfileMeanStim{i}.percChangeBefRunVs3to5);
        barPlotWithStat1(1:2,...
            [mean(FRProfileMean{i}.percChangeBefRunVs3to5(meanIsNan)),...
            mean(FRProfileMeanStim{i}.percChangeBefRunVs3to5(meanStimIsNan))],...
            [std(FRProfileMean{i}.percChangeBefRunVs3to5(meanIsNan))...
                /sqrt(length(FRProfileMean{i}.percChangeBefRunVs3to5(meanIsNan))),...
            std(FRProfileMeanStim{i}.percChangeBefRunVs3to5(meanStimIsNan))...
                /sqrt(length(FRProfileMeanStim{i}.percChangeBefRunVs3to5(meanStimIsNan)))],...
            [FRProfileMean{i}.percChangeBefRunVs3to5,...
            FRProfileMeanStim{i}.percChangeBefRunVs3to5],...
            ['BefRunVs3to5 cond ' num2str(i)],...
            '', FRProfileMeanStats{i}.pRSPercChangeBefRunVs3to5All,...
            ['FRMeanBefRunVs3to5GoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,colorSel,xlabels);
        
        
        %% FR mean relative change between segments       
        meanIsNan = ~isnan(FRProfileMean{i}.relChangeBefRunVsBL) & ...
            ~isinf(FRProfileMean{i}.relChangeBefRunVsBL);
        meanStimIsNan = ~isnan(FRProfileMeanStim{i}.relChangeBefRunVsBL) & ...
            ~isinf(FRProfileMeanStim{i}.relChangeBefRunVsBL);
        barPlotWithStat1(1:2,...
            [mean(FRProfileMean{i}.relChangeBefRunVsBL(meanIsNan)),...
            mean(FRProfileMeanStim{i}.relChangeBefRunVsBL(meanStimIsNan))],...
            [std(FRProfileMean{i}.relChangeBefRunVsBL(meanIsNan))...
                /sqrt(length(FRProfileMean{i}.relChangeBefRunVsBL(meanIsNan))),...
            std(FRProfileMeanStim{i}.relChangeBefRunVsBL(meanStimIsNan))...
                /sqrt(length(FRProfileMeanStim{i}.relChangeBefRunVsBL(meanStimIsNan)))],...
            [FRProfileMean{i}.relChangeBefRunVsBL,...
            FRProfileMeanStim{i}.relChangeBefRunVsBL],...
            ['BefRunVsBL Rel cond ' num2str(i)],...
            '', [FRProfileMeanStats{i}.pRSRelChangeBefRunVsBLAll,...
            FRProfileMeanStats{i}.pSignRRelChangeBefRunVsBLAll],...
            ['FRMeanRelBefRunVsBLGoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,colorSel,xlabels,[-0.6 0.6]);
        
        meanIsNan = ~isnan(FRProfileMean{i}.relChange0to1VsBL) & ...
            ~isinf(FRProfileMean{i}.relChange0to1VsBL);
        meanStimIsNan = ~isnan(FRProfileMeanStim{i}.relChange0to1VsBL) & ...
            ~isinf(FRProfileMeanStim{i}.relChange0to1VsBL);
        barPlotWithStat1(1:2,...
            [mean(FRProfileMean{i}.relChange0to1VsBL(meanIsNan)),...
            mean(FRProfileMeanStim{i}.relChange0to1VsBL(meanStimIsNan))],...
            [std(FRProfileMean{i}.relChange0to1VsBL(meanIsNan))...
                /sqrt(length(FRProfileMean{i}.relChange0to1VsBL(meanIsNan))),...
            std(FRProfileMeanStim{i}.relChange0to1VsBL(meanStimIsNan))...
                /sqrt(length(FRProfileMeanStim{i}.relChange0to1VsBL(meanStimIsNan)))],...
            [FRProfileMean{i}.relChange0to1VsBL,...
            FRProfileMeanStim{i}.relChange0to1VsBL],...
            ['0to1VsBL Rel cond ' num2str(i)],...
            '', [FRProfileMeanStats{i}.pRSRelChange0to1VsBLAll,...
            FRProfileMeanStats{i}.pSignRRelChange0to1VsBLAll],...
            ['FRMeanRel0to1VsBLGoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,colorSel,xlabels,[-0.6 0.6]);
        
        meanIsNan = ~isnan(FRProfileMean{i}.relChangeBefRunVs0to1) & ...
            ~isinf(FRProfileMean{i}.relChangeBefRunVs0to1);
        meanStimIsNan = ~isnan(FRProfileMeanStim{i}.relChangeBefRunVs0to1) & ...
            ~isinf(FRProfileMeanStim{i}.relChangeBefRunVs0to1);
        barPlotWithStat1(1:2,...
            [mean(FRProfileMean{i}.relChangeBefRunVs0to1(meanIsNan)),...
            mean(FRProfileMeanStim{i}.relChangeBefRunVs0to1(meanStimIsNan))],...
            [std(FRProfileMean{i}.relChangeBefRunVs0to1(meanIsNan))...
                /sqrt(length(FRProfileMean{i}.relChangeBefRunVs0to1(meanIsNan))),...
            std(FRProfileMeanStim{i}.relChangeBefRunVs0to1(meanStimIsNan))...
                /sqrt(length(FRProfileMeanStim{i}.relChangeBefRunVs0to1(meanStimIsNan)))],...
            [FRProfileMean{i}.relChangeBefRunVs0to1,...
            FRProfileMeanStim{i}.relChangeBefRunVs0to1],...
            ['BefRunVs0to1 Rel cond ' num2str(i)],...
            '', [FRProfileMeanStats{i}.pRSRelChangeBefRunVs0to1All,...
            FRProfileMeanStats{i}.pSignRRelChangeBefRunVs0to1All],...
            ['FRMeanRelBefRunVs0to1GoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,colorSel,xlabels,[-0.6 0.6]);
        
        meanIsNan = ~isnan(FRProfileMean{i}.relChangeBefRunVs1to3) & ...
            ~isinf(FRProfileMean{i}.relChangeBefRunVs1to3);
        meanStimIsNan = ~isnan(FRProfileMeanStim{i}.relChangeBefRunVs1to3) & ...
            ~isinf(FRProfileMeanStim{i}.relChangeBefRunVs1to3);
        barPlotWithStat1(1:2,...
            [mean(FRProfileMean{i}.relChangeBefRunVs1to3(meanIsNan)),...
            mean(FRProfileMeanStim{i}.relChangeBefRunVs1to3(meanStimIsNan))],...
            [std(FRProfileMean{i}.relChangeBefRunVs1to3(meanIsNan))...
                /sqrt(length(FRProfileMean{i}.relChangeBefRunVs1to3(meanIsNan))),...
            std(FRProfileMeanStim{i}.relChangeBefRunVs1to3(meanStimIsNan))...
                /sqrt(length(FRProfileMeanStim{i}.relChangeBefRunVs1to3(meanStimIsNan)))],...
            [FRProfileMean{i}.relChangeBefRunVs1to3,...
            FRProfileMeanStim{i}.relChangeBefRunVs1to3],...
            ['BefRunVs1to3 Rel cond ' num2str(i)],...
            '', [FRProfileMeanStats{i}.pRSRelChangeBefRunVs1to3All,...
            FRProfileMeanStats{i}.pSignRRelChangeBefRunVs1to3All],...
            ['FRMeanRelBefRunVs1to3GoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,colorSel,xlabels,[-0.6 0.6]);
        
         meanIsNan = ~isnan(FRProfileMean{i}.relChangeBefRunVs3to5) & ...
            ~isinf(FRProfileMean{i}.relChangeBefRunVs3to5);
        meanStimIsNan = ~isnan(FRProfileMeanStim{i}.relChangeBefRunVs3to5) & ...
            ~isinf(FRProfileMeanStim{i}.relChangeBefRunVs3to5);
        barPlotWithStat1(1:2,...
            [mean(FRProfileMean{i}.relChangeBefRunVs3to5(meanIsNan)),...
            mean(FRProfileMeanStim{i}.relChangeBefRunVs3to5(meanStimIsNan))],...
            [std(FRProfileMean{i}.relChangeBefRunVs3to5(meanIsNan))...
                /sqrt(length(FRProfileMean{i}.relChangeBefRunVs3to5(meanIsNan))),...
            std(FRProfileMeanStim{i}.relChangeBefRunVs3to5(meanStimIsNan))...
                /sqrt(length(FRProfileMeanStim{i}.relChangeBefRunVs3to5(meanStimIsNan)))],...
            [FRProfileMean{i}.relChangeBefRunVs3to5,...
            FRProfileMeanStim{i}.relChangeBefRunVs3to5],...
            ['BefRunVs3to5 Rel cond ' num2str(i)],...
            '', [FRProfileMeanStats{i}.pRSRelChangeBefRunVs3to5All,...
            FRProfileMeanStats{i}.pSignRRelChangeBefRunVs3to5All],...
            ['FRMeanRelBefRunVs3to5GoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,colorSel,xlabels,[-0.6 0.6]);
    end