function plotPyrNeuWithFieldStimStats_1stStimCtrl(pathAnal0,FRProfileMean,FRProfileMeanStim,FRProfileMeanStats,xlabels,fnstr,isField)

    colorSel = 0;
    if(isField)
        xLimTmp = [0 4];
    else
        xLimTmp = [0 3.1];
    end
    for i = 1:length(FRProfileMean)
        
        %% added pm 10/26/2023
        barPlotWithStat1(1:2,...
            [mean(FRProfileMean{i}.meanAvgFRProfileAll),...
            mean(FRProfileMeanStim{i}.meanAvgFRProfileAll)],...
            [std(FRProfileMean{i}.meanAvgFRProfileAll)...
                /sqrt(length(FRProfileMean{i}.meanAvgFRProfileAll)),...
            std(FRProfileMeanStim{i}.meanAvgFRProfileAll)...
                /sqrt(length(FRProfileMeanStim{i}.meanAvgFRProfileAll))],...
            [FRProfileMean{i}.meanAvgFRProfileAll,...
            FRProfileMeanStim{i}.meanAvgFRProfileAll],...
            ['FRMean All cond ' num2str(i)],...
            '', [FRProfileMeanStats{i}.pRSAll,FRProfileMeanStats{i}.pSignRAll],...
            ['FRMeanAll' fnstr '_cond' num2str(i)],...
            pathAnal0,colorSel,xlabels,xLimTmp);
        
       
        barPlotWithStat1(1:2,...
            [mean(FRProfileMean{i}.meanAvgFRProfileBefRun),...
            mean(FRProfileMeanStim{i}.meanAvgFRProfileBefRun)],...
            [std(FRProfileMean{i}.meanAvgFRProfileBefRun)...
                /sqrt(length(FRProfileMean{i}.meanAvgFRProfileBefRun)),...
            std(FRProfileMeanStim{i}.meanAvgFRProfileBefRun)...
                /sqrt(length(FRProfileMeanStim{i}.meanAvgFRProfileBefRun))],...
            [FRProfileMean{i}.meanAvgFRProfileBefRun,...
            FRProfileMeanStim{i}.meanAvgFRProfileBefRun],...
            ['FRMean Befrun cond ' num2str(i)],...
            '', [FRProfileMeanStats{i}.pRSBefRunAll,FRProfileMeanStats{i}.pSignRBefRunAll],...
            ['FRMeanBefRun' fnstr '_cond' num2str(i)],...
            pathAnal0,colorSel,xlabels,xLimTmp); %pathAnal0,colorSel,xlabels,[0 4]); %
        
        barPlotWithStat1(1:2,...
            [mean(FRProfileMean{i}.meanAvgFRProfile0to1),...
            mean(FRProfileMeanStim{i}.meanAvgFRProfile0to1)],...
            [std(FRProfileMean{i}.meanAvgFRProfile0to1)...
                /sqrt(length(FRProfileMean{i}.meanAvgFRProfile0to1)),...
            std(FRProfileMeanStim{i}.meanAvgFRProfile0to1)...
                /sqrt(length(FRProfileMeanStim{i}.meanAvgFRProfile0to1))],...
            [FRProfileMean{i}.meanAvgFRProfile0to1,...
            FRProfileMeanStim{i}.meanAvgFRProfile0to1],...
            ['FRMean 0to1s cond ' num2str(i)],...
            '', [FRProfileMeanStats{i}.pRS0to1All,FRProfileMeanStats{i}.pSignR0to1All],...
            ['FRMean0to1s' fnstr '_cond' num2str(i)],...
            pathAnal0,colorSel,xlabels,xLimTmp); %pathAnal0,colorSel,xlabels,[0 4]); %
        
        barPlotWithStat1(1:2,...
            [mean(FRProfileMean{i}.meanAvgFRProfile0to1st),...
            mean(FRProfileMeanStim{i}.meanAvgFRProfile0to1st)],...
            [std(FRProfileMean{i}.meanAvgFRProfile0to1st)...
                /sqrt(length(FRProfileMean{i}.meanAvgFRProfile0to1st)),...
            std(FRProfileMeanStim{i}.meanAvgFRProfile0to1st)...
                /sqrt(length(FRProfileMeanStim{i}.meanAvgFRProfile0to1st))],...
            [FRProfileMean{i}.meanAvgFRProfile0to1st,...
            FRProfileMeanStim{i}.meanAvgFRProfile0to1st],...
            ['FRMean 0to1s-st cond ' num2str(i)],...
            '', [FRProfileMeanStats{i}.pRS0to1stAll,FRProfileMeanStats{i}.pSignR0to1stAll],...
            ['FRMean0to1sSt' fnstr '_cond' num2str(i)],...
            pathAnal0,colorSel,xlabels,xLimTmp); %pathAnal0,colorSel,xlabels,[0 4]); %
        
       
        barPlotWithStat1(1:2,...
            [mean(FRProfileMean{i}.meanAvgFRProfile3to4),...
            mean(FRProfileMeanStim{i}.meanAvgFRProfile3to4)],...
            [std(FRProfileMean{i}.meanAvgFRProfile3to4)...
                /sqrt(length(FRProfileMean{i}.meanAvgFRProfile3to4)),...
            std(FRProfileMeanStim{i}.meanAvgFRProfile3to4)...
                /sqrt(length(FRProfileMeanStim{i}.meanAvgFRProfile3to4))],...
            [FRProfileMean{i}.meanAvgFRProfile3to4,...
            FRProfileMeanStim{i}.meanAvgFRProfile3to4],...
            ['FRMean 3to4s cond ' num2str(i)],...
            '', [FRProfileMeanStats{i}.pRS3to4All,FRProfileMeanStats{i}.pSignR3to4All],...
            ['FRMean3to4s' fnstr '_cond' num2str(i)],...
            pathAnal0,colorSel,xlabels,xLimTmp); %pathAnal0,colorSel,xlabels,[0 4]); %
        
        
    end