function plotPyrNeuStimUpDownAlone_NoF(pathAnal0, FRProfileMeanRise, FRProfileMeanDown, timeStepRun, PyrStim, FRProfile)

    %% all pyramidal neurons
    for i = 1:length(FRProfileMeanRise)
       %% normalized
        %% order pyramidal neurons based on bef/aft run firing rate ratio
        % and compare good non-stim with stim trials
        plotIndFRProfileCmp(timeStepRun,...
                PyrStim.avgFRProfileNorm(FRProfile{i}.indPyrRise,:),...
                PyrStim.avgFRProfileNormStim(FRProfile{i}.indPyrRise,:),['Neuron no.'],...
                ['PyrRise_IndFRProfileNormFR0to1VsBefRunNeuCmpGoodNoStimVsStim_Cond' num2str(i)],...
                pathAnal0,[],4,FRProfileMeanRise{i}.indFRBefRun,...
                FRProfileMeanRise{i}.indFR0to1)

        %% order pyramidal neurons based on before and after run FR ratio 
        % and compare good non-stim with stim trials
        plotIndFRProfileCmp(timeStepRun,...
                PyrStim.avgFRProfileNorm(FRProfile{i}.indPyrDown,:),...
                PyrStim.avgFRProfileNormStim(FRProfile{i}.indPyrDown,:),['Neuron no.'],...
                ['PyrDown_IndFRProfileNormFR0to1VsBefRunNeuCmpGoodNoStimVsStim_Cond' num2str(i)],...
                pathAnal0,[],4,FRProfileMeanDown{i}.indFRBefRun,...
                FRProfileMeanDown{i}.indFR0to1)

        %% order pyramidal neurons based on bef/aft run firing rate ratio
        % and compare good non-stim with stim trials, normalized to the
        % peak of ctrl trials
        plotIndFRProfileCmp(timeStepRun,...
                PyrStim.avgFRProfileNorm(FRProfile{i}.indPyrRise,:),...
                PyrStim.avgFRProfileNormStim1(FRProfile{i}.indPyrRise,:),['Neuron no.'],...
                ['PyrRise_IndFRProfileNormFR0to1VsBefRunNeuCmpGoodNoStimVsStim1_Cond' num2str(i)],...
                pathAnal0,[],4,FRProfileMeanRise{i}.indFRBefRun,...
                FRProfileMeanRise{i}.indFR0to1)

        %% order pyramidal neurons based on before and after run FR ratio 
        % and compare good non-stim with stim trials, normalized to the
        % peak of ctrl trials
        plotIndFRProfileCmp(timeStepRun,...
                PyrStim.avgFRProfileNorm(FRProfile{i}.indPyrDown,:),...
                PyrStim.avgFRProfileNormStim1(FRProfile{i}.indPyrDown,:),['Neuron no.'],...
                ['PyrDown_IndFRProfileNormFR0to1VsBefRunNeuCmpGoodNoStimVsStim1_Cond' num2str(i)],...
                pathAnal0,[],4,FRProfileMeanDown{i}.indFRBefRun,...
                FRProfileMeanDown{i}.indFR0to1)

        %% order pyramidal neurons based on the peak firing rate after 0
        % and compare good non-stim with stim trials
        plotIndFRProfileCmp(timeStepRun,...
                    PyrStim.avgFRProfileNorm(FRProfile{i}.indPyrRise,:),...
                    PyrStim.avgFRProfileNormStim(FRProfile{i}.indPyrRise,:),['Neuron no.'],...
                    ['PyrRise_IndFRProfileNormFRPeakAftRunNeuCmpGoodNoStimVsStim_Cond' num2str(i)],...
                    pathAnal0,[],5,[],[])

        %% order pyramidal neurons based on before and after run FR ratio 
        % and compare good non-stim with stim trials
        plotIndFRProfileCmp(timeStepRun,...
                    PyrStim.avgFRProfileNorm(FRProfile{i}.indPyrDown,:),...
                    PyrStim.avgFRProfileNormStim(FRProfile{i}.indPyrDown,:),['Neuron no.'],...
                    ['PyrDown_IndFRProfileNormFRPeakAftRunNeuCmpGoodNoStimVsStim_Cond' num2str(i)],...
                    pathAnal0,[],5,[],[])
    end