function plotPyrNeuStimUpDown_1stStimCtrl(pathAnal0,FRProfileMean1, modPyr1AL, PyrStim, FRProfile1)

    %% all pyramidal neurons
    for i = 1:length(FRProfileMean1)
        
        %% normalized
%         %% order pyramidal neurons based on the peak firing rate after 0
%         % and compare good non-stim with stim trials
%         plotIndFRProfileCmp(modPyr1AL.timeStepRun,...
%                 PyrStim.avgFRProfileNorm(FRProfile1{i}.ind,:),...
%                 PyrStim.avgFRProfileNormStim(FRProfile1{i}.ind,:),['Neuron no.'],...
%                 ['Pyr_IndFRProfileNormFRPeakAftRunNeuCmpGoodNoStimVsStim_Cond' num2str(i)],...
%                 pathAnal0,[],5,[],[])
        
        %% order pyramidal neurons based on before and after run FR ratio 
        % and compare good non-stim with stim trials
        plotIndFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileNorm(FRProfile1{i}.ind,:),...
                PyrStim.avgFRProfileNormStim(FRProfile1{i}.ind,:),['Neuron no.'],...
                ['Pyr_IndFRProfileNormFR0to1VsBefRunNeuCmpGoodNoStimVsStim_Cond' num2str(i)],...
                pathAnal0,[],4,FRProfileMean1{i}.indFRBefRun,...
                FRProfileMean1{i}.indFR0to1)
       
        %% order pyramidal neurons based on before and after run FR ratio 
        % and compare 1st stim ctrl with stim trials
        plotIndFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileNorm1stStimCtrl(FRProfile1{i}.ind,:),...
                PyrStim.avgFRProfileNormStim(FRProfile1{i}.ind,:),['Neuron no.'],...
                ['Pyr_IndFRProfileNormFR0to1VsBefRunNeuCmp1stStimCtrlVsStim_Cond' num2str(i)],...
                pathAnal0,[],4,FRProfileMean1{i}.indFRBefRun,...
                FRProfileMean1{i}.indFR0to1)   
            
        %% order pyramidal neurons based on before and after run FR ratio 
        % and compare 2nd stim ctrl with stim trials
        plotIndFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileNorm2ndStimCtrl(FRProfile1{i}.ind,:),...
                PyrStim.avgFRProfileNormStim(FRProfile1{i}.ind,:),['Neuron no.'],...
                ['Pyr_IndFRProfileNormFR0to1VsBefRunNeuCmp2ndStimCtrlVsStim_Cond' num2str(i)],...
                pathAnal0,[],4,FRProfileMean1{i}.indFRBefRun,...
                FRProfileMean1{i}.indFR0to1)
            
        %% order pyramidal neurons based on before and after run FR ratio 
        % and compare 1st stim ctrl with good non-strim trials
        plotIndFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileNorm(FRProfile1{i}.ind,:),...
                PyrStim.avgFRProfileNorm1stStimCtrl(FRProfile1{i}.ind,:),['Neuron no.'],...
                ['Pyr_IndFRProfileNormFR0to1VsBefRunNeuCmpGoodNonStim1stStimCtrl_Cond' num2str(i)],...
                pathAnal0,[],4,FRProfileMean1{i}.indFRBefRun,...
                FRProfileMean1{i}.indFR0to1)
            
        %% order pyramidal neurons based on before and after run FR ratio 
        % and compare 2nd stim ctrl with good non-strim trials
        plotIndFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfileNorm(FRProfile1{i}.ind,:),...
                PyrStim.avgFRProfileNorm2ndStimCtrl(FRProfile1{i}.ind,:),['Neuron no.'],...
                ['Pyr_IndFRProfileNormFR0to1VsBefRunNeuCmpGoodNonStimVs2ndStimCtrl_Cond' num2str(i)],...
                pathAnal0,[],4,FRProfileMean1{i}.indFRBefRun,...
                FRProfileMean1{i}.indFR0to1)
        
            
            
        %% not normalized, from non-stim Ctrl trials
        %% compare good non stim trials with stim trials, pyr rise
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfile(FRProfile1{i}.indPyrRise,:),...
                PyrStim.avgFRProfileStim(FRProfile1{i}.indPyrRise,:),...
                ['FR PyrRise'],...
                ['Pyr_FRProfilePyrRiseNoStimGoodVsStim_Cond' num2str(i)],...
                pathAnal0,[],[{'GoodNoStim'},{'Stim'}])
        
        %% compare good non stim trials with stim trials, pyr down
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfile(FRProfile1{i}.indPyrDown,:),...
                PyrStim.avgFRProfileStim(FRProfile1{i}.indPyrDown,:),...
                ['FR PyrDown'],...
                ['Pyr_FRProfilePyrDownNoStimGoodVsStim_Cond' num2str(i)],...
                pathAnal0,[],[{'GoodNoStim'},{'Stim'}])
            
        % added on 7/8/2022        
        %% compare good non stim trials with stim trials, pyr down
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfile(FRProfile1{i}.indPyrOther,:),...
                PyrStim.avgFRProfileStim(FRProfile1{i}.indPyrOther,:),...
                ['FR PyrOther'],...
                ['Pyr_FRProfilePyrOtherNoStimGoodVsStim_Cond' num2str(i)],...
                pathAnal0,[],[{'GoodNoStim'},{'Stim'}])
            
            
            
        %% not normalized, from 1st stim Ctrl trials
        %% compare stim Ctrl trials with stim trials, pyr rise
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfile1stStimCtrl(FRProfile1{i}.indPyrRise,:),...
                PyrStim.avgFRProfileStim(FRProfile1{i}.indPyrRise,:),...
                ['FR PyrRise'],...
                ['Pyr_FRProfilePyrRise1stStimCtrlVsStim_Cond' num2str(i)],...
                pathAnal0,[],[{'StimCtrl1'},{'Stim'}])
        
        %% compare stim Ctrl trials with stim trials, pyr down
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfile1stStimCtrl(FRProfile1{i}.indPyrDown,:),...
                PyrStim.avgFRProfileStim(FRProfile1{i}.indPyrDown,:),...
                ['FR PyrDown'],...
                ['Pyr_FRProfilePyrDown1stStimCtrlVsStim_Cond' num2str(i)],...
                pathAnal0,[],[{'StimCtrl1'},{'Stim'}])
            
        % added on 7/8/2022   
        %% compare stim Ctrl trials with stim trials, pyr other
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfile1stStimCtrl(FRProfile1{i}.indPyrOther,:),...
                PyrStim.avgFRProfileStim(FRProfile1{i}.indPyrOther,:),...
                ['FR PyrOther'],...
                ['Pyr_FRProfilePyrOther1stStimCtrlVsStim_Cond' num2str(i)],...
                pathAnal0,[],[{'StimCtrl1'},{'Stim'}])
            
            
            
        %% not normalized, from 2nd stim Ctrl trials
        %% compare stim Ctrl trials with stim trials, pyr rise
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfile2ndStimCtrl(FRProfile1{i}.indPyrRise,:),...
                PyrStim.avgFRProfileStim(FRProfile1{i}.indPyrRise,:),...
                ['FR PyrRise'],...
                ['Pyr_FRProfilePyrRise2ndStimCtrlVsStim_Cond' num2str(i)],...
                pathAnal0,[],[{'StimCtrl2'},{'Stim'}])
        
        %% compare stim Ctrl trials with stim trials, pyr down
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfile2ndStimCtrl(FRProfile1{i}.indPyrDown,:),...
                PyrStim.avgFRProfileStim(FRProfile1{i}.indPyrDown,:),...
                ['FR PyrDown'],...
                ['Pyr_FRProfilePyrDown2ndStimCtrlVsStim_Cond' num2str(i)],...
                pathAnal0,[],[{'StimCtrl2'},{'Stim'}])
            
        % added on 7/8/2022   
        %% compare stim Ctrl trials with stim trials, pyr other
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfile2ndStimCtrl(FRProfile1{i}.indPyrOther,:),...
                PyrStim.avgFRProfileStim(FRProfile1{i}.indPyrOther,:),...
                ['FR PyrOther'],...
                ['Pyr_FRProfilePyrOther2ndStimCtrlVsStim_Cond' num2str(i)],...
                pathAnal0,[],[{'StimCtrl2'},{'Stim'}])
            
        
                
        %% not normalized, nonstim ctrl vs 1st stim Ctrl trials
        %% compare stim Ctrl trials with stim trials, pyr rise
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfile1stStimCtrl(FRProfile1{i}.indPyrRise,:),...
                PyrStim.avgFRProfile(FRProfile1{i}.indPyrRise,:),...
                ['FR PyrRise'],...
                ['Pyr_FRProfilePyrRise1stStimCtrlVsGoodNonStim_Cond' num2str(i)],...
                pathAnal0,[],[{'StimCtrl1'},{'GoodNoStim'}])
        
        %% compare stim Ctrl trials with stim trials, pyr down
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfile1stStimCtrl(FRProfile1{i}.indPyrDown,:),...
                PyrStim.avgFRProfile(FRProfile1{i}.indPyrDown,:),...
                ['FR PyrDown'],...
                ['Pyr_FRProfilePyrDown1stStimCtrlVsGoodNonStim_Cond' num2str(i)],...
                pathAnal0,[],[{'StimCtrl1'},{'GoodNoStim'}])
            
        % added on 7/8/2022   
        %% compare stim Ctrl trials with stim trials, pyr other
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfile1stStimCtrl(FRProfile1{i}.indPyrOther,:),...
                PyrStim.avgFRProfile(FRProfile1{i}.indPyrOther,:),...
                ['FR PyrOther'],...
                ['Pyr_FRProfilePyrOther1stStimCtrlVsGoodNonStim_Cond' num2str(i)],...
                pathAnal0,[],[{'StimCtrl1'},{'GoodNoStim'}])
            
            
            
        %% not normalized, nonstim ctrl vs 1st stim Ctrl trials
        %% compare stim Ctrl trials with stim trials, pyr rise
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfile2ndStimCtrl(FRProfile1{i}.indPyrRise,:),...
                PyrStim.avgFRProfile(FRProfile1{i}.indPyrRise,:),...
                ['FR PyrRise'],...
                ['Pyr_FRProfilePyrRise2ndStimCtrlVsGoodNonStim_Cond' num2str(i)],...
                pathAnal0,[],[{'StimCtrl2'},{'GoodNoStim'}])
        
        %% compare stim Ctrl trials with stim trials, pyr down
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfile2ndStimCtrl(FRProfile1{i}.indPyrDown,:),...
                PyrStim.avgFRProfile(FRProfile1{i}.indPyrDown,:),...
                ['FR PyrDown'],...
                ['Pyr_FRProfilePyrDown2ndStimCtrlVsGoodNonStim_Cond' num2str(i)],...
                pathAnal0,[],[{'StimCtrl2'},{'GoodNoStim'}])
            
        % added on 7/8/2022   
        %% compare stim Ctrl trials with stim trials, pyr other
        plotAvgFRProfileCmp(modPyr1AL.timeStepRun,...
                PyrStim.avgFRProfile2ndStimCtrl(FRProfile1{i}.indPyrOther,:),...
                PyrStim.avgFRProfile(FRProfile1{i}.indPyrOther,:),...
                ['FR PyrOther'],...
                ['Pyr_FRProfilePyrOther2ndStimCtrlVsGoodNonStim_Cond' num2str(i)],...
                pathAnal0,[],[{'StimCtrl2'},{'GoodNoStim'}])
    end