function plotPyrNeuWithFieldStimStatsBox(pathAnal0,FRProfileMean,FRProfileMeanStim,FRProfileMeanStats,xlabels,fnstr)

    colorSel = 0;
    for i = 1:length(FRProfileMean)
        
        %% FR mean of each segment
        plotBoxPlot(FRProfileMean{i}.meanAvgFRProfileBaseline,...
            FRProfileMeanStim{i}.meanAvgFRProfileBaseline,...
            ['FRMean Baseline cond ' num2str(i)],...
            ['FRMeanBLGoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,[-1 8],FRProfileMeanStats{i}.pRSBLAll,colorSel,xlabels);
        
        plotBoxPlot(FRProfileMean{i}.meanAvgFRProfileBefRun,...
            FRProfileMeanStim{i}.meanAvgFRProfileBefRun,...
            ['FRMean Befrun cond ' num2str(i)],...
            ['FRMeanBefRunGoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,[-1 8],FRProfileMeanStats{i}.pRSBefRunAll,colorSel,xlabels);
        
        plotBoxPlot(FRProfileMean{i}.meanAvgFRProfile0to1,...
            FRProfileMeanStim{i}.meanAvgFRProfile0to1,...
            ['FRMean 0to1s cond ' num2str(i)],...
            ['FRMean0to1sGoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,[-1 8],FRProfileMeanStats{i}.pRS0to1All,colorSel,xlabels);
                
        plotBoxPlot(FRProfileMean{i}.meanAvgFRProfile1to3,...
            FRProfileMeanStim{i}.meanAvgFRProfile1to3,...
            ['FRMean 1to3s cond ' num2str(i)],...
            ['FRMean1to3sGoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,[-1 8],FRProfileMeanStats{i}.pRS1to3All,colorSel,xlabels);
        
        plotBoxPlot(FRProfileMean{i}.meanAvgFRProfile3to5,...
            FRProfileMeanStim{i}.meanAvgFRProfile3to5,...
            ['FRMean 3to5s cond ' num2str(i)],...
            ['FRMean3to5sGoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,[-1 8],FRProfileMeanStats{i}.pRS3to5All,colorSel,xlabels);
       
        %% FR mean change between segments
        
        plotBoxPlot(FRProfileMean{i}.percChangeBefRunVsBL,...
            FRProfileMeanStim{i}.percChangeBefRunVsBL,...
            ['BefRunVsBL cond ' num2str(i)],...
            ['FRMeanBefRunVsBLGoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,[-1 8],FRProfileMeanStats{i}.pRSPercChangeBefRunVsBLAll,colorSel,xlabels);
        
        plotBoxPlot(FRProfileMean{i}.percChange0to1VsBL,...
            FRProfileMeanStim{i}.percChange0to1VsBL,...
            ['0to1VsBL cond ' num2str(i)],...
            ['FRMean0to1VsBLGoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,[-1 8],FRProfileMeanStats{i}.pRSPercChange0to1VsBLAll,colorSel,xlabels);
       
        plotBoxPlot(FRProfileMean{i}.percChangeBefRunVs0to1,...
            FRProfileMeanStim{i}.percChangeBefRunVs0to1,...
            ['BefRunVs0to1 cond ' num2str(i)],...
            ['FRMeanBefRunVs0to1GoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,[-1 8],FRProfileMeanStats{i}.pRSPercChangeBefRunVs0to1All,colorSel,xlabels);
        
        plotBoxPlot(FRProfileMean{i}.percChangeBefRunVs1to3,...
            FRProfileMeanStim{i}.percChangeBefRunVs1to3,...
            ['BefRunVs1to3 cond ' num2str(i)],...
            ['FRMeanBefRunVs1to3GoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,[-1 8],FRProfileMeanStats{i}.pRSPercChangeBefRunVs1to3All,colorSel,xlabels);
        
        plotBoxPlot(FRProfileMean{i}.percChangeBefRunVs3to5,...
            FRProfileMeanStim{i}.percChangeBefRunVs3to5,...
            ['BefRunVs3to5 cond ' num2str(i)],...
            ['FRMeanBefRunVs3to5GoodNoStimVsStim' fnstr '_cond' num2str(i)],...
            pathAnal0,[-1 8],FRProfileMeanStats{i}.pRSPercChangeBefRunVs3to5All,colorSel,xlabels);
    end