function PyrIntInitPeakPVStimNonStim2ndStimCtrlSelSigChange1SelRec1(methodKMean,p1,pdrift)
% compare Pyramidal neurons and PV interneurons on their initial peak
          
    GlobalConstFq;
    
    %% load modPyr1AL.indDriftRec
    pathAnal = ['Z:\Yingxue\Draft\PV\PyramidalStimALNonStim2ndStimCtrlSig\' num2str(methodKMean) '\'];
    if(exist([pathAnal 'initPeakPyrAllRecSigStimNoStim2ndStimCtrl.mat']))
        load([pathAnal 'initPeakPyrAllRecSigStimNoStim2ndStimCtrl.mat']);
    end
    indDriftRec = modPyr1AL.indDriftRec;
    pKSMeanFRNonStimVsStimCtrlBL = modPyr1AL.pKSMeanFRNonStimVsStimCtrlBL;
    pRSMeanFRNonStimVsStimCtrlBL = modPyr1AL.pRSMeanFRNonStimVsStimCtrlBL;
    pKSMeanFRNonStimVsStimCtrl0to1 = modPyr1AL.pKSMeanFRNonStimVsStimCtrl0to1;
    pRSMeanFRNonStimVsStimCtrl0to1 = modPyr1AL.pRSMeanFRNonStimVsStimCtrl0to1;
    %% label recordings to be excluded
    indInclRec = ones(1,length(modPyr1AL.indRec));
    for i = 1:length(excludeRec)
        ind = modPyr1AL.indRec == excludeRec(i);
        indInclRec(ind) = 0;
    end
    
    pathAnal0 = ['Z:\Yingxue\Draft\PV\PyramidalStimALNonStim_1stStimCtrlSelSigP' num2str(p1) '-NoDriftSelRec\'];
    pathAnal = ['Z:\Yingxue\Draft\PV\PyramidalStimALNonStim_1stStimCtrlSig\' num2str(methodKMean) '\'];
      
    %% load modPyr1AL generated by PyrInitPeakAllStimPVRecSigNonStim_1stStimCtrlTr
    if(exist([pathAnal 'initPeakPyrAllRecSigStimNoStim_1stStimCtrl.mat']))
        load([pathAnal 'initPeakPyrAllRecSigStimNoStim_1stStimCtrl.mat']);
    end
    
    %% load statistics generated by PyrInitPeakAllStimPVRecSigNonStim_1stStimCtrlTr
    if(exist([pathAnal 'initPeakPyrAllRecSigStimNoStim_1stSTimCtrl_km' num2str(methodKMean) '.mat']))
        load([pathAnal 'initPeakPyrAllRecSigStimNoStim_1stSTimCtrl_km' num2str(methodKMean) '.mat']);
    end
    
    %% load the results if this code has been run before
    if(exist([pathAnal0 'initPeakPyrIntAllRecStimSigNoStim_1stStimCtrl.mat']))
        load([pathAnal0 'initPeakPyrIntAllRecStimSigNoStim_1stStimCtrl.mat']);
    end
    
    if(~exist(pathAnal0))
        mkdir(pathAnal0);
    end
    
    if(p1 == 99.5)
        r = 1;
    elseif(p1 == 99)
        r = 2;
    else
        r = 3;
    end
    
    ind = indDriftRec & indInclRec;
    modPyr1AL.actOrInact = modPyr1AL.actOrInact(ind); % is it activation or inactivation
    modPyr1AL.indRec = modPyr1AL.indRec(ind); % recording index
    modPyr1AL.indNeu = modPyr1AL.indNeu(ind); % neuron indices trials
    modPyr1AL.pulseMeth = modPyr1AL.pulseMeth(ind); % pulse method
    modPyr1AL.stimLoc = modPyr1AL.stimLoc(ind); % stimulation location on the track
    modPyr1AL.avgFRProfile = modPyr1AL.avgFRProfile(ind,:); % average firing rate profile good trials
    modPyr1AL.avgFRProfileStim = modPyr1AL.avgFRProfileStim(ind,:); % average firing rate profile stim trials
    modPyr1AL.avgFRProfile1stStimCtrl = modPyr1AL.avgFRProfile1stStimCtrl(ind,:); % average firing rate profile 1st stim ctrl trials
    modPyr1AL.avgFRProfile2ndStimCtrl = modPyr1AL.avgFRProfile2ndStimCtrl(ind,:); % average firing rate profile 2nd stim ctrl trials
    modPyr1AL.isPeakNeuArrAll = modPyr1AL.isPeakNeuArrAll(:,ind);
    modPyr1AL.pKSMeanFRNonStimVsStimCtrlBL = pKSMeanFRNonStimVsStimCtrlBL(ind);
    modPyr1AL.pRSMeanFRNonStimVsStimCtrlBL = pRSMeanFRNonStimVsStimCtrlBL(ind);
    modPyr1AL.pKSMeanFRNonStimVsStimCtrl0to1 = pKSMeanFRNonStimVsStimCtrl0to1(ind);
    modPyr1AL.pRSMeanFRNonStimVsStimCtrl0to1 = pRSMeanFRNonStimVsStimCtrl0to1(ind);
        
    avgFRProfile = modPyr1AL.avgFRProfile; 
    avgFRProfileStim = modPyr1AL.avgFRProfileStim;
    avgFRProfile1stStimCtrl = modPyr1AL.avgFRProfile1stStimCtrl;
    avgFRProfile2ndStimCtrl = modPyr1AL.avgFRProfile2ndStimCtrl;

    PyrStim.avgFRProfile = avgFRProfile;
    PyrStim.avgFRProfileStim = avgFRProfileStim;
    PyrStim.avgFRProfile1stStimCtrl = avgFRProfile1stStimCtrl;
    PyrStim.avgFRProfile2ndStimCtrl = avgFRProfile2ndStimCtrl;
    PyrStim.avgFRProfileNorm = zeros(size(avgFRProfile,1),size(avgFRProfile,2));
    for i = 1:size(avgFRProfile,1)
        if(max(avgFRProfile(i,:)) ~= 0)
            PyrStim.avgFRProfileNorm(i,:) = avgFRProfile(i,:)/max(avgFRProfile(i,:));
        end
    end
    PyrStim.avgFRProfileNormStim = zeros(size(avgFRProfileStim,1),size(avgFRProfileStim,2));
    for i = 1:size(avgFRProfileStim,1)
        if(max(avgFRProfileStim(i,:)) ~= 0)
            PyrStim.avgFRProfileNormStim(i,:) = avgFRProfileStim(i,:)/max(avgFRProfileStim(i,:));
        end
    end
    
    PyrStim.avgFRProfileNorm1stStimCtrl = zeros(size(avgFRProfile1stStimCtrl,1),size(avgFRProfile1stStimCtrl,2));
    for i = 1:size(avgFRProfile1stStimCtrl,1)
        if(max(avgFRProfile1stStimCtrl(i,:)) ~= 0)
            PyrStim.avgFRProfileNorm1stStimCtrl(i,:) = avgFRProfile1stStimCtrl(i,:)/max(avgFRProfile1stStimCtrl(i,:));
        end
    end
    
    PyrStim.avgFRProfileNorm2ndStimCtrl = zeros(size(avgFRProfile2ndStimCtrl,1),size(avgFRProfile2ndStimCtrl,2));
    for i = 1:size(avgFRProfile2ndStimCtrl,1)
        if(max(avgFRProfile2ndStimCtrl(i,:)) ~= 0)
            PyrStim.avgFRProfileNorm2ndStimCtrl(i,:) = avgFRProfile2ndStimCtrl(i,:)/max(avgFRProfile2ndStimCtrl(i,:));
        end
    end

%     if(~exist('PyrRise'))
%         mean0to1 = mean(avgFRProfile(:,FRProfileMeanAll.indFR0to1),2);
%         meanBefRun = mean(avgFRProfile(:,FRProfileMeanAll.indFRBefRun),2);
%         ratio0to1BefRun = mean0to1./meanBefRun;
%         [ratio0to1BefRunOrd,indOrd] = sort(ratio0to1BefRun,'descend');
%         idxNan = isnan(ratio0to1BefRunOrd);
%         idxInf = isinf(ratio0to1BefRunOrd);
    %     idx = find(ratio0to1BefRunOrd < 1.25,1);
    %     idx1 = find(ratio0to1BefRunOrd >= 0.8,1,'last');

    %     idx = find(ratio0to1BefRunOrd < 2,1);
    %     idx1 = find(ratio0to1BefRunOrd >= 0.5,1,'last');

%         idx = find(ratio0to1BefRunOrd < 1.5,1);
%         idx1 = find(ratio0to1BefRunOrd >= 2/3,1,'last');
%         
%         tsneEmbed(PyrStim.avgFRProfileNorm(indOrd,FRProfileMeanAll.indFRBefRun(1):FRProfileMeanAll.indFR0to1(end)),...
%             idx,idx1,pathAnal0,'tsneEmbedPyrRiseDown');

        %% neurons with FR increase around 0
        indOrdTmp = find(modPyr1AL.isPeakNeuArrAll(r,:) == 1);
        
        PyrRise.idxRise = indOrdTmp;
        PyrRise.pulseMethod = modPyr1AL.pulseMeth(indOrdTmp);
        PyrRise.stimLoc = modPyr1AL.stimLoc(indOrdTmp);
        PyrRise.actOrInact = modPyr1AL.actOrInact(indOrdTmp);
        PyrRise.indRec = modPyr1AL.indRec(indOrdTmp);
        PyrRise.indNeu = modPyr1AL.indNeu(indOrdTmp);
        PyrRise.pKSMeanFRNonStimVsStimCtrlBL = modPyr1AL.pKSMeanFRNonStimVsStimCtrlBL(indOrdTmp);
        PyrRise.pRSMeanFRNonStimVsStimCtrlBL = modPyr1AL.pRSMeanFRNonStimVsStimCtrlBL(indOrdTmp);
        PyrRise.pKSMeanFRNonStimVsStimCtrl0to1 = modPyr1AL.pKSMeanFRNonStimVsStimCtrl0to1(indOrdTmp);
        PyrRise.pRSMeanFRNonStimVsStimCtrl0to1 = modPyr1AL.pRSMeanFRNonStimVsStimCtrl0to1(indOrdTmp);

        %% neurons with FR decrease around 0
        indOrdTmp = find(modPyr1AL.isPeakNeuArrAll(r,:) == -1);
        
        PyrDown.idxDown = indOrdTmp;
        PyrDown.pulseMethod = modPyr1AL.pulseMeth(indOrdTmp);
        PyrDown.stimLoc = modPyr1AL.stimLoc(indOrdTmp);
        PyrDown.actOrInact = modPyr1AL.actOrInact(indOrdTmp);
        PyrDown.indRec = modPyr1AL.indRec(indOrdTmp);
        PyrDown.indNeu = modPyr1AL.indNeu(indOrdTmp);
        PyrDown.pKSMeanFRNonStimVsStimCtrlBL = modPyr1AL.pKSMeanFRNonStimVsStimCtrlBL(indOrdTmp);
        PyrDown.pRSMeanFRNonStimVsStimCtrlBL = modPyr1AL.pRSMeanFRNonStimVsStimCtrlBL(indOrdTmp);
        PyrDown.pKSMeanFRNonStimVsStimCtrl0to1 = modPyr1AL.pKSMeanFRNonStimVsStimCtrl0to1(indOrdTmp);
        PyrDown.pRSMeanFRNonStimVsStimCtrl0to1 = modPyr1AL.pRSMeanFRNonStimVsStimCtrl0to1(indOrdTmp);
        
        %% other neurons (added on 7/8/2022)
        indOrdTmp = find(modPyr1AL.isPeakNeuArrAll(r,:) == 0);
        PyrOther.idxOther = indOrdTmp;
        PyrOther.pulseMethod = modPyr1AL.pulseMeth(indOrdTmp);
        PyrOther.stimLoc = modPyr1AL.stimLoc(indOrdTmp);
        PyrOther.actOrInact = modPyr1AL.actOrInact(indOrdTmp);
        PyrOther.indRec = modPyr1AL.indRec(indOrdTmp);
        PyrOther.indNeu = modPyr1AL.indNeu(indOrdTmp);
        PyrOther.pKSMeanFRNonStimVsStimCtrlBL = modPyr1AL.pKSMeanFRNonStimVsStimCtrlBL(indOrdTmp);
        PyrOther.pRSMeanFRNonStimVsStimCtrlBL = modPyr1AL.pRSMeanFRNonStimVsStimCtrlBL(indOrdTmp);
        PyrOther.pKSMeanFRNonStimVsStimCtrl0to1 = modPyr1AL.pKSMeanFRNonStimVsStimCtrl0to1(indOrdTmp);
        PyrOther.pRSMeanFRNonStimVsStimCtrl0to1 = modPyr1AL.pRSMeanFRNonStimVsStimCtrl0to1(indOrdTmp);

        pm3StimLoc{1} = unique(modPyr1AL.stimLocPerRec(modPyr1AL.pulseMethPerRec == 3 ...
            & modPyr1AL.actOrInactPerRec == 1)); % stim location for inactivation
        pm3StimLoc{2} = unique(modPyr1AL.stimLocPerRec(modPyr1AL.pulseMethPerRec == 3 ...
            & modPyr1AL.actOrInactPerRec == 2)); % stim location for activation
        % activation or inactivation
        cond = 0;
        for i = 1: 2
            % different pulse methods
            for j = 1:length(pulseMethod{i})
                if(pulseMethod{i}(j) == 3)
                    stimLocs = pm3StimLoc{i};
                else
                    stimLocs = 0;
                end
                for m = 1:length(stimLocs)  
                    cond = cond + 1;
                    ind = find(PyrRise.actOrInact == i & PyrRise.pulseMethod == pulseMethod{i}(j) ...
                            & PyrRise.stimLoc == stimLocs(m));
                    
                    PyrStim1.FRProfile1{cond}.actOrInact = i;
                    PyrStim1.FRProfile1{cond}.pulseMethod = pulseMethod{i}(j);
                    PyrStim1.FRProfile1{cond}.stimLoc = stimLocs(m);
                    PyrStim1.FRProfile1{cond}.indPyrRise = PyrRise.idxRise(ind);
                    PyrStim1.FRProfile1{cond}.indRecPyrRise = PyrRise.indRec(ind);
                    PyrStim1.FRProfile1{cond}.indNeuPyrRise = PyrRise.indNeu(ind);

                    ind = find(PyrDown.actOrInact == i & PyrDown.pulseMethod == pulseMethod{i}(j) ...
                            & PyrDown.stimLoc == stimLocs(m));
                    
                    PyrStim1.FRProfile1{cond}.indPyrDown = PyrDown.idxDown(ind);
                    PyrStim1.FRProfile1{cond}.indRecPyrDown = PyrDown.indRec(ind);
                    PyrStim1.FRProfile1{cond}.indNeuPyrDown = PyrDown.indNeu(ind);

                    %% added on 7/8/2022
                    ind = find(PyrOther.actOrInact == i & PyrOther.pulseMethod == pulseMethod{i}(j) ...
                            & PyrOther.stimLoc == stimLocs(m));
                    
                    PyrStim1.FRProfile1{cond}.indPyrOther = PyrOther.idxOther(ind);
                    PyrStim1.FRProfile1{cond}.indRecPyrOther = PyrOther.indRec(ind);
                    PyrStim1.FRProfile1{cond}.indNeuPyrOther = PyrOther.indNeu(ind);
                    
                    ind = find(modPyr1AL.actOrInact == i & modPyr1AL.pulseMeth == pulseMethod{i}(j) ...
                            & modPyr1AL.stimLoc == stimLocs(m));
                    
                    PyrStim1.FRProfile1{cond}.ind = ind;

                    %% Pyramidal neurons
                    PyrStim1.FRProfileMean1{cond} = accumMeanPVStim(avgFRProfile(PyrStim1.FRProfile1{cond}.ind,:),modPyr1AL.timeStepRun);
                    PyrStim1.FRProfileMeanStim1{cond} = accumMeanPVStim(avgFRProfileStim(PyrStim1.FRProfile1{cond}.ind,:),modPyr1AL.timeStepRun);
                    PyrStim1.FRProfileMean1stStimCtrl1{cond} = accumMeanPVStim(avgFRProfile1stStimCtrl(PyrStim1.FRProfile1{cond}.ind,:),modPyr1AL.timeStepRun);
                    PyrStim1.FRProfileMean2ndStimCtrl1{cond} = accumMeanPVStim(avgFRProfile2ndStimCtrl(PyrStim1.FRProfile1{cond}.ind,:),modPyr1AL.timeStepRun);

                    % compare good non-stim and stim trials
                    PyrStim1.FRProfileMeanStatNonStimVsStim{cond} = accumMeanPVStimStatGoodBad_1stStimCtrl(PyrStim1.FRProfileMean1{cond},PyrStim1.FRProfileMeanStim1{cond});
                    % compare stim and 1st stim ctrl trials
                    PyrStim1.FRProfileMeanStatStimVs1stStimCtrl{cond} = accumMeanPVStimStatGoodBad_1stStimCtrl(PyrStim1.FRProfileMeanStim1{cond},PyrStim1.FRProfileMean1stStimCtrl1{cond});
                    % compare stim and 2nd stim ctrl trials
                    PyrStim1.FRProfileMeanStatStimVs2ndStimCtrl{cond} = accumMeanPVStimStatGoodBad_1stStimCtrl(PyrStim1.FRProfileMeanStim1{cond},PyrStim1.FRProfileMean2ndStimCtrl1{cond});
                    % compare good non-stim and 1st stim ctrl trials
                    PyrStim1.FRProfileMeanStatGoodNonStimVs1stStimCtrl{cond} = accumMeanPVStimStatGoodBad_1stStimCtrl(PyrStim1.FRProfileMean1{cond},PyrStim1.FRProfileMean1stStimCtrl1{cond});
                    % compare good non-stim and 2nd stim ctrl trials
                    PyrStim1.FRProfileMeanStatGoodNonStimVs2ndStimCtrl{cond} = accumMeanPVStimStatGoodBad_1stStimCtrl(PyrStim1.FRProfileMean1{cond},PyrStim1.FRProfileMean2ndStimCtrl1{cond});

                    
                    %% pyramidal neurons rise and down
                    PyrRise.FRProfileMean{cond} = accumMeanPVStim(avgFRProfile(PyrStim1.FRProfile1{cond}.indPyrRise,:),modPyr1AL.timeStepRun);
                    PyrDown.FRProfileMean{cond} = accumMeanPVStim(avgFRProfile(PyrStim1.FRProfile1{cond}.indPyrDown,:),modPyr1AL.timeStepRun);
                    PyrOther.FRProfileMean{cond} = accumMeanPVStim(avgFRProfile(PyrStim1.FRProfile1{cond}.indPyrOther,:),modPyr1AL.timeStepRun); % added on 7/8/2022
                    
                    PyrRise.FRProfileMeanStim{cond} = accumMeanPVStim(avgFRProfileStim(PyrStim1.FRProfile1{cond}.indPyrRise,:),modPyr1AL.timeStepRun);
                    PyrDown.FRProfileMeanStim{cond} = accumMeanPVStim(avgFRProfileStim(PyrStim1.FRProfile1{cond}.indPyrDown,:),modPyr1AL.timeStepRun);
                    PyrOther.FRProfileMeanStim{cond} = accumMeanPVStim(avgFRProfileStim(PyrStim1.FRProfile1{cond}.indPyrOther,:),modPyr1AL.timeStepRun); % added on 7/8/2022
                    
                    PyrRise.FRProfileMean1stStimCtrl{cond} = accumMeanPVStim(avgFRProfile1stStimCtrl(PyrStim1.FRProfile1{cond}.indPyrRise,:),modPyr1AL.timeStepRun);
                    PyrDown.FRProfileMean1stStimCtrl{cond} = accumMeanPVStim(avgFRProfile1stStimCtrl(PyrStim1.FRProfile1{cond}.indPyrDown,:),modPyr1AL.timeStepRun);
                    PyrOther.FRProfileMean1stStimCtrl{cond} = accumMeanPVStim(avgFRProfile1stStimCtrl(PyrStim1.FRProfile1{cond}.indPyrOther,:),modPyr1AL.timeStepRun); % added on 7/8/2022
                    
                    PyrRise.FRProfileMean2ndStimCtrl{cond} = accumMeanPVStim(avgFRProfile2ndStimCtrl(PyrStim1.FRProfile1{cond}.indPyrRise,:),modPyr1AL.timeStepRun);
                    PyrDown.FRProfileMean2ndStimCtrl{cond} = accumMeanPVStim(avgFRProfile2ndStimCtrl(PyrStim1.FRProfile1{cond}.indPyrDown,:),modPyr1AL.timeStepRun);
                    PyrOther.FRProfileMean2ndStimCtrl{cond} = accumMeanPVStim(avgFRProfile2ndStimCtrl(PyrStim1.FRProfile1{cond}.indPyrOther,:),modPyr1AL.timeStepRun); % added on 7/8/2022

                    % compare good non-stim and stim trials rise neurons
                    PyrRise.FRProfileMeanStatNonStimVsStim{cond} = accumMeanPVStimStatGoodBad_1stStimCtrl(PyrRise.FRProfileMean{cond},PyrRise.FRProfileMeanStim{cond});
                    % compare stim and 1st stim ctrl trials rise neurons
                    PyrRise.FRProfileMeanStatStimVs1stStimCtrl{cond} = accumMeanPVStimStatGoodBad_1stStimCtrl(PyrRise.FRProfileMeanStim{cond},PyrRise.FRProfileMean1stStimCtrl{cond});
                    % compare stim and 2nd stim ctrl trials rise neurons
                    PyrRise.FRProfileMeanStatStimVs2ndStimCtrl{cond} = accumMeanPVStimStatGoodBad_1stStimCtrl(PyrRise.FRProfileMeanStim{cond},PyrRise.FRProfileMean2ndStimCtrl{cond});
                    % compare good non-stim and 1st stim ctrl trials rise neurons
                    PyrRise.FRProfileMeanStatNonStimVs1stStimCtrl{cond} = accumMeanPVStimStatGoodBad_1stStimCtrl(PyrRise.FRProfileMean{cond},PyrRise.FRProfileMean1stStimCtrl{cond});
                    % compare good non-stim and 2nd stim ctrl trials rise neurons
                    PyrRise.FRProfileMeanStatNonStimVs2ndStimCtrl{cond} = accumMeanPVStimStatGoodBad_1stStimCtrl(PyrRise.FRProfileMean{cond},PyrRise.FRProfileMean2ndStimCtrl{cond});

                    % compare good non-stim and stim trials down neurons
                    PyrDown.FRProfileMeanStatNonStimVsStim{cond} = accumMeanPVStimStatGoodBad_1stStimCtrl(PyrDown.FRProfileMean{cond},PyrDown.FRProfileMeanStim{cond});
                    % compare stim and 1st stim ctrl trials rise neurons
                    PyrDown.FRProfileMeanStatStimVs1stStimCtrl{cond} = accumMeanPVStimStatGoodBad_1stStimCtrl(PyrDown.FRProfileMeanStim{cond},PyrDown.FRProfileMean1stStimCtrl{cond});
                    % compare stim and 2nd stim ctrl trials rise neurons
                    PyrDown.FRProfileMeanStatStimVs2ndStimCtrl{cond} = accumMeanPVStimStatGoodBad_1stStimCtrl(PyrDown.FRProfileMeanStim{cond},PyrDown.FRProfileMean2ndStimCtrl{cond});
                    % compare good non-stim and 1st stim ctrl trials rise neurons
                    PyrDown.FRProfileMeanStatNonStimVs1stStimCtrl{cond} = accumMeanPVStimStatGoodBad_1stStimCtrl(PyrDown.FRProfileMean{cond},PyrDown.FRProfileMean1stStimCtrl{cond});
                    % compare good non-stim and 2nd stim ctrl trials rise neurons
                    PyrDown.FRProfileMeanStatNonStimVs2ndStimCtrl{cond} = accumMeanPVStimStatGoodBad_1stStimCtrl(PyrDown.FRProfileMean{cond},PyrDown.FRProfileMean2ndStimCtrl{cond});

                    %% added on 7/8/2022
                    % compare good non-stim and stim trials other neurons
                    PyrOther.FRProfileMeanStatNonStimVsStim{cond} = accumMeanPVStimStatGoodBad_1stStimCtrl(PyrOther.FRProfileMean{cond},PyrOther.FRProfileMeanStim{cond});
                    % compare stim and 1st stim ctrl trials rise neurons
                    PyrOther.FRProfileMeanStatStimVs1stStimCtrl{cond} = accumMeanPVStimStatGoodBad_1stStimCtrl(PyrOther.FRProfileMeanStim{cond},PyrOther.FRProfileMean1stStimCtrl{cond});
                    % compare stim and 2nd stim ctrl trials rise neurons
                    PyrOther.FRProfileMeanStatStimVs2ndStimCtrl{cond} = accumMeanPVStimStatGoodBad_1stStimCtrl(PyrOther.FRProfileMeanStim{cond},PyrOther.FRProfileMean2ndStimCtrl{cond});
                    % compare good non-stim and 1st stim ctrl trials rise neurons
                    PyrOther.FRProfileMeanStatNonStimVs1stStimCtrl{cond} = accumMeanPVStimStatGoodBad_1stStimCtrl(PyrOther.FRProfileMean{cond},PyrOther.FRProfileMean1stStimCtrl{cond});
                    % compare good non-stim and 2nd stim ctrl trials rise neurons
                    PyrOther.FRProfileMeanStatNonStimVs2ndStimCtrl{cond} = accumMeanPVStimStatGoodBad_1stStimCtrl(PyrOther.FRProfileMean{cond},PyrOther.FRProfileMean2ndStimCtrl{cond});
                                       
                end
            end
        end

        save([pathAnal0 'initPeakPyrIntAllRecStimSigNoStim_1stStimCtrl.mat'],'PyrStim1','PyrRise','PyrDown','PyrOther','-v7.3'); 
%     end
    
   
    plotPyrNeuStimUpDown_1stStimCtrl(pathAnal0,PyrStim1.FRProfileMean1,modPyr1AL,PyrStim,PyrStim1.FRProfile1);
    close all;
    
    % pyr rise
    plotPyrNeuWithFieldStimStats_1stStimCtrl(pathAnal0,PyrRise.FRProfileMean,PyrRise.FRProfileMeanStim,...
        PyrRise.FRProfileMeanStatNonStimVsStim,[{'Nonstim'} {'Stim'}],'PyrRiseGoodNonStimVsStim',0);
    close all;

    plotPyrNeuWithFieldStimStats_1stStimCtrl(pathAnal0,PyrRise.FRProfileMean1stStimCtrl,PyrRise.FRProfileMeanStim,...
        PyrRise.FRProfileMeanStatStimVs1stStimCtrl,[{'StimCtrl1'} {'Stim'}],'PyrRise1stStimCtrlVsStim',0);
    close all;
    
    plotPyrNeuWithFieldStimStats_1stStimCtrl(pathAnal0,PyrRise.FRProfileMean1stStimCtrl,PyrRise.FRProfileMean,...
        PyrRise.FRProfileMeanStatStimVs1stStimCtrl,[{'StimCtrl1'} {'Nonstim'}],'PyrRise1stStimCtrlVsGoodNonStim',0);
    close all;


    % pyr down
    plotPyrNeuWithFieldStimStats_1stStimCtrl(pathAnal0,PyrDown.FRProfileMean,PyrDown.FRProfileMeanStim,...
        PyrDown.FRProfileMeanStatNonStimVsStim,[{'Nonstim'} {'Stim'}],'PyrDownGoodNonStimVsStim',0);
    close all;

    plotPyrNeuWithFieldStimStats_1stStimCtrl(pathAnal0,PyrDown.FRProfileMean1stStimCtrl,PyrDown.FRProfileMeanStim,...
        PyrDown.FRProfileMeanStatStimVs1stStimCtrl,[{'StimCtrl1'} {'Stim'}],'PyrDown1stStimCtrlVsStim',0);
    close all;
    
    plotPyrNeuWithFieldStimStats_1stStimCtrl(pathAnal0,PyrDown.FRProfileMean1stStimCtrl,PyrDown.FRProfileMean,...
        PyrDown.FRProfileMeanStatStimVs1stStimCtrl,[{'StimCtrl1'} {'Nonstim'}],'PyrDown1stStimCtrlVsGoodNonStim',0);
    close all;


    % pyr other
    plotPyrNeuWithFieldStimStats_1stStimCtrl(pathAnal0,PyrOther.FRProfileMean,PyrOther.FRProfileMeanStim,...
        PyrOther.FRProfileMeanStatNonStimVsStim,[{'Nonstim'} {'Stim'}],'PyrOtherGoodNonStimVsStim',0);
    close all;

    plotPyrNeuWithFieldStimStats_1stStimCtrl(pathAnal0,PyrOther.FRProfileMean1stStimCtrl,PyrOther.FRProfileMeanStim,...
        PyrOther.FRProfileMeanStatStimVs1stStimCtrl,[{'StimCtrl1'} {'Stim'}],'PyrOther1stStimCtrlVsStim',0);
    close all;
    
    plotPyrNeuWithFieldStimStats_1stStimCtrl(pathAnal0,PyrOther.FRProfileMean1stStimCtrl,PyrOther.FRProfileMean,...
        PyrOther.FRProfileMeanStatStimVs1stStimCtrl,[{'StimCtrl1'} {'Nonstim'}],'PyrOther1stStimCtrlVsGoodNonStim',0);
    close all;

    
   
end







