function PyrIntInitPeakCorrTPVStimCtrlSelRec(methodKMean)
%% activity correlation of PyrRise and PyrDown neurons before and during stimulation

    pathAnal0 = ['Z:\Yingxue\Draft\PV\PyramidalPVStimALCtrlSel\'];
    pathAnal = ['Z:\Yingxue\Draft\PV\PyramidalPVStimALCtrl\' num2str(methodKMean) '\'];
    
    if(exist([pathAnal 'initPeakPyrAllRecStimCtrlTr.mat']))
        load([pathAnal 'initPeakPyrAllRecStimCtrlTr.mat']);
    end
    
    if(exist([pathAnal0 'initPeakPyrIntAllRecStimCtrlTr.mat']))
        load([pathAnal0 'initPeakPyrIntAllRecStimCtrlTr.mat']);
    end
    
    if(exist([pathAnal0 'initPeakPyrIntCorrTAllRecStimCtrlTr.mat']))
        load([pathAnal0 'initPeakPyrIntCorrTAllRecStimCtrlTr.mat']);
    end
    
    %% exclude certain cells based on their baseline firng rate change between ctrl and stimctrl trials
    %% PLEASE MAKE SURE THAT THIS PART IS THE SAME AS IN PyrIntInitPeakPVStimCtrlSelRec
    ind = modPyr1AL.pRSMeanFRNonStimVsStimCtrlBL >= 0.01 & ...
        modPyr1AL.pKSMeanFRNonStimVsStimCtrlBL >= 0.01;
    %%
    
    PyrStimT.indNeuSel = ind;
    PyrStimT.actOrInact = modPyr1AL.actOrInact(ind); % is it activation or inactivation
    PyrStimT.indRec = modPyr1AL.indRec(ind); % recording index
    PyrStimT.indNeu = modPyr1AL.indNeu(ind); % neuron indices trials
    PyrStimT.pulseMeth = modPyr1AL.pulseMeth(ind); % pulse method
    PyrStimT.stimLoc = modPyr1AL.stimLoc(ind); % stimulation location on the track
    PyrStimT.meanNZNonStim = modPyr1AL.meanNZNonStim(ind);
    PyrStimT.meanNZStim = modPyr1AL.meanNZStim(ind);
    PyrStimT.meanNZStimCtrl = modPyr1AL.meanNZStimCtrl(ind);
    PyrStimT.meanNZStimNonStim = modPyr1AL.meanNZStimNonStim(ind);
    
    PyrRise1.meanNZNonStim = PyrStimT.meanNZNonStim(PyrRise.idxRise);
    PyrRise1.meanNZStim = PyrStimT.meanNZStim(PyrRise.idxRise);
    PyrRise1.meanNZStimCtrl = PyrStimT.meanNZStimCtrl(PyrRise.idxRise);
    PyrRise1.meanNZStimNonStim = PyrStimT.meanNZStimNonStim(PyrRise.idxRise);
    
    PyrDown1.meanNZNonStim = PyrStimT.meanNZNonStim(PyrDown.idxDown);
    PyrDown1.meanNZStim = PyrStimT.meanNZStim(PyrDown.idxDown);
    PyrDown1.meanNZStimCtrl = PyrStimT.meanNZStimCtrl(PyrDown.idxDown);
    PyrDown1.meanNZStimNonStim = PyrStimT.meanNZStimNonStim(PyrDown.idxDown);
    
    PyrOther1.meanNZNonStim = PyrStimT.meanNZNonStim(PyrOther.idxOther);
    PyrOther1.meanNZStim = PyrStimT.meanNZStim(PyrOther.idxOther);
    PyrOther1.meanNZStimCtrl = PyrStimT.meanNZStimCtrl(PyrOther.idxOther);
    PyrOther1.meanNZStimNonStim = PyrStimT.meanNZStimNonStim(PyrOther.idxOther);
    
    for cond = 1:length(PyrStim1.FRProfile1)
        PyrStimT.meanCorrTNZ{cond}.actOrInact = PyrStim1.FRProfile1{cond}.actOrInact;
        PyrStimT.meanCorrTNZ{cond}.pulseMethod = PyrStim1.FRProfile1{cond}.pulseMethod;
        PyrStimT.meanCorrTNZ{cond}.stimLoc = PyrStim1.FRProfile1{cond}.stimLoc;
        
        PyrStimT.meanCorrTNZ{cond}.indPyrRise = PyrStim1.FRProfile1{cond}.indPyrRise;
        PyrStimT.meanCorrTNZ{cond}.indRecPyrRise = PyrStim1.FRProfile1{cond}.indRecPyrRise;
        PyrStimT.meanCorrTNZ{cond}.indNeuPyrRise = PyrStim1.FRProfile1{cond}.indNeuPyrRise;
        
        PyrStimT.meanCorrTNZ{cond}.indPyrDown = PyrStim1.FRProfile1{cond}.indPyrDown;
        PyrStimT.meanCorrTNZ{cond}.indRecPyrDown = PyrStim1.FRProfile1{cond}.indRecPyrDown;
        PyrStimT.meanCorrTNZ{cond}.indNeuPyrDown = PyrStim1.FRProfile1{cond}.indNeuPyrDown;
        
        PyrStimT.meanCorrTNZ{cond}.indPyrOther = PyrStim1.FRProfile1{cond}.indPyrOther;
        PyrStimT.meanCorrTNZ{cond}.indRecPyrOther = PyrStim1.FRProfile1{cond}.indRecPyrOther;
        PyrStimT.meanCorrTNZ{cond}.indNeuPyrOther = PyrStim1.FRProfile1{cond}.indNeuPyrOther;
                
        %% pyramidal neurons
        PyrRise1.meanCorrTNZ{cond}.NonStim = ...
            PyrStimT.meanNZNonStim(PyrStimT.meanCorrTNZ{cond}.indPyrRise);
        PyrRise1.meanCorrTNZ{cond}.Stim = ...
            PyrStimT.meanNZStim(PyrStimT.meanCorrTNZ{cond}.indPyrRise);
        PyrRise1.meanCorrTNZ{cond}.StimCtrl = ...
            PyrStimT.meanNZStimCtrl(PyrStimT.meanCorrTNZ{cond}.indPyrRise);
        PyrRise1.meanCorrTNZ{cond}.StimNonStim = ...
            PyrStimT.meanNZStimNonStim(PyrStimT.meanCorrTNZ{cond}.indPyrRise);
        
        PyrDown1.meanCorrTNZ{cond}.NonStim = ...
            PyrStimT.meanNZNonStim(PyrStimT.meanCorrTNZ{cond}.indPyrDown);
        PyrDown1.meanCorrTNZ{cond}.Stim = ...
            PyrStimT.meanNZStim(PyrStimT.meanCorrTNZ{cond}.indPyrDown);
        PyrDown1.meanCorrTNZ{cond}.StimCtrl = ...
            PyrStimT.meanNZStimCtrl(PyrStimT.meanCorrTNZ{cond}.indPyrDown);
        PyrDown1.meanCorrTNZ{cond}.StimNonStim = ...
            PyrStimT.meanNZStimNonStim(PyrStimT.meanCorrTNZ{cond}.indPyrDown);
        
        PyrOther1.meanCorrTNZ{cond}.NonStim = ...
            PyrStimT.meanNZNonStim(PyrStimT.meanCorrTNZ{cond}.indPyrOther);
        PyrOther1.meanCorrTNZ{cond}.Stim = ...
            PyrStimT.meanNZStim(PyrStimT.meanCorrTNZ{cond}.indPyrOther);
        PyrOther1.meanCorrTNZ{cond}.StimCtrl = ...
            PyrStimT.meanNZStimCtrl(PyrStimT.meanCorrTNZ{cond}.indPyrOther);
        PyrOther1.meanCorrTNZ{cond}.StimNonStim = ...
            PyrStimT.meanNZStimNonStim(PyrStimT.meanCorrTNZ{cond}.indPyrOther);
        
        %% compare pyramidal neurons
        PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStim = ...
            ranksum(PyrRise1.meanCorrTNZ{cond}.NonStim,...
                    PyrRise1.meanCorrTNZ{cond}.Stim);
        PyrRise1.meanCorrTNZ{cond}.pRSStimVsStimCtrl = ...
            ranksum(PyrRise1.meanCorrTNZ{cond}.Stim,...
                    PyrRise1.meanCorrTNZ{cond}.StimCtrl);
        PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStim = ...
            ranksum(PyrRise1.meanCorrTNZ{cond}.NonStim,...
                    PyrRise1.meanCorrTNZ{cond}.StimNonStim);
        
        PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStim = ...
            ranksum(PyrDown1.meanCorrTNZ{cond}.NonStim,...
                    PyrDown1.meanCorrTNZ{cond}.Stim);
        PyrDown1.meanCorrTNZ{cond}.pRSStimVsStimCtrl = ...
            ranksum(PyrDown1.meanCorrTNZ{cond}.Stim,...
                    PyrDown1.meanCorrTNZ{cond}.StimCtrl);
        PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStim = ...
            ranksum(PyrDown1.meanCorrTNZ{cond}.NonStim,...
                    PyrDown1.meanCorrTNZ{cond}.StimNonStim);
                
        PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStim = ...
            ranksum(PyrOther1.meanCorrTNZ{cond}.NonStim,...
                    PyrOther1.meanCorrTNZ{cond}.Stim);
        PyrOther1.meanCorrTNZ{cond}.pRSStimVsStimCtrl = ...
            ranksum(PyrOther1.meanCorrTNZ{cond}.Stim,...
                    PyrOther1.meanCorrTNZ{cond}.StimCtrl);
        PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStim = ...
            ranksum(PyrOther1.meanCorrTNZ{cond}.NonStim,...
                    PyrOther1.meanCorrTNZ{cond}.StimNonStim);
                
        %% pyramidal neurons with fields
        PyrRise1.meanCorrTNZ{cond}.isField = PyrRise.isNeuWithFieldAligned{cond}.isField;
        PyrRise1.meanCorrTNZ{cond}.isFieldComb = PyrRise.isNeuWithFieldAligned{cond}.isFieldComb;
        
        PyrDown1.meanCorrTNZ{cond}.isField = PyrDown.isNeuWithFieldAligned{cond}.isField;
        PyrDown1.meanCorrTNZ{cond}.isFieldComb = PyrDown.isNeuWithFieldAligned{cond}.isFieldComb;
        
        PyrOther1.meanCorrTNZ{cond}.isField = PyrOther.isNeuWithFieldAligned{cond}.isField;
        PyrOther1.meanCorrTNZ{cond}.isFieldComb = PyrOther.isNeuWithFieldAligned{cond}.isFieldComb;
        
        % field
        PyrRise1.meanCorrTNZ{cond}.NonStimField = ...
            PyrRise1.meanCorrTNZ{cond}.NonStim(PyrRise1.meanCorrTNZ{cond}.isField == 1);
        PyrRise1.meanCorrTNZ{cond}.StimField = ...
            PyrRise1.meanCorrTNZ{cond}.Stim(PyrRise1.meanCorrTNZ{cond}.isField == 1);
        PyrRise1.meanCorrTNZ{cond}.StimCtrlField = ...
            PyrRise1.meanCorrTNZ{cond}.StimCtrl(PyrRise1.meanCorrTNZ{cond}.isField == 1);
        PyrRise1.meanCorrTNZ{cond}.StimNonStimField = ...
            PyrRise1.meanCorrTNZ{cond}.StimNonStim(PyrRise1.meanCorrTNZ{cond}.isField == 1);
        
        PyrDown1.meanCorrTNZ{cond}.NonStimField = ...
            PyrDown1.meanCorrTNZ{cond}.NonStim(PyrDown1.meanCorrTNZ{cond}.isField == 1);
        PyrDown1.meanCorrTNZ{cond}.StimField = ...
            PyrDown1.meanCorrTNZ{cond}.Stim(PyrDown1.meanCorrTNZ{cond}.isField == 1);
        PyrDown1.meanCorrTNZ{cond}.StimCtrlField = ...
            PyrDown1.meanCorrTNZ{cond}.StimCtrl(PyrDown1.meanCorrTNZ{cond}.isField == 1);
        PyrDown1.meanCorrTNZ{cond}.StimNonStimField = ...
            PyrDown1.meanCorrTNZ{cond}.StimNonStim(PyrDown1.meanCorrTNZ{cond}.isField == 1);
        
        PyrOther1.meanCorrTNZ{cond}.NonStimField = ...
            PyrOther1.meanCorrTNZ{cond}.NonStim(PyrOther1.meanCorrTNZ{cond}.isField == 1);
        PyrOther1.meanCorrTNZ{cond}.StimField = ...
            PyrOther1.meanCorrTNZ{cond}.Stim(PyrOther1.meanCorrTNZ{cond}.isField == 1);
        PyrOther1.meanCorrTNZ{cond}.StimCtrlField = ...
            PyrOther1.meanCorrTNZ{cond}.StimCtrl(PyrOther1.meanCorrTNZ{cond}.isField == 1);
        PyrOther1.meanCorrTNZ{cond}.StimNonStimField = ...
            PyrOther1.meanCorrTNZ{cond}.StimNonStim(PyrOther1.meanCorrTNZ{cond}.isField == 1);
        
        % field combo
        PyrRise1.meanCorrTNZ{cond}.NonStimFieldComb = ...
            PyrRise1.meanCorrTNZ{cond}.NonStim(PyrRise1.meanCorrTNZ{cond}.isFieldComb == 1);
        PyrRise1.meanCorrTNZ{cond}.StimFieldComb = ...
            PyrRise1.meanCorrTNZ{cond}.Stim(PyrRise1.meanCorrTNZ{cond}.isFieldComb == 1);
        PyrRise1.meanCorrTNZ{cond}.StimCtrlFieldComb = ...
            PyrRise1.meanCorrTNZ{cond}.StimCtrl(PyrRise1.meanCorrTNZ{cond}.isFieldComb == 1);
        PyrRise1.meanCorrTNZ{cond}.StimNonStimFieldComb = ...
            PyrRise1.meanCorrTNZ{cond}.StimNonStim(PyrRise1.meanCorrTNZ{cond}.isFieldComb == 1);
        
        PyrDown1.meanCorrTNZ{cond}.NonStimFieldComb = ...
            PyrDown1.meanCorrTNZ{cond}.NonStim(PyrDown1.meanCorrTNZ{cond}.isFieldComb == 1);
        PyrDown1.meanCorrTNZ{cond}.StimFieldComb = ...
            PyrDown1.meanCorrTNZ{cond}.Stim(PyrDown1.meanCorrTNZ{cond}.isFieldComb == 1);
        PyrDown1.meanCorrTNZ{cond}.StimCtrlFieldComb = ...
            PyrDown1.meanCorrTNZ{cond}.StimCtrl(PyrDown1.meanCorrTNZ{cond}.isFieldComb == 1);
        PyrDown1.meanCorrTNZ{cond}.StimNonStimFieldComb = ...
            PyrDown1.meanCorrTNZ{cond}.StimNonStim(PyrDown1.meanCorrTNZ{cond}.isFieldComb == 1);
        
        PyrOther1.meanCorrTNZ{cond}.NonStimFieldComb = ...
            PyrOther1.meanCorrTNZ{cond}.NonStim(PyrOther1.meanCorrTNZ{cond}.isFieldComb == 1);
        PyrOther1.meanCorrTNZ{cond}.StimFieldComb = ...
            PyrOther1.meanCorrTNZ{cond}.Stim(PyrOther1.meanCorrTNZ{cond}.isFieldComb == 1);
        PyrOther1.meanCorrTNZ{cond}.StimCtrlFieldComb = ...
            PyrOther1.meanCorrTNZ{cond}.StimCtrl(PyrOther1.meanCorrTNZ{cond}.isFieldComb == 1);
        PyrOther1.meanCorrTNZ{cond}.StimNonStimFieldComb = ...
            PyrOther1.meanCorrTNZ{cond}.StimNonStim(PyrOther1.meanCorrTNZ{cond}.isFieldComb == 1);
        
        %% compare pyramidal neurons with fields
        % field
        PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStimField = ...
            ranksum(PyrRise1.meanCorrTNZ{cond}.NonStimField,...
                    PyrRise1.meanCorrTNZ{cond}.StimField);
        PyrRise1.meanCorrTNZ{cond}.pRSStimVsStimCtrlField = ...
            ranksum(PyrRise1.meanCorrTNZ{cond}.StimField,...
                    PyrRise1.meanCorrTNZ{cond}.StimCtrlField);
        PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimField = ...
            ranksum(PyrRise1.meanCorrTNZ{cond}.NonStimField,...
                    PyrRise1.meanCorrTNZ{cond}.StimNonStimField);
        
        PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStimField = ...
            ranksum(PyrDown1.meanCorrTNZ{cond}.NonStimField,...
                    PyrDown1.meanCorrTNZ{cond}.StimField);
        PyrDown1.meanCorrTNZ{cond}.pRSStimVsStimCtrlField = ...
            ranksum(PyrDown1.meanCorrTNZ{cond}.StimField,...
                    PyrDown1.meanCorrTNZ{cond}.StimCtrlField);
        PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimField = ...
            ranksum(PyrDown1.meanCorrTNZ{cond}.NonStimField,...
                    PyrDown1.meanCorrTNZ{cond}.StimNonStimField);
                
        PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStimField = ...
            ranksum(PyrOther1.meanCorrTNZ{cond}.NonStimField,...
                    PyrOther1.meanCorrTNZ{cond}.StimField);
        PyrOther1.meanCorrTNZ{cond}.pRSStimVsStimCtrlField = ...
            ranksum(PyrOther1.meanCorrTNZ{cond}.StimField,...
                    PyrOther1.meanCorrTNZ{cond}.StimCtrlField);
        PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimField = ...
            ranksum(PyrOther1.meanCorrTNZ{cond}.NonStimField,...
                    PyrOther1.meanCorrTNZ{cond}.StimNonStimField);
                
        % field combo
        PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStimFieldComb = ...
            ranksum(PyrRise1.meanCorrTNZ{cond}.NonStimFieldComb,...
                    PyrRise1.meanCorrTNZ{cond}.StimFieldComb);
        PyrRise1.meanCorrTNZ{cond}.pRSStimVsStimCtrlFieldComb = ...
            ranksum(PyrRise1.meanCorrTNZ{cond}.StimFieldComb,...
                    PyrRise1.meanCorrTNZ{cond}.StimCtrlFieldComb);
        PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimFieldComb = ...
            ranksum(PyrRise1.meanCorrTNZ{cond}.NonStimFieldComb,...
                    PyrRise1.meanCorrTNZ{cond}.StimNonStimFieldComb);
        
        PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStimFieldComb = ...
            ranksum(PyrDown1.meanCorrTNZ{cond}.NonStimFieldComb,...
                    PyrDown1.meanCorrTNZ{cond}.StimFieldComb);
        PyrDown1.meanCorrTNZ{cond}.pRSStimVsStimCtrlFieldComb = ...
            ranksum(PyrDown1.meanCorrTNZ{cond}.StimFieldComb,...
                    PyrDown1.meanCorrTNZ{cond}.StimCtrlFieldComb);
        PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimFieldComb = ...
            ranksum(PyrDown1.meanCorrTNZ{cond}.NonStimFieldComb,...
                    PyrDown1.meanCorrTNZ{cond}.StimNonStimFieldComb);
                
        PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStimFieldComb = ...
            ranksum(PyrOther1.meanCorrTNZ{cond}.NonStimFieldComb,...
                    PyrOther1.meanCorrTNZ{cond}.StimFieldComb);
        PyrOther1.meanCorrTNZ{cond}.pRSStimVsStimCtrlFieldComb = ...
            ranksum(PyrOther1.meanCorrTNZ{cond}.StimFieldComb,...
                    PyrOther1.meanCorrTNZ{cond}.StimCtrlFieldComb);
        PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimFieldComb = ...
            ranksum(PyrOther1.meanCorrTNZ{cond}.NonStimFieldComb,...
                    PyrOther1.meanCorrTNZ{cond}.StimNonStimFieldComb);
    end
    
    save([pathAnal0 'initPeakPyrIntCorrTAllRecStimCtrlTr.mat'],'PyrStimT','PyrRise1','PyrDown1','PyrOther1'); 
   
    colorSel = 0;
    for cond = 1:length(PyrStim1.FRProfile1)
        if(PyrStimT.meanCorrTNZ{cond}.actOrInact == 1)
            actOrInActStr = 'inact';  
        else
            actOrInActStr = 'act';
        end
        pulseMethodStr = num2str(PyrStimT.meanCorrTNZ{cond}.pulseMethod);
        stimLocsStr = num2str(PyrStimT.meanCorrTNZ{cond}.stimLoc);
        
        %% pyramidal neurons
        % pyr rise good non-stim vs. stim
        indNotNan = ~isnan(PyrRise1.meanCorrTNZ{cond}.NonStim);
        barPlotWithStat3(1:2,...
            [mean(PyrRise1.meanCorrTNZ{cond}.NonStim(indNotNan)),...
            mean(PyrRise1.meanCorrTNZ{cond}.Stim(indNotNan))],...
            [std(PyrRise1.meanCorrTNZ{cond}.NonStim(indNotNan))/sqrt(length(PyrRise1.meanCorrTNZ{cond}.NonStim(indNotNan))),...
            std(PyrRise1.meanCorrTNZ{cond}.Stim(indNotNan))/sqrt(length(PyrRise1.meanCorrTNZ{cond}.Stim(indNotNan)))],...
            PyrRise1.meanCorrTNZ{cond}.NonStim(indNotNan),...
            PyrRise1.meanCorrTNZ{cond}.Stim(indNotNan),...
            ['Mean corrT NZ PR' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStim,...
            ['CorrTAlignedPyrRiseNoStimVsStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Nonstim'} {'Stim'}]);
        
        % pyr rise stim vs. stim ctrl
        barPlotWithStat3(1:2,...
            [mean(PyrRise1.meanCorrTNZ{cond}.Stim),...
            mean(PyrRise1.meanCorrTNZ{cond}.StimCtrl)],...
            [std(PyrRise1.meanCorrTNZ{cond}.Stim)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.Stim)),...
            std(PyrRise1.meanCorrTNZ{cond}.StimCtrl)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.StimCtrl))],...
            PyrRise1.meanCorrTNZ{cond}.Stim,...
            PyrRise1.meanCorrTNZ{cond}.StimCtrl,...
            ['Mean corrT NZ PR' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrRise1.meanCorrTNZ{cond}.pRSStimVsStimCtrl,...
            ['CorrTAlignedPyrRiseStimVsStimCtrl_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Stim'} {'StimCtrl'}]);
        
        % pyr rise non-stim vs. stim-NonStim
        barPlotWithStat3(1:2,...
            [mean(PyrRise1.meanCorrTNZ{cond}.NonStim),...
            mean(PyrRise1.meanCorrTNZ{cond}.StimNonStim)],...
            [std(PyrRise1.meanCorrTNZ{cond}.NonStim)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.NonStim)),...
            std(PyrRise1.meanCorrTNZ{cond}.StimNonStim)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.StimNonStim))],...
            PyrRise1.meanCorrTNZ{cond}.NonStim,...
            PyrRise1.meanCorrTNZ{cond}.StimNonStim,...
            ['Mean corrT NZ PR' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStim,...
            ['CorrTAlignedPyrRiseNoStimVsStimNoStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'NonStim'} {'StimNonStim'}]);
        
        % pyr down good non-stim vs. stim
        barPlotWithStat3(1:2,...
            [mean(PyrDown1.meanCorrTNZ{cond}.NonStim),...
            mean(PyrDown1.meanCorrTNZ{cond}.Stim)],...
            [std(PyrDown1.meanCorrTNZ{cond}.NonStim)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.NonStim)),...
            std(PyrDown1.meanCorrTNZ{cond}.Stim)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.Stim))],...
            PyrDown1.meanCorrTNZ{cond}.NonStim,...
            PyrDown1.meanCorrTNZ{cond}.Stim,...
            ['Mean corrT NZ PD' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStim,...
            ['CorrTAlignedPyrDownNoStimVsStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Nonstim'} {'Stim'}]);
        
        % pyr down stim vs. stim ctrl
        barPlotWithStat3(1:2,...
            [mean(PyrDown1.meanCorrTNZ{cond}.Stim),...
            mean(PyrDown1.meanCorrTNZ{cond}.StimCtrl)],...
            [std(PyrDown1.meanCorrTNZ{cond}.Stim)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.Stim)),...
            std(PyrDown1.meanCorrTNZ{cond}.StimCtrl)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.StimCtrl))],...
            PyrDown1.meanCorrTNZ{cond}.Stim,...
            PyrDown1.meanCorrTNZ{cond}.StimCtrl,...
            ['Mean corrT NZ PD' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrDown1.meanCorrTNZ{cond}.pRSStimVsStimCtrl,...
            ['CorrTAlignedPyrDownStimVsStimCtrl_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Stim'} {'StimCtrl'}]);
        
        % pyr down non-stim vs. stim-NonStim
        barPlotWithStat3(1:2,...
            [mean(PyrDown1.meanCorrTNZ{cond}.NonStim),...
            mean(PyrDown1.meanCorrTNZ{cond}.StimNonStim)],...
            [std(PyrDown1.meanCorrTNZ{cond}.NonStim)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.NonStim)),...
            std(PyrDown1.meanCorrTNZ{cond}.StimNonStim)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.StimNonStim))],...
            PyrDown1.meanCorrTNZ{cond}.NonStim,...
            PyrDown1.meanCorrTNZ{cond}.StimNonStim,...
            ['Mean corrT NZ PD' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStim,...
            ['CorrTAlignedPyrDownNoStimVsStimNoStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'NonStim'} {'StimNonStim'}]);
        
        % pyr other good non-stim vs. stim
        barPlotWithStat3(1:2,...
            [mean(PyrOther1.meanCorrTNZ{cond}.NonStim),...
            mean(PyrOther1.meanCorrTNZ{cond}.Stim)],...
            [std(PyrOther1.meanCorrTNZ{cond}.NonStim)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.NonStim)),...
            std(PyrOther1.meanCorrTNZ{cond}.Stim)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.Stim))],...
            PyrOther1.meanCorrTNZ{cond}.NonStim,...
            PyrOther1.meanCorrTNZ{cond}.Stim,...
            ['Mean corrT NZ PO' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStim,...
            ['CorrTAlignedPyrOtherNoStimVsStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Nonstim'} {'Stim'}]);
        
        % pyr other stim vs. stim ctrl
        barPlotWithStat3(1:2,...
            [mean(PyrOther1.meanCorrTNZ{cond}.Stim),...
            mean(PyrOther1.meanCorrTNZ{cond}.StimCtrl)],...
            [std(PyrOther1.meanCorrTNZ{cond}.Stim)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.Stim)),...
            std(PyrOther1.meanCorrTNZ{cond}.StimCtrl)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.StimCtrl))],...
            PyrOther1.meanCorrTNZ{cond}.Stim,...
            PyrOther1.meanCorrTNZ{cond}.StimCtrl,...
            ['Mean corrT NZ PO' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrOther1.meanCorrTNZ{cond}.pRSStimVsStimCtrl,...
            ['CorrTAlignedPyrOtherStimVsStimCtrl_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Stim'} {'StimCtrl'}]);
        
        % pyr other non-stim vs. stim-NonStim
        barPlotWithStat3(1:2,...
            [mean(PyrOther1.meanCorrTNZ{cond}.NonStim),...
            mean(PyrOther1.meanCorrTNZ{cond}.StimNonStim)],...
            [std(PyrOther1.meanCorrTNZ{cond}.NonStim)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.NonStim)),...
            std(PyrOther1.meanCorrTNZ{cond}.StimNonStim)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.StimNonStim))],...
            PyrOther1.meanCorrTNZ{cond}.NonStim,...
            PyrOther1.meanCorrTNZ{cond}.StimNonStim,...
            ['Mean corrT NZ PO' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStim,...
            ['CorrTAlignedPyrOtherNoStimVsStimNoStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'NonStim'} {'StimNonStim'}]);
                
        %% pyramidal neurons with field
        % pyr rise good non-stim vs. stim
        barPlotWithStat3(1:2,...
            [mean(PyrRise1.meanCorrTNZ{cond}.NonStimField),...
            mean(PyrRise1.meanCorrTNZ{cond}.StimField)],...
            [std(PyrRise1.meanCorrTNZ{cond}.NonStimField)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.NonStimField)),...
            std(PyrRise1.meanCorrTNZ{cond}.StimField)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.StimField))],...
            PyrRise1.meanCorrTNZ{cond}.NonStimField,...
            PyrRise1.meanCorrTNZ{cond}.StimField,...
            ['Mean corrT NZ PRF' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStimField,...
            ['CorrTAlignedPyrRiseFieldNoStimVsStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Nonstim'} {'Stim'}],[0 0.8]);
        
        % pyr rise stim vs. stim ctrl
        barPlotWithStat3(1:2,...
            [mean(PyrRise1.meanCorrTNZ{cond}.StimField),...
            mean(PyrRise1.meanCorrTNZ{cond}.StimCtrlField)],...
            [std(PyrRise1.meanCorrTNZ{cond}.StimField)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.StimField)),...
            std(PyrRise1.meanCorrTNZ{cond}.StimCtrlField)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.StimCtrlField))],...
            PyrRise1.meanCorrTNZ{cond}.StimField,...
            PyrRise1.meanCorrTNZ{cond}.StimCtrlField,...
            ['Mean corrT NZ PRF' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrRise1.meanCorrTNZ{cond}.pRSStimVsStimCtrlField,...
            ['CorrTAlignedPyrRiseFieldStimVsStimCtrl_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Stim'} {'StimCtrl'}],[0 0.8]);
        
        % pyr rise non-stim vs. stim-NonStim
        barPlotWithStat3(1:2,...
            [mean(PyrRise1.meanCorrTNZ{cond}.NonStimField),...
            mean(PyrRise1.meanCorrTNZ{cond}.StimNonStimField)],...
            [std(PyrRise1.meanCorrTNZ{cond}.NonStimField)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.NonStimField)),...
            std(PyrRise1.meanCorrTNZ{cond}.StimNonStimField)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.StimNonStimField))],...
            PyrRise1.meanCorrTNZ{cond}.NonStimField,...
            PyrRise1.meanCorrTNZ{cond}.StimNonStimField,...
            ['Mean corrT NZ PRF' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimField,...
            ['CorrTAlignedPyrRiseFieldNoStimVsStimNoStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'NonStim'} {'StimNonStim'}],[0 0.8]);
                
        % pyr down good non-stim vs. stim
        barPlotWithStat3(1:2,...
            [mean(PyrDown1.meanCorrTNZ{cond}.NonStimField),...
            mean(PyrDown1.meanCorrTNZ{cond}.StimField)],...
            [std(PyrDown1.meanCorrTNZ{cond}.NonStimField)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.NonStimField)),...
            std(PyrDown1.meanCorrTNZ{cond}.StimField)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.StimField))],...
            PyrDown1.meanCorrTNZ{cond}.NonStimField,...
            PyrDown1.meanCorrTNZ{cond}.StimField,...
            ['Mean corrT NZ PDF' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStimField,...
            ['CorrTAlignedPyrDownFieldNoStimVsStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Nonstim'} {'Stim'}],[0 0.8]);
        
        % pyr down stim vs. stim ctrl
        barPlotWithStat3(1:2,...
            [mean(PyrDown1.meanCorrTNZ{cond}.StimField),...
            mean(PyrDown1.meanCorrTNZ{cond}.StimCtrlField)],...
            [std(PyrDown1.meanCorrTNZ{cond}.StimField)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.StimField)),...
            std(PyrDown1.meanCorrTNZ{cond}.StimCtrlField)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.StimCtrlField))],...
            PyrDown1.meanCorrTNZ{cond}.StimField,...
            PyrDown1.meanCorrTNZ{cond}.StimCtrlField,...
            ['Mean corrT NZ PDF' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrDown1.meanCorrTNZ{cond}.pRSStimVsStimCtrlField,...
            ['CorrTAlignedPyrDownFieldStimVsStimCtrl_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Stim'} {'StimCtrl'}],[0 0.8]);
        
        % pyr down non-stim vs. stim-NonStim
        barPlotWithStat3(1:2,...
            [mean(PyrDown1.meanCorrTNZ{cond}.NonStimField),...
            mean(PyrDown1.meanCorrTNZ{cond}.StimNonStimField)],...
            [std(PyrDown1.meanCorrTNZ{cond}.NonStimField)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.NonStimField)),...
            std(PyrDown1.meanCorrTNZ{cond}.StimNonStimField)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.StimNonStimField))],...
            PyrDown1.meanCorrTNZ{cond}.NonStimField,...
            PyrDown1.meanCorrTNZ{cond}.StimNonStimField,...
            ['Mean corrT NZ PDF' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimField,...
            ['CorrTAlignedPyrDownFieldNoStimVsStimNoStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'NonStim'} {'StimNonStim'}],[0 0.8]);
        
        % pyr other good non-stim vs. stim
        barPlotWithStat3(1:2,...
            [mean(PyrOther1.meanCorrTNZ{cond}.NonStimField),...
            mean(PyrOther1.meanCorrTNZ{cond}.StimField)],...
            [std(PyrOther1.meanCorrTNZ{cond}.NonStimField)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.NonStimField)),...
            std(PyrOther1.meanCorrTNZ{cond}.StimField)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.StimField))],...
            PyrOther1.meanCorrTNZ{cond}.NonStimField,...
            PyrOther1.meanCorrTNZ{cond}.StimField,...
            ['Mean corrT NZ POF' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStimField,...
            ['CorrTAlignedPyrOtherFieldNoStimVsStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Nonstim'} {'Stim'}],[0 0.8]);
        
        % pyr other stim vs. stim ctrl
        barPlotWithStat3(1:2,...
            [mean(PyrOther1.meanCorrTNZ{cond}.StimField),...
            mean(PyrOther1.meanCorrTNZ{cond}.StimCtrlField)],...
            [std(PyrOther1.meanCorrTNZ{cond}.StimField)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.StimField)),...
            std(PyrOther1.meanCorrTNZ{cond}.StimCtrlField)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.StimCtrlField))],...
            PyrOther1.meanCorrTNZ{cond}.StimField,...
            PyrOther1.meanCorrTNZ{cond}.StimCtrlField,...
            ['Mean corrT NZ POF' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrOther1.meanCorrTNZ{cond}.pRSStimVsStimCtrlField,...
            ['CorrTAlignedPyrOtherFieldStimVsStimCtrl_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Stim'} {'StimCtrl'}],[0 0.8]);
        
        % pyr other non-stim vs. stim-NonStim
        barPlotWithStat3(1:2,...
            [mean(PyrOther1.meanCorrTNZ{cond}.NonStimField),...
            mean(PyrOther1.meanCorrTNZ{cond}.StimNonStimField)],...
            [std(PyrOther1.meanCorrTNZ{cond}.NonStimField)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.NonStimField)),...
            std(PyrOther1.meanCorrTNZ{cond}.StimNonStimField)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.StimNonStimField))],...
            PyrOther1.meanCorrTNZ{cond}.NonStimField,...
            PyrOther1.meanCorrTNZ{cond}.StimNonStimField,...
            ['Mean corrT NZ POF' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimField,...
            ['CorrTAlignedPyrOtherFieldNoStimVsStimNoStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'NonStim'} {'StimNonStim'}],[0 0.8]);
                
        %% pyramidal neurons with field combo
        % pyr rise good non-stim vs. stim
        barPlotWithStat3(1:2,...
            [mean(PyrRise1.meanCorrTNZ{cond}.NonStimFieldComb),...
            mean(PyrRise1.meanCorrTNZ{cond}.StimFieldComb)],...
            [std(PyrRise1.meanCorrTNZ{cond}.NonStimFieldComb)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.NonStimFieldComb)),...
            std(PyrRise1.meanCorrTNZ{cond}.StimFieldComb)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.StimFieldComb))],...
            PyrRise1.meanCorrTNZ{cond}.NonStimFieldComb,...
            PyrRise1.meanCorrTNZ{cond}.StimFieldComb,...
            ['Mean corrT NZ PRFC' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStimFieldComb,...
            ['CorrTAlignedPyrRiseFieldCombNoStimVsStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Nonstim'} {'Stim'}],[0 0.8]);
        
        % pyr rise stim vs. stim ctrl
        barPlotWithStat3(1:2,...
            [mean(PyrRise1.meanCorrTNZ{cond}.StimFieldComb),...
            mean(PyrRise1.meanCorrTNZ{cond}.StimCtrlFieldComb)],...
            [std(PyrRise1.meanCorrTNZ{cond}.StimFieldComb)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.StimFieldComb)),...
            std(PyrRise1.meanCorrTNZ{cond}.StimCtrlFieldComb)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.StimCtrlFieldComb))],...
            PyrRise1.meanCorrTNZ{cond}.StimFieldComb,...
            PyrRise1.meanCorrTNZ{cond}.StimCtrlFieldComb,...
            ['Mean corrT NZ PRFC' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrRise1.meanCorrTNZ{cond}.pRSStimVsStimCtrlFieldComb,...
            ['CorrTAlignedPyrRiseFieldCombStimVsStimCtrl_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Stim'} {'StimCtrl'}],[0 0.8]);
        
        % pyr rise non-stim vs. stim-NonStim
        barPlotWithStat3(1:2,...
            [mean(PyrRise1.meanCorrTNZ{cond}.NonStimFieldComb),...
            mean(PyrRise1.meanCorrTNZ{cond}.StimNonStimFieldComb)],...
            [std(PyrRise1.meanCorrTNZ{cond}.NonStimFieldComb)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.NonStimFieldComb)),...
            std(PyrRise1.meanCorrTNZ{cond}.StimNonStimFieldComb)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.StimNonStimFieldComb))],...
            PyrRise1.meanCorrTNZ{cond}.NonStimFieldComb,...
            PyrRise1.meanCorrTNZ{cond}.StimNonStimFieldComb,...
            ['Mean corrT NZ PRFC' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimFieldComb,...
            ['CorrTAlignedPyrRiseFieldCombNoStimVsStimNoStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'NonStim'} {'StimNonStim'}],[0 0.8]);
                
        
        % pyr down good non-stim vs. stim
        barPlotWithStat3(1:2,...
            [mean(PyrDown1.meanCorrTNZ{cond}.NonStimFieldComb),...
            mean(PyrDown1.meanCorrTNZ{cond}.StimFieldComb)],...
            [std(PyrDown1.meanCorrTNZ{cond}.NonStimFieldComb)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.NonStimFieldComb)),...
            std(PyrDown1.meanCorrTNZ{cond}.StimFieldComb)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.StimFieldComb))],...
            PyrDown1.meanCorrTNZ{cond}.NonStimFieldComb,...
            PyrDown1.meanCorrTNZ{cond}.StimFieldComb,...
            ['Mean corrT NZ PDFC' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStimFieldComb,...
            ['CorrTAlignedPyrDownFieldCombNoStimVsStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Nonstim'} {'Stim'}],[0 0.8]);
        
        % pyr down stim vs. stim ctrl
        barPlotWithStat3(1:2,...
            [mean(PyrDown1.meanCorrTNZ{cond}.StimFieldComb),...
            mean(PyrDown1.meanCorrTNZ{cond}.StimCtrlFieldComb)],...
            [std(PyrDown1.meanCorrTNZ{cond}.StimFieldComb)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.StimFieldComb)),...
            std(PyrDown1.meanCorrTNZ{cond}.StimCtrlFieldComb)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.StimCtrlFieldComb))],...
            PyrDown1.meanCorrTNZ{cond}.StimFieldComb,...
            PyrDown1.meanCorrTNZ{cond}.StimCtrlFieldComb,...
            ['Mean corrT NZ PDFC' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrDown1.meanCorrTNZ{cond}.pRSStimVsStimCtrlFieldComb,...
            ['CorrTAlignedPyrDownFieldCombStimVsStimCtrl_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Stim'} {'StimCtrl'}],[0 0.8]);
        
        % pyr down non-stim vs. stim-NonStim
        barPlotWithStat3(1:2,...
            [mean(PyrDown1.meanCorrTNZ{cond}.NonStimFieldComb),...
            mean(PyrDown1.meanCorrTNZ{cond}.StimNonStimFieldComb)],...
            [std(PyrDown1.meanCorrTNZ{cond}.NonStimFieldComb)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.NonStimFieldComb)),...
            std(PyrDown1.meanCorrTNZ{cond}.StimNonStimFieldComb)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.StimNonStimFieldComb))],...
            PyrDown1.meanCorrTNZ{cond}.NonStimFieldComb,...
            PyrDown1.meanCorrTNZ{cond}.StimNonStimFieldComb,...
            ['Mean corrT NZ PDFC' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimFieldComb,...
            ['CorrTAlignedPyrDownFieldCombNoStimVsStimNoStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'NonStim'} {'StimNonStim'}],[0 0.8]);
                        
        % pyr other good non-stim vs. stim
        barPlotWithStat3(1:2,...
            [mean(PyrOther1.meanCorrTNZ{cond}.NonStimFieldComb),...
            mean(PyrOther1.meanCorrTNZ{cond}.StimFieldComb)],...
            [std(PyrOther1.meanCorrTNZ{cond}.NonStimFieldComb)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.NonStimFieldComb)),...
            std(PyrOther1.meanCorrTNZ{cond}.StimFieldComb)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.StimFieldComb))],...
            PyrOther1.meanCorrTNZ{cond}.NonStimFieldComb,...
            PyrOther1.meanCorrTNZ{cond}.StimFieldComb,...
            ['Mean corrT NZ POFC' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStimFieldComb,...
            ['CorrTAlignedPyrOtherFieldCombNoStimVsStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Nonstim'} {'Stim'}],[0 0.8]);
        
        % pyr other stim vs. stim ctrl
        barPlotWithStat3(1:2,...
            [mean(PyrOther1.meanCorrTNZ{cond}.StimFieldComb),...
            mean(PyrOther1.meanCorrTNZ{cond}.StimCtrlFieldComb)],...
            [std(PyrOther1.meanCorrTNZ{cond}.StimFieldComb)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.StimFieldComb)),...
            std(PyrOther1.meanCorrTNZ{cond}.StimCtrlFieldComb)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.StimCtrlFieldComb))],...
            PyrOther1.meanCorrTNZ{cond}.StimFieldComb,...
            PyrOther1.meanCorrTNZ{cond}.StimCtrlFieldComb,...
            ['Mean corrT NZ POFC' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrOther1.meanCorrTNZ{cond}.pRSStimVsStimCtrlFieldComb,...
            ['CorrTAlignedPyrOtherFieldCombStimVsStimCtrl_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Stim'} {'StimCtrl'}],[0 0.8]);
        
        % pyr other non-stim vs. stim-NonStim
        barPlotWithStat3(1:2,...
            [mean(PyrOther1.meanCorrTNZ{cond}.NonStimFieldComb),...
            mean(PyrOther1.meanCorrTNZ{cond}.StimNonStimFieldComb)],...
            [std(PyrOther1.meanCorrTNZ{cond}.NonStimFieldComb)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.NonStimFieldComb)),...
            std(PyrOther1.meanCorrTNZ{cond}.StimNonStimFieldComb)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.StimNonStimFieldComb))],...
            PyrOther1.meanCorrTNZ{cond}.NonStimFieldComb,...
            PyrOther1.meanCorrTNZ{cond}.StimNonStimFieldComb,...
            ['Mean corrT NZ POFC' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimFieldComb,...
            ['CorrTAlignedPyrOtherFieldCombNoStimVsStimNoStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'NonStim'} {'StimNonStim'}],[0 0.8]);
                
    end
end