function PyrIntInitPeakCorrTPVSigNonStim2ndStimCtrl1(methodKMean)
%% activity correlation of PyrRise and PyrDown neurons before and during stimulation

    pathAnal0 = ['Z:\Yingxue\Draft\PV\PyramidalStimALNonStim2ndStimCtrlSig1\'];
    pathAnal = ['Z:\Yingxue\Draft\PV\PyramidalStimALNonStim2ndStimCtrlSig1\' num2str(methodKMean) '\'];
    
    if(exist([pathAnal 'initPeakPyrAllRecSigStimNoStim2ndStimCtrl.mat']))
        load([pathAnal 'initPeakPyrAllRecSigStimNoStim2ndStimCtrl.mat']);
    end
    
    if(exist([pathAnal0 'initPeakPyrIntAllRecStimSigNoStim2ndStimCtrl.mat']))
        load([pathAnal0 'initPeakPyrIntAllRecStimSigNoStim2ndStimCtrl.mat']);
    end
        
    if(exist([pathAnal0 'initPeakPyrIntCorrTAllRecStimSigNoStim2ndStimCtrlTr.mat']))
        load([pathAnal0 'initPeakPyrIntCorrTAllRecStimSigNoStim2ndStimCtrlTr.mat']);
    end
    
    ind = 1:length(modPyr1AL.actOrInact);

    PyrStimT.indNeuSel = ind;
    PyrStimT.actOrInact = modPyr1AL.actOrInact(ind); % is it activation or inactivation
    PyrStimT.indRec = modPyr1AL.indRec(ind); % recording index
    PyrStimT.indNeu = modPyr1AL.indNeu(ind); % neuron indices trials
    PyrStimT.pulseMeth = modPyr1AL.pulseMeth(ind); % pulse method
    PyrStimT.stimLoc = modPyr1AL.stimLoc(ind); % stimulation location on the track
    PyrStimT.meanNZNonStim = modPyr1AL.meanNZNonStim(ind);
    PyrStimT.meanNZStim = modPyr1AL.meanNZStim(ind);
    PyrStimT.meanNZStimCtrl = modPyr1AL.meanNZStimCtrl(ind);
    PyrStimT.meanNZStimNonStim = modPyr1AL.meanNZStimNonStim(ind);
    
    PyrRise1.meanNZNonStim = PyrStimT.meanNZNonStim(PyrRise.idxRise);
    PyrRise1.meanNZStim = PyrStimT.meanNZStim(PyrRise.idxRise);
    PyrRise1.meanNZStimCtrl = PyrStimT.meanNZStimCtrl(PyrRise.idxRise);
    PyrRise1.meanNZStimNonStim = PyrStimT.meanNZStimNonStim(PyrRise.idxRise);
    
    PyrDown1.meanNZNonStim = PyrStimT.meanNZNonStim(PyrDown.idxDown);
    PyrDown1.meanNZStim = PyrStimT.meanNZStim(PyrDown.idxDown);
    PyrDown1.meanNZStimCtrl = PyrStimT.meanNZStimCtrl(PyrDown.idxDown);
    PyrDown1.meanNZStimNonStim = PyrStimT.meanNZStimNonStim(PyrDown.idxDown);
    
    PyrOther1.meanNZNonStim = PyrStimT.meanNZNonStim(PyrOther.idxOther);
    PyrOther1.meanNZStim = PyrStimT.meanNZStim(PyrOther.idxOther);
    PyrOther1.meanNZStimCtrl = PyrStimT.meanNZStimCtrl(PyrOther.idxOther);
    PyrOther1.meanNZStimNonStim = PyrStimT.meanNZStimNonStim(PyrOther.idxOther);
    
    for cond = 1:length(PyrStim1.FRProfile1)
        PyrStimT.meanCorrTNZ{cond}.actOrInact = PyrStim1.FRProfile1{cond}.actOrInact;
        PyrStimT.meanCorrTNZ{cond}.pulseMethod = PyrStim1.FRProfile1{cond}.pulseMethod;
        PyrStimT.meanCorrTNZ{cond}.stimLoc = PyrStim1.FRProfile1{cond}.stimLoc;
        
        PyrStimT.meanCorrTNZ{cond}.indPyrRise = PyrStim1.FRProfile1{cond}.indPyrRise;
        PyrStimT.meanCorrTNZ{cond}.indRecPyrRise = PyrStim1.FRProfile1{cond}.indRecPyrRise;
        PyrStimT.meanCorrTNZ{cond}.indNeuPyrRise = PyrStim1.FRProfile1{cond}.indNeuPyrRise;
        
        PyrStimT.meanCorrTNZ{cond}.indPyrDown = PyrStim1.FRProfile1{cond}.indPyrDown;
        PyrStimT.meanCorrTNZ{cond}.indRecPyrDown = PyrStim1.FRProfile1{cond}.indRecPyrDown;
        PyrStimT.meanCorrTNZ{cond}.indNeuPyrDown = PyrStim1.FRProfile1{cond}.indNeuPyrDown;
        
        PyrStimT.meanCorrTNZ{cond}.indPyrOther = PyrStim1.FRProfile1{cond}.indPyrOther;
        PyrStimT.meanCorrTNZ{cond}.indRecPyrOther = PyrStim1.FRProfile1{cond}.indRecPyrOther;
        PyrStimT.meanCorrTNZ{cond}.indNeuPyrOther = PyrStim1.FRProfile1{cond}.indNeuPyrOther;
        
        
        %% pyramidal neurons all, added on 9/15/2022
        indAll = PyrStim1.FRProfile1{cond}.ind;
        PyrStimT.meanCorrTNZ{cond}.indPyrAll = PyrStim1.FRProfile1{cond}.ind;
        PyrStimT.meanCorrTNZ{cond}.NonStim = ...
            PyrStimT.meanNZNonStim(indAll);
        PyrStimT.meanCorrTNZ{cond}.Stim = ...
            PyrStimT.meanNZStim(indAll);
        PyrStimT.meanCorrTNZ{cond}.StimCtrl = ...
            PyrStimT.meanNZStimCtrl(indAll);
        PyrStimT.meanCorrTNZ{cond}.StimNonStim = ...
            PyrStimT.meanNZStimNonStim(indAll);
                
        %% pyramidal neurons
        PyrRise1.meanCorrTNZ{cond}.NonStim = ...
            PyrStimT.meanNZNonStim(PyrStimT.meanCorrTNZ{cond}.indPyrRise);
        PyrRise1.meanCorrTNZ{cond}.Stim = ...
            PyrStimT.meanNZStim(PyrStimT.meanCorrTNZ{cond}.indPyrRise);
        PyrRise1.meanCorrTNZ{cond}.StimCtrl = ...
            PyrStimT.meanNZStimCtrl(PyrStimT.meanCorrTNZ{cond}.indPyrRise);
        PyrRise1.meanCorrTNZ{cond}.StimNonStim = ...
            PyrStimT.meanNZStimNonStim(PyrStimT.meanCorrTNZ{cond}.indPyrRise);
        
        PyrDown1.meanCorrTNZ{cond}.NonStim = ...
            PyrStimT.meanNZNonStim(PyrStimT.meanCorrTNZ{cond}.indPyrDown);
        PyrDown1.meanCorrTNZ{cond}.Stim = ...
            PyrStimT.meanNZStim(PyrStimT.meanCorrTNZ{cond}.indPyrDown);
        PyrDown1.meanCorrTNZ{cond}.StimCtrl = ...
            PyrStimT.meanNZStimCtrl(PyrStimT.meanCorrTNZ{cond}.indPyrDown);
        PyrDown1.meanCorrTNZ{cond}.StimNonStim = ...
            PyrStimT.meanNZStimNonStim(PyrStimT.meanCorrTNZ{cond}.indPyrDown);
        
        PyrOther1.meanCorrTNZ{cond}.NonStim = ...
            PyrStimT.meanNZNonStim(PyrStimT.meanCorrTNZ{cond}.indPyrOther);
        PyrOther1.meanCorrTNZ{cond}.Stim = ...
            PyrStimT.meanNZStim(PyrStimT.meanCorrTNZ{cond}.indPyrOther);
        PyrOther1.meanCorrTNZ{cond}.StimCtrl = ...
            PyrStimT.meanNZStimCtrl(PyrStimT.meanCorrTNZ{cond}.indPyrOther);
        PyrOther1.meanCorrTNZ{cond}.StimNonStim = ...
            PyrStimT.meanNZStimNonStim(PyrStimT.meanCorrTNZ{cond}.indPyrOther);
        
        %% compare pyramidal neurons
        %% added on 9/15/2022
        if(~isempty(PyrStimT.meanCorrTNZ{cond}.Stim))
            PyrStimT.meanCorrTNZ{cond}.pRSNonStimVsStim = ...
                ranksum(PyrStimT.meanCorrTNZ{cond}.NonStim,...
                        PyrStimT.meanCorrTNZ{cond}.Stim);
            PyrStimT.meanCorrTNZ{cond}.pRSStimVsStimCtrl = ...
                ranksum(PyrStimT.meanCorrTNZ{cond}.Stim,...
                        PyrStimT.meanCorrTNZ{cond}.StimCtrl);
            PyrStimT.meanCorrTNZ{cond}.pRSNonStimVsStimNonStim = ...
                ranksum(PyrStimT.meanCorrTNZ{cond}.NonStim,...
                        PyrStimT.meanCorrTNZ{cond}.StimNonStim);
            %%
            PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStim = ...
                ranksum(PyrRise1.meanCorrTNZ{cond}.NonStim,...
                        PyrRise1.meanCorrTNZ{cond}.Stim);
            PyrRise1.meanCorrTNZ{cond}.pRSStimVsStimCtrl = ...
                ranksum(PyrRise1.meanCorrTNZ{cond}.Stim,...
                        PyrRise1.meanCorrTNZ{cond}.StimCtrl);
            PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStim = ...
                ranksum(PyrRise1.meanCorrTNZ{cond}.NonStim,...
                        PyrRise1.meanCorrTNZ{cond}.StimNonStim);
            
            PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStim = ...
                ranksum(PyrDown1.meanCorrTNZ{cond}.NonStim,...
                        PyrDown1.meanCorrTNZ{cond}.Stim);
            PyrDown1.meanCorrTNZ{cond}.pRSStimVsStimCtrl = ...
                ranksum(PyrDown1.meanCorrTNZ{cond}.Stim,...
                        PyrDown1.meanCorrTNZ{cond}.StimCtrl);
            PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStim = ...
                ranksum(PyrDown1.meanCorrTNZ{cond}.NonStim,...
                        PyrDown1.meanCorrTNZ{cond}.StimNonStim);
                    
            PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStim = ...
                ranksum(PyrOther1.meanCorrTNZ{cond}.NonStim,...
                        PyrOther1.meanCorrTNZ{cond}.Stim);
            PyrOther1.meanCorrTNZ{cond}.pRSStimVsStimCtrl = ...
                ranksum(PyrOther1.meanCorrTNZ{cond}.Stim,...
                        PyrOther1.meanCorrTNZ{cond}.StimCtrl);
            PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStim = ...
                ranksum(PyrOther1.meanCorrTNZ{cond}.NonStim,...
                        PyrOther1.meanCorrTNZ{cond}.StimNonStim);
        else
            PyrStimT.meanCorrTNZ{cond}.pRSNonStimVsStim = 1;
            PyrStimT.meanCorrTNZ{cond}.pRSStimVsStimCtrl = 1;
            PyrStimT.meanCorrTNZ{cond}.pRSNonStimVsStimNonStim = 1;

            PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStim = 1;
            PyrRise1.meanCorrTNZ{cond}.pRSStimVsStimCtrl = 1;
            PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStim = 1;

            PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStim = 1;
            PyrDown1.meanCorrTNZ{cond}.pRSStimVsStimCtrl = 1;
            PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStim = 1;

            PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStim = 1;
            PyrOther1.meanCorrTNZ{cond}.pRSStimVsStimCtrl = 1;
            PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStim = 1;
        end
                
        %% pyramidal neurons with fields
        %% pyramidal neurons all, added on 9/15/2022; added field location on 8/6/2023
        PyrStimT.meanCorrTNZ{cond}.isField = PyrStim1.FRProfile1{cond}.isField;
        PyrStimT.meanCorrTNZ{cond}.isFieldComb = PyrStim1.FRProfile1{cond}.isFieldComb;
               
        %% added field location on 8/6/2023
        PyrRise1.meanCorrTNZ{cond}.isField = PyrRise.isNeuWithFieldAligned{cond}.isField;
        PyrRise1.meanCorrTNZ{cond}.isFieldComb = PyrRise.isNeuWithFieldAligned{cond}.isFieldComb;
                
        PyrDown1.meanCorrTNZ{cond}.isField = PyrDown.isNeuWithFieldAligned{cond}.isField;
        PyrDown1.meanCorrTNZ{cond}.isFieldComb = PyrDown.isNeuWithFieldAligned{cond}.isFieldComb;
               
        PyrOther1.meanCorrTNZ{cond}.isField = PyrOther.isNeuWithFieldAligned{cond}.isField;
        PyrOther1.meanCorrTNZ{cond}.isFieldComb = PyrOther.isNeuWithFieldAligned{cond}.isFieldComb;
                
        % field
        %% pyramidal neurons all, added on 9/15/2022
        PyrStimT.meanCorrTNZ{cond}.NonStimField = ...
            PyrStimT.meanCorrTNZ{cond}.NonStim(PyrStimT.meanCorrTNZ{cond}.isField == 1);
        PyrStimT.meanCorrTNZ{cond}.StimField = ...
            PyrStimT.meanCorrTNZ{cond}.Stim(PyrStimT.meanCorrTNZ{cond}.isField == 1);
        PyrStimT.meanCorrTNZ{cond}.StimCtrlField = ...
            PyrStimT.meanCorrTNZ{cond}.StimCtrl(PyrStimT.meanCorrTNZ{cond}.isField == 1);
        PyrStimT.meanCorrTNZ{cond}.StimNonStimField = ...
            PyrStimT.meanCorrTNZ{cond}.StimNonStim(PyrStimT.meanCorrTNZ{cond}.isField == 1);
        %%
        PyrRise1.meanCorrTNZ{cond}.NonStimField = ...
            PyrRise1.meanCorrTNZ{cond}.NonStim(PyrRise1.meanCorrTNZ{cond}.isField == 1);
        PyrRise1.meanCorrTNZ{cond}.StimField = ...
            PyrRise1.meanCorrTNZ{cond}.Stim(PyrRise1.meanCorrTNZ{cond}.isField == 1);
        PyrRise1.meanCorrTNZ{cond}.StimCtrlField = ...
            PyrRise1.meanCorrTNZ{cond}.StimCtrl(PyrRise1.meanCorrTNZ{cond}.isField == 1);
        PyrRise1.meanCorrTNZ{cond}.StimNonStimField = ...
            PyrRise1.meanCorrTNZ{cond}.StimNonStim(PyrRise1.meanCorrTNZ{cond}.isField == 1);
        
        PyrDown1.meanCorrTNZ{cond}.NonStimField = ...
            PyrDown1.meanCorrTNZ{cond}.NonStim(PyrDown1.meanCorrTNZ{cond}.isField == 1);
        PyrDown1.meanCorrTNZ{cond}.StimField = ...
            PyrDown1.meanCorrTNZ{cond}.Stim(PyrDown1.meanCorrTNZ{cond}.isField == 1);
        PyrDown1.meanCorrTNZ{cond}.StimCtrlField = ...
            PyrDown1.meanCorrTNZ{cond}.StimCtrl(PyrDown1.meanCorrTNZ{cond}.isField == 1);
        PyrDown1.meanCorrTNZ{cond}.StimNonStimField = ...
            PyrDown1.meanCorrTNZ{cond}.StimNonStim(PyrDown1.meanCorrTNZ{cond}.isField == 1);
        
        PyrOther1.meanCorrTNZ{cond}.NonStimField = ...
            PyrOther1.meanCorrTNZ{cond}.NonStim(PyrOther1.meanCorrTNZ{cond}.isField == 1);
        PyrOther1.meanCorrTNZ{cond}.StimField = ...
            PyrOther1.meanCorrTNZ{cond}.Stim(PyrOther1.meanCorrTNZ{cond}.isField == 1);
        PyrOther1.meanCorrTNZ{cond}.StimCtrlField = ...
            PyrOther1.meanCorrTNZ{cond}.StimCtrl(PyrOther1.meanCorrTNZ{cond}.isField == 1);
        PyrOther1.meanCorrTNZ{cond}.StimNonStimField = ...
            PyrOther1.meanCorrTNZ{cond}.StimNonStim(PyrOther1.meanCorrTNZ{cond}.isField == 1);
        
        % field combo
        %% pyramidal neurons all, added on 9/15/2022
        PyrStimT.meanCorrTNZ{cond}.NonStimFieldComb = ...
            PyrStimT.meanCorrTNZ{cond}.NonStim(PyrStimT.meanCorrTNZ{cond}.isFieldComb == 1);
        PyrStimT.meanCorrTNZ{cond}.StimFieldComb = ...
            PyrStimT.meanCorrTNZ{cond}.Stim(PyrStimT.meanCorrTNZ{cond}.isFieldComb == 1);
        PyrStimT.meanCorrTNZ{cond}.StimCtrlFieldComb = ...
            PyrStimT.meanCorrTNZ{cond}.StimCtrl(PyrStimT.meanCorrTNZ{cond}.isFieldComb == 1);
        PyrStimT.meanCorrTNZ{cond}.StimNonStimFieldComb = ...
            PyrStimT.meanCorrTNZ{cond}.StimNonStim(PyrStimT.meanCorrTNZ{cond}.isFieldComb == 1);
        %%
        PyrRise1.meanCorrTNZ{cond}.NonStimFieldComb = ...
            PyrRise1.meanCorrTNZ{cond}.NonStim(PyrRise1.meanCorrTNZ{cond}.isFieldComb == 1);
        PyrRise1.meanCorrTNZ{cond}.StimFieldComb = ...
            PyrRise1.meanCorrTNZ{cond}.Stim(PyrRise1.meanCorrTNZ{cond}.isFieldComb == 1);
        PyrRise1.meanCorrTNZ{cond}.StimCtrlFieldComb = ...
            PyrRise1.meanCorrTNZ{cond}.StimCtrl(PyrRise1.meanCorrTNZ{cond}.isFieldComb == 1);
        PyrRise1.meanCorrTNZ{cond}.StimNonStimFieldComb = ...
            PyrRise1.meanCorrTNZ{cond}.StimNonStim(PyrRise1.meanCorrTNZ{cond}.isFieldComb == 1);
        
        PyrDown1.meanCorrTNZ{cond}.NonStimFieldComb = ...
            PyrDown1.meanCorrTNZ{cond}.NonStim(PyrDown1.meanCorrTNZ{cond}.isFieldComb == 1);
        PyrDown1.meanCorrTNZ{cond}.StimFieldComb = ...
            PyrDown1.meanCorrTNZ{cond}.Stim(PyrDown1.meanCorrTNZ{cond}.isFieldComb == 1);
        PyrDown1.meanCorrTNZ{cond}.StimCtrlFieldComb = ...
            PyrDown1.meanCorrTNZ{cond}.StimCtrl(PyrDown1.meanCorrTNZ{cond}.isFieldComb == 1);
        PyrDown1.meanCorrTNZ{cond}.StimNonStimFieldComb = ...
            PyrDown1.meanCorrTNZ{cond}.StimNonStim(PyrDown1.meanCorrTNZ{cond}.isFieldComb == 1);
        
        PyrOther1.meanCorrTNZ{cond}.NonStimFieldComb = ...
            PyrOther1.meanCorrTNZ{cond}.NonStim(PyrOther1.meanCorrTNZ{cond}.isFieldComb == 1);
        PyrOther1.meanCorrTNZ{cond}.StimFieldComb = ...
            PyrOther1.meanCorrTNZ{cond}.Stim(PyrOther1.meanCorrTNZ{cond}.isFieldComb == 1);
        PyrOther1.meanCorrTNZ{cond}.StimCtrlFieldComb = ...
            PyrOther1.meanCorrTNZ{cond}.StimCtrl(PyrOther1.meanCorrTNZ{cond}.isFieldComb == 1);
        PyrOther1.meanCorrTNZ{cond}.StimNonStimFieldComb = ...
            PyrOther1.meanCorrTNZ{cond}.StimNonStim(PyrOther1.meanCorrTNZ{cond}.isFieldComb == 1);
        
        %% compare pyramidal neurons with fields
        % field
        %% pyramidal neurons all, added on 9/15/2022
        if(isempty(PyrStimT.meanCorrTNZ{cond}.NonStimField) || ...
                isempty(PyrStimT.meanCorrTNZ{cond}.StimField) || ...
                isempty(PyrStimT.meanCorrTNZ{cond}.StimCtrlField))
            PyrStimT.meanCorrTNZ{cond}.pRSNonStimVsStimField = 1;
            PyrStimT.meanCorrTNZ{cond}.pRSStimVsStimCtrlField = 1;
            PyrStimT.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimField = 1;
        else
            PyrStimT.meanCorrTNZ{cond}.pRSNonStimVsStimField = ...
                ranksum(PyrStimT.meanCorrTNZ{cond}.NonStimField,...
                        PyrStimT.meanCorrTNZ{cond}.StimField);
            PyrStimT.meanCorrTNZ{cond}.pRSStimVsStimCtrlField = ...
                ranksum(PyrStimT.meanCorrTNZ{cond}.StimField,...
                        PyrStimT.meanCorrTNZ{cond}.StimCtrlField);
            PyrStimT.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimField = ...
                ranksum(PyrStimT.meanCorrTNZ{cond}.NonStimField,...
                        PyrStimT.meanCorrTNZ{cond}.StimNonStimField);
        end
        %%
        if(isempty(PyrRise1.meanCorrTNZ{cond}.NonStimField) || ...
                isempty(PyrRise1.meanCorrTNZ{cond}.StimField) || ...
                isempty(PyrRise1.meanCorrTNZ{cond}.StimCtrlField))
            PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStimField = 1;
            PyrRise1.meanCorrTNZ{cond}.pRSStimVsStimCtrlField = 1;
            PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimField = 1;
        else
            PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStimField = ...
                ranksum(PyrRise1.meanCorrTNZ{cond}.NonStimField,...
                        PyrRise1.meanCorrTNZ{cond}.StimField);
            PyrRise1.meanCorrTNZ{cond}.pRSStimVsStimCtrlField = ...
                ranksum(PyrRise1.meanCorrTNZ{cond}.StimField,...
                        PyrRise1.meanCorrTNZ{cond}.StimCtrlField);
            PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimField = ...
                ranksum(PyrRise1.meanCorrTNZ{cond}.NonStimField,...
                        PyrRise1.meanCorrTNZ{cond}.StimNonStimField);
        end
        
        if(isempty(PyrDown1.meanCorrTNZ{cond}.NonStimField) || ...
                isempty(PyrDown1.meanCorrTNZ{cond}.StimField) || ...
                isempty(PyrDown1.meanCorrTNZ{cond}.StimCtrlField))
            PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStimField = 1;
            PyrDown1.meanCorrTNZ{cond}.pRSStimVsStimCtrlField = 1;
            PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimField = 1;
        else
            PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStimField = ...
                ranksum(PyrDown1.meanCorrTNZ{cond}.NonStimField,...
                        PyrDown1.meanCorrTNZ{cond}.StimField);
            PyrDown1.meanCorrTNZ{cond}.pRSStimVsStimCtrlField = ...
                ranksum(PyrDown1.meanCorrTNZ{cond}.StimField,...
                        PyrDown1.meanCorrTNZ{cond}.StimCtrlField);
            PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimField = ...
                ranksum(PyrDown1.meanCorrTNZ{cond}.NonStimField,...
                        PyrDown1.meanCorrTNZ{cond}.StimNonStimField);
        end
                
        if(isempty(PyrOther1.meanCorrTNZ{cond}.NonStimField) || ...
                isempty(PyrOther1.meanCorrTNZ{cond}.StimField) || ...
                isempty(PyrOther1.meanCorrTNZ{cond}.StimCtrlField))
            PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStimField = 1;
            PyrOther1.meanCorrTNZ{cond}.pRSStimVsStimCtrlField = 1;
            PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimField = 1;
        else
            PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStimField = ...
                ranksum(PyrOther1.meanCorrTNZ{cond}.NonStimField,...
                        PyrOther1.meanCorrTNZ{cond}.StimField);
            PyrOther1.meanCorrTNZ{cond}.pRSStimVsStimCtrlField = ...
                ranksum(PyrOther1.meanCorrTNZ{cond}.StimField,...
                        PyrOther1.meanCorrTNZ{cond}.StimCtrlField);
            PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimField = ...
                ranksum(PyrOther1.meanCorrTNZ{cond}.NonStimField,...
                        PyrOther1.meanCorrTNZ{cond}.StimNonStimField);
        end
                
        % field combo
        %% pyramidal neurons all, added on 9/15/2022
        if(isempty(PyrStimT.meanCorrTNZ{cond}.NonStimFieldComb) || ...
                isempty(PyrStimT.meanCorrTNZ{cond}.StimFieldComb) || ...
                isempty(PyrStimT.meanCorrTNZ{cond}.StimCtrlFieldComb))
            PyrStimT.meanCorrTNZ{cond}.pRSNonStimVsStimFieldComb = 1;
            PyrStimT.meanCorrTNZ{cond}.pRSStimVsStimCtrlFieldComb = 1;
            PyrStimT.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimFieldComb = 1;

            PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStimFieldComb = 1;
            PyrRise1.meanCorrTNZ{cond}.pRSStimVsStimCtrlFieldComb = 1;
            PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimFieldComb = 1;

            PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStimFieldComb = 1;
            PyrDown1.meanCorrTNZ{cond}.pRSStimVsStimCtrlFieldComb = 1;
            PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimFieldComb = 1;

            PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStimFieldComb = 1;
            PyrOther1.meanCorrTNZ{cond}.pRSStimVsStimCtrlFieldComb = 1;
            PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimFieldComb = 1;
        else
            PyrStimT.meanCorrTNZ{cond}.pRSNonStimVsStimFieldComb = ...
                ranksum(PyrStimT.meanCorrTNZ{cond}.NonStimFieldComb,...
                        PyrStimT.meanCorrTNZ{cond}.StimFieldComb);
            PyrStimT.meanCorrTNZ{cond}.pRSStimVsStimCtrlFieldComb = ...
                ranksum(PyrStimT.meanCorrTNZ{cond}.StimFieldComb,...
                        PyrStimT.meanCorrTNZ{cond}.StimCtrlFieldComb);
            PyrStimT.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimFieldComb = ...
                ranksum(PyrStimT.meanCorrTNZ{cond}.NonStimFieldComb,...
                        PyrStimT.meanCorrTNZ{cond}.StimNonStimFieldComb);
            %%
            PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStimFieldComb = ...
                ranksum(PyrRise1.meanCorrTNZ{cond}.NonStimFieldComb,...
                        PyrRise1.meanCorrTNZ{cond}.StimFieldComb);
            PyrRise1.meanCorrTNZ{cond}.pRSStimVsStimCtrlFieldComb = ...
                ranksum(PyrRise1.meanCorrTNZ{cond}.StimFieldComb,...
                        PyrRise1.meanCorrTNZ{cond}.StimCtrlFieldComb);
            PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimFieldComb = ...
                ranksum(PyrRise1.meanCorrTNZ{cond}.NonStimFieldComb,...
                        PyrRise1.meanCorrTNZ{cond}.StimNonStimFieldComb);
            
            PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStimFieldComb = ...
                ranksum(PyrDown1.meanCorrTNZ{cond}.NonStimFieldComb,...
                        PyrDown1.meanCorrTNZ{cond}.StimFieldComb);
            PyrDown1.meanCorrTNZ{cond}.pRSStimVsStimCtrlFieldComb = ...
                ranksum(PyrDown1.meanCorrTNZ{cond}.StimFieldComb,...
                        PyrDown1.meanCorrTNZ{cond}.StimCtrlFieldComb);
            PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimFieldComb = ...
                ranksum(PyrDown1.meanCorrTNZ{cond}.NonStimFieldComb,...
                        PyrDown1.meanCorrTNZ{cond}.StimNonStimFieldComb);
                    
            PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStimFieldComb = ...
                ranksum(PyrOther1.meanCorrTNZ{cond}.NonStimFieldComb,...
                        PyrOther1.meanCorrTNZ{cond}.StimFieldComb);
            PyrOther1.meanCorrTNZ{cond}.pRSStimVsStimCtrlFieldComb = ...
                ranksum(PyrOther1.meanCorrTNZ{cond}.StimFieldComb,...
                        PyrOther1.meanCorrTNZ{cond}.StimCtrlFieldComb);
            PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimFieldComb = ...
                ranksum(PyrOther1.meanCorrTNZ{cond}.NonStimFieldComb,...
                        PyrOther1.meanCorrTNZ{cond}.StimNonStimFieldComb);
        end
    end
    
    save([pathAnal0 'initPeakPyrIntCorrTAllRecStimSigNoStim2ndStimCtrlTr.mat'],'PyrStimT','PyrRise1','PyrDown1','PyrOther1'); 
   
    colorSel = 0;
    for cond = 1:length(PyrStim1.FRProfile1)
        if(PyrStimT.meanCorrTNZ{cond}.actOrInact == 1)
            actOrInActStr = 'inact';  
        else
            actOrInActStr = 'act';
        end
        pulseMethodStr = num2str(PyrStimT.meanCorrTNZ{cond}.pulseMethod);
        stimLocsStr = num2str(PyrStimT.meanCorrTNZ{cond}.stimLoc);
        
        %% pyramidal neurons
        if(isempty(PyrRise1.meanCorrTNZ{cond}.NonStim))
            continue;
        end

        % pyr rise good non-stim vs. stim
        indNotNan = ~isnan(PyrRise1.meanCorrTNZ{cond}.NonStim);
        barPlotWithStat3(1:2,...
            [mean(PyrRise1.meanCorrTNZ{cond}.NonStim(indNotNan)),...
            mean(PyrRise1.meanCorrTNZ{cond}.Stim(indNotNan))],...
            [std(PyrRise1.meanCorrTNZ{cond}.NonStim(indNotNan))/sqrt(length(PyrRise1.meanCorrTNZ{cond}.NonStim(indNotNan))),...
            std(PyrRise1.meanCorrTNZ{cond}.Stim(indNotNan))/sqrt(length(PyrRise1.meanCorrTNZ{cond}.Stim(indNotNan)))],...
            PyrRise1.meanCorrTNZ{cond}.NonStim(indNotNan),...
            PyrRise1.meanCorrTNZ{cond}.Stim(indNotNan),...
            ['Mean corrT NZ PR' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStim,...
            ['CorrTAlignedPyrRiseNoStimVsStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Nonstim'} {'Stim'}]);
        
        % pyr rise stim vs. stim ctrl
        barPlotWithStat3(1:2,...
            [mean(PyrRise1.meanCorrTNZ{cond}.Stim),...
            mean(PyrRise1.meanCorrTNZ{cond}.StimCtrl)],...
            [std(PyrRise1.meanCorrTNZ{cond}.Stim)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.Stim)),...
            std(PyrRise1.meanCorrTNZ{cond}.StimCtrl)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.StimCtrl))],...
            PyrRise1.meanCorrTNZ{cond}.Stim,...
            PyrRise1.meanCorrTNZ{cond}.StimCtrl,...
            ['Mean corrT NZ PR' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrRise1.meanCorrTNZ{cond}.pRSStimVsStimCtrl,...
            ['CorrTAlignedPyrRiseStimVsStimCtrl_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Stim'} {'StimCtrl'}]);
        
        % pyr rise non-stim vs. stim-NonStim
        barPlotWithStat3(1:2,...
            [mean(PyrRise1.meanCorrTNZ{cond}.NonStim),...
            mean(PyrRise1.meanCorrTNZ{cond}.StimNonStim)],...
            [std(PyrRise1.meanCorrTNZ{cond}.NonStim)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.NonStim)),...
            std(PyrRise1.meanCorrTNZ{cond}.StimNonStim)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.StimNonStim))],...
            PyrRise1.meanCorrTNZ{cond}.NonStim,...
            PyrRise1.meanCorrTNZ{cond}.StimNonStim,...
            ['Mean corrT NZ PR' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStim,...
            ['CorrTAlignedPyrRiseNoStimVsStimNoStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'NonStim'} {'StimNonStim'}]);
        
        % pyr down good non-stim vs. stim
        barPlotWithStat3(1:2,...
            [mean(PyrDown1.meanCorrTNZ{cond}.NonStim),...
            mean(PyrDown1.meanCorrTNZ{cond}.Stim)],...
            [std(PyrDown1.meanCorrTNZ{cond}.NonStim)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.NonStim)),...
            std(PyrDown1.meanCorrTNZ{cond}.Stim)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.Stim))],...
            PyrDown1.meanCorrTNZ{cond}.NonStim,...
            PyrDown1.meanCorrTNZ{cond}.Stim,...
            ['Mean corrT NZ PD' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStim,...
            ['CorrTAlignedPyrDownNoStimVsStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Nonstim'} {'Stim'}]);
        
        % pyr down stim vs. stim ctrl
        barPlotWithStat3(1:2,...
            [mean(PyrDown1.meanCorrTNZ{cond}.Stim),...
            mean(PyrDown1.meanCorrTNZ{cond}.StimCtrl)],...
            [std(PyrDown1.meanCorrTNZ{cond}.Stim)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.Stim)),...
            std(PyrDown1.meanCorrTNZ{cond}.StimCtrl)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.StimCtrl))],...
            PyrDown1.meanCorrTNZ{cond}.Stim,...
            PyrDown1.meanCorrTNZ{cond}.StimCtrl,...
            ['Mean corrT NZ PD' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrDown1.meanCorrTNZ{cond}.pRSStimVsStimCtrl,...
            ['CorrTAlignedPyrDownStimVsStimCtrl_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Stim'} {'StimCtrl'}]);
        
        % pyr down non-stim vs. stim-NonStim
        barPlotWithStat3(1:2,...
            [mean(PyrDown1.meanCorrTNZ{cond}.NonStim),...
            mean(PyrDown1.meanCorrTNZ{cond}.StimNonStim)],...
            [std(PyrDown1.meanCorrTNZ{cond}.NonStim)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.NonStim)),...
            std(PyrDown1.meanCorrTNZ{cond}.StimNonStim)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.StimNonStim))],...
            PyrDown1.meanCorrTNZ{cond}.NonStim,...
            PyrDown1.meanCorrTNZ{cond}.StimNonStim,...
            ['Mean corrT NZ PD' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStim,...
            ['CorrTAlignedPyrDownNoStimVsStimNoStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'NonStim'} {'StimNonStim'}]);
        
        % pyr other good non-stim vs. stim
        barPlotWithStat3(1:2,...
            [mean(PyrOther1.meanCorrTNZ{cond}.NonStim),...
            mean(PyrOther1.meanCorrTNZ{cond}.Stim)],...
            [std(PyrOther1.meanCorrTNZ{cond}.NonStim)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.NonStim)),...
            std(PyrOther1.meanCorrTNZ{cond}.Stim)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.Stim))],...
            PyrOther1.meanCorrTNZ{cond}.NonStim,...
            PyrOther1.meanCorrTNZ{cond}.Stim,...
            ['Mean corrT NZ PO' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStim,...
            ['CorrTAlignedPyrOtherNoStimVsStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Nonstim'} {'Stim'}]);
        
        % pyr other stim vs. stim ctrl
        barPlotWithStat3(1:2,...
            [mean(PyrOther1.meanCorrTNZ{cond}.Stim),...
            mean(PyrOther1.meanCorrTNZ{cond}.StimCtrl)],...
            [std(PyrOther1.meanCorrTNZ{cond}.Stim)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.Stim)),...
            std(PyrOther1.meanCorrTNZ{cond}.StimCtrl)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.StimCtrl))],...
            PyrOther1.meanCorrTNZ{cond}.Stim,...
            PyrOther1.meanCorrTNZ{cond}.StimCtrl,...
            ['Mean corrT NZ PO' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrOther1.meanCorrTNZ{cond}.pRSStimVsStimCtrl,...
            ['CorrTAlignedPyrOtherStimVsStimCtrl_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Stim'} {'StimCtrl'}]);
        
        % pyr other non-stim vs. stim-NonStim
        barPlotWithStat3(1:2,...
            [mean(PyrOther1.meanCorrTNZ{cond}.NonStim),...
            mean(PyrOther1.meanCorrTNZ{cond}.StimNonStim)],...
            [std(PyrOther1.meanCorrTNZ{cond}.NonStim)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.NonStim)),...
            std(PyrOther1.meanCorrTNZ{cond}.StimNonStim)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.StimNonStim))],...
            PyrOther1.meanCorrTNZ{cond}.NonStim,...
            PyrOther1.meanCorrTNZ{cond}.StimNonStim,...
            ['Mean corrT NZ PO' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStim,...
            ['CorrTAlignedPyrOtherNoStimVsStimNoStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'NonStim'} {'StimNonStim'}]);
                
        %% pyramidal neurons with field
        % pyr all good non-stim vs. stim, added on 8/6/2023
        barPlotWithStat3(1:2,...
            [mean(PyrStimT.meanCorrTNZ{cond}.NonStimField),...
            mean(PyrStimT.meanCorrTNZ{cond}.StimField)],...
            [std(PyrStimT.meanCorrTNZ{cond}.NonStimField)/sqrt(length(PyrStimT.meanCorrTNZ{cond}.NonStimField)),...
            std(PyrStimT.meanCorrTNZ{cond}.StimField)/sqrt(length(PyrStimT.meanCorrTNZ{cond}.StimField))],...
            PyrStimT.meanCorrTNZ{cond}.NonStimField,...
            PyrStimT.meanCorrTNZ{cond}.StimField,...
            ['Mean corrT NZ PAF' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrStimT.meanCorrTNZ{cond}.pRSNonStimVsStimField,...
            ['CorrTAlignedPyrAllFieldNoStimVsStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Nonstim'} {'Stim'}],[0 0.8]);
        
        % pyr all stim vs. stim ctrl
        barPlotWithStat3(1:2,...
            [mean(PyrStimT.meanCorrTNZ{cond}.StimField),...
            mean(PyrStimT.meanCorrTNZ{cond}.StimCtrlField)],...
            [std(PyrStimT.meanCorrTNZ{cond}.StimField)/sqrt(length(PyrStimT.meanCorrTNZ{cond}.StimField)),...
            std(PyrStimT.meanCorrTNZ{cond}.StimCtrlField)/sqrt(length(PyrStimT.meanCorrTNZ{cond}.StimCtrlField))],...
            PyrStimT.meanCorrTNZ{cond}.StimField,...
            PyrStimT.meanCorrTNZ{cond}.StimCtrlField,...
            ['Mean corrT NZ PAF' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrStimT.meanCorrTNZ{cond}.pRSStimVsStimCtrlField,...
            ['CorrTAlignedPyrAllFieldStimVsStimCtrl_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Stim'} {'StimCtrl'}],[0 0.8]);
        
        % pyr all non-stim vs. stim-NonStim
        barPlotWithStat3(1:2,...
            [mean(PyrStimT.meanCorrTNZ{cond}.NonStimField),...
            mean(PyrStimT.meanCorrTNZ{cond}.StimNonStimField)],...
            [std(PyrStimT.meanCorrTNZ{cond}.NonStimField)/sqrt(length(PyrStimT.meanCorrTNZ{cond}.NonStimField)),...
            std(PyrStimT.meanCorrTNZ{cond}.StimNonStimField)/sqrt(length(PyrStimT.meanCorrTNZ{cond}.StimNonStimField))],...
            PyrStimT.meanCorrTNZ{cond}.NonStimField,...
            PyrStimT.meanCorrTNZ{cond}.StimNonStimField,...
            ['Mean corrT NZ PAF' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrStimT.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimField,...
            ['CorrTAlignedPyrAllFieldNoStimVsStimNoStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'NonStim'} {'StimNonStim'}],[0 0.8]);
                
        % pyr rise good non-stim vs. stim
        if(~isempty(PyrRise1.meanCorrTNZ{cond}.NonStimField) && ...
                ~isempty(PyrRise1.meanCorrTNZ{cond}.StimField))
            barPlotWithStat3(1:2,...
                [mean(PyrRise1.meanCorrTNZ{cond}.NonStimField),...
                mean(PyrRise1.meanCorrTNZ{cond}.StimField)],...
                [std(PyrRise1.meanCorrTNZ{cond}.NonStimField)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.NonStimField)),...
                std(PyrRise1.meanCorrTNZ{cond}.StimField)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.StimField))],...
                PyrRise1.meanCorrTNZ{cond}.NonStimField,...
                PyrRise1.meanCorrTNZ{cond}.StimField,...
                ['Mean corrT NZ PRF' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
                '', PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStimField,...
                ['CorrTAlignedPyrRiseFieldNoStimVsStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
                pathAnal0,colorSel,[{'Nonstim'} {'Stim'}],[0 0.8]);
        end

        % pyr rise stim vs. stim ctrl
        if(~isempty(PyrRise1.meanCorrTNZ{cond}.StimCtrlField) && ...
                ~isempty(PyrRise1.meanCorrTNZ{cond}.StimField))
            barPlotWithStat3(1:2,...
                [mean(PyrRise1.meanCorrTNZ{cond}.StimField),...
                mean(PyrRise1.meanCorrTNZ{cond}.StimCtrlField)],...
                [std(PyrRise1.meanCorrTNZ{cond}.StimField)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.StimField)),...
                std(PyrRise1.meanCorrTNZ{cond}.StimCtrlField)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.StimCtrlField))],...
                PyrRise1.meanCorrTNZ{cond}.StimField,...
                PyrRise1.meanCorrTNZ{cond}.StimCtrlField,...
                ['Mean corrT NZ PRF' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
                '', PyrRise1.meanCorrTNZ{cond}.pRSStimVsStimCtrlField,...
                ['CorrTAlignedPyrRiseFieldStimVsStimCtrl_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
                pathAnal0,colorSel,[{'Stim'} {'StimCtrl'}],[0 0.8]);
        end

        % pyr rise non-stim vs. stim-NonStim
        if(~isempty(PyrRise1.meanCorrTNZ{cond}.NonStimField) && ...
                ~isempty(PyrRise1.meanCorrTNZ{cond}.StimNonStimField))
            barPlotWithStat3(1:2,...
                [mean(PyrRise1.meanCorrTNZ{cond}.NonStimField),...
                mean(PyrRise1.meanCorrTNZ{cond}.StimNonStimField)],...
                [std(PyrRise1.meanCorrTNZ{cond}.NonStimField)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.NonStimField)),...
                std(PyrRise1.meanCorrTNZ{cond}.StimNonStimField)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.StimNonStimField))],...
                PyrRise1.meanCorrTNZ{cond}.NonStimField,...
                PyrRise1.meanCorrTNZ{cond}.StimNonStimField,...
                ['Mean corrT NZ PRF' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
                '', PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimField,...
                ['CorrTAlignedPyrRiseFieldNoStimVsStimNoStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
                pathAnal0,colorSel,[{'NonStim'} {'StimNonStim'}],[0 0.8]);
        end
                
        % pyr down good non-stim vs. stim
        if(~isempty(PyrDown1.meanCorrTNZ{cond}.NonStimField) && ...
                ~isempty(PyrDown1.meanCorrTNZ{cond}.StimField))
            barPlotWithStat3(1:2,...
                [mean(PyrDown1.meanCorrTNZ{cond}.NonStimField),...
                mean(PyrDown1.meanCorrTNZ{cond}.StimField)],...
                [std(PyrDown1.meanCorrTNZ{cond}.NonStimField)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.NonStimField)),...
                std(PyrDown1.meanCorrTNZ{cond}.StimField)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.StimField))],...
                PyrDown1.meanCorrTNZ{cond}.NonStimField,...
                PyrDown1.meanCorrTNZ{cond}.StimField,...
                ['Mean corrT NZ PDF' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
                '', PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStimField,...
                ['CorrTAlignedPyrDownFieldNoStimVsStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
                pathAnal0,colorSel,[{'Nonstim'} {'Stim'}],[0 0.8]);
        end
        
        % pyr down stim vs. stim ctrl
        if(~isempty(PyrDown1.meanCorrTNZ{cond}.StimCtrlField) && ...
                ~isempty(PyrDown1.meanCorrTNZ{cond}.StimField))
            barPlotWithStat3(1:2,...
                [mean(PyrDown1.meanCorrTNZ{cond}.StimField),...
                mean(PyrDown1.meanCorrTNZ{cond}.StimCtrlField)],...
                [std(PyrDown1.meanCorrTNZ{cond}.StimField)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.StimField)),...
                std(PyrDown1.meanCorrTNZ{cond}.StimCtrlField)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.StimCtrlField))],...
                PyrDown1.meanCorrTNZ{cond}.StimField,...
                PyrDown1.meanCorrTNZ{cond}.StimCtrlField,...
                ['Mean corrT NZ PDF' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
                '', PyrDown1.meanCorrTNZ{cond}.pRSStimVsStimCtrlField,...
                ['CorrTAlignedPyrDownFieldStimVsStimCtrl_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
                pathAnal0,colorSel,[{'Stim'} {'StimCtrl'}],[0 0.8]);
        end
        
        % pyr down non-stim vs. stim-NonStim
        if(~isempty(PyrDown1.meanCorrTNZ{cond}.NonStimField) && ...
                ~isempty(PyrDown1.meanCorrTNZ{cond}.StimNonStimField))
            barPlotWithStat3(1:2,...
                [mean(PyrDown1.meanCorrTNZ{cond}.NonStimField),...
                mean(PyrDown1.meanCorrTNZ{cond}.StimNonStimField)],...
                [std(PyrDown1.meanCorrTNZ{cond}.NonStimField)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.NonStimField)),...
                std(PyrDown1.meanCorrTNZ{cond}.StimNonStimField)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.StimNonStimField))],...
                PyrDown1.meanCorrTNZ{cond}.NonStimField,...
                PyrDown1.meanCorrTNZ{cond}.StimNonStimField,...
                ['Mean corrT NZ PDF' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
                '', PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimField,...
                ['CorrTAlignedPyrDownFieldNoStimVsStimNoStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
                pathAnal0,colorSel,[{'NonStim'} {'StimNonStim'}],[0 0.8]);
        end
        
        % pyr other good non-stim vs. stim
        if(~isempty(PyrOther1.meanCorrTNZ{cond}.NonStimField) && ...
                ~isempty(PyrOther1.meanCorrTNZ{cond}.StimField))
            barPlotWithStat3(1:2,...
                [mean(PyrOther1.meanCorrTNZ{cond}.NonStimField),...
                mean(PyrOther1.meanCorrTNZ{cond}.StimField)],...
                [std(PyrOther1.meanCorrTNZ{cond}.NonStimField)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.NonStimField)),...
                std(PyrOther1.meanCorrTNZ{cond}.StimField)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.StimField))],...
                PyrOther1.meanCorrTNZ{cond}.NonStimField,...
                PyrOther1.meanCorrTNZ{cond}.StimField,...
                ['Mean corrT NZ POF' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
                '', PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStimField,...
                ['CorrTAlignedPyrOtherFieldNoStimVsStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
                pathAnal0,colorSel,[{'Nonstim'} {'Stim'}],[0 0.8]);
        end
        
        % pyr other stim vs. stim ctrl
        if(~isempty(PyrOther1.meanCorrTNZ{cond}.StimCtrlField) && ...
                ~isempty(PyrOther1.meanCorrTNZ{cond}.StimField))
            barPlotWithStat3(1:2,...
                [mean(PyrOther1.meanCorrTNZ{cond}.StimField),...
                mean(PyrOther1.meanCorrTNZ{cond}.StimCtrlField)],...
                [std(PyrOther1.meanCorrTNZ{cond}.StimField)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.StimField)),...
                std(PyrOther1.meanCorrTNZ{cond}.StimCtrlField)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.StimCtrlField))],...
                PyrOther1.meanCorrTNZ{cond}.StimField,...
                PyrOther1.meanCorrTNZ{cond}.StimCtrlField,...
                ['Mean corrT NZ POF' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
                '', PyrOther1.meanCorrTNZ{cond}.pRSStimVsStimCtrlField,...
                ['CorrTAlignedPyrOtherFieldStimVsStimCtrl_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
                pathAnal0,colorSel,[{'Stim'} {'StimCtrl'}],[0 0.8]);
        end
        
        % pyr other non-stim vs. stim-NonStim
        if(~isempty(PyrOther1.meanCorrTNZ{cond}.NonStimField) && ...
                ~isempty(PyrOther1.meanCorrTNZ{cond}.StimNonStimField))
            barPlotWithStat3(1:2,...
                [mean(PyrOther1.meanCorrTNZ{cond}.NonStimField),...
                mean(PyrOther1.meanCorrTNZ{cond}.StimNonStimField)],...
                [std(PyrOther1.meanCorrTNZ{cond}.NonStimField)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.NonStimField)),...
                std(PyrOther1.meanCorrTNZ{cond}.StimNonStimField)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.StimNonStimField))],...
                PyrOther1.meanCorrTNZ{cond}.NonStimField,...
                PyrOther1.meanCorrTNZ{cond}.StimNonStimField,...
                ['Mean corrT NZ POF' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
                '', PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimField,...
                ['CorrTAlignedPyrOtherFieldNoStimVsStimNoStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
                pathAnal0,colorSel,[{'NonStim'} {'StimNonStim'}],[0 0.8]);
        end
                
        %% pyramidal neurons with field combo
        % pyr all good non-stim vs. stim, added on 9/15/2022
        barPlotWithStat3(1:2,...
            [mean(PyrStimT.meanCorrTNZ{cond}.NonStimFieldComb),...
            mean(PyrStimT.meanCorrTNZ{cond}.StimFieldComb)],...
            [std(PyrStimT.meanCorrTNZ{cond}.NonStimFieldComb)/sqrt(length(PyrStimT.meanCorrTNZ{cond}.NonStimFieldComb)),...
            std(PyrStimT.meanCorrTNZ{cond}.StimFieldComb)/sqrt(length(PyrStimT.meanCorrTNZ{cond}.StimFieldComb))],...
            PyrStimT.meanCorrTNZ{cond}.NonStimFieldComb,...
            PyrStimT.meanCorrTNZ{cond}.StimFieldComb,...
            ['Mean corrT NZ PAFC' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrStimT.meanCorrTNZ{cond}.pRSNonStimVsStimFieldComb,...
            ['CorrTAlignedPyrAllFieldCombNoStimVsStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Nonstim'} {'Stim'}],[0 0.8]);
        
        % pyr all stim vs. stim ctrl
        barPlotWithStat3(1:2,...
            [mean(PyrStimT.meanCorrTNZ{cond}.StimFieldComb),...
            mean(PyrStimT.meanCorrTNZ{cond}.StimCtrlFieldComb)],...
            [std(PyrStimT.meanCorrTNZ{cond}.StimFieldComb)/sqrt(length(PyrStimT.meanCorrTNZ{cond}.StimFieldComb)),...
            std(PyrStimT.meanCorrTNZ{cond}.StimCtrlFieldComb)/sqrt(length(PyrStimT.meanCorrTNZ{cond}.StimCtrlFieldComb))],...
            PyrStimT.meanCorrTNZ{cond}.StimFieldComb,...
            PyrStimT.meanCorrTNZ{cond}.StimCtrlFieldComb,...
            ['Mean corrT NZ PAFC' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrStimT.meanCorrTNZ{cond}.pRSStimVsStimCtrlFieldComb,...
            ['CorrTAlignedPyrAllFieldCombStimVsStimCtrl_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Stim'} {'StimCtrl'}],[0 0.8]);
        
        % pyr all non-stim vs. stim-NonStim
        barPlotWithStat3(1:2,...
            [mean(PyrStimT.meanCorrTNZ{cond}.NonStimFieldComb),...
            mean(PyrStimT.meanCorrTNZ{cond}.StimNonStimFieldComb)],...
            [std(PyrStimT.meanCorrTNZ{cond}.NonStimFieldComb)/sqrt(length(PyrStimT.meanCorrTNZ{cond}.NonStimFieldComb)),...
            std(PyrStimT.meanCorrTNZ{cond}.StimNonStimFieldComb)/sqrt(length(PyrStimT.meanCorrTNZ{cond}.StimNonStimFieldComb))],...
            PyrStimT.meanCorrTNZ{cond}.NonStimFieldComb,...
            PyrStimT.meanCorrTNZ{cond}.StimNonStimFieldComb,...
            ['Mean corrT NZ PAFC' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrStimT.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimFieldComb,...
            ['CorrTAlignedPyrAllFieldCombNoStimVsStimNoStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'NonStim'} {'StimNonStim'}],[0 0.8]);
                
        
        % pyr rise good non-stim vs. stim
        barPlotWithStat3(1:2,...
            [mean(PyrRise1.meanCorrTNZ{cond}.NonStimFieldComb),...
            mean(PyrRise1.meanCorrTNZ{cond}.StimFieldComb)],...
            [std(PyrRise1.meanCorrTNZ{cond}.NonStimFieldComb)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.NonStimFieldComb)),...
            std(PyrRise1.meanCorrTNZ{cond}.StimFieldComb)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.StimFieldComb))],...
            PyrRise1.meanCorrTNZ{cond}.NonStimFieldComb,...
            PyrRise1.meanCorrTNZ{cond}.StimFieldComb,...
            ['Mean corrT NZ PRFC' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStimFieldComb,...
            ['CorrTAlignedPyrRiseFieldCombNoStimVsStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Nonstim'} {'Stim'}],[0 0.8]);
        
        % pyr rise stim vs. stim ctrl
        barPlotWithStat3(1:2,...
            [mean(PyrRise1.meanCorrTNZ{cond}.StimFieldComb),...
            mean(PyrRise1.meanCorrTNZ{cond}.StimCtrlFieldComb)],...
            [std(PyrRise1.meanCorrTNZ{cond}.StimFieldComb)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.StimFieldComb)),...
            std(PyrRise1.meanCorrTNZ{cond}.StimCtrlFieldComb)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.StimCtrlFieldComb))],...
            PyrRise1.meanCorrTNZ{cond}.StimFieldComb,...
            PyrRise1.meanCorrTNZ{cond}.StimCtrlFieldComb,...
            ['Mean corrT NZ PRFC' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrRise1.meanCorrTNZ{cond}.pRSStimVsStimCtrlFieldComb,...
            ['CorrTAlignedPyrRiseFieldCombStimVsStimCtrl_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Stim'} {'StimCtrl'}],[0 0.8]);
        
        % pyr rise non-stim vs. stim-NonStim
        barPlotWithStat3(1:2,...
            [mean(PyrRise1.meanCorrTNZ{cond}.NonStimFieldComb),...
            mean(PyrRise1.meanCorrTNZ{cond}.StimNonStimFieldComb)],...
            [std(PyrRise1.meanCorrTNZ{cond}.NonStimFieldComb)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.NonStimFieldComb)),...
            std(PyrRise1.meanCorrTNZ{cond}.StimNonStimFieldComb)/sqrt(length(PyrRise1.meanCorrTNZ{cond}.StimNonStimFieldComb))],...
            PyrRise1.meanCorrTNZ{cond}.NonStimFieldComb,...
            PyrRise1.meanCorrTNZ{cond}.StimNonStimFieldComb,...
            ['Mean corrT NZ PRFC' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrRise1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimFieldComb,...
            ['CorrTAlignedPyrRiseFieldCombNoStimVsStimNoStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'NonStim'} {'StimNonStim'}],[0 0.8]);
                
        
        % pyr down good non-stim vs. stim
        barPlotWithStat3(1:2,...
            [mean(PyrDown1.meanCorrTNZ{cond}.NonStimFieldComb),...
            mean(PyrDown1.meanCorrTNZ{cond}.StimFieldComb)],...
            [std(PyrDown1.meanCorrTNZ{cond}.NonStimFieldComb)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.NonStimFieldComb)),...
            std(PyrDown1.meanCorrTNZ{cond}.StimFieldComb)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.StimFieldComb))],...
            PyrDown1.meanCorrTNZ{cond}.NonStimFieldComb,...
            PyrDown1.meanCorrTNZ{cond}.StimFieldComb,...
            ['Mean corrT NZ PDFC' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStimFieldComb,...
            ['CorrTAlignedPyrDownFieldCombNoStimVsStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Nonstim'} {'Stim'}],[0 0.8]);
        
        % pyr down stim vs. stim ctrl
        barPlotWithStat3(1:2,...
            [mean(PyrDown1.meanCorrTNZ{cond}.StimFieldComb),...
            mean(PyrDown1.meanCorrTNZ{cond}.StimCtrlFieldComb)],...
            [std(PyrDown1.meanCorrTNZ{cond}.StimFieldComb)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.StimFieldComb)),...
            std(PyrDown1.meanCorrTNZ{cond}.StimCtrlFieldComb)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.StimCtrlFieldComb))],...
            PyrDown1.meanCorrTNZ{cond}.StimFieldComb,...
            PyrDown1.meanCorrTNZ{cond}.StimCtrlFieldComb,...
            ['Mean corrT NZ PDFC' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrDown1.meanCorrTNZ{cond}.pRSStimVsStimCtrlFieldComb,...
            ['CorrTAlignedPyrDownFieldCombStimVsStimCtrl_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Stim'} {'StimCtrl'}],[0 0.8]);
        
        % pyr down non-stim vs. stim-NonStim
        barPlotWithStat3(1:2,...
            [mean(PyrDown1.meanCorrTNZ{cond}.NonStimFieldComb),...
            mean(PyrDown1.meanCorrTNZ{cond}.StimNonStimFieldComb)],...
            [std(PyrDown1.meanCorrTNZ{cond}.NonStimFieldComb)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.NonStimFieldComb)),...
            std(PyrDown1.meanCorrTNZ{cond}.StimNonStimFieldComb)/sqrt(length(PyrDown1.meanCorrTNZ{cond}.StimNonStimFieldComb))],...
            PyrDown1.meanCorrTNZ{cond}.NonStimFieldComb,...
            PyrDown1.meanCorrTNZ{cond}.StimNonStimFieldComb,...
            ['Mean corrT NZ PDFC' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrDown1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimFieldComb,...
            ['CorrTAlignedPyrDownFieldCombNoStimVsStimNoStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'NonStim'} {'StimNonStim'}],[0 0.8]);
                        
        % pyr other good non-stim vs. stim
        barPlotWithStat3(1:2,...
            [mean(PyrOther1.meanCorrTNZ{cond}.NonStimFieldComb),...
            mean(PyrOther1.meanCorrTNZ{cond}.StimFieldComb)],...
            [std(PyrOther1.meanCorrTNZ{cond}.NonStimFieldComb)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.NonStimFieldComb)),...
            std(PyrOther1.meanCorrTNZ{cond}.StimFieldComb)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.StimFieldComb))],...
            PyrOther1.meanCorrTNZ{cond}.NonStimFieldComb,...
            PyrOther1.meanCorrTNZ{cond}.StimFieldComb,...
            ['Mean corrT NZ POFC' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStimFieldComb,...
            ['CorrTAlignedPyrOtherFieldCombNoStimVsStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Nonstim'} {'Stim'}],[0 0.8]);
        
        % pyr other stim vs. stim ctrl
        barPlotWithStat3(1:2,...
            [mean(PyrOther1.meanCorrTNZ{cond}.StimFieldComb),...
            mean(PyrOther1.meanCorrTNZ{cond}.StimCtrlFieldComb)],...
            [std(PyrOther1.meanCorrTNZ{cond}.StimFieldComb)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.StimFieldComb)),...
            std(PyrOther1.meanCorrTNZ{cond}.StimCtrlFieldComb)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.StimCtrlFieldComb))],...
            PyrOther1.meanCorrTNZ{cond}.StimFieldComb,...
            PyrOther1.meanCorrTNZ{cond}.StimCtrlFieldComb,...
            ['Mean corrT NZ POFC' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrOther1.meanCorrTNZ{cond}.pRSStimVsStimCtrlFieldComb,...
            ['CorrTAlignedPyrOtherFieldCombStimVsStimCtrl_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Stim'} {'StimCtrl'}],[0 0.8]);
        
        % pyr other non-stim vs. stim-NonStim
        barPlotWithStat3(1:2,...
            [mean(PyrOther1.meanCorrTNZ{cond}.NonStimFieldComb),...
            mean(PyrOther1.meanCorrTNZ{cond}.StimNonStimFieldComb)],...
            [std(PyrOther1.meanCorrTNZ{cond}.NonStimFieldComb)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.NonStimFieldComb)),...
            std(PyrOther1.meanCorrTNZ{cond}.StimNonStimFieldComb)/sqrt(length(PyrOther1.meanCorrTNZ{cond}.StimNonStimFieldComb))],...
            PyrOther1.meanCorrTNZ{cond}.NonStimFieldComb,...
            PyrOther1.meanCorrTNZ{cond}.StimNonStimFieldComb,...
            ['Mean corrT NZ POFC' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrOther1.meanCorrTNZ{cond}.pRSNonStimVsStimNonStimFieldComb,...
            ['CorrTAlignedPyrOtherFieldCombNoStimVsStimNoStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'NonStim'} {'StimNonStim'}],[0 0.8]);
                
    end
    
    close all;
end