function PyrIntInitPeakNumFieldPVStimCtrlSelRec(methodKMean)
%% number of field of PyrRise and PyrDown neurons before and during stimulation

    pathAnal0 = ['Z:\Yingxue\Draft\PV\PyramidalPVStimALCtrlSel\'];
    pathAnal = ['Z:\Yingxue\Draft\PV\PyramidalPVStimALCtrl\' num2str(methodKMean) '\'];
    
    if(exist([pathAnal 'initPeakPyrAllRecStimCtrlTr.mat']))
        load([pathAnal 'initPeakPyrAllRecStimCtrlTr.mat']);
    end
    
    if(exist([pathAnal0 'initPeakPyrIntAllRecStimCtrlTr.mat']))
        load([pathAnal0 'initPeakPyrIntAllRecStimCtrlTr.mat']);
    end
    
    if(exist([pathAnal0 'initPeakPyrIntCorrTAllRecStimCtrlTr.mat']))
        load([pathAnal0 'initPeakPyrIntCorrTAllRecStimCtrlTr.mat']);
    end
    
    if(exist([pathAnal0 'initPeakPyrIntNumFieldAllRecStimCtrlTr.mat']))
        load([pathAnal0 'initPeakPyrIntNumFieldAllRecStimCtrlTr.mat']);
    end
    
    ind = PyrStimT.indNeuSel;
    PyrStimF.isNeuWithFieldAlignedGoodNonStim = ...
            modPyr1AL.isNeuWithFieldAlignedGoodNonStim(ind);
    PyrStimF.isNeuWithFieldAlignedStim = ...
            modPyr1AL.isNeuWithFieldAlignedStim(ind);
    PyrStimF.isNeuWithFieldAlignedStimCtrl = ...
            modPyr1AL.isNeuWithFieldAlignedStimCtrl(ind);
        
    for cond = 1:length(PyrStim1.FRProfile1)
        PyrRiseF{cond}.NonStimIsField = PyrStimF.isNeuWithFieldAlignedGoodNonStim(...
            PyrStimT.meanCorrTNZ{cond}.indPyrRise);
        PyrRiseF{cond}.StimIsField = PyrStimF.isNeuWithFieldAlignedStim(...
            PyrStimT.meanCorrTNZ{cond}.indPyrRise);
        PyrRiseF{cond}.StimCtrlIsField = PyrStimF.isNeuWithFieldAlignedStimCtrl(...
            PyrStimT.meanCorrTNZ{cond}.indPyrRise);
        
        PyrDownF{cond}.NonStimIsField = PyrStimF.isNeuWithFieldAlignedGoodNonStim(...
            PyrStimT.meanCorrTNZ{cond}.indPyrDown);
        PyrDownF{cond}.StimIsField = PyrStimF.isNeuWithFieldAlignedStim(...
            PyrStimT.meanCorrTNZ{cond}.indPyrDown);
        PyrDownF{cond}.StimCtrlIsField = PyrStimF.isNeuWithFieldAlignedStimCtrl(...
            PyrStimT.meanCorrTNZ{cond}.indPyrDown);
        
        PyrOtherF{cond}.NonStimIsField = PyrStimF.isNeuWithFieldAlignedGoodNonStim(...
            PyrStimT.meanCorrTNZ{cond}.indPyrOther);
        PyrOtherF{cond}.StimIsField = PyrStimF.isNeuWithFieldAlignedStim(...
            PyrStimT.meanCorrTNZ{cond}.indPyrOther);
        PyrOtherF{cond}.StimCtrlIsField = PyrStimF.isNeuWithFieldAlignedStimCtrl(...
            PyrStimT.meanCorrTNZ{cond}.indPyrOther);
        
        PyrRiseF{cond}.NonStimNumField = sum(PyrRiseF{cond}.NonStimIsField);
        PyrRiseF{cond}.StimNumField = sum(PyrRiseF{cond}.StimIsField);
        PyrRiseF{cond}.StimCtrlNumField = sum(PyrRiseF{cond}.StimCtrlIsField);
        
        PyrDownF{cond}.NonStimNumField = sum(PyrDownF{cond}.NonStimIsField);
        PyrDownF{cond}.StimNumField = sum(PyrDownF{cond}.StimIsField);
        PyrDownF{cond}.StimCtrlNumField = sum(PyrDownF{cond}.StimCtrlIsField);
        
        PyrOtherF{cond}.NonStimNumField = sum(PyrOtherF{cond}.NonStimIsField);
        PyrOtherF{cond}.StimNumField = sum(PyrOtherF{cond}.StimIsField);
        PyrOtherF{cond}.StimCtrlNumField = sum(PyrOtherF{cond}.StimCtrlIsField);
                
        PyrRiseF{cond}.NonStimAndStimNumField = sum(PyrRiseF{cond}.NonStimIsField == 1 &...
            PyrRiseF{cond}.StimIsField == 1);
        PyrRiseF{cond}.NonStimNotStimNumField = sum(PyrRiseF{cond}.NonStimIsField == 1 & ...
            PyrRiseF{cond}.StimIsField ~= 1);
        PyrRiseF{cond}.StimNotNonStimNumField = sum(PyrRiseF{cond}.NonStimIsField ~= 1 & ...
            PyrRiseF{cond}.StimIsField == 1);
        
        PyrRiseF{cond}.StimAndStimCtrlNumField = sum(PyrRiseF{cond}.StimIsField == 1 &...
            PyrRiseF{cond}.StimCtrlIsField == 1);
        PyrRiseF{cond}.StimNotStimCtrlNumField = sum(PyrRiseF{cond}.StimIsField == 1 & ...
            PyrRiseF{cond}.StimCtrlIsField ~= 1);
        PyrRiseF{cond}.StimCtrlNotStimNumField = sum(PyrRiseF{cond}.StimIsField ~= 1 & ...
            PyrRiseF{cond}.StimCtrlIsField == 1);
        
        PyrDownF{cond}.NonStimAndStimNumField = sum(PyrDownF{cond}.NonStimIsField == 1 &...
            PyrDownF{cond}.StimIsField == 1);
        PyrDownF{cond}.NonStimNotStimNumField = sum(PyrDownF{cond}.NonStimIsField == 1 & ...
            PyrDownF{cond}.StimIsField ~= 1);
        PyrDownF{cond}.StimNotNonStimNumField = sum(PyrDownF{cond}.NonStimIsField ~= 1 & ...
            PyrDownF{cond}.StimIsField == 1);
        
        PyrDownF{cond}.StimAndStimCtrlNumField = sum(PyrDownF{cond}.StimIsField == 1 &...
            PyrDownF{cond}.StimCtrlIsField == 1);
        PyrDownF{cond}.StimNotStimCtrlNumField = sum(PyrDownF{cond}.StimIsField == 1 & ...
            PyrDownF{cond}.StimCtrlIsField ~= 1);
        PyrDownF{cond}.StimCtrlNotStimNumField = sum(PyrDownF{cond}.StimIsField ~= 1 & ...
            PyrDownF{cond}.StimCtrlIsField == 1);
        
        PyrOtherF{cond}.NonStimAndStimNumField = sum(PyrOtherF{cond}.NonStimIsField == 1 &...
            PyrOtherF{cond}.StimIsField == 1);
        PyrOtherF{cond}.NonStimNotStimNumField = sum(PyrOtherF{cond}.NonStimIsField == 1 & ...
            PyrOtherF{cond}.StimIsField ~= 1);
        PyrOtherF{cond}.StimNotNonStimNumField = sum(PyrOtherF{cond}.NonStimIsField ~= 1 & ...
            PyrOtherF{cond}.StimIsField == 1);
        
        PyrOtherF{cond}.StimAndStimCtrlNumField = sum(PyrOtherF{cond}.StimIsField == 1 &...
            PyrOtherF{cond}.StimCtrlIsField == 1);
        PyrOtherF{cond}.StimNotStimCtrlNumField = sum(PyrOtherF{cond}.StimIsField == 1 & ...
            PyrOtherF{cond}.StimCtrlIsField ~= 1);
        PyrOtherF{cond}.StimCtrlNotStimNumField = sum(PyrOtherF{cond}.StimIsField ~= 1 & ...
            PyrOtherF{cond}.StimCtrlIsField == 1);
        
        %% quantifying fields per recording
        %% rise neurons
        indRec = unique(PyrStimT.meanCorrTNZ{cond}.indRecPyrRise);
        for i = 1:length(indRec)
            ind = find(PyrStimT.meanCorrTNZ{cond}.indRecPyrRise == indRec(i));
            PyrRiseF{cond}.indRec(i) = indRec(i);
            PyrRiseF{cond}.NonStimIsFieldPerRec{i} = PyrRiseF{cond}.NonStimIsField(ind);
            PyrRiseF{cond}.StimIsFieldPerRec{i} = PyrRiseF{cond}.StimIsField(ind);
            PyrRiseF{cond}.StimCtrlIsFieldPerRec{i} = PyrRiseF{cond}.StimCtrlIsField(ind);
            
            PyrRiseF{cond}.NonStimNumFieldPerRec(i) = sum(PyrRiseF{cond}.NonStimIsFieldPerRec{i});
            PyrRiseF{cond}.StimNumFieldPerRec(i) = sum(PyrRiseF{cond}.StimIsFieldPerRec{i});
            PyrRiseF{cond}.StimCtrlNumFieldPerRec(i) = sum(PyrRiseF{cond}.StimCtrlIsFieldPerRec{i});
            
            PyrRiseF{cond}.NonStimAndStimNumFieldPerRec(i) = sum(PyrRiseF{cond}.NonStimIsFieldPerRec{i} == 1 & ...
                PyrRiseF{cond}.StimIsFieldPerRec{i} == 1);
            PyrRiseF{cond}.NonStimNotStimNumFieldPerRec(i) = sum(PyrRiseF{cond}.NonStimIsFieldPerRec{i} == 1 & ...
                PyrRiseF{cond}.StimIsFieldPerRec{i} ~= 1);
            PyrRiseF{cond}.StimNotNonStimNumFieldPerRec(i) = sum(PyrRiseF{cond}.NonStimIsFieldPerRec{i} ~= 1 & ...
                PyrRiseF{cond}.StimIsFieldPerRec{i} == 1);
            
            PyrRiseF{cond}.PercNonStimAndStimNumFieldToNonStimPerRec(i) = ...
                PyrRiseF{cond}.NonStimAndStimNumFieldPerRec(i)/PyrRiseF{cond}.NonStimNumFieldPerRec(i);
            PyrRiseF{cond}.PercNonStimAndStimNumFieldToStimPerRec(i) = ...
                PyrRiseF{cond}.NonStimAndStimNumFieldPerRec(i)/PyrRiseF{cond}.StimNumFieldPerRec(i);
                        
            PyrRiseF{cond}.StimAndStimCtrlNumFieldPerRec(i) = sum(PyrRiseF{cond}.StimIsFieldPerRec{i} == 1 & ...
                PyrRiseF{cond}.StimCtrlIsFieldPerRec{i} == 1);
            PyrRiseF{cond}.StimNotStimCtrlNumFieldPerRec(i) = sum(PyrRiseF{cond}.StimIsFieldPerRec{i} == 1 & ...
                PyrRiseF{cond}.StimCtrlIsFieldPerRec{i} ~= 1);
            PyrRiseF{cond}.StimCtrlNotStimNumFieldPerRec(i) = sum(PyrRiseF{cond}.StimIsFieldPerRec{i} ~= 1 & ...
                PyrRiseF{cond}.StimCtrlIsFieldPerRec{i} == 1);
            
            PyrRiseF{cond}.PercStimAndStimCtrlNumFieldToStimPerRec(i) = ...
                PyrRiseF{cond}.StimAndStimCtrlNumFieldPerRec(i)/PyrRiseF{cond}.StimNumFieldPerRec(i);
            PyrRiseF{cond}.PercStimAndStimCtrlNumFieldToStimCtrlPerRec(i) = ...
                PyrRiseF{cond}.StimAndStimCtrlNumFieldPerRec(i)/PyrRiseF{cond}.StimCtrlNumFieldPerRec(i);
        end
        
        %% down neurons
        indRec = unique(PyrStimT.meanCorrTNZ{cond}.indRecPyrDown);
        for i = 1:length(indRec)
            ind = find(PyrStimT.meanCorrTNZ{cond}.indRecPyrDown == indRec(i));
            PyrDownF{cond}.indRec(i) = indRec(i);
            PyrDownF{cond}.NonStimIsFieldPerRec{i} = PyrDownF{cond}.NonStimIsField(ind);
            PyrDownF{cond}.StimIsFieldPerRec{i} = PyrDownF{cond}.StimIsField(ind);
            PyrDownF{cond}.StimCtrlIsFieldPerRec{i} = PyrDownF{cond}.StimCtrlIsField(ind);
            
            PyrDownF{cond}.NonStimNumFieldPerRec(i) = sum(PyrDownF{cond}.NonStimIsFieldPerRec{i});
            PyrDownF{cond}.StimNumFieldPerRec(i) = sum(PyrDownF{cond}.StimIsFieldPerRec{i});
            PyrDownF{cond}.StimCtrlNumFieldPerRec(i) = sum(PyrDownF{cond}.StimCtrlIsFieldPerRec{i});
            
            PyrDownF{cond}.NonStimAndStimNumFieldPerRec(i) = sum(PyrDownF{cond}.NonStimIsFieldPerRec{i} == 1 & ...
                PyrDownF{cond}.StimIsFieldPerRec{i} == 1);
            PyrDownF{cond}.NonStimNotStimNumFieldPerRec(i) = sum(PyrDownF{cond}.NonStimIsFieldPerRec{i} == 1 & ...
                PyrDownF{cond}.StimIsFieldPerRec{i} ~= 1);
            PyrDownF{cond}.StimNotNonStimNumFieldPerRec(i) = sum(PyrDownF{cond}.NonStimIsFieldPerRec{i} ~= 1 & ...
                PyrDownF{cond}.StimIsFieldPerRec{i} == 1);
            
            PyrDownF{cond}.PercNonStimAndStimNumFieldToNonStimPerRec(i) = ...
                PyrDownF{cond}.NonStimAndStimNumFieldPerRec(i)/PyrDownF{cond}.NonStimNumFieldPerRec(i);
            PyrDownF{cond}.PercNonStimAndStimNumFieldToStimPerRec(i) = ...
                PyrDownF{cond}.NonStimAndStimNumFieldPerRec(i)/PyrDownF{cond}.StimNumFieldPerRec(i);
            
            PyrDownF{cond}.StimAndStimCtrlNumFieldPerRec(i) = sum(PyrDownF{cond}.StimIsFieldPerRec{i} == 1 & ...
                PyrDownF{cond}.StimCtrlIsFieldPerRec{i} == 1);
            PyrDownF{cond}.StimNotStimCtrlNumFieldPerRec(i) = sum(PyrDownF{cond}.StimIsFieldPerRec{i} == 1 & ...
                PyrDownF{cond}.StimCtrlIsFieldPerRec{i} ~= 1);
            PyrDownF{cond}.StimCtrlNotStimNumFieldPerRec(i) = sum(PyrDownF{cond}.StimIsFieldPerRec{i} ~= 1 & ...
                PyrDownF{cond}.StimCtrlIsFieldPerRec{i} == 1);
            
            PyrDownF{cond}.PercStimAndStimCtrlNumFieldToStimPerRec(i) = ...
                PyrDownF{cond}.StimAndStimCtrlNumFieldPerRec(i)/PyrDownF{cond}.StimNumFieldPerRec(i);
            PyrDownF{cond}.PercStimAndStimCtrlNumFieldToStimCtrlPerRec(i) = ...
                PyrDownF{cond}.StimAndStimCtrlNumFieldPerRec(i)/PyrDownF{cond}.StimCtrlNumFieldPerRec(i);
        end
        
        %% other neurons
        indRec = unique(PyrStimT.meanCorrTNZ{cond}.indRecPyrOther);
        for i = 1:length(indRec)            
            ind = find(PyrStimT.meanCorrTNZ{cond}.indRecPyrOther == indRec(i));
            PyrOtherF{cond}.indRec(i) = indRec(i);
            PyrOtherF{cond}.NonStimIsFieldPerRec{i} = PyrOtherF{cond}.NonStimIsField(ind);
            PyrOtherF{cond}.StimIsFieldPerRec{i} = PyrOtherF{cond}.StimIsField(ind);
            PyrOtherF{cond}.StimCtrlIsFieldPerRec{i} = PyrOtherF{cond}.StimCtrlIsField(ind);
            
            PyrOtherF{cond}.NonStimNumFieldPerRec(i) = sum(PyrOtherF{cond}.NonStimIsFieldPerRec{i});
            PyrOtherF{cond}.StimNumFieldPerRec(i) = sum(PyrOtherF{cond}.StimIsFieldPerRec{i});
            PyrOtherF{cond}.StimCtrlNumFieldPerRec(i) = sum(PyrOtherF{cond}.StimCtrlIsFieldPerRec{i});
            
            PyrOtherF{cond}.NonStimAndStimNumFieldPerRec(i) = sum(PyrOtherF{cond}.NonStimIsFieldPerRec{i} == 1 & ...
                PyrOtherF{cond}.StimIsFieldPerRec{i} == 1);
            PyrOtherF{cond}.NonStimNotStimNumFieldPerRec(i) = sum(PyrOtherF{cond}.NonStimIsFieldPerRec{i} == 1 & ...
                PyrOtherF{cond}.StimIsFieldPerRec{i} ~= 1);
            PyrOtherF{cond}.StimNotNonStimNumFieldPerRec(i) = sum(PyrOtherF{cond}.NonStimIsFieldPerRec{i} ~= 1 & ...
                PyrOtherF{cond}.StimIsFieldPerRec{i} == 1);
            
            PyrOtherF{cond}.PercNonStimAndStimNumFieldToNonStimPerRec(i) = ...
                PyrOtherF{cond}.NonStimAndStimNumFieldPerRec(i)/PyrOtherF{cond}.NonStimNumFieldPerRec(i);
            PyrOtherF{cond}.PercNonStimAndStimNumFieldToStimPerRec(i) = ...
                PyrOtherF{cond}.NonStimAndStimNumFieldPerRec(i)/PyrOtherF{cond}.StimNumFieldPerRec(i);
            
            PyrOtherF{cond}.StimAndStimCtrlNumFieldPerRec(i) = sum(PyrOtherF{cond}.StimIsFieldPerRec{i} == 1 & ...
                PyrOtherF{cond}.StimCtrlIsFieldPerRec{i} == 1);
            PyrOtherF{cond}.StimNotStimCtrlNumFieldPerRec(i) = sum(PyrOtherF{cond}.StimIsFieldPerRec{i} == 1 & ...
                PyrOtherF{cond}.StimCtrlIsFieldPerRec{i} ~= 1);
            PyrOtherF{cond}.StimCtrlNotStimNumFieldPerRec(i) = sum(PyrOtherF{cond}.StimIsFieldPerRec{i} ~= 1 & ...
                PyrOtherF{cond}.StimCtrlIsFieldPerRec{i} == 1);
            
            PyrOtherF{cond}.PercStimAndStimCtrlNumFieldToStimPerRec(i) = ...
                PyrOtherF{cond}.StimAndStimCtrlNumFieldPerRec(i)/PyrOtherF{cond}.StimNumFieldPerRec(i);
            PyrOtherF{cond}.PercStimAndStimCtrlNumFieldToStimCtrlPerRec(i) = ...
                PyrOtherF{cond}.StimAndStimCtrlNumFieldPerRec(i)/PyrOtherF{cond}.StimCtrlNumFieldPerRec(i);
        end
   
        %% statistics on number of fields 
        PyrRiseF{cond}.pRSNonStimVsStimNumField = ranksum(PyrRiseF{cond}.NonStimNumFieldPerRec,...
            PyrRiseF{cond}.StimNumFieldPerRec);
        PyrRiseF{cond}.pRSStimVsStimCtrlNumField = ranksum(PyrRiseF{cond}.StimNumFieldPerRec,...
            PyrRiseF{cond}.StimCtrlNumFieldPerRec);
        
        PyrRiseF{cond}.pRSPercNonStimStimNumField = ...
            ranksum(PyrRiseF{cond}.PercNonStimAndStimNumFieldToNonStimPerRec,...
                    PyrRiseF{cond}.PercNonStimAndStimNumFieldToStimPerRec);
        PyrRiseF{cond}.pRSPercStimStimCtrlNumField = ...
            ranksum(PyrRiseF{cond}.PercStimAndStimCtrlNumFieldToStimPerRec,...
                    PyrRiseF{cond}.PercStimAndStimCtrlNumFieldToStimCtrlPerRec);
        
        PyrDownF{cond}.pRSNonStimVsStimNumField = ranksum(PyrDownF{cond}.NonStimNumFieldPerRec,...
            PyrDownF{cond}.StimNumFieldPerRec);
        PyrDownF{cond}.pRSStimVsStimCtrlNumField = ranksum(PyrDownF{cond}.StimNumFieldPerRec,...
            PyrDownF{cond}.StimCtrlNumFieldPerRec);
        
        PyrDownF{cond}.pRSPercNonStimStimNumField = ...
            ranksum(PyrDownF{cond}.PercNonStimAndStimNumFieldToNonStimPerRec,...
                    PyrDownF{cond}.PercNonStimAndStimNumFieldToStimPerRec);
        PyrDownF{cond}.pRSPercStimStimCtrlNumField = ...
            ranksum(PyrDownF{cond}.PercStimAndStimCtrlNumFieldToStimPerRec,...
                    PyrDownF{cond}.PercStimAndStimCtrlNumFieldToStimCtrlPerRec);
                
        PyrOtherF{cond}.pRSNonStimVsStimNumField = ranksum(PyrOtherF{cond}.NonStimNumFieldPerRec,...
            PyrOtherF{cond}.StimNumFieldPerRec);
        PyrOtherF{cond}.pRSStimVsStimCtrlNumField = ranksum(PyrOtherF{cond}.StimNumFieldPerRec,...
            PyrOtherF{cond}.StimCtrlNumFieldPerRec);
        
        PyrOtherF{cond}.pRSPercNonStimStimNumField = ...
            ranksum(PyrOtherF{cond}.PercNonStimAndStimNumFieldToNonStimPerRec,...
                    PyrOtherF{cond}.PercNonStimAndStimNumFieldToStimPerRec);
        PyrOtherF{cond}.pRSPercStimStimCtrlNumField = ...
            ranksum(PyrOtherF{cond}.PercStimAndStimCtrlNumFieldToStimPerRec,...
                    PyrOtherF{cond}.PercStimAndStimCtrlNumFieldToStimCtrlPerRec);
        
    end
        
    save([pathAnal0 'initPeakPyrIntNumFieldAllRecStimCtrlTr.mat'],'PyrRiseF','PyrDownF','PyrOtherF','PyrStimF');
    
    colorSel = 0;
    for cond = 1:length(PyrStim1.FRProfile1)
        if(PyrStimT.meanCorrTNZ{cond}.actOrInact == 1)
            actOrInActStr = 'inact';  
        else
            actOrInActStr = 'act';
        end
        pulseMethodStr = num2str(PyrStimT.meanCorrTNZ{cond}.pulseMethod);
        stimLocsStr = num2str(PyrStimT.meanCorrTNZ{cond}.stimLoc);
        
        %% pyramidal neurons
        % pyr rise good non-stim vs. stim
        barPlotWithStat3(1:2,...
            [mean(PyrRiseF{cond}.NonStimNumFieldPerRec),...
            mean(PyrRiseF{cond}.StimNumFieldPerRec)],...
            [std(PyrRiseF{cond}.NonStimNumFieldPerRec)/sqrt(length(PyrRiseF{cond}.NonStimNumFieldPerRec)),...
            std(PyrRiseF{cond}.StimNumFieldPerRec)/sqrt(length(PyrRiseF{cond}.StimNumFieldPerRec))],...
            PyrRiseF{cond}.NonStimNumFieldPerRec,...
            PyrRiseF{cond}.StimNumFieldPerRec,...
            ['Num. Field NZ PR' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrRiseF{cond}.pRSNonStimVsStimNumField,...
            ['NumFieldAlignedPyrRiseNoStimVsStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Nonstim'} {'Stim'}]);
        
        barPlotWithStat3(1:2,...
            [mean(PyrRiseF{cond}.StimNumFieldPerRec),...
            mean(PyrRiseF{cond}.StimCtrlNumFieldPerRec)],...
            [std(PyrRiseF{cond}.StimNumFieldPerRec)/sqrt(length(PyrRiseF{cond}.StimNumFieldPerRec)),...
            std(PyrRiseF{cond}.StimCtrlNumFieldPerRec)/sqrt(length(PyrRiseF{cond}.StimCtrlNumFieldPerRec))],...
            PyrRiseF{cond}.StimNumFieldPerRec,...
            PyrRiseF{cond}.StimCtrlNumFieldPerRec,...
            ['Num. Field NZ PR' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrRiseF{cond}.pRSStimVsStimCtrlNumField,...
            ['NumFieldAlignedPyrRiseStimVsStimCtrl_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Stim'} {'StimCtrl'}]);
                
        barPlotWithStat3(1:2,...
            [mean(PyrRiseF{cond}.PercNonStimAndStimNumFieldToNonStimPerRec),...
            mean(PyrRiseF{cond}.PercNonStimAndStimNumFieldToStimPerRec)],...
            [std(PyrRiseF{cond}.PercNonStimAndStimNumFieldToNonStimPerRec)/sqrt(length(PyrRiseF{cond}.PercNonStimAndStimNumFieldToNonStimPerRec)),...
            std(PyrRiseF{cond}.PercNonStimAndStimNumFieldToStimPerRec)/sqrt(length(PyrRiseF{cond}.PercNonStimAndStimNumFieldToStimPerRec))],...
            PyrRiseF{cond}.PercNonStimAndStimNumFieldToNonStimPerRec,...
            PyrRiseF{cond}.PercNonStimAndStimNumFieldToStimPerRec,...
            ['Perc. Field PR' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrRiseF{cond}.pRSPercNonStimStimNumField,...
            ['PercFieldAlignedPyrRiseNoStimVsStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'/Nonstim'} {'/Stim'}]);
        
        barPlotWithStat3(1:2,...
            [mean(PyrRiseF{cond}.PercStimAndStimCtrlNumFieldToStimPerRec),...
            mean(PyrRiseF{cond}.PercStimAndStimCtrlNumFieldToStimCtrlPerRec)],...
            [std(PyrRiseF{cond}.PercStimAndStimCtrlNumFieldToStimPerRec)/sqrt(length(PyrRiseF{cond}.PercStimAndStimCtrlNumFieldToStimPerRec)),...
            std(PyrRiseF{cond}.PercStimAndStimCtrlNumFieldToStimCtrlPerRec)/sqrt(length(PyrRiseF{cond}.PercStimAndStimCtrlNumFieldToStimCtrlPerRec))],...
            PyrRiseF{cond}.PercStimAndStimCtrlNumFieldToStimPerRec,...
            PyrRiseF{cond}.PercStimAndStimCtrlNumFieldToStimCtrlPerRec,...
            ['Perc. Field NZ PR' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrRiseF{cond}.pRSPercStimStimCtrlNumField,...
            ['PercFieldAlignedPyrRiseStimVsStimCtrl_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'/Stim'} {'/StimCtrl'}]);
              
        % pyr down good non-stim vs. stim
        barPlotWithStat3(1:2,...
            [mean(PyrDownF{cond}.NonStimNumFieldPerRec),...
            mean(PyrDownF{cond}.StimNumFieldPerRec)],...
            [std(PyrDownF{cond}.NonStimNumFieldPerRec)/sqrt(length(PyrDownF{cond}.NonStimNumFieldPerRec)),...
            std(PyrDownF{cond}.StimNumFieldPerRec)/sqrt(length(PyrDownF{cond}.StimNumFieldPerRec))],...
            PyrDownF{cond}.NonStimNumFieldPerRec,...
            PyrDownF{cond}.StimNumFieldPerRec,...
            ['Num. Field NZ PD' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrDownF{cond}.pRSNonStimVsStimNumField,...
            ['NumFieldAlignedPyrDownNoStimVsStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Nonstim'} {'Stim'}]);
        
        barPlotWithStat3(1:2,...
            [mean(PyrDownF{cond}.StimNumFieldPerRec),...
            mean(PyrDownF{cond}.StimCtrlNumFieldPerRec)],...
            [std(PyrDownF{cond}.StimNumFieldPerRec)/sqrt(length(PyrDownF{cond}.StimNumFieldPerRec)),...
            std(PyrDownF{cond}.StimCtrlNumFieldPerRec)/sqrt(length(PyrDownF{cond}.StimCtrlNumFieldPerRec))],...
            PyrDownF{cond}.StimNumFieldPerRec,...
            PyrDownF{cond}.StimCtrlNumFieldPerRec,...
            ['Num. Field NZ PD' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrDownF{cond}.pRSStimVsStimCtrlNumField,...
            ['NumFieldAlignedPyrDownStimVsStimCtrl_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Stim'} {'StimCtrl'}]);
                
        barPlotWithStat3(1:2,...
            [mean(PyrDownF{cond}.PercNonStimAndStimNumFieldToNonStimPerRec),...
            mean(PyrDownF{cond}.PercNonStimAndStimNumFieldToStimPerRec)],...
            [std(PyrDownF{cond}.PercNonStimAndStimNumFieldToNonStimPerRec)/sqrt(length(PyrDownF{cond}.PercNonStimAndStimNumFieldToNonStimPerRec)),...
            std(PyrDownF{cond}.PercNonStimAndStimNumFieldToStimPerRec)/sqrt(length(PyrDownF{cond}.PercNonStimAndStimNumFieldToStimPerRec))],...
            PyrDownF{cond}.PercNonStimAndStimNumFieldToNonStimPerRec,...
            PyrDownF{cond}.PercNonStimAndStimNumFieldToStimPerRec,...
            ['Perc. Field PD' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrDownF{cond}.pRSPercNonStimStimNumField,...
            ['PercFieldAlignedPyrDownNoStimVsStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'/Nonstim'} {'/Stim'}]);
        
        barPlotWithStat3(1:2,...
            [mean(PyrDownF{cond}.PercStimAndStimCtrlNumFieldToStimPerRec),...
            mean(PyrDownF{cond}.PercStimAndStimCtrlNumFieldToStimCtrlPerRec)],...
            [std(PyrDownF{cond}.PercStimAndStimCtrlNumFieldToStimPerRec)/sqrt(length(PyrDownF{cond}.PercStimAndStimCtrlNumFieldToStimPerRec)),...
            std(PyrDownF{cond}.PercStimAndStimCtrlNumFieldToStimCtrlPerRec)/sqrt(length(PyrDownF{cond}.PercStimAndStimCtrlNumFieldToStimCtrlPerRec))],...
            PyrDownF{cond}.PercStimAndStimCtrlNumFieldToStimPerRec,...
            PyrDownF{cond}.PercStimAndStimCtrlNumFieldToStimCtrlPerRec,...
            ['Perc. Field NZ PD' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrDownF{cond}.pRSPercStimStimCtrlNumField,...
            ['PercFieldAlignedPyrDownStimVsStimCtrl_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'/Stim'} {'/StimCtrl'}]);
        
        % pyr other good non-stim vs. stim
        barPlotWithStat3(1:2,...
            [mean(PyrOtherF{cond}.NonStimNumFieldPerRec),...
            mean(PyrOtherF{cond}.StimNumFieldPerRec)],...
            [std(PyrOtherF{cond}.NonStimNumFieldPerRec)/sqrt(length(PyrOtherF{cond}.NonStimNumFieldPerRec)),...
            std(PyrOtherF{cond}.StimNumFieldPerRec)/sqrt(length(PyrOtherF{cond}.StimNumFieldPerRec))],...
            PyrOtherF{cond}.NonStimNumFieldPerRec,...
            PyrOtherF{cond}.StimNumFieldPerRec,...
            ['Num. Field NZ PO' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrOtherF{cond}.pRSNonStimVsStimNumField,...
            ['NumFieldAlignedPyrOtherNoStimVsStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Nonstim'} {'Stim'}]);
        
        barPlotWithStat3(1:2,...
            [mean(PyrOtherF{cond}.StimNumFieldPerRec),...
            mean(PyrOtherF{cond}.StimCtrlNumFieldPerRec)],...
            [std(PyrOtherF{cond}.StimNumFieldPerRec)/sqrt(length(PyrOtherF{cond}.StimNumFieldPerRec)),...
            std(PyrOtherF{cond}.StimCtrlNumFieldPerRec)/sqrt(length(PyrOtherF{cond}.StimCtrlNumFieldPerRec))],...
            PyrOtherF{cond}.StimNumFieldPerRec,...
            PyrOtherF{cond}.StimCtrlNumFieldPerRec,...
            ['Num. Field NZ PO' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrOtherF{cond}.pRSStimVsStimCtrlNumField,...
            ['NumFieldAlignedPyrOtherStimVsStimCtrl_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'Stim'} {'StimCtrl'}]);
                
        barPlotWithStat3(1:2,...
            [mean(PyrOtherF{cond}.PercNonStimAndStimNumFieldToNonStimPerRec),...
            mean(PyrOtherF{cond}.PercNonStimAndStimNumFieldToStimPerRec)],...
            [std(PyrOtherF{cond}.PercNonStimAndStimNumFieldToNonStimPerRec)/sqrt(length(PyrOtherF{cond}.PercNonStimAndStimNumFieldToNonStimPerRec)),...
            std(PyrOtherF{cond}.PercNonStimAndStimNumFieldToStimPerRec)/sqrt(length(PyrOtherF{cond}.PercNonStimAndStimNumFieldToStimPerRec))],...
            PyrOtherF{cond}.PercNonStimAndStimNumFieldToNonStimPerRec,...
            PyrOtherF{cond}.PercNonStimAndStimNumFieldToStimPerRec,...
            ['Perc. Field PO' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrOtherF{cond}.pRSPercNonStimStimNumField,...
            ['PercFieldAlignedPyrOtherNoStimVsStim_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'/Nonstim'} {'/Stim'}]);
        
        barPlotWithStat3(1:2,...
            [mean(PyrOtherF{cond}.PercStimAndStimCtrlNumFieldToStimPerRec),...
            mean(PyrOtherF{cond}.PercStimAndStimCtrlNumFieldToStimCtrlPerRec)],...
            [std(PyrOtherF{cond}.PercStimAndStimCtrlNumFieldToStimPerRec)/sqrt(length(PyrOtherF{cond}.PercStimAndStimCtrlNumFieldToStimPerRec)),...
            std(PyrOtherF{cond}.PercStimAndStimCtrlNumFieldToStimCtrlPerRec)/sqrt(length(PyrOtherF{cond}.PercStimAndStimCtrlNumFieldToStimCtrlPerRec))],...
            PyrOtherF{cond}.PercStimAndStimCtrlNumFieldToStimPerRec,...
            PyrOtherF{cond}.PercStimAndStimCtrlNumFieldToStimCtrlPerRec,...
            ['Perc. Field NZ PO' actOrInActStr '-' pulseMethodStr '-' stimLocsStr],...
            '', PyrOtherF{cond}.pRSPercStimStimCtrlNumField,...
            ['PercFieldAlignedPyrOtherStimVsStimCtrl_' actOrInActStr '_P' pulseMethodStr '_sl' stimLocsStr],...
            pathAnal0,colorSel,[{'/Stim'} {'/StimCtrl'}]);
              
    end
    
    close all;