function plotPyrInitPeakClu(pathAnal,idxC,FRProfileMean,FRProfileMeanStatC,colorSel,idxCInd,strEnd)
% plot avg FR for each segment of profile, all the recordings for each cluster
% this function is called by PyrInitPeakAllRec.m

    for i = 1:length(idxCInd)
        if(i == 1)
            str = 'Deep';
        elseif(i == 2)
            str = 'Sup';
        else
            str = [];
        end
%         plotAvgFRProfile(modPyr1NoCue.timeStepRun,...
%             avgFRProfile(idxC == i,:),['C' num2str(i) ' FR (Hz)'],...
%             ['Pyr_FRProfileC' num2str(i)],...
%             pathAnal,[])
        
        plotBoxPlot(FRProfileMean.meanAvgFRProfileBaseline(idxC == idxCInd(i)),...
            FRProfileMean.meanAvgFRProfile0to1(idxC == idxCInd(i)),...
            [str ' average FR (Hz) BL vs 0to1s'],...
            ['Pyr_FRMean' str 'BL-0to1Box' strEnd],...
            pathAnal,[-1 8],FRProfileMeanStatC.pRS0to1VsBL(idxCInd(i)),colorSel,[{'BL'} {'0to1s'}]);
        
        plotBoxPlot(FRProfileMean.meanAvgFRProfileBaseline(idxC == idxCInd(i)),...
            FRProfileMean.meanAvgFRProfileBefRun(idxC == idxCInd(i)),...
            [str ' average FR (Hz) BL vs BefRun'],...
            ['Pyr_FRMean' str 'BL-BefRunBox' strEnd],...
            pathAnal,[-1 8],FRProfileMeanStatC.pRSBefRunVsBL(idxCInd(i)),colorSel,[{'BL'} {'BefRun'}]);
        
        plotBoxPlot(FRProfileMean.meanAvgFRProfileBaseline(idxC == idxCInd(i)),...
            FRProfileMean.meanAvgFRProfile3to5(idxC == idxCInd(i)),...
            [str ' average FR (Hz) BL vs 3to5s'],...
            ['Pyr_FRMean' str 'BL-3to5Box' strEnd],...
            pathAnal,[-1 8],FRProfileMeanStatC.pRS3to5VsBL(idxCInd(i)),colorSel,[{'BL'} {'3to5s'}]);
        
        plotBoxPlot(FRProfileMean.meanAvgFRProfileBefRun(idxC == idxCInd(i)),...
            FRProfileMean.meanAvgFRProfile0to1(idxC == idxCInd(i)),...
            [str ' average FR (Hz) BefRun vs 0to1s'],...
            ['Pyr_FRMean' str 'BefRun-0to1Box' strEnd],...
            pathAnal,[-1 8],FRProfileMeanStatC.pRSBefRunVs0to1(idxCInd(i)),colorSel,[{'BefRun'} {'0to1s'}]);
        
        plotBoxPlot(FRProfileMean.meanAvgFRProfileBefRun(idxC == idxCInd(i)),...
            FRProfileMean.meanAvgFRProfile3to5(idxC == idxCInd(i)),...
            [str ' average FR (Hz) BefRun vs 3to5s'],...
            ['Pyr_FRMean' str 'BefRun-3to5Box' strEnd],...
            pathAnal,[-1 8],FRProfileMeanStatC.pRS3to5VsBefRun(idxCInd(i)),colorSel,[{'BefRun'} {'3to5s'}]);
        
        plotBoxPlot(FRProfileMean.meanAvgFRProfile0to1(idxC == idxCInd(i)),...
            FRProfileMean.meanAvgFRProfile3to5(idxC == idxCInd(i)),...
            [str ' average FR (Hz) 0to1s vs 3to5s'],...
            ['Pyr_FRMean' str '0to1-3to5Box' strEnd],...
            pathAnal,[-1 8],FRProfileMeanStatC.pRS3to5Vs0to1(idxCInd(i)),colorSel,[{'0to1s'} {'3to5s'}]);
    end
    
    