function plotPyrInitGoodVsBadTr(pathAnal,timeStepRun,avgFRProfile,avgFRProfileBad,...
        avgFRProfileNorm,avgFRProfileNormBad,...
        FRProfileMean,FRProfileMeanBad,FRProfileMeanStatGoodBad,colorSel)
%% FR change good vs. bad trials
%  this function is called by PyrInitPeakAllRec.m

    plotAvgFRProfileCmp(timeStepRun,...
            avgFRProfile,avgFRProfileBad,...
            'FR (Hz) Good vs. Bad',...
            'Pyr_FRProfileGoodVsBadAll',...
            pathAnal,[1.5 2.5],[{'Good'} {''} {'Bad'} {''}])
        
    plotAvgFRProfileCmp(timeStepRun,...
            avgFRProfileNorm,avgFRProfileNormBad,...
            'FR (Hz) Good vs. Bad (Norm)',...
            'Pyr_FRProfileNormGoodVsBadAll',...
            pathAnal,[0.2 0.4],[{'Good'} {''} {'Bad'} {''}])
    
    plotBoxPlot(FRProfileMean.percChange0to1VsBL',...
        FRProfileMeanBad.percChange0to1VsBL',...
        ['average FR change 0-1s/BL G/B'],...
        ['Pyr_FRChange0to1-BLGoodBadBox'],...
        pathAnal,[-1 4],FRProfileMeanStatGoodBad.pRSPercChange0to1VsBLAll,...
        colorSel,[{'Good'} {'Bad'}]);

    plotBoxPlot(FRProfileMean.percChangeBefRunVsBL',...
        FRProfileMeanBad.percChangeBefRunVsBL',...
        ['average FR change BefRun/BL G/B'],...
        ['Pyr_FRChangeBefRun-BLGoodBadBox'],...
        pathAnal,[-1 4],FRProfileMeanStatGoodBad.pRSPercChangeBefRunVsBLAll,...
        colorSel,[{'Good'} {'Bad'}]);

    plotBoxPlot(FRProfileMean.percChangeBefRunVs0to1',...
        FRProfileMeanBad.percChangeBefRunVs0to1',...
        ['average FR change BefRun/0to1s G/B'],...
        ['Pyr_FRChangeBefRun-0to1GoodBadBox'],...
        pathAnal,[-1 5],FRProfileMeanStatGoodBad.pRSPercChangeBefRunVs0to1All,...
        colorSel,[{'Good'} {'Bad'}]);
    
    plotBoxPlot(FRProfileMean.percChange0to1Vs3to5',...
        FRProfileMeanBad.percChange0to1Vs3to5',...
        ['average FR change 0-1s/3-5s G/B'],...
        ['Pyr_FRChange0to1-3to5GoodBadBox'],...
        pathAnal,[-1 4],FRProfileMeanStatGoodBad.pRSPercChange0to1Vs3to5All,...
        colorSel,[{'Good'} {'Bad'}]);

    plotBoxPlot(FRProfileMean.percChangeBefRunVs3to5',...
        FRProfileMeanBad.percChangeBefRunVs3to5',...
        ['average FR change BefRun/3-5s G/B'],...
        ['Pyr_FRChangeBefRun-3to5GoodBadBox'],...
        pathAnal,[-1 4],FRProfileMeanStatGoodBad.pRSPercChangeBefRunVs3to5All,...
        colorSel,[{'Good'} {'Bad'}]);