function plotPyrInitCmpClu(pathAnal,idxC1,idxC2,timeStepRun,avgFRProfile,avgFRProfileNorm,...
    FRProfileMean,FRProfileMeanStatC1C2,colorSel)
%% clusters 1 and 2
% this function is called by PyrInitPeakAllRec.m
    
    plotAvgFRProfileCmp(timeStepRun,...
            avgFRProfile(idxC1,:),avgFRProfile(idxC2,:),...
            ['FR (Hz)'],...
            ['Pyr_FRProfileDeep-Sup'],...
            pathAnal,[1 2.5],[{'Deep'} {''} {'Sup'} {''}])
        
    plotAvgFRProfileCmp(timeStepRun,...
            avgFRProfileNorm(idxC1,:),avgFRProfileNorm(idxC2,:),...
            ['Norm FR'],...
            ['Pyr_FRProfileNormDeep-Sup'],...
            pathAnal,[0.2 0.4],[{'Deep'} {''} {'Sup'} {''}])
        
    plotBoxPlot(FRProfileMean.percChange0to1VsBL(idxC1)',...
        FRProfileMean.percChange0to1VsBL(idxC2)',...
        ['average FR change 0-1s/BL'],...
        ['Pyr_FRChange0to1-BLDeep-SupBox'],...
        pathAnal,[-1 4],FRProfileMeanStatC1C2.pRSPercChange0to1VsBLC,...
        colorSel,[{'Deep'} {'Sup'}]);

    plotBoxPlot(FRProfileMean.percChangeBefRunVsBL(idxC1)',...
        FRProfileMean.percChangeBefRunVsBL(idxC2)',...
        ['average FR change BefRun/BL'],...
        ['Pyr_FRChangeBefRun-BLDeep-SupBox'],...
        pathAnal,[-1 4],FRProfileMeanStatC1C2.pRSPercChangeBefRunVsBLC,...
        colorSel,[{'Deep'} {'Sup'}]);
    
    plotBoxPlot(FRProfileMean.percChangeBefRunVs0to1(idxC1)',...
        FRProfileMean.percChangeBefRunVs0to1(idxC2)',...
        ['average FR change BefRun/0to1s'],...
        ['Pyr_FRChangeBefRun-0to1Deep-SupBox'],...
        pathAnal,[-1 4],FRProfileMeanStatC1C2.pRSPercChangeBefRunVs0to1C,...
        colorSel,[{'Deep'} {'Sup'}]);

    plotBoxPlot(FRProfileMean.percChange0to1Vs3to5(idxC1)',...
        FRProfileMean.percChange0to1Vs3to5(idxC2)',...
        ['average FR change 0-1s/3-5s'],...
        ['Pyr_FRChange0to1-3to5Deep-SupBox'],...
        pathAnal,[-1 4],FRProfileMeanStatC1C2.pRSPercChange0to1Vs3to5C,...
        colorSel,[{'Deep'} {'Sup'}]);

    plotBoxPlot(FRProfileMean.percChangeBefRunVs3to5(idxC1)',...
        FRProfileMean.percChangeBefRunVs3to5(idxC2)',...
        ['average FR change BefRun/3-5s'],...
        ['Pyr_FRChangeBefRun-3to5Deep-SupBox'],...
        pathAnal,[-1 4],FRProfileMeanStatC1C2.pRSPercChangeBefRunVs3to5C,...
        colorSel,[{'Deep'} {'Sup'}]);
       