function plotPyrInitGoodBadTrPerClu(pathAnal,idxC,idxCBad,timeStepRun,avgFRProfile,avgFRProfileBad,...
    avgFRProfileNorm,avgFRProfileNormBad,FRProfileMean,FRProfileMeanBad,FRProfileMeanStatGoodBad,colorSel,idxCInd)
%% FR change good vs. bad trials for each cluster
% this function is called by PyrInitPeakAllRec.m

    for i = 1:length(idxCInd)
        if(i == 1)
            str = 'Deep';
        elseif(i == 2)
            str = 'Sup';
        else
            str = [];
        end
        
        plotAvgFRProfileCmp(timeStepRun,...
            avgFRProfile(idxC == idxCInd(i),:),avgFRProfileBad(idxCBad == idxCInd(i),:),...
            [str ' FR (Hz) Good vs. Bad'],...
            ['Pyr_FRProfileGoodVsBad' str],...
            pathAnal,[1 2.5],[{'Good'} {''} {'Bad'} {''}])
        
        plotAvgFRProfileCmp(timeStepRun,...
            avgFRProfileNorm(idxC == idxCInd(i),:),avgFRProfileNormBad(idxCBad == idxCInd(i),:),...
            [str ' Norm Good vs. Bad'],...
            ['Pyr_FRProfileNormGoodVsBad' str],...
            pathAnal,[0.2 0.4],[{'Good'} {''} {'Bad'} {''}])
        
        plotBoxPlot(FRProfileMean.percChange0to1VsBL(idxC == idxCInd(i))',...
            FRProfileMeanBad.percChange0to1VsBL(idxCBad == idxCInd(i))',...
            [str ' average FR change 0-1s/BL G/B'],...
            ['Pyr_FRChange' str '0to1-BLGoodBadBox'],...
            pathAnal,[-1 4],FRProfileMeanStatGoodBad.pRSPercChange0to1VsBL(idxCInd(i)),...
            colorSel,[{'Good'} {'Bad'}]);
        
        plotBoxPlot(FRProfileMean.percChangeBefRunVsBL(idxC == idxCInd(i))',...
            FRProfileMeanBad.percChangeBefRunVsBL(idxCBad == idxCInd(i))',...
            [str ' average FR change BefRun/BL G/B'],...
            ['Pyr_FRChange' str 'BefRun-BLGoodBadBox'],...
            pathAnal,[-1 4],FRProfileMeanStatGoodBad.pRSPercChangeBefRunVsBL(idxCInd(i)),...
            colorSel,[{'Good'} {'Bad'}]);
        
        plotBoxPlot(FRProfileMean.percChangeBefRunVs0to1(idxC == idxCInd(i))',...
            FRProfileMeanBad.percChangeBefRunVs0to1(idxCBad == idxCInd(i))',...
            [str ' average FR change BefRun/0to1s G/B'],...
            ['Pyr_FRChange' str 'BefRun-0to1GoodBadBox'],...
            pathAnal,[-1 4],FRProfileMeanStatGoodBad.pRSPercChangeBefRunVs0to1(idxCInd(i)),...
            colorSel,[{'Good'} {'Bad'}]);
        
        plotBoxPlot(FRProfileMean.percChange0to1Vs3to5(idxC == idxCInd(i))',...
            FRProfileMeanBad.percChange0to1Vs3to5(idxCBad == idxCInd(i))',...
            [str ' average FR change 0-1s/3-5s G/B'],...
            ['Pyr_FRChange' str '0to1-3to5GoodBadBox'],...
            pathAnal,[-1 4],FRProfileMeanStatGoodBad.pRSPercChange0to1Vs3to5(idxCInd(i)),...
            colorSel,[{'Good'} {'Bad'}]);
        
        plotBoxPlot(FRProfileMean.percChangeBefRunVs3to5(idxC == idxCInd(i))',...
            FRProfileMeanBad.percChangeBefRunVs3to5(idxCBad == idxCInd(i))',...
            [str ' average FR change BefRun/3-5s G/B'],...
            ['Pyr_FRChange' str 'BefRun-3to5Box'],...
            pathAnal,[-1 8],FRProfileMeanStatGoodBad.pRSPercChangeBefRunVs3to5(idxCInd(i)),...
            colorSel,[{'Good'} {'Bad'}]);
    end