function plotPyrInitFieldRecPerClu(pathAnal,idxC,nNeuWithField,timeStepRun,avgFRProfile,avgFRProfileNorm,...
    FRProfileMean,FRProfileMeanStatC,colorSel,idxCInd,appendStr)
%% recordings with fields for each cluster
% this function is called by PyrInitPeakAllRec.m

    for i = 1:length(idxCInd)
        if(i == 1)
            str = [appendStr 'Deep'];
        elseif(i == 2)
            str = [appendStr 'Sup'];
        else
            str = appendStr;
        end
        
        indCurCField = idxC == idxCInd(i) & nNeuWithField > 1;
        indCurCNoField = idxC == idxCInd(i) & nNeuWithField < 1;
        plotAvgFRProfileCmp(timeStepRun,...
            avgFRProfile(indCurCField,:),avgFRProfile(indCurCNoField,:),...
            [str ' RecFR (Hz) F vs. NoF'],...
            ['Pyr_FRProfileRecFieldNoField' str],...
            pathAnal,[1 2.5],[{'F'} {''} {'NoF'} {''}])
        
        plotAvgFRProfileCmp(timeStepRun,...
            avgFRProfileNorm(indCurCField,:),avgFRProfileNorm(indCurCNoField,:),...
            [str ' Norm RecFR F vs. NoF'],...
            ['Pyr_FRProfileNormRecFieldNoField' str],...
            pathAnal,[0.2 0.45],[{'F'} {''} {'NoF'} {''}])
        
        plotBoxPlot(FRProfileMean.percChange0to1VsBL(indCurCField)',...
            FRProfileMean.percChange0to1VsBL(indCurCNoField)',...
            [str ' average RecFR change 0-1s/BL F/NoF'],...
            ['Pyr_FRChange' str 'Rec0to1-BLFieldNoFieldBox'],...
            pathAnal,[-1 4],FRProfileMeanStatC.pRSPercChange0to1VsBLFieldVsNoField(idxCInd(i)),colorSel,[{'F'} {'NoF'}]);
        
        plotBoxPlot(FRProfileMean.percChangeBefRunVsBL(indCurCField)',...
            FRProfileMean.percChangeBefRunVsBL(indCurCNoField)',...
            [str ' average RecFR change BefRun/BL F/NoF'],...
            ['Pyr_FRChange' str 'RecBefRun-BLFieldNoFieldBox'],...
            pathAnal,[-1 4],FRProfileMeanStatC.pRSPercChangeBefRunVsBLFieldVsNoField(idxCInd(i)),colorSel,[{'F'} {'NoF'}]);
        
        plotBoxPlot(FRProfileMean.percChangeBefRunVs0to1(indCurCField)',...
            FRProfileMean.percChangeBefRunVs0to1(indCurCNoField)',...
            [str ' average RecFR change BefRun/0to1s F/NoF'],...
            ['Pyr_FRChange' str 'RecBefRun-0to1FieldNoFieldBox'],...
            pathAnal,[-1 4],FRProfileMeanStatC.pRSPercChangeBefRunVs0to1FieldVsNoField(idxCInd(i)),colorSel,[{'F'} {'NoF'}]);
        
        plotBoxPlot(FRProfileMean.percChange0to1Vs3to5(indCurCField)',...
            FRProfileMean.percChange0to1Vs3to5(indCurCNoField)',...
            [str ' average RecFR change 0-1s/3-5s F/NoF'],...
            ['Pyr_FRChange' str 'Rec0to1-3to5FieldNoFieldBox'],...
            pathAnal,[-1 4],FRProfileMeanStatC.pRSPercChange0to1Vs3to5FieldVsNoField(idxCInd(i)),colorSel,[{'F'} {'NoF'}]);
        
        plotBoxPlot(FRProfileMean.percChangeBefRunVs3to5(indCurCField)',...
            FRProfileMean.percChangeBefRunVs3to5(indCurCNoField)',...
            [str ' average RecFR change BefRun/3-5s F/NoF'],...
            ['Pyr_FRChange' str 'RecBefRun-3to5FieldNoFieldBox'],...
            pathAnal,[-1 8],FRProfileMeanStatC.pRSPercChangeBefRunVs3to5FieldVsNoField(idxCInd(i)),colorSel,[{'F'} {'NoF'}]);
    end