function behAlignedMean = accumMeanBeh(behAlignedNoCue,behAlignedAL,behAlignedPL,behAligned,task)   
% mean behavior for recordings with fields
% this function is called by PyrBehAlignedAllRec.m

    %% find recordings
    [indNonStimRecNoCueField,nonStimRecNoCueField] = intersect(behAlignedNoCue.indRecNonStim,behAligned.indRecNoCueField);
    [indNonStimRecALField,nonStimRecALField] = intersect(behAlignedAL.indRecNonStim,behAligned.indRecALField);
    [indNonStimRecPLField,nonStimRecPLField] = intersect(behAlignedPL.indRecNonStim,behAligned.indRecPLField);
    
    [indNonStimGoodRecNoCueField,nonStimGoodRecNoCueField] = intersect(behAlignedNoCue.indRecNonStimGood,behAligned.indRecNoCueField);
    [indNonStimGoodRecALField,nonStimGoodRecALField] = intersect(behAlignedAL.indRecNonStimGood,behAligned.indRecALField);
    [indNonStimGoodRecPLField,nonStimGoodRecPLField] = intersect(behAlignedPL.indRecNonStimGood,behAligned.indRecPLField);
    
    [~,nonStimBadRecNoCueField] = intersect(behAlignedNoCue.indRecNonStimBad,behAligned.indRecNoCueField);
    [~,nonStimBadRecALField] = intersect(behAlignedAL.indRecNonStimBad,behAligned.indRecALField);
    [~,nonStimBadRecPLField] = intersect(behAlignedPL.indRecNonStimBad,behAligned.indRecPLField);
    
    [~,stimRecNoCueField] = intersect(behAlignedNoCue.indRecStim,behAligned.indRecNoCueField);
    [~,stimRecALField] = intersect(behAlignedAL.indRecStim,behAligned.indRecALField);
    [~,stimRecPLField] = intersect(behAlignedPL.indRecStim,behAligned.indRecPLField);
    
    [indNonStimRecNoCueNoField,nonStimRecNoCueNoField] = intersect(behAlignedNoCue.indRecNonStim,behAligned.indRecNoCueNoField);
    [indNonStimRecALNoField,nonStimRecALNoField] = intersect(behAlignedAL.indRecNonStim,behAligned.indRecALNoField);
    [indNonStimRecPLNoField,nonStimRecPLNoField] = intersect(behAlignedPL.indRecNonStim,behAligned.indRecPLNoField);
    
    [indNonStimGoodRecNoCueNoField,nonStimGoodRecNoCueNoField] = intersect(behAlignedNoCue.indRecNonStimGood,behAligned.indRecNoCueNoField);
    [indNonStimGoodRecALNoField,nonStimGoodRecALNoField] = intersect(behAlignedAL.indRecNonStimGood,behAligned.indRecALNoField);
    [indNonStimGoodRecPLNoField,nonStimGoodRecPLNoField] = intersect(behAlignedPL.indRecNonStimGood,behAligned.indRecPLNoField);
    
    [~,nonStimBadRecNoCueNoField] = intersect(behAlignedNoCue.indRecNonStimBad,behAligned.indRecNoCueNoField);
    [~,nonStimBadRecALNoField] = intersect(behAlignedAL.indRecNonStimBad,behAligned.indRecALNoField);
    [~,nonStimBadRecPLNoField] = intersect(behAlignedPL.indRecNonStimBad,behAligned.indRecPLNoField);
    
    [~,stimRecNoCueNoField] = intersect(behAlignedNoCue.indRecStim,behAligned.indRecNoCueNoField);
    [~,stimRecALNoField] = intersect(behAlignedAL.indRecStim,behAligned.indRecALNoField);
    [~,stimRecPLNoField] = intersect(behAlignedPL.indRecStim,behAligned.indRecPLNoField);
    
    if(task == 1)
        % mean behavior for recordings with fields
        %% reward to run time, added on 9/12/2022
        behAlignedMean.meanRewardToRunNonStimPerRec = ...
            [behAlignedNoCue.meanRewardToRunNonStimPerRec;...
            behAlignedAL.meanRewardToRunNonStimPerRec;...
            behAlignedPL.meanRewardToRunNonStimPerRec];
        
        fieldTmp = [behAlignedNoCue.rewardToRunNonStimPerRec ...
            behAlignedAL.rewardToRunNonStimPerRec ...
            behAlignedPL.rewardToRunNonStimPerRec];
        behAlignedMean.rewardToRunNonStimPerRec = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.rewardToRunNonStimPerRec = [...
                behAlignedMean.rewardToRunNonStimPerRec; ...
                fieldTmp{i}'];
        end   
        
        %% start cue to run time, added on 6/9/2022
        behAlignedMean.meanStartCueToRunNonStimPerRec = ...
            [behAlignedNoCue.meanStartCueToRunNonStimPerRec;...
            behAlignedAL.meanStartCueToRunNonStimPerRec;...
            behAlignedPL.meanStartCueToRunNonStimPerRec];
        
        fieldTmp = [behAlignedNoCue.startCueToRunNonStimPerRec ...
            behAlignedAL.startCueToRunNonStimPerRec ...
            behAlignedPL.startCueToRunNonStimPerRec];
        behAlignedMean.startCueToRunNonStimPerRec = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.startCueToRunNonStimPerRec = [...
                behAlignedMean.startCueToRunNonStimPerRec; ...
                fieldTmp{i}'];
        end   
        
        %% stop time, added on 6/9/2022
        behAlignedMean.meanTotStopLenTNonStimPerRec = ...
            [behAlignedNoCue.meanTotStopLenTNonStimPerRec;...
            behAlignedAL.meanTotStopLenTNonStimPerRec;...
            behAlignedPL.meanTotStopLenTNonStimPerRec];
        
        fieldTmp = [behAlignedNoCue.totStopLenTNonStimPerRec ...
            behAlignedAL.totStopLenTNonStimPerRec ...
            behAlignedPL.totStopLenTNonStimPerRec];
        behAlignedMean.totStopLenTNonStimPerRec = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.totStopLenTNonStimPerRec = [...
                behAlignedMean.totStopLenTNonStimPerRec; ...
                fieldTmp{i}'];
        end   
        
        behAlignedMean.meanTotStopLenTPerRecField = ...
            [behAlignedNoCue.meanTotStopLenTPerRec(behAligned.indRecNoCueField)';...
            behAlignedAL.meanTotStopLenTPerRec(behAligned.indRecALField)';...
            behAlignedPL.meanTotStopLenTPerRec(behAligned.indRecPLField)'];
        
        behAlignedMean.meanTotStopLenTNonStimPerRecField = ...
            [behAlignedNoCue.meanTotStopLenTNonStimPerRec(nonStimRecNoCueField)';...
            behAlignedAL.meanTotStopLenTNonStimPerRec(nonStimRecALField);...
            behAlignedPL.meanTotStopLenTNonStimPerRec(nonStimRecPLField)];

        fieldTmp = [behAlignedNoCue.totStopLenTNonStimPerRec(indNonStimRecNoCueField) ...
            behAlignedAL.totStopLenTNonStimPerRec(indNonStimRecALField) ...
            behAlignedPL.totStopLenTNonStimPerRec(indNonStimRecPLField)];
        behAlignedMean.totStopLenTNonStimPerRecField = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.totStopLenTNonStimPerRecField = [...
                behAlignedMean.totStopLenTNonStimPerRecField; ...
                fieldTmp{i}'];
        end    
        
        behAlignedMean.meanTotStopLenTNonStimGoodPerRecField = ...
            [behAlignedNoCue.meanTotStopLenTNonStimGoodPerRec(nonStimGoodRecNoCueField);...
            behAlignedAL.meanTotStopLenTNonStimGoodPerRec(nonStimGoodRecALField);...
            behAlignedPL.meanTotStopLenTNonStimGoodPerRec(nonStimGoodRecPLField)];

        fieldTmp = [behAlignedNoCue.totStopLenTNonStimGoodPerRec(indNonStimGoodRecNoCueField) ...
            behAlignedAL.totStopLenTNonStimGoodPerRec(indNonStimGoodRecALField) ...
            behAlignedPL.totStopLenTNonStimGoodPerRec(indNonStimGoodRecPLField)];
        behAlignedMean.totStopLenTNonStimGoodPerRecField = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.totStopLenTNonStimGoodPerRecField = [...
                behAlignedMean.totStopLenTNonStimGoodPerRecField; ...
                fieldTmp{i}'];
        end    

        behAlignedMean.meanTotStopLenTNonStimBadPerRecField = ...
            [behAlignedNoCue.meanTotStopLenTNonStimBadPerRec(nonStimBadRecNoCueField);...
            behAlignedAL.meanTotStopLenTNonStimBadPerRec(nonStimBadRecALField);...
            behAlignedPL.meanTotStopLenTNonStimBadPerRec(nonStimBadRecPLField)];

        %% lick
        behAlignedMean.meanLickPerRecField = ...
            [behAlignedNoCue.meanLickPerRec(behAligned.indRecNoCueField,:);...
            behAlignedAL.meanLickPerRec(behAligned.indRecALField,:);...
            behAlignedPL.meanLickPerRec(behAligned.indRecPLField,:)];
        
        behAlignedMean.meanLickNonStimPerRecField = ...
            [behAlignedNoCue.meanLickNonStimPerRec(nonStimRecNoCueField,:);...
            behAlignedAL.meanLickNonStimPerRec(nonStimRecALField,:);...
            behAlignedPL.meanLickNonStimPerRec(nonStimRecPLField,:)];

        fieldTmp = [behAlignedNoCue.lickTraceNonStimPerRec(indNonStimRecNoCueField) ...
            behAlignedAL.lickTraceNonStimPerRec(indNonStimRecALField) ...
            behAlignedPL.lickTraceNonStimPerRec(indNonStimRecPLField)];
        behAlignedMean.lickTraceNonStimPerRecField = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.lickTraceNonStimPerRecField = [...
                behAlignedMean.lickTraceNonStimPerRecField; ...
                fieldTmp{i}];
        end    
        
        behAlignedMean.meanLickNonStimGoodPerRecField = ...
            [behAlignedNoCue.meanLickNonStimGoodPerRec(nonStimGoodRecNoCueField,:);...
            behAlignedAL.meanLickNonStimGoodPerRec(nonStimGoodRecALField,:);...
            behAlignedPL.meanLickNonStimGoodPerRec(nonStimGoodRecPLField,:)];

        fieldTmp = [behAlignedNoCue.lickTraceNonStimGoodPerRec(indNonStimGoodRecNoCueField) ...
            behAlignedAL.lickTraceNonStimGoodPerRec(indNonStimGoodRecALField) ...
            behAlignedPL.lickTraceNonStimGoodPerRec(indNonStimGoodRecPLField)];
        behAlignedMean.lickTraceNonStimGoodPerRecField = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.lickTraceNonStimGoodPerRecField = [...
                behAlignedMean.lickTraceNonStimGoodPerRecField; ...
                fieldTmp{i}];
        end    

        behAlignedMean.meanLickNonStimBadPerRecField = ...
            [behAlignedNoCue.meanLickNonStimBadPerRec(nonStimBadRecNoCueField,:);...
            behAlignedAL.meanLickNonStimBadPerRec(nonStimBadRecALField,:);...
            behAlignedPL.meanLickNonStimBadPerRec(nonStimBadRecPLField,:)];

        behAlignedMean.meanLickStimPerRecField = ...
            [behAlignedNoCue.meanLickStimPerRec(stimRecNoCueField,:);...
            behAlignedAL.meanLickStimPerRec(stimRecALField,:);...
            behAlignedPL.meanLickStimPerRec(stimRecPLField,:)];

        %% speed
        behAlignedMean.meanSpeedPerRecField = ...
            [behAlignedNoCue.meanSpeedPerRec(behAligned.indRecNoCueField,:);...
            behAlignedAL.meanSpeedPerRec(behAligned.indRecALField,:);...
            behAlignedPL.meanSpeedPerRec(behAligned.indRecPLField,:)];

        behAlignedMean.meanSpeedNonStimPerRecField = ...
            [behAlignedNoCue.meanSpeedNonStimPerRec(nonStimRecNoCueField,:);...
            behAlignedAL.meanSpeedNonStimPerRec(nonStimRecALField,:);...
            behAlignedPL.meanSpeedNonStimPerRec(nonStimRecPLField,:)];

        fieldTmp = [behAlignedNoCue.speedTraceNonStimPerRec(indNonStimRecNoCueField) ...
            behAlignedAL.speedTraceNonStimPerRec(indNonStimRecALField) ...
            behAlignedPL.speedTraceNonStimPerRec(indNonStimRecPLField)];
        behAlignedMean.speedTraceNonStimPerRecField = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.speedTraceNonStimPerRecField = [...
                behAlignedMean.speedTraceNonStimPerRecField; ...
                fieldTmp{i}];
        end
        
        behAlignedMean.meanSpeedNonStimGoodPerRecField = ...
            [behAlignedNoCue.meanSpeedNonStimGoodPerRec(nonStimGoodRecNoCueField,:);...
            behAlignedAL.meanSpeedNonStimGoodPerRec(nonStimGoodRecALField,:);...
            behAlignedPL.meanSpeedNonStimGoodPerRec(nonStimGoodRecPLField,:)];

        fieldTmp = [behAlignedNoCue.speedTraceNonStimGoodPerRec(indNonStimGoodRecNoCueField) ...
            behAlignedAL.speedTraceNonStimGoodPerRec(indNonStimGoodRecALField) ...
            behAlignedPL.speedTraceNonStimGoodPerRec(indNonStimGoodRecPLField)];
        behAlignedMean.speedTraceNonStimGoodPerRecField = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.speedTraceNonStimGoodPerRecField = [...
                behAlignedMean.speedTraceNonStimGoodPerRecField; ...
                fieldTmp{i}];
        end

        behAlignedMean.meanSpeedNonStimBadPerRecField = ...
            [behAlignedNoCue.meanSpeedNonStimBadPerRec(nonStimBadRecNoCueField,:);...
            behAlignedAL.meanSpeedNonStimBadPerRec(nonStimBadRecALField,:);...
            behAlignedPL.meanSpeedNonStimBadPerRec(nonStimBadRecPLField,:)];

        behAlignedMean.meanSpeedStimPerRecField = ...
            [behAlignedNoCue.meanSpeedStimPerRec(stimRecNoCueField,:);...
            behAlignedAL.meanSpeedStimPerRec(stimRecALField,:);...
            behAlignedPL.meanSpeedStimPerRec(stimRecPLField,:)];

        % mean behavior for recordings without fields
        %% stop time, added on 6/9/2022
        behAlignedMean.meanTotStopLenTPerRecNoField = ...
            [behAlignedNoCue.meanTotStopLenTPerRec(behAligned.indRecNoCueNoField)';...
            behAlignedAL.meanTotStopLenTPerRec(behAligned.indRecALNoField)';...
            behAlignedPL.meanTotStopLenTPerRec(behAligned.indRecPLNoField)'];
        
        behAlignedMean.meanTotStopLenTNonStimPerRecNoField = ...
            [behAlignedNoCue.meanTotStopLenTNonStimPerRec(nonStimRecNoCueNoField);...
            behAlignedAL.meanTotStopLenTNonStimPerRec(nonStimRecALNoField);...
            behAlignedPL.meanTotStopLenTNonStimPerRec(nonStimRecPLNoField)];

        fieldTmp = [behAlignedNoCue.totStopLenTNonStimPerRec(indNonStimRecNoCueNoField) ...
            behAlignedAL.totStopLenTNonStimPerRec(indNonStimRecALNoField) ...
            behAlignedPL.totStopLenTNonStimPerRec(indNonStimRecPLNoField)];
        behAlignedMean.totStopLenTNonStimPerRecNoField = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.totStopLenTNonStimPerRecNoField = [...
                behAlignedMean.totStopLenTNonStimPerRecNoField; ...
                fieldTmp{i}'];
        end    
        
        behAlignedMean.meanTotStopLenTNonStimGoodPerRecNoField = ...
            [behAlignedNoCue.meanTotStopLenTNonStimGoodPerRec(nonStimGoodRecNoCueNoField);...
            behAlignedAL.meanTotStopLenTNonStimGoodPerRec(nonStimGoodRecALNoField);...
            behAlignedPL.meanTotStopLenTNonStimGoodPerRec(nonStimGoodRecPLNoField)];

        fieldTmp = [behAlignedNoCue.totStopLenTNonStimGoodPerRec(indNonStimGoodRecNoCueNoField) ...
            behAlignedAL.totStopLenTNonStimGoodPerRec(indNonStimGoodRecALNoField) ...
            behAlignedPL.totStopLenTNonStimGoodPerRec(indNonStimGoodRecPLNoField)];
        behAlignedMean.totStopLenTNonStimGoodPerRecNoField = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.totStopLenTNonStimGoodPerRecNoField = [...
                behAlignedMean.totStopLenTNonStimGoodPerRecNoField; ...
                fieldTmp{i}'];
        end    

        behAlignedMean.meanTotStopLenTNonStimBadPerRecNoField = ...
            [behAlignedNoCue.meanTotStopLenTNonStimBadPerRec(nonStimBadRecNoCueNoField);...
            behAlignedAL.meanTotStopLenTNonStimBadPerRec(nonStimBadRecALNoField);...
            behAlignedPL.meanTotStopLenTNonStimBadPerRec(nonStimBadRecPLNoField)];

        %% lick
        behAlignedMean.meanLickPerRecNoField = ...
            [behAlignedNoCue.meanLickPerRec(behAligned.indRecNoCueNoField,:);...
            behAlignedAL.meanLickPerRec(behAligned.indRecALNoField,:);...
            behAlignedPL.meanLickPerRec(behAligned.indRecPLNoField,:)];

        behAlignedMean.meanLickNonStimPerRecNoField = ...
            [behAlignedNoCue.meanLickNonStimPerRec(nonStimRecNoCueNoField,:);...
            behAlignedAL.meanLickNonStimPerRec(nonStimRecALNoField,:);...
            behAlignedPL.meanLickNonStimPerRec(nonStimRecPLNoField,:)];

        noFieldTmp = [behAlignedNoCue.lickTraceNonStimPerRec(indNonStimRecNoCueNoField) ...
            behAlignedAL.lickTraceNonStimPerRec(indNonStimRecALNoField) ...
            behAlignedPL.lickTraceNonStimPerRec(indNonStimRecPLNoField)];
        behAlignedMean.lickTraceNonStimPerRecNoField = [];
        for i = 1:length(noFieldTmp)
            behAlignedMean.lickTraceNonStimPerRecNoField = [...
                behAlignedMean.lickTraceNonStimPerRecNoField; ...
                noFieldTmp{i}];
        end

        behAlignedMean.meanLickNonStimGoodPerRecNoField = ...
            [behAlignedNoCue.meanLickNonStimGoodPerRec(nonStimGoodRecNoCueNoField,:);...
            behAlignedAL.meanLickNonStimGoodPerRec(nonStimGoodRecALNoField,:);...
            behAlignedPL.meanLickNonStimGoodPerRec(nonStimGoodRecPLNoField,:)];

        noFieldTmp = [behAlignedNoCue.lickTraceNonStimGoodPerRec(indNonStimGoodRecNoCueNoField) ...
            behAlignedAL.lickTraceNonStimGoodPerRec(indNonStimGoodRecALNoField) ...
            behAlignedPL.lickTraceNonStimGoodPerRec(indNonStimGoodRecPLNoField)];
        behAlignedMean.lickTraceNonStimGoodPerRecNoField = [];
        for i = 1:length(noFieldTmp)
            behAlignedMean.lickTraceNonStimGoodPerRecNoField = [...
                behAlignedMean.lickTraceNonStimGoodPerRecNoField; ...
                noFieldTmp{i}];
        end

        behAlignedMean.meanLickNonStimBadPerRecNoField = ...
            [behAlignedNoCue.meanLickNonStimBadPerRec(nonStimBadRecNoCueNoField,:);...
            behAlignedAL.meanLickNonStimBadPerRec(nonStimBadRecALNoField,:);...
            behAlignedPL.meanLickNonStimBadPerRec(nonStimBadRecPLNoField,:)];

        behAlignedMean.meanLickStimPerRecNoField = ...
            [behAlignedNoCue.meanLickStimPerRec(stimRecNoCueNoField,:);...
            behAlignedAL.meanLickStimPerRec(stimRecALNoField,:);...
            behAlignedPL.meanLickStimPerRec(stimRecPLNoField,:)];

        %% speed
        behAlignedMean.meanSpeedPerRecNoField = ...
            [behAlignedNoCue.meanSpeedPerRec(behAligned.indRecNoCueNoField,:);...
            behAlignedAL.meanSpeedPerRec(behAligned.indRecALNoField,:);...
            behAlignedPL.meanSpeedPerRec(behAligned.indRecPLNoField,:)];

        behAlignedMean.meanSpeedNonStimPerRecNoField = ...
            [behAlignedNoCue.meanSpeedNonStimPerRec(nonStimRecNoCueNoField,:);...
            behAlignedAL.meanSpeedNonStimPerRec(nonStimRecALNoField,:);...
            behAlignedPL.meanSpeedNonStimPerRec(nonStimRecPLNoField,:)];

        noFieldTmp = [behAlignedNoCue.speedTraceNonStimPerRec(indNonStimRecNoCueNoField) ...
            behAlignedAL.speedTraceNonStimPerRec(indNonStimRecALNoField) ...
            behAlignedPL.speedTraceNonStimPerRec(indNonStimRecPLNoField)];
        behAlignedMean.speedTraceNonStimPerRecNoField = [];
        for i = 1:length(noFieldTmp)
            behAlignedMean.speedTraceNonStimPerRecNoField = [...
                behAlignedMean.speedTraceNonStimPerRecNoField; ...
                noFieldTmp{i}];
        end
        
        behAlignedMean.meanSpeedNonStimGoodPerRecNoField = ...
            [behAlignedNoCue.meanSpeedNonStimGoodPerRec(nonStimGoodRecNoCueNoField,:);...
            behAlignedAL.meanSpeedNonStimGoodPerRec(nonStimGoodRecALNoField,:);...
            behAlignedPL.meanSpeedNonStimGoodPerRec(nonStimGoodRecPLNoField,:)];

        noFieldTmp = [behAlignedNoCue.speedTraceNonStimGoodPerRec(indNonStimGoodRecNoCueNoField) ...
            behAlignedAL.speedTraceNonStimGoodPerRec(indNonStimGoodRecALNoField) ...
            behAlignedPL.speedTraceNonStimGoodPerRec(indNonStimGoodRecPLNoField)];
        behAlignedMean.speedTraceNonStimGoodPerRecNoField = [];
        for i = 1:length(noFieldTmp)
            behAlignedMean.speedTraceNonStimGoodPerRecNoField = [...
                behAlignedMean.speedTraceNonStimGoodPerRecNoField; ...
                noFieldTmp{i}];
        end

        behAlignedMean.meanSpeedNonStimBadPerRecNoField = ...
            [behAlignedNoCue.meanSpeedNonStimBadPerRec(nonStimBadRecNoCueNoField,:);...
            behAlignedAL.meanSpeedNonStimBadPerRec(nonStimBadRecALNoField,:);...
            behAlignedPL.meanSpeedNonStimBadPerRec(nonStimBadRecPLNoField,:)];

        behAlignedMean.meanSpeedStimPerRecNoField = ...
            [behAlignedNoCue.meanSpeedStimPerRec(stimRecNoCueNoField,:);...
            behAlignedAL.meanSpeedStimPerRec(stimRecALNoField,:);...
            behAlignedPL.meanSpeedStimPerRec(stimRecPLNoField,:)];
    elseif(task == 2)
        % mean behavior for recordings with fields
        
        %% reward to run time, added on 9/12/2022
        behAlignedMean.meanRewardToRunNonStimPerRec = ...
            [behAlignedAL.meanRewardToRunNonStimPerRec;...
            behAlignedPL.meanRewardToRunNonStimPerRec];
        
        fieldTmp = [behAlignedAL.rewardToRunNonStimPerRec ...
            behAlignedPL.rewardToRunNonStimPerRec];
        behAlignedMean.rewardToRunNonStimPerRec = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.rewardToRunNonStimPerRec = [...
                behAlignedMean.rewardToRunNonStimPerRec; ...
                fieldTmp{i}'];
        end   
        
        %% start cue to run time, added on 6/9/2022
        behAlignedMean.meanStartCueToRunNonStimPerRec = ...
            [behAlignedAL.meanStartCueToRunNonStimPerRec;...
            behAlignedPL.meanStartCueToRunNonStimPerRec];
        
        fieldTmp = [behAlignedAL.startCueToRunNonStimPerRec ...
            behAlignedPL.startCueToRunNonStimPerRec];
        behAlignedMean.startCueToRunNonStimPerRec = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.startCueToRunNonStimPerRec = [...
                behAlignedMean.startCueToRunNonStimPerRec; ...
                fieldTmp{i}'];
        end   
        
        %% stop time, added on 6/9/2022
        behAlignedMean.meanTotStopLenTNonStimPerRec = ...
            [behAlignedAL.meanTotStopLenTNonStimPerRec;...
            behAlignedPL.meanTotStopLenTNonStimPerRec];
        
        fieldTmp = [...
            behAlignedAL.totStopLenTNonStimPerRec ...
            behAlignedPL.totStopLenTNonStimPerRec];
        behAlignedMean.totStopLenTNonStimPerRec = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.totStopLenTNonStimPerRec = [...
                behAlignedMean.totStopLenTNonStimPerRec; ...
                fieldTmp{i}'];
        end   
        
        behAlignedMean.meanTotStopLenTPerRecField = ...
            [behAlignedAL.meanTotStopLenTPerRec(behAligned.indRecALField)';...
            behAlignedPL.meanTotStopLenTPerRec(behAligned.indRecPLField)'];
        
        behAlignedMean.meanTotStopLenTNonStimPerRecField = ...
            [behAlignedAL.meanTotStopLenTNonStimPerRec(nonStimRecALField);...
            behAlignedPL.meanTotStopLenTNonStimPerRec(nonStimRecPLField)];

        fieldTmp = [behAlignedAL.totStopLenTNonStimPerRec(indNonStimRecALField) ...
            behAlignedPL.totStopLenTNonStimPerRec(indNonStimRecPLField)];
        behAlignedMean.totStopLenTNonStimPerRecField = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.totStopLenTNonStimPerRecField = [...
                behAlignedMean.totStopLenTNonStimPerRecField; ...
                fieldTmp{i}'];
        end    
        
        behAlignedMean.meanTotStopLenTNonStimGoodPerRecField = ...
            [behAlignedAL.meanTotStopLenTNonStimGoodPerRec(nonStimGoodRecALField);...
            behAlignedPL.meanTotStopLenTNonStimGoodPerRec(nonStimGoodRecPLField)];

        fieldTmp = [behAlignedAL.totStopLenTNonStimGoodPerRec(indNonStimGoodRecALField) ...
            behAlignedPL.totStopLenTNonStimGoodPerRec(indNonStimGoodRecPLField)];
        behAlignedMean.totStopLenTNonStimGoodPerRecField = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.totStopLenTNonStimGoodPerRecField = [...
                behAlignedMean.totStopLenTNonStimGoodPerRecField; ...
                fieldTmp{i}'];
        end    

        behAlignedMean.meanTotStopLenTNonStimBadPerRecField = ...
            [behAlignedAL.meanTotStopLenTNonStimBadPerRec(nonStimBadRecALField);...
            behAlignedPL.meanTotStopLenTNonStimBadPerRec(nonStimBadRecPLField)];

        %% lick
        behAlignedMean.meanLickPerRecField = ...
            [behAlignedAL.meanLickPerRec(behAligned.indRecALField,:);...
            behAlignedPL.meanLickPerRec(behAligned.indRecPLField,:)];

        behAlignedMean.meanLickNonStimPerRecField = ...
            [behAlignedAL.meanLickNonStimPerRec(nonStimRecALField,:);...
            behAlignedPL.meanLickNonStimPerRec(nonStimRecPLField,:)];

        fieldTmp = [behAlignedAL.lickTraceNonStimPerRec(indNonStimRecALField) ...
            behAlignedPL.lickTraceNonStimPerRec(indNonStimRecPLField)];
        behAlignedMean.lickTraceNonStimPerRecField = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.lickTraceNonStimPerRecField = [...
                behAlignedMean.lickTraceNonStimPerRecField; ...
                fieldTmp{i}];
        end    
        
        behAlignedMean.meanLickNonStimGoodPerRecField = ...
            [behAlignedAL.meanLickNonStimGoodPerRec(nonStimGoodRecALField,:);...
            behAlignedPL.meanLickNonStimGoodPerRec(nonStimGoodRecPLField,:)];

        fieldTmp = [behAlignedAL.lickTraceNonStimGoodPerRec(indNonStimGoodRecALField) ...
            behAlignedPL.lickTraceNonStimGoodPerRec(indNonStimGoodRecPLField)];
        behAlignedMean.lickTraceNonStimGoodPerRecField = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.lickTraceNonStimGoodPerRecField = [...
                behAlignedMean.lickTraceNonStimGoodPerRecField; ...
                fieldTmp{i}];
        end    

        behAlignedMean.meanLickNonStimBadPerRecField = ...
            [behAlignedAL.meanLickNonStimBadPerRec(nonStimBadRecALField,:);...
            behAlignedPL.meanLickNonStimBadPerRec(nonStimBadRecPLField,:)];

        behAlignedMean.meanLickStimPerRecField = ...
            [behAlignedAL.meanLickStimPerRec(stimRecALField,:);...
            behAlignedPL.meanLickStimPerRec(stimRecPLField,:)];

        %% speed
        behAlignedMean.meanSpeedPerRecField = ...
            [behAlignedAL.meanSpeedPerRec(behAligned.indRecALField,:);...
            behAlignedPL.meanSpeedPerRec(behAligned.indRecPLField,:)];

        behAlignedMean.meanSpeedNonStimPerRecField = ...
            [behAlignedAL.meanSpeedNonStimPerRec(nonStimRecALField,:);...
            behAlignedPL.meanSpeedNonStimPerRec(nonStimRecPLField,:)];

        fieldTmp = [behAlignedAL.speedTraceNonStimPerRec(indNonStimRecALField) ...
            behAlignedPL.speedTraceNonStimPerRec(indNonStimRecPLField)];
        behAlignedMean.speedTraceNonStimPerRecField = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.speedTraceNonStimPerRecField = [...
                behAlignedMean.speedTraceNonStimPerRecField; ...
                fieldTmp{i}];
        end
        
        behAlignedMean.meanSpeedNonStimGoodPerRecField = ...
            [behAlignedAL.meanSpeedNonStimGoodPerRec(nonStimGoodRecALField,:);...
            behAlignedPL.meanSpeedNonStimGoodPerRec(nonStimGoodRecPLField,:)];

        fieldTmp = [behAlignedAL.speedTraceNonStimGoodPerRec(indNonStimGoodRecALField) ...
            behAlignedPL.speedTraceNonStimGoodPerRec(indNonStimGoodRecPLField)];
        behAlignedMean.speedTraceNonStimGoodPerRecField = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.speedTraceNonStimGoodPerRecField = [...
                behAlignedMean.speedTraceNonStimGoodPerRecField; ...
                fieldTmp{i}];
        end

        behAlignedMean.meanSpeedNonStimBadPerRecField = ...
            [behAlignedAL.meanSpeedNonStimBadPerRec(nonStimBadRecALField,:);...
            behAlignedPL.meanSpeedNonStimBadPerRec(nonStimBadRecPLField,:)];

        behAlignedMean.meanSpeedStimPerRecField = ...
            [behAlignedAL.meanSpeedStimPerRec(stimRecALField,:);...
            behAlignedPL.meanSpeedStimPerRec(stimRecPLField,:)];

        % mean behavior for recordings without fields
        %% stop time, added on 6/9/2022
        behAlignedMean.meanTotStopLenTPerRecNoField = ...
            [behAlignedAL.meanTotStopLenTPerRec(behAligned.indRecALNoField)';...
            behAlignedPL.meanTotStopLenTPerRec(behAligned.indRecPLNoField)'];
        
        behAlignedMean.meanTotStopLenTNonStimPerRecNoField = ...
            [behAlignedAL.meanTotStopLenTNonStimPerRec(nonStimRecALNoField);...
            behAlignedPL.meanTotStopLenTNonStimPerRec(nonStimRecPLNoField)];

        fieldTmp = [behAlignedAL.totStopLenTNonStimPerRec(indNonStimRecALNoField) ...
            behAlignedPL.totStopLenTNonStimPerRec(indNonStimRecPLNoField)];
        behAlignedMean.totStopLenTNonStimPerRecNoField = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.totStopLenTNonStimPerRecNoField = [...
                behAlignedMean.totStopLenTNonStimPerRecNoField; ...
                fieldTmp{i}'];
        end    
        
        behAlignedMean.meanTotStopLenTNonStimGoodPerRecNoField = ...
            [behAlignedAL.meanTotStopLenTNonStimGoodPerRec(nonStimGoodRecALNoField);...
            behAlignedPL.meanTotStopLenTNonStimGoodPerRec(nonStimGoodRecPLNoField)];

        fieldTmp = [behAlignedAL.totStopLenTNonStimGoodPerRec(indNonStimGoodRecALNoField) ...
            behAlignedPL.totStopLenTNonStimGoodPerRec(indNonStimGoodRecPLNoField)];
        behAlignedMean.totStopLenTNonStimGoodPerRecNoField = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.totStopLenTNonStimGoodPerRecNoField = [...
                behAlignedMean.totStopLenTNonStimGoodPerRecNoField; ...
                fieldTmp{i}'];
        end    

        behAlignedMean.meanTotStopLenTNonStimBadPerRecNoField = ...
            [behAlignedAL.meanTotStopLenTNonStimBadPerRec(nonStimBadRecALNoField);...
            behAlignedPL.meanTotStopLenTNonStimBadPerRec(nonStimBadRecPLNoField)];

        %% lick
        behAlignedMean.meanLickPerRecNoField = ...
            [behAlignedAL.meanLickPerRec(behAligned.indRecALNoField,:);...
            behAlignedPL.meanLickPerRec(behAligned.indRecPLNoField,:)];

        behAlignedMean.meanLickNonStimPerRecNoField = ...
            [behAlignedAL.meanLickNonStimPerRec(nonStimRecALNoField,:);...
            behAlignedPL.meanLickNonStimPerRec(nonStimRecPLNoField,:)];

        noFieldTmp = [behAlignedAL.lickTraceNonStimPerRec(indNonStimRecALNoField) ...
            behAlignedPL.lickTraceNonStimPerRec(indNonStimRecPLNoField)];
        behAlignedMean.lickTraceNonStimPerRecNoField = [];
        for i = 1:length(noFieldTmp)
            behAlignedMean.lickTraceNonStimPerRecNoField = [...
                behAlignedMean.lickTraceNonStimPerRecNoField; ...
                noFieldTmp{i}];
        end
        
        behAlignedMean.meanLickNonStimGoodPerRecNoField = ...
            [behAlignedAL.meanLickNonStimGoodPerRec(nonStimGoodRecALNoField,:);...
            behAlignedPL.meanLickNonStimGoodPerRec(nonStimGoodRecPLNoField,:)];

        noFieldTmp = [behAlignedAL.lickTraceNonStimGoodPerRec(indNonStimGoodRecALNoField) ...
            behAlignedPL.lickTraceNonStimGoodPerRec(indNonStimGoodRecPLNoField)];
        behAlignedMean.lickTraceNonStimGoodPerRecNoField = [];
        for i = 1:length(noFieldTmp)
            behAlignedMean.lickTraceNonStimGoodPerRecNoField = [...
                behAlignedMean.lickTraceNonStimGoodPerRecNoField; ...
                noFieldTmp{i}];
        end

        behAlignedMean.meanLickNonStimBadPerRecNoField = ...
            [behAlignedAL.meanLickNonStimBadPerRec(nonStimBadRecALNoField,:);...
            behAlignedPL.meanLickNonStimBadPerRec(nonStimBadRecPLNoField,:)];

        behAlignedMean.meanLickStimPerRecNoField = ...
            [behAlignedAL.meanLickStimPerRec(stimRecALNoField,:);...
            behAlignedPL.meanLickStimPerRec(stimRecPLNoField,:)];

        %% speed
        behAlignedMean.meanSpeedPerRecNoField = ...
            [behAlignedAL.meanSpeedPerRec(behAligned.indRecALNoField,:);...
            behAlignedPL.meanSpeedPerRec(behAligned.indRecPLNoField,:)];

        behAlignedMean.meanSpeedNonStimPerRecNoField = ...
            [behAlignedAL.meanSpeedNonStimPerRec(nonStimRecALNoField,:);...
            behAlignedPL.meanSpeedNonStimPerRec(nonStimRecPLNoField,:)];

        noFieldTmp = [behAlignedAL.speedTraceNonStimPerRec(indNonStimRecALNoField) ...
            behAlignedPL.speedTraceNonStimPerRec(indNonStimRecPLNoField)];
        behAlignedMean.speedTraceNonStimPerRecNoField = [];
        for i = 1:length(noFieldTmp)
            behAlignedMean.speedTraceNonStimPerRecNoField = [...
                behAlignedMean.speedTraceNonStimPerRecNoField; ...
                noFieldTmp{i}];
        end
        
        behAlignedMean.meanSpeedNonStimGoodPerRecNoField = ...
            [behAlignedAL.meanSpeedNonStimGoodPerRec(nonStimGoodRecALNoField,:);...
            behAlignedPL.meanSpeedNonStimGoodPerRec(nonStimGoodRecPLNoField,:)];

        noFieldTmp = [behAlignedAL.speedTraceNonStimGoodPerRec(indNonStimGoodRecALNoField) ...
            behAlignedPL.speedTraceNonStimGoodPerRec(indNonStimGoodRecPLNoField)];
        behAlignedMean.speedTraceNonStimGoodPerRecNoField = [];
        for i = 1:length(noFieldTmp)
            behAlignedMean.speedTraceNonStimGoodPerRecNoField = [...
                behAlignedMean.speedTraceNonStimGoodPerRecNoField; ...
                noFieldTmp{i}];
        end

        behAlignedMean.meanSpeedNonStimBadPerRecNoField = ...
            [behAlignedAL.meanSpeedNonStimBadPerRec(nonStimBadRecALNoField,:);...
            behAlignedPL.meanSpeedNonStimBadPerRec(nonStimBadRecPLNoField,:)];

        behAlignedMean.meanSpeedStimPerRecNoField = ...
            [behAlignedAL.meanSpeedStimPerRec(stimRecALNoField,:);...
            behAlignedPL.meanSpeedStimPerRec(stimRecPLNoField,:)];
    elseif(task == 3)
        % mean behavior for recordings with fields
        
        %% reward to run time, added on 9/12/2022
        behAlignedMean.meanRewardToRunNonStimPerRec = ...
            behAlignedAL.meanRewardToRunNonStimPerRec;
        
        fieldTmp = behAlignedAL.rewardToRunNonStimPerRec;
        behAlignedMean.rewardToRunNonStimPerRec = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.rewardToRunNonStimPerRec = [...
                behAlignedMean.rewardToRunNonStimPerRec; ...
                fieldTmp{i}'];
        end
        
        %% start cue to run time, added on 6/9/2022
        behAlignedMean.meanStartCueToRunNonStimPerRec = ...
            behAlignedAL.meanStartCueToRunNonStimPerRec;
        
        fieldTmp = behAlignedAL.startCueToRunNonStimPerRec;
        behAlignedMean.startCueToRunNonStimPerRec = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.startCueToRunNonStimPerRec = [...
                behAlignedMean.startCueToRunNonStimPerRec; ...
                fieldTmp{i}'];
        end   
        
        %% stop time, added on 6/9/2022
        behAlignedMean.meanTotStopLenTNonStimPerRec = ...
            behAlignedAL.meanTotStopLenTNonStimPerRec;
        
        fieldTmp = behAlignedAL.totStopLenTNonStimPerRec;
        behAlignedMean.totStopLenTNonStimPerRec = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.totStopLenTNonStimPerRec = [...
                behAlignedMean.totStopLenTNonStimPerRec; ...
                fieldTmp{i}'];
        end  
        
        behAlignedMean.meanTotStopLenTPerRecField = ...
            behAlignedAL.meanTotStopLenTPerRec(behAligned.indRecALField)';
        
        behAlignedMean.meanTotStopLenTNonStimPerRecField = ...
            behAlignedAL.meanTotStopLenTNonStimPerRec(nonStimRecALField);

        fieldTmp = behAlignedAL.totStopLenTNonStimPerRec(indNonStimRecALField);
        behAlignedMean.totStopLenTNonStimPerRecField = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.totStopLenTNonStimPerRecField = [...
                behAlignedMean.totStopLenTNonStimPerRecField; ...
                fieldTmp{i}'];
        end    
        
        behAlignedMean.meanTotStopLenTNonStimGoodPerRecField = ...
            behAlignedAL.meanTotStopLenTNonStimGoodPerRec(nonStimGoodRecALField);

        fieldTmp = behAlignedAL.totStopLenTNonStimGoodPerRec(indNonStimGoodRecALField);
        behAlignedMean.totStopLenTNonStimGoodPerRecField = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.totStopLenTNonStimGoodPerRecField = [...
                behAlignedMean.totStopLenTNonStimGoodPerRecField; ...
                fieldTmp{i}'];
        end    

        behAlignedMean.meanTotStopLenTNonStimBadPerRecField = ...
            behAlignedAL.meanTotStopLenTNonStimBadPerRec(nonStimBadRecALField);

        %% lick
        behAlignedMean.meanLickPerRecField = ...
            behAlignedAL.meanLickPerRec(behAligned.indRecALField,:);

        behAlignedMean.meanLickNonStimPerRecField = ...
            behAlignedAL.meanLickNonStimPerRec(nonStimRecALField,:);

        fieldTmp = behAlignedAL.lickTraceNonStimPerRec(indNonStimRecALField);
        behAlignedMean.lickTraceNonStimPerRecField = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.lickTraceNonStimPerRecField = [...
                behAlignedMean.lickTraceNonStimPerRecField; ...
                fieldTmp{i}];
        end
        
        behAlignedMean.meanLickNonStimGoodPerRecField = ...
            behAlignedAL.meanLickNonStimGoodPerRec(nonStimGoodRecALField,:);

        fieldTmp = behAlignedAL.lickTraceNonStimGoodPerRec(indNonStimGoodRecALField);
        behAlignedMean.lickTraceNonStimGoodPerRecField = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.lickTraceNonStimGoodPerRecField = [...
                behAlignedMean.lickTraceNonStimGoodPerRecField; ...
                fieldTmp{i}];
        end    

        behAlignedMean.meanLickNonStimBadPerRecField = ...
            behAlignedAL.meanLickNonStimBadPerRec(nonStimBadRecALField,:);

        behAlignedMean.meanLickStimPerRecField = ...
            behAlignedAL.meanLickStimPerRec(stimRecALField,:);

        %% speed
        behAlignedMean.meanSpeedPerRecField = ...
            behAlignedAL.meanSpeedPerRec(behAligned.indRecALField,:);

        behAlignedMean.meanSpeedNonStimPerRecField = ...
            behAlignedAL.meanSpeedNonStimPerRec(nonStimRecALField,:);

        fieldTmp = behAlignedAL.speedTraceNonStimPerRec(indNonStimRecALField);
        behAlignedMean.speedTraceNonStimPerRecField = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.speedTraceNonStimPerRecField = [...
                behAlignedMean.speedTraceNonStimPerRecField; ...
                fieldTmp{i}];
        end
        
        behAlignedMean.meanSpeedNonStimGoodPerRecField = ...
            behAlignedAL.meanSpeedNonStimGoodPerRec(nonStimGoodRecALField,:);

        fieldTmp = behAlignedAL.speedTraceNonStimGoodPerRec(indNonStimGoodRecALField);
        behAlignedMean.speedTraceNonStimGoodPerRecField = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.speedTraceNonStimGoodPerRecField = [...
                behAlignedMean.speedTraceNonStimGoodPerRecField; ...
                fieldTmp{i}];
        end

        behAlignedMean.meanSpeedNonStimBadPerRecField = ...
            behAlignedAL.meanSpeedNonStimBadPerRec(nonStimBadRecALField,:);

        behAlignedMean.meanSpeedStimPerRecField = ...
            behAlignedAL.meanSpeedStimPerRec(stimRecALField,:);

        % mean behavior for recordings without fields
        %% stop time, added on 6/9/2022
        behAlignedMean.meanTotStopLenTPerRecNoField = ...
            behAlignedAL.meanTotStopLenTPerRec(behAligned.indRecALNoField)';
        
        behAlignedMean.meanTotStopLenTNonStimPerRecNoField = ...
            behAlignedAL.meanTotStopLenTNonStimPerRec(nonStimRecALNoField);

        fieldTmp = behAlignedAL.totStopLenTNonStimPerRec(indNonStimRecALNoField);
        behAlignedMean.totStopLenTNonStimPerRecNoField = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.totStopLenTNonStimPerRecNoField = [...
                behAlignedMean.totStopLenTNonStimPerRecNoField; ...
                fieldTmp{i}'];
        end    
        
        behAlignedMean.meanTotStopLenTNonStimGoodPerRecNoField = ...
            behAlignedAL.meanTotStopLenTNonStimGoodPerRec(nonStimGoodRecALNoField);

        fieldTmp = behAlignedAL.totStopLenTNonStimGoodPerRec(indNonStimGoodRecALNoField);
        behAlignedMean.totStopLenTNonStimGoodPerRecNoField = [];
        for i = 1:length(fieldTmp)
            behAlignedMean.totStopLenTNonStimGoodPerRecNoField = [...
                behAlignedMean.totStopLenTNonStimGoodPerRecNoField; ...
                fieldTmp{i}'];
        end    

        behAlignedMean.meanTotStopLenTNonStimBadPerRecNoField = ...
            behAlignedAL.meanTotStopLenTNonStimBadPerRec(nonStimBadRecALNoField);

        %% lick
        behAlignedMean.meanLickPerRecNoField = ...
            behAlignedAL.meanLickPerRec(behAligned.indRecALNoField,:);

        behAlignedMean.meanLickNonStimPerRecNoField = ...
            behAlignedAL.meanLickNonStimPerRec(nonStimRecALNoField,:);

        noFieldTmp = behAlignedAL.lickTraceNonStimPerRec(indNonStimRecALNoField);
        behAlignedMean.lickTraceNonStimPerRecNoField = [];
        for i = 1:length(noFieldTmp)
            behAlignedMean.lickTraceNonStimPerRecNoField = [...
                behAlignedMean.lickTraceNonStimPerRecNoField; ...
                noFieldTmp{i}];
        end
        
        behAlignedMean.meanLickNonStimGoodPerRecNoField = ...
            behAlignedAL.meanLickNonStimGoodPerRec(nonStimGoodRecALNoField,:);

        noFieldTmp = behAlignedAL.lickTraceNonStimGoodPerRec(indNonStimGoodRecALNoField);
        behAlignedMean.lickTraceNonStimGoodPerRecNoField = [];
        for i = 1:length(noFieldTmp)
            behAlignedMean.lickTraceNonStimGoodPerRecNoField = [...
                behAlignedMean.lickTraceNonStimGoodPerRecNoField; ...
                noFieldTmp{i}];
        end

        behAlignedMean.meanLickNonStimBadPerRecNoField = ...
            behAlignedAL.meanLickNonStimBadPerRec(nonStimBadRecALNoField,:);

        behAlignedMean.meanLickStimPerRecNoField = ...
            behAlignedAL.meanLickStimPerRec(stimRecALNoField,:);

        %% speed
        behAlignedMean.meanSpeedPerRecNoField = ...
            behAlignedAL.meanSpeedPerRec(behAligned.indRecALNoField,:);

        behAlignedMean.meanSpeedNonStimPerRecNoField = ...
            behAlignedAL.meanSpeedNonStimPerRec(nonStimRecALNoField,:);

        noFieldTmp = behAlignedAL.speedTraceNonStimPerRec(indNonStimRecALNoField);
        behAlignedMean.speedTraceNonStimPerRecNoField = [];
        for i = 1:length(noFieldTmp)
            behAlignedMean.speedTraceNonStimPerRecNoField = [...
                behAlignedMean.speedTraceNonStimPerRecNoField; ...
                noFieldTmp{i}];
        end
        
        behAlignedMean.meanSpeedNonStimGoodPerRecNoField = ...
            behAlignedAL.meanSpeedNonStimGoodPerRec(nonStimGoodRecALNoField,:);

        noFieldTmp = behAlignedAL.speedTraceNonStimGoodPerRec(indNonStimGoodRecALNoField);
        behAlignedMean.speedTraceNonStimGoodPerRecNoField = [];
        for i = 1:length(noFieldTmp)
            behAlignedMean.speedTraceNonStimGoodPerRecNoField = [...
                behAlignedMean.speedTraceNonStimGoodPerRecNoField; ...
                noFieldTmp{i}];
        end

        behAlignedMean.meanSpeedNonStimBadPerRecNoField = ...
            behAlignedAL.meanSpeedNonStimBadPerRec(nonStimBadRecALNoField,:);

        behAlignedMean.meanSpeedStimPerRecNoField = ...
            behAlignedAL.meanSpeedStimPerRec(stimRecALNoField,:);
    end
    
    %% calculating mean 
    % non stim trials with field
    behAlignedMean.meanMeanRewardToRunNonStimPerRec = ...
        mean(behAlignedMean.meanRewardToRunNonStimPerRec);
    behAlignedMean.semMeanRewardToRunNonStimPerRec = ...
        std(behAlignedMean.meanRewardToRunNonStimPerRec)/...
        sqrt(length(behAlignedMean.meanRewardToRunNonStimPerRec));
    
    behAlignedMean.meanMeanStartCueToRunNonStimPerRec = ...
        mean(behAlignedMean.meanStartCueToRunNonStimPerRec);
    behAlignedMean.semMeanStartCueToRunNonStimPerRec = ...
        std(behAlignedMean.meanStartCueToRunNonStimPerRec)/...
        sqrt(length(behAlignedMean.meanStartCueToRunNonStimPerRec));
    
    behAlignedMean.meanMeanTotStopLenTNonStimPerRec = ...
        mean(behAlignedMean.meanTotStopLenTNonStimPerRec);
    behAlignedMean.semMeanTotStopLenTNonStimPerRec= ...
        std(behAlignedMean.meanTotStopLenTNonStimPerRec)/...
        sqrt(length(behAlignedMean.meanTotStopLenTNonStimPerRec));
    
    behAlignedMean.meanMeanTotStopLenTNonStimPerRecField = ...
        mean(behAlignedMean.meanTotStopLenTNonStimPerRecField);
    behAlignedMean.semMeanTotStopLenTNonStimPerRecField = ...
        std(behAlignedMean.meanTotStopLenTNonStimPerRecField)/...
        sqrt(length(behAlignedMean.meanTotStopLenTNonStimPerRecField));
    
    behAlignedMean.meanLickTraceNonStimPerRecField = ...
        mean(behAlignedMean.lickTraceNonStimPerRecField);
    behAlignedMean.semLickTraceNonStimPerRecField = ...
        std(behAlignedMean.lickTraceNonStimPerRecField)/...
        sqrt(size(behAlignedMean.lickTraceNonStimPerRecField,1));
    
    behAlignedMean.meanSpeedTraceNonStimPerRecField = ...
        mean(behAlignedMean.speedTraceNonStimPerRecField);
    behAlignedMean.semSpeedTraceNonStimPerRecField = ...
        std(behAlignedMean.speedTraceNonStimPerRecField)/...
        sqrt(size(behAlignedMean.speedTraceNonStimPerRecField,1));
    
    % non stim good trials without field
    behAlignedMean.meanMeanTotStopLenTNonStimPerRecNoField = ...
        mean(behAlignedMean.meanTotStopLenTNonStimPerRecNoField);
    behAlignedMean.semMeanTotStopLenTNonStimPerRecNoField = ...
        std(behAlignedMean.meanTotStopLenTNonStimPerRecNoField)/...
        sqrt(length(behAlignedMean.meanTotStopLenTNonStimPerRecNoField));
    
    behAlignedMean.meanLickTraceNonStimPerRecNoField = ...
        mean(behAlignedMean.lickTraceNonStimPerRecNoField);
    behAlignedMean.semLickTraceNonStimPerRecNoField = ...
        std(behAlignedMean.lickTraceNonStimPerRecNoField)/...
        sqrt(size(behAlignedMean.lickTraceNonStimPerRecNoField,1));
    
    behAlignedMean.meanSpeedTraceNonStimPerRecNoField = ...
        mean(behAlignedMean.speedTraceNonStimPerRecNoField);
    behAlignedMean.semSpeedTraceNonStimPerRecNoField = ...
        std(behAlignedMean.speedTraceNonStimPerRecNoField)/...
        sqrt(size(behAlignedMean.speedTraceNonStimPerRecNoField,1));
    
    % non stim good trials with field
    behAlignedMean.meanMeanTotStopLenTNonStimGoodPerRecField = ...
        mean(behAlignedMean.meanTotStopLenTNonStimGoodPerRecField);
    behAlignedMean.semMeanTotStopLenTNonStimGoodPerRecField = ...
        std(behAlignedMean.meanTotStopLenTNonStimGoodPerRecField)/...
        sqrt(length(behAlignedMean.meanTotStopLenTNonStimGoodPerRecField));
    
    behAlignedMean.meanLickTraceNonStimGoodPerRecField = ...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecField);
    behAlignedMean.semLickTraceNonStimGoodPerRecField = ...
        std(behAlignedMean.lickTraceNonStimGoodPerRecField)/...
        sqrt(size(behAlignedMean.lickTraceNonStimGoodPerRecField,1));
    
    behAlignedMean.meanSpeedTraceNonStimGoodPerRecField = ...
        mean(behAlignedMean.speedTraceNonStimGoodPerRecField);
    behAlignedMean.semSpeedTraceNonStimGoodPerRecField = ...
        std(behAlignedMean.speedTraceNonStimGoodPerRecField)/...
        sqrt(size(behAlignedMean.speedTraceNonStimGoodPerRecField,1));
    
    % non stim good trials without field
    behAlignedMean.meanMeanTotStopLenTNonStimGoodPerRecNoField = ...
        mean(behAlignedMean.meanTotStopLenTNonStimGoodPerRecNoField);
    behAlignedMean.semMeanTotStopLenTNonStimGoodPerRecNoField = ...
        std(behAlignedMean.meanTotStopLenTNonStimGoodPerRecNoField)/...
        sqrt(length(behAlignedMean.meanTotStopLenTNonStimGoodPerRecNoField));
    
    behAlignedMean.meanLickTraceNonStimGoodPerRecNoField = ...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField);
    behAlignedMean.semLickTraceNonStimGoodPerRecNoField = ...
        std(behAlignedMean.lickTraceNonStimGoodPerRecNoField)/...
        sqrt(size(behAlignedMean.lickTraceNonStimGoodPerRecNoField,1));
    
    behAlignedMean.meanSpeedTraceNonStimGoodPerRecNoField = ...
        mean(behAlignedMean.speedTraceNonStimGoodPerRecNoField);
    behAlignedMean.semSpeedTraceNonStimGoodPerRecNoField = ...
        std(behAlignedMean.speedTraceNonStimGoodPerRecNoField)/...
        sqrt(size(behAlignedMean.speedTraceNonStimGoodPerRecNoField,1));
end