function behAlignedMeanStat = accumMeanBehTimeStat(behAlignedMean,spaceStepsLick,spaceStepsSpeed)
% statistics for behavior for recordings with and without fields
% % this function is called by PyrBehAlignedAllRec.m

    sampFq = 1250;

    %% before 4 sec
    indLickBef4s = find(spaceStepsLick >= 0 & spaceStepsLick < 4*sampFq);
    behAlignedMeanStat.indLickBef4s = indLickBef4s;
    
    behAlignedMeanStat.meanLickPerRecField = [...
        mean(mean(behAlignedMean.meanLickPerRecField(:,indLickBef4s))),...
        mean(mean(behAlignedMean.meanLickPerRecNoField(:,indLickBef4s)))];
    behAlignedMeanStat.meanLickNonStimGoodPerRecField = [...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLickBef4s))),...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLickBef4s)))];
    behAlignedMeanStat.meanLickNonStimBadPerRecField = [...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecField(:,indLickBef4s))),...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLickBef4s)))];
    
    behAlignedMeanStat.pRSMeanLickPerRecField = ...
        ranksum(reshape(behAlignedMean.meanLickPerRecField(:,indLickBef4s),[],1),...
        reshape(behAlignedMean.meanLickPerRecNoField(:,indLickBef4s),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecField = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLickBef4s),[],1),...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLickBef4s),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimBadPerRecField = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,indLickBef4s),[],1),...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLickBef4s),[],1));
    
    behAlignedMeanStat.pRSMeanLickNonStimGoodMeanPerRecField = ...
        ranksum(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLickBef4s),2),...
        mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLickBef4s),2));
    
    behAlignedMeanStat.pRSLickTraceNonStimMeanPerRecField = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimPerRecField(:,indLickBef4s),2),...
        mean(behAlignedMean.lickTraceNonStimPerRecNoField(:,indLickBef4s),2));
    
    behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecField = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,indLickBef4s),2),...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,indLickBef4s),2));

    %% before 1 sec
    indLickBef1s = find(spaceStepsLick >= 0 & spaceStepsLick < sampFq);
    behAlignedMeanStat.indLickBef1s = indLickBef1s;
    behAlignedMeanStat.meanLickPerRecFieldBef1s = [...
        mean(mean(behAlignedMean.meanLickPerRecField(:,indLickBef1s))),...
        mean(mean(behAlignedMean.meanLickPerRecNoField(:,indLickBef1s)))];
    behAlignedMeanStat.meanLickNonStimGoodPerRecFieldBef1s = [...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLickBef1s))),...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLickBef1s)))];
    behAlignedMeanStat.meanLickNonStimBadPerRecFieldBef1s = [...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecField(:,indLickBef1s))),...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLickBef1s)))];
    
    behAlignedMeanStat.pRSMeanLickPerRecFieldBef1s = ...
        ranksum(reshape(behAlignedMean.meanLickPerRecField(:,indLickBef1s),[],1),...
        reshape(behAlignedMean.meanLickPerRecNoField(:,indLickBef1s),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecFieldBef1s = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLickBef1s),[],1),...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLickBef1s),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimBadPerRecFieldBef1s = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,indLickBef1s),[],1),...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLickBef1s),[],1));
        
    behAlignedMeanStat.pRSMeanLickNonStimGoodMeanPerRecFieldBef1s = ...
        ranksum(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLickBef1s),2),...
        mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLickBef1s),2));
    
    behAlignedMeanStat.pRSLickTraceNonStimMeanPerRecFieldBef1s = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimPerRecField(:,indLickBef1s),2),...
        mean(behAlignedMean.lickTraceNonStimPerRecNoField(:,indLickBef1s),2));
    
    behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecFieldBef1s = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,indLickBef1s),2),...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,indLickBef1s),2));
    
    %% between 1 and 2 sec
    indLick1to2s = find(spaceStepsLick >= sampFq & spaceStepsLick < 2*sampFq);
    behAlignedMeanStat.indLick1to2s = indLick1to2s;
    behAlignedMeanStat.meanLickPerRecField1to2s = [...
        mean(mean(behAlignedMean.meanLickPerRecField(:,indLick1to2s))),...
        mean(mean(behAlignedMean.meanLickPerRecNoField(:,indLick1to2s)))];
    behAlignedMeanStat.meanLickNonStimGoodPerRecField1to2s = [...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLick1to2s))),...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLick1to2s)))];
    behAlignedMeanStat.meanLickNonStimBadPerRecField1to2s = [...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecField(:,indLick1to2s))),...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLick1to2s)))];
    
    behAlignedMeanStat.pRSMeanLickPerRecField1to2s = ...
        ranksum(reshape(behAlignedMean.meanLickPerRecField(:,indLick1to2s),[],1),...
        reshape(behAlignedMean.meanLickPerRecNoField(:,indLick1to2s),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecField1to2s = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLick1to2s),[],1),...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLick1to2s),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimBadPerRecField1to2s = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,indLick1to2s),[],1),...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLick1to2s),[],1));
        
    behAlignedMeanStat.pRSMeanLickNonStimGoodMeanPerRecField1to2s = ...
        ranksum(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLick1to2s),2),...
        mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLick1to2s),2));
    
    behAlignedMeanStat.pRSLickTraceNonStimMeanPerRecField1to2s = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimPerRecField(:,indLick1to2s),2),...
        mean(behAlignedMean.lickTraceNonStimPerRecNoField(:,indLick1to2s),2));
    
    behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecField1to2s = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,indLick1to2s),2),...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,indLick1to2s),2));
    
    %% between 2 to 3 sec
    indLick2to3s = find(spaceStepsLick >= 2*sampFq & spaceStepsLick < 3*sampFq);
    behAlignedMeanStat.indLick2to3s = indLick2to3s;
    behAlignedMeanStat.meanLickPerRecField2to3s = [...
        mean(mean(behAlignedMean.meanLickPerRecField(:,indLick2to3s))),...
        mean(mean(behAlignedMean.meanLickPerRecNoField(:,indLick2to3s)))];
    behAlignedMeanStat.meanLickNonStimGoodPerRecField2to3s = [...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLick2to3s))),...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLick2to3s)))];
    behAlignedMeanStat.meanLickNonStimBadPerRecField2to3s = [...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecField(:,indLick2to3s))),...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLick2to3s)))];
    
    behAlignedMeanStat.pRSMeanLickPerRecField2to3s = ...
        ranksum(reshape(behAlignedMean.meanLickPerRecField(:,indLick2to3s),[],1),...
        reshape(behAlignedMean.meanLickPerRecNoField(:,indLick2to3s),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecField2to3s = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLick2to3s),[],1),...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLick2to3s),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimBadPerRecField2to3s = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,indLick2to3s),[],1),...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLick2to3s),[],1));
        
    behAlignedMeanStat.pRSMeanLickNonStimGoodMeanPerRecField2to3s = ...
        ranksum(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLick2to3s),2),...
        mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLick2to3s),2));
    
    behAlignedMeanStat.pRSLickTraceNonStimMeanPerRecField2to3s = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimPerRecField(:,indLick2to3s),2),...
        mean(behAlignedMean.lickTraceNonStimPerRecNoField(:,indLick2to3s),2));
        
    behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecField2to3s = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,indLick2to3s),2),...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,indLick2to3s),2));
        
    %% between 3 to 4 sec
    indLick3to4s = find(spaceStepsLick >= 3*sampFq & spaceStepsLick < 4*sampFq);
    behAlignedMeanStat.indLick3to4s = indLick3to4s;
    behAlignedMeanStat.meanLickPerRecField3to4s = [...
        mean(mean(behAlignedMean.meanLickPerRecField(:,indLick3to4s))),...
        mean(mean(behAlignedMean.meanLickPerRecNoField(:,indLick3to4s)))];
    behAlignedMeanStat.meanLickNonStimGoodPerRecField3to4s = [...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLick3to4s))),...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLick3to4s)))];
    behAlignedMeanStat.meanLickNonStimBadPerRecField3to4s = [...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecField(:,indLick3to4s))),...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLick3to4s)))];
    
    behAlignedMeanStat.pRSMeanLickPerRecField3to4s = ...
        ranksum(reshape(behAlignedMean.meanLickPerRecField(:,indLick3to4s),[],1),...
        reshape(behAlignedMean.meanLickPerRecNoField(:,indLick3to4s),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecField3to4s = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLick3to4s),[],1),...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLick3to4s),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimBadPerRecField3to4s = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,indLick3to4s),[],1),...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLick3to4s),[],1));
        
    behAlignedMeanStat.pRSMeanLickNonStimGoodMeanPerRecField3to4s = ...
        ranksum(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLick3to4s),2),...
        mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLick3to4s),2));
    
    behAlignedMeanStat.pRSLickTraceNonStimMeanPerRecField3to4s = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimPerRecField(:,indLick3to4s),2),...
        mean(behAlignedMean.lickTraceNonStimPerRecNoField(:,indLick3to4s),2));
    
    behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecField3to4s = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,indLick3to4s),2),...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,indLick3to4s),2));
    
    %% total mean
    indSpeedBef4s = find(spaceStepsSpeed >= 0 & spaceStepsSpeed < 4*sampFq);
    behAlignedMeanStat.indSpeedBef4s = indSpeedBef4s;
    behAlignedMeanStat.meanSpeedPerRecField = [...
        mean(mean(behAlignedMean.meanSpeedPerRecField(:,indSpeedBef4s))),...
        mean(mean(behAlignedMean.meanSpeedPerRecNoField(:,indSpeedBef4s)))];
    behAlignedMeanStat.meanSpeedNonStimGoodPerRecField = [...
        mean(mean(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,indSpeedBef4s))),...
        mean(mean(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,indSpeedBef4s)))];
    behAlignedMeanStat.meanSpeedNonStimBadPerRecField = [...
        mean(mean(behAlignedMean.meanSpeedNonStimBadPerRecField(:,indSpeedBef4s))),...
        mean(mean(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:,indSpeedBef4s)))];
    
    behAlignedMeanStat.pRSMeanSpeedPerRecField = ...
        ranksum(reshape(behAlignedMean.meanSpeedPerRecField(:,indSpeedBef4s),[],1),...
        reshape(behAlignedMean.meanSpeedPerRecNoField(:,indSpeedBef4s),[],1));
    behAlignedMeanStat.pRSMeanSpeedNonStimGoodPerRecField = ...
        ranksum(reshape(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,indSpeedBef4s),[],1),...
        reshape(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,indSpeedBef4s),[],1));
    behAlignedMeanStat.pRSMeanSpeedNonStimBadPerRecField = ...
        ranksum(reshape(behAlignedMean.meanSpeedNonStimBadPerRecField(:,indSpeedBef4s),[],1),...
        reshape(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:,indSpeedBef4s),[],1));
    
    behAlignedMeanStat.pRSMeanSpeedNonStimGoodMeanPerRecField = ...
        ranksum(mean(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,indSpeedBef4s),2),...
        mean(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,indSpeedBef4s),2));
    
    behAlignedMeanStat.pRSSpeedTraceNonStimMeanPerRecField = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimPerRecField(:,indSpeedBef4s),2),...
        mean(behAlignedMean.speedTraceNonStimPerRecNoField(:,indSpeedBef4s),2));
    
    behAlignedMeanStat.pRSSpeedTraceNonStimGoodMeanPerRecField = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimGoodPerRecField(:,indSpeedBef4s),2),...
        mean(behAlignedMean.speedTraceNonStimGoodPerRecNoField(:,indSpeedBef4s),2));
    
    %% before 1 sec
    indSpeedBef1s = find(spaceStepsSpeed >= 0 & spaceStepsSpeed < sampFq);
    behAlignedMeanStat.indSpeedBef1s = indSpeedBef1s;
    behAlignedMeanStat.meanSpeedPerRecFieldBef1s = [...
        mean(mean(behAlignedMean.meanSpeedPerRecField(:,indSpeedBef1s))),...
        mean(mean(behAlignedMean.meanSpeedPerRecNoField(:,indSpeedBef1s)))];
    behAlignedMeanStat.meanSpeedNonStimGoodPerRecFieldBef1s = [...
        mean(mean(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,indSpeedBef1s))),...
        mean(mean(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,indSpeedBef1s)))];
    behAlignedMeanStat.meanSpeedNonStimBadPerRecFieldBef1s = [...
        mean(mean(behAlignedMean.meanSpeedNonStimBadPerRecField(:,indSpeedBef1s))),...
        mean(mean(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:,indSpeedBef1s)))];
    
    behAlignedMeanStat.pRSMeanSpeedPerRecFieldBef1s = ...
        ranksum(reshape(behAlignedMean.meanSpeedPerRecField(:,indSpeedBef1s),[],1),...
        reshape(behAlignedMean.meanSpeedPerRecNoField(:,indSpeedBef1s),[],1));
    behAlignedMeanStat.pRSMeanSpeedNonStimGoodPerRecFieldBef1s = ...
        ranksum(reshape(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,indSpeedBef1s),[],1),...
        reshape(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,indSpeedBef1s),[],1));
    behAlignedMeanStat.pRSMeanSpeedNonStimBadPerRecFieldBef1s = ...
        ranksum(reshape(behAlignedMean.meanSpeedNonStimBadPerRecField(:,indSpeedBef1s),[],1),...
        reshape(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:,indSpeedBef1s),[],1));
        
    behAlignedMeanStat.pRSMeanSpeedNonStimGoodMeanPerRecFieldBef1s = ...
        ranksum(mean(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,indSpeedBef1s),2),...
        mean(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,indSpeedBef1s),2));
    
    behAlignedMeanStat.pRSSpeedTraceNonStimMeanPerRecFieldBef1s = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimPerRecField(:,indSpeedBef1s),2),...
        mean(behAlignedMean.speedTraceNonStimPerRecNoField(:,indSpeedBef1s),2));
    
    behAlignedMeanStat.pRSSpeedTraceNonStimGoodMeanPerRecFieldBef1s = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimGoodPerRecField(:,indSpeedBef1s),2),...
        mean(behAlignedMean.speedTraceNonStimGoodPerRecNoField(:,indSpeedBef1s),2));
    
    %% between 1-2 sec
    indSpeed1to2s = find(spaceStepsSpeed >= sampFq & spaceStepsSpeed < 2*sampFq);
    behAlignedMeanStat.indSpeed1to2s = indSpeed1to2s;
    behAlignedMeanStat.meanSpeedPerRecField1to2s = [...
        mean(mean(behAlignedMean.meanSpeedPerRecField(:,indSpeed1to2s))),...
        mean(mean(behAlignedMean.meanSpeedPerRecNoField(:,indSpeed1to2s)))];
    behAlignedMeanStat.meanSpeedNonStimGoodPerRecField1to2s = [...
        mean(mean(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,indSpeed1to2s))),...
        mean(mean(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,indSpeed1to2s)))];
    behAlignedMeanStat.meanSpeedNonStimBadPerRecField1to2s = [...
        mean(mean(behAlignedMean.meanSpeedNonStimBadPerRecField(:,indSpeed1to2s))),...
        mean(mean(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:,indSpeed1to2s)))];
    
    behAlignedMeanStat.pRSMeanSpeedPerRecField1to2s = ...
        ranksum(reshape(behAlignedMean.meanSpeedPerRecField(:,indSpeed1to2s),[],1),...
        reshape(behAlignedMean.meanSpeedPerRecNoField(:,indSpeed1to2s),[],1));
    behAlignedMeanStat.pRSMeanSpeedNonStimGoodPerRecField1to2s = ...
        ranksum(reshape(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,indSpeed1to2s),[],1),...
        reshape(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,indSpeed1to2s),[],1));
    behAlignedMeanStat.pRSMeanSpeedNonStimBadPerRecField1to2s = ...
        ranksum(reshape(behAlignedMean.meanSpeedNonStimBadPerRecField(:,indSpeed1to2s),[],1),...
        reshape(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:,indSpeed1to2s),[],1));
    
    behAlignedMeanStat.pRSMeanSpeedNonStimGoodMeanPerRecField1to2s = ...
        ranksum(mean(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,indSpeed1to2s),2),...
        mean(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,indSpeed1to2s),2));
    
    behAlignedMeanStat.pRSSpeedTraceNonStimMeanPerRecField1to2s = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimPerRecField(:,indSpeed1to2s),2),...
        mean(behAlignedMean.speedTraceNonStimPerRecNoField(:,indSpeed1to2s),2));

    behAlignedMeanStat.pRSSpeedTraceNonStimGoodMeanPerRecField1to2s = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimGoodPerRecField(:,indSpeed1to2s),2),...
        mean(behAlignedMean.speedTraceNonStimGoodPerRecNoField(:,indSpeed1to2s),2));

    %% between 2-3 sec
    indSpeed2to3s = find(spaceStepsSpeed >= 2*sampFq & spaceStepsSpeed < 3*sampFq);
    behAlignedMeanStat.indSpeed2to3s = indSpeed2to3s;
    behAlignedMeanStat.meanSpeedPerRecField2to3s = [...
        mean(mean(behAlignedMean.meanSpeedPerRecField(:,indSpeed2to3s))),...
        mean(mean(behAlignedMean.meanSpeedPerRecNoField(:,indSpeed2to3s)))];
    behAlignedMeanStat.meanSpeedNonStimGoodPerRecField2to3s = [...
        mean(mean(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,indSpeed2to3s))),...
        mean(mean(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,indSpeed2to3s)))];
    behAlignedMeanStat.meanSpeedNonStimBadPerRecField2to3s = [...
        mean(mean(behAlignedMean.meanSpeedNonStimBadPerRecField(:,indSpeed2to3s))),...
        mean(mean(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:,indSpeed2to3s)))];
    
    behAlignedMeanStat.pRSMeanSpeedPerRecField2to3s = ...
        ranksum(reshape(behAlignedMean.meanSpeedPerRecField(:,indSpeed2to3s),[],1),...
        reshape(behAlignedMean.meanSpeedPerRecNoField(:,indSpeed2to3s),[],1));
    behAlignedMeanStat.pRSMeanSpeedNonStimGoodPerRecField2to3s = ...
        ranksum(reshape(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,indSpeed2to3s),[],1),...
        reshape(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,indSpeed2to3s),[],1));
    behAlignedMeanStat.pRSMeanSpeedNonStimBadPerRecField2to3s = ...
        ranksum(reshape(behAlignedMean.meanSpeedNonStimBadPerRecField(:,indSpeed2to3s),[],1),...
        reshape(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:,indSpeed2to3s),[],1));
    
    behAlignedMeanStat.pRSMeanSpeedNonStimGoodMeanPerRecField2to3s = ...
        ranksum(mean(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,indSpeed2to3s),2),...
        mean(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,indSpeed2to3s),2));
    
    behAlignedMeanStat.pRSSpeedTraceNonStimMeanPerRecField2to3s = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimPerRecField(:,indSpeed2to3s),2),...
        mean(behAlignedMean.speedTraceNonStimPerRecNoField(:,indSpeed2to3s),2));

    behAlignedMeanStat.pRSSpeedTraceNonStimGoodMeanPerRecField2to3s = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimGoodPerRecField(:,indSpeed2to3s),2),...
        mean(behAlignedMean.speedTraceNonStimGoodPerRecNoField(:,indSpeed2to3s),2));

    %% between 3-4 sec
    indSpeed3to4s = find(spaceStepsSpeed >= 3*sampFq & spaceStepsSpeed < 4*sampFq);
    behAlignedMeanStat.indSpeed3to4s = indSpeed3to4s;
    behAlignedMeanStat.meanSpeedPerRecField3to4s = [...
        mean(mean(behAlignedMean.meanSpeedPerRecField(:,indSpeed3to4s))),...
        mean(mean(behAlignedMean.meanSpeedPerRecNoField(:,indSpeed3to4s)))];
    behAlignedMeanStat.meanSpeedNonStimGoodPerRecField3to4s = [...
        mean(mean(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,indSpeed3to4s))),...
        mean(mean(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,indSpeed3to4s)))];
    behAlignedMeanStat.meanSpeedNonStimBadPerRecField3to4s = [...
        mean(mean(behAlignedMean.meanSpeedNonStimBadPerRecField(:,indSpeed3to4s))),...
        mean(mean(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:,indSpeed3to4s)))];
    
    behAlignedMeanStat.pRSMeanSpeedPerRecField3to4s = ...
        ranksum(reshape(behAlignedMean.meanSpeedPerRecField(:,indSpeed3to4s),[],1),...
        reshape(behAlignedMean.meanSpeedPerRecNoField(:,indSpeed3to4s),[],1));
    behAlignedMeanStat.pRSMeanSpeedNonStimGoodPerRecField3to4s = ...
        ranksum(reshape(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,indSpeed3to4s),[],1),...
        reshape(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,indSpeed3to4s),[],1));
    behAlignedMeanStat.pRSMeanSpeedNonStimBadPerRecField3to4s = ...
        ranksum(reshape(behAlignedMean.meanSpeedNonStimBadPerRecField(:,indSpeed3to4s),[],1),...
        reshape(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:,indSpeed3to4s),[],1));
    
    behAlignedMeanStat.pRSMeanSpeedNonStimGoodMeanPerRecField3to4s = ...
        ranksum(mean(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,indSpeed3to4s),2),...
        mean(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,indSpeed3to4s),2));
    
    behAlignedMeanStat.pRSSpeedTraceNonStimMeanPerRecField3to4s = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimPerRecField(:,indSpeed3to4s),2),...
        mean(behAlignedMean.speedTraceNonStimPerRecNoField(:,indSpeed3to4s),2));

    behAlignedMeanStat.pRSSpeedTraceNonStimGoodMeanPerRecField3to4s = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimGoodPerRecField(:,indSpeed3to4s),2),...
        mean(behAlignedMean.speedTraceNonStimGoodPerRecNoField(:,indSpeed3to4s),2));

end