function behAlignedMeanStat = accumMeanBehTimeStatGoodBad(behAlignedMean,spaceStepsLick,spaceStepsSpeed)
% statistics for good vs bad trials
% this function is called by PyrBehAlignedAllRec.m

    sampFq = 1250;

    %% before 4 sec
    indLickBef4s = find(spaceStepsLick >= 0 & spaceStepsLick < 4*sampFq);
    behAlignedMeanStat.indLickBef4s = indLickBef4s;
    behAlignedMeanStat.meanLickPerRec = [...
        mean(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLickBef4s),2)),...
        mean(mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLickBef4s),2))];
    behAlignedMeanStat.stdLickPerRec = [...
        std(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLickBef4s),2))/...
            sqrt(size(behAlignedMean.meanLickPerRecNonStimGood,1)),...
        std(mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLickBef4s),2))/...
            sqrt(size(behAlignedMean.meanLickPerRecNonStimBad,1))];% added on 6/7/2022
    
    behAlignedMeanStat.pRSLickTracePerRec = ...
        ranksum(reshape(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLickBef4s),[],1),...
        reshape(behAlignedMean.lickTraceNonStimBadPerRec(:,indLickBef4s),[],1));
    
    behAlignedMeanStat.pRSMeanLickMeanPerRec = ...
        ranksum(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLickBef4s),2),...
        mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLickBef4s),2));
            
    behAlignedMeanStat.pRSMeanLickTracePerRec = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLickBef4s),2),...
        mean(behAlignedMean.lickTraceNonStimBadPerRec(:,indLickBef4s),2));

    %% before 2 sec
    indLickBef2s = find(spaceStepsLick >= 0 & spaceStepsLick < 2*sampFq);
    behAlignedMeanStat.indLickBef2s = indLickBef2s;
    behAlignedMeanStat.meanLickPerRecBef2s = [...
        mean(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLickBef2s),2)),...
        mean(mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLickBef2s),2))];
    behAlignedMeanStat.stdLickPerRecBef2s = [...
        std(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLickBef2s),2))/...
            sqrt(size(behAlignedMean.meanLickPerRecNonStimGood,1)),...
        std(mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLickBef2s),2))/...
            sqrt(size(behAlignedMean.meanLickPerRecNonStimBad,1))];% added on 6/7/2022
    
    behAlignedMeanStat.pRSLickTracePerRecBef2s = ...
        ranksum(reshape(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLickBef2s),[],1),...
        reshape(behAlignedMean.lickTraceNonStimBadPerRec(:,indLickBef2s),[],1));
    
    behAlignedMeanStat.pRSMeanLickMeanPerRecBef2s = ...
        ranksum(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLickBef2s),2),...
        mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLickBef2s),2));
            
    behAlignedMeanStat.pRSMeanLickTracePerRecBef2s = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLickBef2s),2),...
        mean(behAlignedMean.lickTraceNonStimBadPerRec(:,indLickBef2s),2));
    
    %% before 1 sec
    indLickBef1s = find(spaceStepsLick >= 0 & spaceStepsLick < sampFq);
    behAlignedMeanStat.indLickBef1s = indLickBef1s;
    behAlignedMeanStat.meanLickPerRecBef1s = [...
        mean(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLickBef1s),2)),...
        mean(mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLickBef1s),2))];
    behAlignedMeanStat.stdLickPerRecBef1s = [...
        std(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLickBef1s),2))/...
            sqrt(size(behAlignedMean.meanLickPerRecNonStimGood,1)),...
        std(mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLickBef1s),2))/...
            sqrt(size(behAlignedMean.meanLickPerRecNonStimBad,1))];% added on 6/7/2022
    
    behAlignedMeanStat.pRSLickTracePerRecBef1s = ...
        ranksum(reshape(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLickBef1s),[],1),...
        reshape(behAlignedMean.lickTraceNonStimBadPerRec(:,indLickBef1s),[],1));
    
    behAlignedMeanStat.pRSMeanLickMeanPerRecBef1s = ...
        ranksum(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLickBef1s),2),...
        mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLickBef1s),2));
            
    behAlignedMeanStat.pRSMeanLickTracePerRecBef1s = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLickBef1s),2),...
        mean(behAlignedMean.lickTraceNonStimBadPerRec(:,indLickBef1s),2));
    
    %% between 1 and 2 sec
    indLick1to2s = find(spaceStepsLick >= sampFq & spaceStepsLick < 2*sampFq);
    behAlignedMeanStat.indLick1to2s = indLick1to2s;
    behAlignedMeanStat.meanLickPerRec1to2s = [...
        mean(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLick1to2s),2)),...
        mean(mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLick1to2s),2))];
    behAlignedMeanStat.stdLickPerRec1to2s = [...
        std(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLick1to2s),2))/...
            sqrt(size(behAlignedMean.meanLickPerRecNonStimGood,1)),...
        std(mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLick1to2s),2))/...
            sqrt(size(behAlignedMean.meanLickPerRecNonStimBad,1))];% added on 5/10/2022
    
    behAlignedMeanStat.pRSLickTracePerRec1to2s = ...
        ranksum(reshape(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLick1to2s),[],1),...
        reshape(behAlignedMean.lickTraceNonStimBadPerRec(:,indLick1to2s),[],1));
    
    behAlignedMeanStat.pRSMeanLickMeanPerRec1to2s = ...
        ranksum(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLick1to2s),2),...
        mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLick1to2s),2));
            
    behAlignedMeanStat.pRSMeanLickTracePerRec1to2s = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLick1to2s),2),...
        mean(behAlignedMean.lickTraceNonStimBadPerRec(:,indLick1to2s),2));
    
    %% between 2 to 3 sec
    indLick2to3s = find(spaceStepsLick >= 2*sampFq & spaceStepsLick < 3*sampFq);
    behAlignedMeanStat.indLick2to3s = indLick2to3s;
    behAlignedMeanStat.meanLickPerRec2to3s = [...
        mean(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLick2to3s))),...
        mean(mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLick2to3s)))];
    behAlignedMeanStat.stdLickPerRec2to3s = [...
        std(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLick2to3s),2))/...
            sqrt(size(behAlignedMean.meanLickPerRecNonStimGood,1)),...
        std(mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLick2to3s),2))/...
            sqrt(size(behAlignedMean.meanLickPerRecNonStimBad,1))];% added on 6/7/2022
        
    behAlignedMeanStat.pRSLickTracePerRec2to3s = ...
        ranksum(reshape(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLick2to3s),[],1),...
        reshape(behAlignedMean.lickTraceNonStimBadPerRec(:,indLick2to3s),[],1));
    
    behAlignedMeanStat.pRSMeanLickMeanPerRec2to3s = ...
        ranksum(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLick2to3s),2),...
        mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLick2to3s),2));
            
    behAlignedMeanStat.pRSMeanLickTracePerRec2to3s = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLick2to3s),2),...
        mean(behAlignedMean.lickTraceNonStimBadPerRec(:,indLick2to3s),2));
        
    %% between 3 to 4 sec
    indLick3to4s = find(spaceStepsLick >= 3*sampFq & spaceStepsLick < 4*sampFq);
    behAlignedMeanStat.indLick3to4s = indLick3to4s;
    behAlignedMeanStat.meanLickPerRec3to4s = [...
        mean(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLick3to4s))),...
        mean(mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLick3to4s)))];
    behAlignedMeanStat.stdLickPerRec3to4s = [...
        std(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLick3to4s),2))/...
            sqrt(size(behAlignedMean.meanLickPerRecNonStimGood,1)),...
        std(mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLick3to4s),2))/...
            sqrt(size(behAlignedMean.meanLickPerRecNonStimBad,1))];% added on 6/7/2022
        
    behAlignedMeanStat.pRSLickTracePerRec3to4s = ...
        ranksum(reshape(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLick3to4s),[],1),...
        reshape(behAlignedMean.lickTraceNonStimBadPerRec(:,indLick3to4s),[],1));
    
    behAlignedMeanStat.pRSMeanLickMeanPerRec3to4s = ...
        ranksum(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLick3to4s),2),...
        mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLick3to4s),2));
            
    behAlignedMeanStat.pRSMeanLickTracePerRec3to4s = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLick3to4s),2),...
        mean(behAlignedMean.lickTraceNonStimBadPerRec(:,indLick3to4s),2));
    
    %% total mean before 4s
    indSpeedBef4s = find(spaceStepsSpeed >= 0 & spaceStepsSpeed < 4*sampFq);
    behAlignedMeanStat.indSpeedBef4s = indSpeedBef4s;
    behAlignedMeanStat.meanSpeedPerRec = [...
        mean(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeedBef4s),2)),...
        mean(mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,indSpeedBef4s),2))];
    behAlignedMeanStat.stdSpeedPerRec = [...
        std(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeedBef4s),2))/...
            sqrt(size(behAlignedMean.meanSpeedPerRecNonStimGood,1)),...
        std(mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,indSpeedBef4s),2))/...
            sqrt(size(behAlignedMean.meanSpeedPerRecNonStimBad,1))];% added on 6/7/2022
        
    behAlignedMeanStat.pRSSpeedTracePerRec = ...
        ranksum(reshape(behAlignedMean.speedTraceNonStimGoodPerRec(:,indSpeedBef4s),[],1),...
        reshape(behAlignedMean.speedTraceNonStimBadPerRec(:,indSpeedBef4s),[],1));
    
    behAlignedMeanStat.pRSMeanSpeedMeanPerRec = ...
         ranksum(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeedBef4s),2),...
        mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,indSpeedBef4s),2));
    
    behAlignedMeanStat.pRSMeanSpeedTracePerRec = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimGoodPerRec(:,indSpeedBef4s),2),...
        mean(behAlignedMean.speedTraceNonStimBadPerRec(:,indSpeedBef4s),2));
    
    %% before 2 sec
    indSpeedBef2s = find(spaceStepsSpeed >= 0 & spaceStepsSpeed < 2*sampFq);
    behAlignedMeanStat.indSpeedBef2s = indSpeedBef2s;
    behAlignedMeanStat.meanSpeedPerRecBef2s = [...
        mean(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeedBef2s))),...
        mean(mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,indSpeedBef2s)))];
    behAlignedMeanStat.stdSpeedPerRecBef2s = [...
        std(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeedBef2s),2))/...
            sqrt(size(behAlignedMean.meanSpeedPerRecNonStimGood,1)),...
        std(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeedBef2s),2))/...
            sqrt(size(behAlignedMean.meanSpeedPerRecNonStimGood,1))];% added on 6/7/2022
    
    behAlignedMeanStat.pRSSpeedTracePerRecBef2s = ...
        ranksum(reshape(behAlignedMean.speedTraceNonStimGoodPerRec(:,indSpeedBef2s),[],1),...
        reshape(behAlignedMean.speedTraceNonStimBadPerRec(:,indSpeedBef2s),[],1));
    
    behAlignedMeanStat.pRSMeanSpeedMeanPerRecBef2s = ...
        ranksum(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeedBef2s),2),...
        mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,indSpeedBef2s),2));
    
    behAlignedMeanStat.pRSMeanSpeedTracePerRecBef2s = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimGoodPerRec(:,indSpeedBef2s),2),...
        mean(behAlignedMean.speedTraceNonStimBadPerRec(:,indSpeedBef2s),2));
    
    %% before 1 sec
    indSpeedBef1s = find(spaceStepsSpeed >= 0 & spaceStepsSpeed < sampFq);
    behAlignedMeanStat.indSpeedBef1s = indSpeedBef1s;
    behAlignedMeanStat.meanSpeedPerRecBef1s = [...
        mean(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeedBef1s))),...
        mean(mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,indSpeedBef1s)))];
    behAlignedMeanStat.stdSpeedPerRecBef1s = [...
        std(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeedBef1s),2))/...
            sqrt(size(behAlignedMean.meanSpeedPerRecNonStimGood,1)),...
        std(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeedBef1s),2))/...
            sqrt(size(behAlignedMean.meanSpeedPerRecNonStimGood,1))];% added on 6/7/2022
    
    behAlignedMeanStat.pRSSpeedTracePerRecBef1s = ...
        ranksum(reshape(behAlignedMean.speedTraceNonStimGoodPerRec(:,indSpeedBef1s),[],1),...
        reshape(behAlignedMean.speedTraceNonStimBadPerRec(:,indSpeedBef1s),[],1));
    
    behAlignedMeanStat.pRSMeanSpeedMeanPerRecBef1s = ...
        ranksum(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeedBef1s),2),...
        mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,indSpeedBef1s),2));
    
    behAlignedMeanStat.pRSMeanSpeedTracePerRecBef1s = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimGoodPerRec(:,indSpeedBef1s),2),...
        mean(behAlignedMean.speedTraceNonStimBadPerRec(:,indSpeedBef1s),2));
    
    %% between 1-2 sec
    indSpeed1to2s = find(spaceStepsSpeed >= sampFq & spaceStepsSpeed < 2*sampFq);
    behAlignedMeanStat.indSpeed1to2s = indSpeed1to2s;
    behAlignedMeanStat.meanSpeedPerRec1to2s = [...
        mean(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeed1to2s))),...
        mean(mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,indSpeed1to2s)))];
    behAlignedMeanStat.stdSpeedPerRec1to2s = [...
        std(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeed1to2s),2))/...
            sqrt(size(behAlignedMean.meanSpeedPerRecNonStimGood,1)),...
        std(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeed1to2s),2))/...
            sqrt(size(behAlignedMean.meanSpeedPerRecNonStimGood,1))];% added on 6/7/2022
    
    behAlignedMeanStat.pRSSpeedTracePerRec1to2s = ...
        ranksum(reshape(behAlignedMean.speedTraceNonStimGoodPerRec(:,indSpeed1to2s),[],1),...
        reshape(behAlignedMean.speedTraceNonStimBadPerRec(:,indSpeed1to2s),[],1));
    
    behAlignedMeanStat.pRSMeanSpeedMeanPerRec1to2s = ...
        ranksum(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeed1to2s),2),...
        mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,indSpeed1to2s),2));
    
    behAlignedMeanStat.pRSMeanSpeedTracePerRec1to2s = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimGoodPerRec(:,indSpeed1to2s),2),...
        mean(behAlignedMean.speedTraceNonStimBadPerRec(:,indSpeed1to2s),2));

    %% between 2-3 sec
    indSpeed2to3s = find(spaceStepsSpeed >= 2*sampFq & spaceStepsSpeed < 3*sampFq);
    behAlignedMeanStat.indSpeed2to3s = indSpeed2to3s;
    behAlignedMeanStat.meanSpeedPerRec2to3s = [...
        mean(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeed2to3s))),...
        mean(mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,indSpeed2to3s)))];
    behAlignedMeanStat.stdSpeedPerRec2to3s = [...
        std(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeed2to3s),2))/...
            sqrt(size(behAlignedMean.meanSpeedPerRecNonStimGood,1)),...
        std(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeed2to3s),2))/...
            sqrt(size(behAlignedMean.meanSpeedPerRecNonStimGood,1))];% added on 6/7/2022
    
    behAlignedMeanStat.pRSSpeedTracePerRec2to3s = ...
        ranksum(reshape(behAlignedMean.speedTraceNonStimGoodPerRec(:,indSpeed2to3s),[],1),...
        reshape(behAlignedMean.speedTraceNonStimBadPerRec(:,indSpeed2to3s),[],1));
    
    behAlignedMeanStat.pRSMeanSpeedMeanPerRec2to3s = ...
        ranksum(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeed2to3s),2),...
        mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,indSpeed2to3s),2));
    
    behAlignedMeanStat.pRSMeanSpeedTracePerRec2to3s = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimGoodPerRec(:,indSpeed2to3s),2),...
        mean(behAlignedMean.speedTraceNonStimBadPerRec(:,indSpeed2to3s),2));

    %% between 3-4 sec
    indSpeed3to4s = find(spaceStepsSpeed >= 3*sampFq & spaceStepsSpeed < 4*sampFq);
    behAlignedMeanStat.indSpeed3to4s = indSpeed3to4s;
    behAlignedMeanStat.meanSpeedPerRec3to4s = [...
        mean(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeed3to4s))),...
        mean(mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,indSpeed3to4s)))];
    behAlignedMeanStat.stdSpeedPerRec3to4s = [...
        std(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeed3to4s),2))/...
            sqrt(size(behAlignedMean.meanSpeedPerRecNonStimGood,1)),...
        std(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeed3to4s),2))/...
            sqrt(size(behAlignedMean.meanSpeedPerRecNonStimGood,1))];% added on 6/7/2022
    
    behAlignedMeanStat.pRSSpeedTracePerRec3to4s = ...
        ranksum(reshape(behAlignedMean.speedTraceNonStimGoodPerRec(:,indSpeed3to4s),[],1),...
        reshape(behAlignedMean.speedTraceNonStimBadPerRec(:,indSpeed3to4s),[],1));
    
    behAlignedMeanStat.pRSMeanSpeedMeanPerRec3to4s = ...
        ranksum(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeed3to4s),2),...
        mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,indSpeed3to4s),2));
    
    behAlignedMeanStat.pRSMeanSpeedTracePerRec3to4s = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimGoodPerRec(:,indSpeed3to4s),2),...
        mean(behAlignedMean.speedTraceNonStimBadPerRec(:,indSpeed3to4s),2));
    
end
