function behAlignedMeanStat = accumMeanBehStat(behAlignedMean,spaceStepsLick,spaceStepsSpeed)
% statistics for behavior for recordings with and without fields
% % this function is called by PyrBehAlignedAllRec.m

    %% total stop time, added on 6/9/2022
    behAlignedMeanStat.meanTotStopLenTPerRecField = [...
        mean(behAlignedMean.meanTotStopLenTPerRecField),...
        mean(behAlignedMean.meanTotStopLenTPerRecNoField)];
    behAlignedMeanStat.meanTotStopLenTNonStimPerRecField = [...
        mean(behAlignedMean.meanTotStopLenTNonStimPerRecField),...
        mean(behAlignedMean.meanTotStopLenTNonStimPerRecNoField)];
    behAlignedMeanStat.meanTotStopLenTNonStimGoodPerRecField = [...
        mean(behAlignedMean.meanTotStopLenTNonStimGoodPerRecField),...
        mean(behAlignedMean.meanTotStopLenTNonStimGoodPerRecNoField)];
    behAlignedMeanStat.meanTotStopLenTNonStimBadPerRecField = [...
        mean(behAlignedMean.meanTotStopLenTNonStimBadPerRecField),...
        mean(behAlignedMean.meanTotStopLenTNonStimBadPerRecNoField)];
    
    behAlignedMeanStat.pRSMeanTotStopLenTPerRecField = ...
        ranksum(behAlignedMean.meanTotStopLenTPerRecField,...
        behAlignedMean.meanTotStopLenTPerRecNoField);
    behAlignedMeanStat.pRSMeanTotStopLenTNonStimPerRecField = ...
        ranksum(behAlignedMean.meanTotStopLenTNonStimPerRecField,...
        behAlignedMean.meanTotStopLenTNonStimPerRecNoField);
    behAlignedMeanStat.pRSMeanTotStopLenTNonStimGoodPerRecField = ...
        ranksum(behAlignedMean.meanTotStopLenTNonStimGoodPerRecField,...
        behAlignedMean.meanTotStopLenTNonStimGoodPerRecNoField);
    behAlignedMeanStat.pRSMeanTotStopLenTNonStimBadPerRecField = ...
        ranksum(behAlignedMean.meanTotStopLenTNonStimBadPerRecField,...
        behAlignedMean.meanTotStopLenTNonStimBadPerRecNoField);
    
    %% total mean
    indLickAfter30 = find(spaceStepsLick >= 300 & spaceStepsLick < 2100);
    behAlignedMeanStat.indLickAfter30 = indLickAfter30;
    
    behAlignedMeanStat.meanLickPerRecField = [...
        mean(mean(behAlignedMean.meanLickPerRecField(:,indLickAfter30))),...
        mean(mean(behAlignedMean.meanLickPerRecNoField(:,indLickAfter30)))];
    behAlignedMeanStat.meanLickNonStimPerRecField = [...
        mean(mean(behAlignedMean.meanLickNonStimPerRecField(:,indLickAfter30))),...
        mean(mean(behAlignedMean.meanLickNonStimPerRecNoField(:,indLickAfter30)))];
    behAlignedMeanStat.meanLickNonStimGoodPerRecField = [...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLickAfter30))),...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLickAfter30)))];
    behAlignedMeanStat.meanLickNonStimBadPerRecField = [...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecField(:,indLickAfter30))),...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLickAfter30)))];
    
    behAlignedMeanStat.pRSMeanLickPerRecField = ...
        ranksum(reshape(behAlignedMean.meanLickPerRecField(:,indLickAfter30),[],1),...
        reshape(behAlignedMean.meanLickPerRecNoField(:,indLickAfter30),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimPerRecField = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimPerRecField(:,indLickAfter30),[],1),...
        reshape(behAlignedMean.meanLickNonStimPerRecNoField(:,indLickAfter30),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecField = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLickAfter30),[],1),...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLickAfter30),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimBadPerRecField = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,indLickAfter30),[],1),...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLickAfter30),[],1));
    
    behAlignedMeanStat.pRSMeanLickNonStimMeanPerRecField = ...
        ranksum(mean(behAlignedMean.meanLickNonStimPerRecField(:,indLickAfter30),2),...
        mean(behAlignedMean.meanLickNonStimPerRecNoField(:,indLickAfter30),2));
    
    behAlignedMeanStat.pRSMeanLickNonStimGoodMeanPerRecField = ...
        ranksum(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLickAfter30),2),...
        mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLickAfter30),2));
    
    behAlignedMeanStat.pRSLickTraceNonStimMeanPerRecField = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimPerRecField(:,indLickAfter30),2),...
        mean(behAlignedMean.lickTraceNonStimPerRecNoField(:,indLickAfter30),2));
    
    behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecField = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,indLickAfter30),2),...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,indLickAfter30),2));

    %% distance 30 to 100
    indLick30to100 = find(spaceStepsLick >= 300 & spaceStepsLick < 1000);
    behAlignedMeanStat.indLick30to100 = indLick30to100;
    behAlignedMeanStat.meanLickPerRecField30to100 = [...
        mean(mean(behAlignedMean.meanLickPerRecField(:,indLick30to100))),...
        mean(mean(behAlignedMean.meanLickPerRecNoField(:,indLick30to100)))];
    behAlignedMeanStat.meanLickNonStimPerRecField30to100 = [...
        mean(mean(behAlignedMean.meanLickNonStimPerRecField(:,indLick30to100))),...
        mean(mean(behAlignedMean.meanLickNonStimPerRecNoField(:,indLick30to100)))];
    behAlignedMeanStat.meanLickNonStimGoodPerRecField30to100 = [...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLick30to100))),...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLick30to100)))];
    behAlignedMeanStat.meanLickNonStimBadPerRecField30to100 = [...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecField(:,indLick30to100))),...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLick30to100)))];
    
    behAlignedMeanStat.pRSMeanLickPerRecField30to100 = ...
        ranksum(reshape(behAlignedMean.meanLickPerRecField(:,indLick30to100),[],1),...
        reshape(behAlignedMean.meanLickPerRecNoField(:,indLick30to100),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimPerRecField30to100 = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimPerRecField(:,indLick30to100),[],1),...
        reshape(behAlignedMean.meanLickNonStimPerRecNoField(:,indLick30to100),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecField30to100 = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLick30to100),[],1),...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLick30to100),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimBadPerRecField30to100 = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,indLick30to100),[],1),...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLick30to100),[],1));
    
    behAlignedMeanStat.pRSMeanLickNonStimMeanPerRecField30to100 = ...
        ranksum(mean(behAlignedMean.meanLickNonStimPerRecField(:,indLick30to100),2),...
        mean(behAlignedMean.meanLickNonStimPerRecNoField(:,indLick30to100),2));
    
    behAlignedMeanStat.pRSMeanLickNonStimGoodMeanPerRecField30to100 = ...
        ranksum(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLick30to100),2),...
        mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLick30to100),2));
    
    behAlignedMeanStat.pRSLickTraceNonStimMeanPerRecField30to100 = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimPerRecField(:,indLick30to100),2),...
        mean(behAlignedMean.lickTraceNonStimPerRecNoField(:,indLick30to100),2));
    
    behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecField30to100 = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,indLick30to100),2),...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,indLick30to100),2));
    
    %% distance 100 to 150
    indLick100to150 = find(spaceStepsLick >= 1000 & spaceStepsLick < 1500);
    behAlignedMeanStat.indLick100to150 = indLick100to150;
    behAlignedMeanStat.meanLickPerRecField100to150 = [...
        mean(mean(behAlignedMean.meanLickPerRecField(:,indLick100to150))),...
        mean(mean(behAlignedMean.meanLickPerRecNoField(:,indLick100to150)))];
    behAlignedMeanStat.meanLickNonStimPerRecField100to150 = [...
        mean(mean(behAlignedMean.meanLickNonStimPerRecField(:,indLick100to150))),...
        mean(mean(behAlignedMean.meanLickNonStimPerRecNoField(:,indLick100to150)))];
    behAlignedMeanStat.meanLickNonStimGoodPerRecField100to150 = [...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLick100to150))),...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLick100to150)))];
    behAlignedMeanStat.meanLickNonStimBadPerRecField100to150 = [...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecField(:,indLick100to150))),...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLick100to150)))];
    
    behAlignedMeanStat.pRSMeanLickPerRecField100to150 = ...
        ranksum(reshape(behAlignedMean.meanLickPerRecField(:,indLick100to150),[],1),...
        reshape(behAlignedMean.meanLickPerRecNoField(:,indLick100to150),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimPerRecField100to150 = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimPerRecField(:,indLick100to150),[],1),...
        reshape(behAlignedMean.meanLickNonStimPerRecNoField(:,indLick100to150),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecField100to150 = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLick100to150),[],1),...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLick100to150),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimBadPerRecField100to150 = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,indLick100to150),[],1),...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLick100to150),[],1));
    
    behAlignedMeanStat.pRSMeanLickNonStimMeanPerRecField100to150 = ...
        ranksum(mean(behAlignedMean.meanLickNonStimPerRecField(:,indLick100to150),2),...
        mean(behAlignedMean.meanLickNonStimPerRecNoField(:,indLick100to150),2));
    
    behAlignedMeanStat.pRSMeanLickNonStimGoodMeanPerRecField100to150 = ...
        ranksum(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLick100to150),2),...
        mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLick100to150),2));
    
    behAlignedMeanStat.pRSLickTraceNonStimMeanPerRecField100to150 = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimPerRecField(:,indLick100to150),2),...
        mean(behAlignedMean.lickTraceNonStimPerRecNoField(:,indLick100to150),2));
    
    behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecField100to150 = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,indLick100to150),2),...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,indLick100to150),2));
    
    %% distance 150 to 180
    indLick150to180 = find(spaceStepsLick >= 1500 & spaceStepsLick < 1800);
    behAlignedMeanStat.indLick150to180 = indLick150to180;
    behAlignedMeanStat.meanLickPerRecField150to180 = [...
        mean(mean(behAlignedMean.meanLickPerRecField(:,indLick150to180))),...
        mean(mean(behAlignedMean.meanLickPerRecNoField(:,indLick150to180)))];
    behAlignedMeanStat.meanLickNonStimPerRecField150to180 = [...
        mean(mean(behAlignedMean.meanLickNonStimPerRecField(:,indLick150to180))),...
        mean(mean(behAlignedMean.meanLickNonStimPerRecNoField(:,indLick150to180)))];
    behAlignedMeanStat.meanLickNonStimGoodPerRecField150to180 = [...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLick150to180))),...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLick150to180)))];
    behAlignedMeanStat.meanLickNonStimBadPerRecField150to180 = [...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecField(:,indLick150to180))),...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLick150to180)))];
    
    behAlignedMeanStat.pRSMeanLickPerRecField150to180 = ...
        ranksum(reshape(behAlignedMean.meanLickPerRecField(:,indLick150to180),[],1),...
        reshape(behAlignedMean.meanLickPerRecNoField(:,indLick150to180),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimPerRecField150to180 = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimPerRecField(:,indLick150to180),[],1),...
        reshape(behAlignedMean.meanLickNonStimPerRecNoField(:,indLick150to180),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecField150to180 = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLick150to180),[],1),...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLick150to180),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimBadPerRecField150to180 = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,indLick150to180),[],1),...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLick150to180),[],1));
    
    behAlignedMeanStat.pRSMeanLickNonStimMeanPerRecField150to180 = ...
        ranksum(mean(behAlignedMean.meanLickNonStimPerRecField(:,indLick150to180),2),...
        mean(behAlignedMean.meanLickNonStimPerRecNoField(:,indLick150to180),2));
    
    behAlignedMeanStat.pRSMeanLickNonStimGoodMeanPerRecField150to180 = ...
        ranksum(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLick150to180),2),...
        mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLick150to180),2));
    
    behAlignedMeanStat.pRSLickTraceNonStimMeanPerRecField150to180 = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimPerRecField(:,indLick150to180),2),...
        mean(behAlignedMean.lickTraceNonStimPerRecNoField(:,indLick150to180),2));
        
    behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecField150to180 = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,indLick150to180),2),...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,indLick150to180),2));
        
    %% distance after 180
    indLickAfter180 = find(spaceStepsLick >= 1800 & spaceStepsLick < 2100);
    behAlignedMeanStat.indLickAfter180 = indLickAfter180;
    behAlignedMeanStat.meanLickPerRecFieldAfter180 = [...
        mean(mean(behAlignedMean.meanLickPerRecField(:,indLickAfter180))),...
        mean(mean(behAlignedMean.meanLickPerRecNoField(:,indLickAfter180)))];
    behAlignedMeanStat.meanLickNonStimPerRecFieldAfter180 = [...
        mean(mean(behAlignedMean.meanLickNonStimPerRecField(:,indLickAfter180))),...
        mean(mean(behAlignedMean.meanLickNonStimPerRecNoField(:,indLickAfter180)))];
    behAlignedMeanStat.meanLickNonStimGoodPerRecFieldAfter180 = [...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLickAfter180))),...
        mean(mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLickAfter180)))];
    behAlignedMeanStat.meanLickNonStimBadPerRecFieldAfter180 = [...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecField(:,indLickAfter180))),...
        mean(mean(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLickAfter180)))];
    
    behAlignedMeanStat.pRSMeanLickPerRecFieldAfter180 = ...
        ranksum(reshape(behAlignedMean.meanLickPerRecField(:,indLickAfter180),[],1),...
        reshape(behAlignedMean.meanLickPerRecNoField(:,indLickAfter180),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimPerRecFieldAfter180 = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimPerRecField(:,indLickAfter180),[],1),...
        reshape(behAlignedMean.meanLickNonStimPerRecNoField(:,indLickAfter180),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecFieldAfter180 = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLickAfter180),[],1),...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLickAfter180),[],1));
    behAlignedMeanStat.pRSMeanLickNonStimBadPerRecFieldAfter180 = ...
        ranksum(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,indLickAfter180),[],1),...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,indLickAfter180),[],1));
    
    behAlignedMeanStat.pRSMeanLickNonStimMeanPerRecFieldAfter180 = ...
        ranksum(mean(behAlignedMean.meanLickNonStimPerRecField(:,indLickAfter180),2),...
        mean(behAlignedMean.meanLickNonStimPerRecNoField(:,indLickAfter180),2));
    
    behAlignedMeanStat.pRSMeanLickNonStimGoodMeanPerRecFieldAfter180 = ...
        ranksum(mean(behAlignedMean.meanLickNonStimGoodPerRecField(:,indLickAfter180),2),...
        mean(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,indLickAfter180),2));
    
    behAlignedMeanStat.pRSLickTraceNonStimMeanPerRecFieldAfter180 = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimPerRecField(:,indLickAfter180),2),...
        mean(behAlignedMean.lickTraceNonStimPerRecNoField(:,indLickAfter180),2));
    
    behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecFieldAfter180 = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,indLickAfter180),2),...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,indLickAfter180),2));
    
    %% total mean
    behAlignedMeanStat.meanSpeedPerRecField = [...
        mean(behAlignedMean.meanSpeedPerRecField(:)),...
        mean(behAlignedMean.meanSpeedPerRecNoField(:))];
    behAlignedMeanStat.meanSpeedNonStimPerRecField = [...
        mean(behAlignedMean.meanSpeedNonStimPerRecField(:)),...
        mean(behAlignedMean.meanSpeedNonStimPerRecNoField(:))];
    behAlignedMeanStat.meanSpeedNonStimGoodPerRecField = [...
        mean(behAlignedMean.meanSpeedNonStimGoodPerRecField(:)),...
        mean(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:))];
    behAlignedMeanStat.meanSpeedNonStimBadPerRecField = [...
        mean(behAlignedMean.meanSpeedNonStimBadPerRecField(:)),...
        mean(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:))];
    
    behAlignedMeanStat.pRSMeanSpeedPerRecField = ...
        ranksum(behAlignedMean.meanSpeedPerRecField(:),...
        behAlignedMean.meanSpeedPerRecNoField(:));
    behAlignedMeanStat.pRSMeanSpeedNonStimPerRecField = ...
        ranksum(behAlignedMean.meanSpeedNonStimPerRecField(:),...
        behAlignedMean.meanSpeedNonStimPerRecNoField(:));
    behAlignedMeanStat.pRSMeanSpeedNonStimGoodPerRecField = ...
        ranksum(behAlignedMean.meanSpeedNonStimGoodPerRecField(:),...
        behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:));
    behAlignedMeanStat.pRSMeanSpeedNonStimBadPerRecField = ...
        ranksum(behAlignedMean.meanSpeedNonStimBadPerRecField(:),...
        behAlignedMean.meanSpeedNonStimBadPerRecNoField(:));
    
    behAlignedMeanStat.pRSMeanSpeedNonStimMeanPerRecField = ...
        ranksum(mean(behAlignedMean.meanSpeedNonStimPerRecField,2),...
        mean(behAlignedMean.meanSpeedNonStimPerRecNoField,2));
    
    behAlignedMeanStat.pRSMeanSpeedNonStimGoodMeanPerRecField = ...
        ranksum(mean(behAlignedMean.meanSpeedNonStimGoodPerRecField,2),...
        mean(behAlignedMean.meanSpeedNonStimGoodPerRecNoField,2));
    
    behAlignedMeanStat.pRSSpeedTraceNonStimMeanPerRecField = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimPerRecField,2),...
        mean(behAlignedMean.speedTraceNonStimPerRecNoField,2));
    
    behAlignedMeanStat.pRSSpeedTraceNonStimGoodMeanPerRecField = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimGoodPerRecField,2),...
        mean(behAlignedMean.speedTraceNonStimGoodPerRecNoField,2));
    
    %% distance 30 to 100
    indSpeed30to100 = find(spaceStepsSpeed >= 300 & spaceStepsSpeed < 1000);
    behAlignedMeanStat.indSpeed30to100 = indSpeed30to100;
    behAlignedMeanStat.meanSpeedPerRecField30to100 = [...
        mean(mean(behAlignedMean.meanSpeedPerRecField(:,indSpeed30to100))),...
        mean(mean(behAlignedMean.meanSpeedPerRecNoField(:,indSpeed30to100)))];
    behAlignedMeanStat.meanSpeedNonStimPerRecField30to100 = [...
        mean(mean(behAlignedMean.meanSpeedNonStimPerRecField(:,indSpeed30to100))),...
        mean(mean(behAlignedMean.meanSpeedNonStimPerRecNoField(:,indSpeed30to100)))];
    behAlignedMeanStat.meanSpeedNonStimGoodPerRecField30to100 = [...
        mean(mean(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,indSpeed30to100))),...
        mean(mean(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,indSpeed30to100)))];
    behAlignedMeanStat.meanSpeedNonStimBadPerRecField30to100 = [...
        mean(mean(behAlignedMean.meanSpeedNonStimBadPerRecField(:,indSpeed30to100))),...
        mean(mean(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:,indSpeed30to100)))];
    
    behAlignedMeanStat.pRSMeanSpeedPerRecField30to100 = ...
        ranksum(reshape(behAlignedMean.meanSpeedPerRecField(:,indSpeed30to100),[],1),...
        reshape(behAlignedMean.meanSpeedPerRecNoField(:,indSpeed30to100),[],1));
    behAlignedMeanStat.pRSMeanSpeedNonStimPerRecField30to100 = ...
        ranksum(reshape(behAlignedMean.meanSpeedNonStimPerRecField(:,indSpeed30to100),[],1),...
        reshape(behAlignedMean.meanSpeedNonStimPerRecNoField(:,indSpeed30to100),[],1));
    behAlignedMeanStat.pRSMeanSpeedNonStimGoodPerRecField30to100 = ...
        ranksum(reshape(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,indSpeed30to100),[],1),...
        reshape(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,indSpeed30to100),[],1));
    behAlignedMeanStat.pRSMeanSpeedNonStimBadPerRecField30to100 = ...
        ranksum(reshape(behAlignedMean.meanSpeedNonStimBadPerRecField(:,indSpeed30to100),[],1),...
        reshape(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:,indSpeed30to100),[],1));
    
    behAlignedMeanStat.pRSMeanSpeedNonStimMeanPerRecField30to100 = ...
        ranksum(mean(behAlignedMean.meanSpeedNonStimPerRecField(:,indSpeed30to100),2),...
        mean(behAlignedMean.meanSpeedNonStimPerRecNoField(:,indSpeed30to100),2));
    
    behAlignedMeanStat.pRSMeanSpeedNonStimGoodMeanPerRecField30to100 = ...
        ranksum(mean(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,indSpeed30to100),2),...
        mean(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,indSpeed30to100),2));
    
    behAlignedMeanStat.pRSSpeedTraceNonStimMeanPerRecField30to100 = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimPerRecField(:,indSpeed30to100),2),...
        mean(behAlignedMean.speedTraceNonStimPerRecNoField(:,indSpeed30to100),2));
    
    behAlignedMeanStat.pRSSpeedTraceNonStimGoodMeanPerRecField30to100 = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimGoodPerRecField(:,indSpeed30to100),2),...
        mean(behAlignedMean.speedTraceNonStimGoodPerRecNoField(:,indSpeed30to100),2));
    
    %% distance > 100
    indSpeedAfter100 = find(spaceStepsSpeed >= 1000);
    behAlignedMeanStat.indSpeedAfter100 = indSpeedAfter100;
    behAlignedMeanStat.meanSpeedPerRecFieldAfter100 = [...
        mean(mean(behAlignedMean.meanSpeedPerRecField(:,indSpeedAfter100))),...
        mean(mean(behAlignedMean.meanSpeedPerRecNoField(:,indSpeedAfter100)))];
    behAlignedMeanStat.meanSpeedNonStimPerRecFieldAfter100 = [...
        mean(mean(behAlignedMean.meanSpeedNonStimPerRecField(:,indSpeedAfter100))),...
        mean(mean(behAlignedMean.meanSpeedNonStimPerRecNoField(:,indSpeedAfter100)))];
    behAlignedMeanStat.meanSpeedNonStimGoodPerRecFieldAfter100 = [...
        mean(mean(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,indSpeedAfter100))),...
        mean(mean(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,indSpeedAfter100)))];
    behAlignedMeanStat.meanSpeedNonStimBadPerRecFieldAfter100 = [...
        mean(mean(behAlignedMean.meanSpeedNonStimBadPerRecField(:,indSpeedAfter100))),...
        mean(mean(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:,indSpeedAfter100)))];
    
    behAlignedMeanStat.pRSMeanSpeedPerRecFieldAfter100 = ...
        ranksum(reshape(behAlignedMean.meanSpeedPerRecField(:,indSpeedAfter100),[],1),...
        reshape(behAlignedMean.meanSpeedPerRecNoField(:,indSpeedAfter100),[],1));
    behAlignedMeanStat.pRSMeanSpeedNonStimPerRecFieldAfter100 = ...
        ranksum(reshape(behAlignedMean.meanSpeedNonStimPerRecField(:,indSpeedAfter100),[],1),...
        reshape(behAlignedMean.meanSpeedNonStimPerRecNoField(:,indSpeedAfter100),[],1));
    behAlignedMeanStat.pRSMeanSpeedNonStimGoodPerRecFieldAfter100 = ...
        ranksum(reshape(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,indSpeedAfter100),[],1),...
        reshape(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,indSpeedAfter100),[],1));
    behAlignedMeanStat.pRSMeanSpeedNonStimBadPerRecFieldAfter100 = ...
        ranksum(reshape(behAlignedMean.meanSpeedNonStimBadPerRecField(:,indSpeedAfter100),[],1),...
        reshape(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:,indSpeedAfter100),[],1));
    
    behAlignedMeanStat.pRSMeanSpeedNonStimMeanPerRecFieldAfter100 = ...
        ranksum(mean(behAlignedMean.meanSpeedNonStimPerRecField(:,indSpeedAfter100),2),...
        mean(behAlignedMean.meanSpeedNonStimPerRecNoField(:,indSpeedAfter100),2));
    
    behAlignedMeanStat.pRSMeanSpeedNonStimGoodMeanPerRecFieldAfter100 = ...
        ranksum(mean(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,indSpeedAfter100),2),...
        mean(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,indSpeedAfter100),2));
    
    behAlignedMeanStat.pRSSpeedTraceNonStimMeanPerRecFieldAfter100 = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimPerRecField(:,indSpeedAfter100),2),...
        mean(behAlignedMean.speedTraceNonStimPerRecNoField(:,indSpeedAfter100),2));

    behAlignedMeanStat.pRSSpeedTraceNonStimGoodMeanPerRecFieldAfter100 = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimGoodPerRecField(:,indSpeedAfter100),2),...
        mean(behAlignedMean.speedTraceNonStimGoodPerRecNoField(:,indSpeedAfter100),2));

end