function behAlignedMeanStat = accumMeanBehStatGoodBad(behAlignedMean,spaceStepsLick,spaceStepsSpeed)
% statistics for good vs bad trials
% this function is called by PyrBehAlignedAllRec.m

    %% added on 7/1/2022
    behAlignedMeanStat.meanPercRewardedNonStim = ...
        [mean(behAlignedMean.percRewardedNonStimGood),...
        mean(behAlignedMean.percRewardedNonStimBad)];
    behAlignedMeanStat.stdPercRewardedNonStim = ...
        [std(behAlignedMean.percRewardedNonStimGood)/...
        sqrt(length(behAlignedMean.percRewardedNonStimGood)),...
        std(behAlignedMean.percRewardedNonStimBad)/...
        sqrt(length(behAlignedMean.percRewardedNonStimBad))]; 
    
    behAlignedMeanStat.pRSMeanPercRewardedNonStim = ...
        ranksum(behAlignedMean.percRewardedNonStimGood,...
        behAlignedMean.percRewardedNonStimBad);
    
    %% total stop time, added on 6/9/2022
    behAlignedMeanStat.meanMeanTotStopLenTPerRec = [...
        mean(behAlignedMean.meanTotStopLenTPerRecNonStimGood),...
        mean(behAlignedMean.meanTotStopLenTPerRecNonStimBad)];
    behAlignedMeanStat.stdMeanTotStopLenTPerRec = [...
        std(behAlignedMean.meanTotStopLenTPerRecNonStimGood)/...
            sqrt(length(behAlignedMean.meanTotStopLenTPerRecNonStimGood)),...
        std(behAlignedMean.meanTotStopLenTPerRecNonStimBad)/...
            sqrt(length(behAlignedMean.meanTotStopLenTPerRecNonStimBad))];
    
    behAlignedMeanStat.pRSMeanTotStopLenTPerRec = ...
        ranksum(behAlignedMean.meanTotStopLenTPerRecNonStimGood,...
        behAlignedMean.meanTotStopLenTPerRecNonStimBad);
    
    behAlignedMeanStat.meanTotStopLenTPerRec = [...
        mean(behAlignedMean.totStopLenTNonStimGoodPerRec),...
        mean(behAlignedMean.totStopLenTNonStimBadPerRec)];
    behAlignedMeanStat.stdTotStopLenTPerRec = [...
        std(behAlignedMean.totStopLenTNonStimGoodPerRec)/...
            sqrt(length(behAlignedMean.totStopLenTNonStimGoodPerRec)),...
        std(behAlignedMean.totStopLenTNonStimBadPerRec)/...
            sqrt(length(behAlignedMean.totStopLenTNonStimBadPerRec))];
        
    behAlignedMeanStat.pRSTotStopLenTPerRec = ...
        ranksum(behAlignedMean.totStopLenTNonStimGoodPerRec,...
        behAlignedMean.totStopLenTNonStimBadPerRec);
    
    %% total mean
    indLickAfter30 = find(spaceStepsLick >= 300 & spaceStepsLick < 2100);
    behAlignedMeanStat.indLickAfter30 = indLickAfter30;
    behAlignedMeanStat.meanLickPerRec = [...
        mean(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLickAfter30),2)),...
        mean(mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLickAfter30),2))];
    behAlignedMeanStat.stdLickPerRec = [...
        std(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLickAfter30),2))/...
            sqrt(size(behAlignedMean.meanLickPerRecNonStimGood,1)),...
        std(mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLickAfter30),2))/...
            sqrt(size(behAlignedMean.meanLickPerRecNonStimBad,1))];% added on 6/7/2022
    
    behAlignedMeanStat.pRSLickTracePerRec = ...
        ranksum(reshape(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLickAfter30),[],1),...
        reshape(behAlignedMean.lickTraceNonStimBadPerRec(:,indLickAfter30),[],1));
    
    behAlignedMeanStat.pRSMeanLickMeanPerRec = ...
        ranksum(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLickAfter30),2),...
        mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLickAfter30),2));
            
    behAlignedMeanStat.pRSMeanLickTracePerRec = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLickAfter30),2),...
        mean(behAlignedMean.lickTraceNonStimBadPerRec(:,indLickAfter30),2));

    %% distance 30 to 100
    indLick30to100 = find(spaceStepsLick >= 300 & spaceStepsLick < 1000);
    behAlignedMeanStat.indLick30to100 = indLick30to100;
    behAlignedMeanStat.meanLickPerRec30to100 = [...
        mean(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLick30to100),2)),...
        mean(mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLick30to100),2))];
    behAlignedMeanStat.stdLickPerRec30to100 = [...
        std(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLick30to100),2))/...
            sqrt(size(behAlignedMean.meanLickPerRecNonStimGood,1)),...
        std(mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLick30to100),2))/...
            sqrt(size(behAlignedMean.meanLickPerRecNonStimBad,1))]; % added on 5/10/2022
    
    behAlignedMeanStat.pRSLickTracePerRec30to100 = ...
        ranksum(reshape(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLick30to100),[],1),...
        reshape(behAlignedMean.lickTraceNonStimBadPerRec(:,indLick30to100),[],1));
    
    behAlignedMeanStat.pRSMeanLickMeanPerRec30to100 = ...
        ranksum(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLick30to100),2),...
        mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLick30to100),2));
            
    behAlignedMeanStat.pRSMeanLickTracePerRec30to100 = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLick30to100),2),...
        mean(behAlignedMean.lickTraceNonStimBadPerRec(:,indLick30to100),2));
    
    %% distance 100 to 150
    indLick100to150 = find(spaceStepsLick >= 1000 & spaceStepsLick < 1500);
    behAlignedMeanStat.indLick100to150 = indLick100to150;
    behAlignedMeanStat.meanLickPerRec100to150 = [...
        mean(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLick100to150),2)),...
        mean(mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLick100to150),2))];
    behAlignedMeanStat.stdLickPerRec100to150 = [...
        std(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLick100to150),2))/...
            sqrt(size(behAlignedMean.meanLickPerRecNonStimGood,1)),...
        std(mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLick100to150),2))/...
            sqrt(size(behAlignedMean.meanLickPerRecNonStimBad,1))];% added on 5/10/2022
    
    behAlignedMeanStat.pRSLickTracePerRec100to150 = ...
        ranksum(reshape(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLick100to150),[],1),...
        reshape(behAlignedMean.lickTraceNonStimBadPerRec(:,indLick100to150),[],1));
    
    behAlignedMeanStat.pRSMeanLickMeanPerRec100to150 = ...
        ranksum(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLick100to150),2),...
        mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLick100to150),2));
            
    behAlignedMeanStat.pRSMeanLickTracePerRec100to150 = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLick100to150),2),...
        mean(behAlignedMean.lickTraceNonStimBadPerRec(:,indLick100to150),2));
    
    %% distance 150 to 180
    indLick150to180 = find(spaceStepsLick >= 1500 & spaceStepsLick < 1800);
    behAlignedMeanStat.indLick150to180 = indLick150to180;
    behAlignedMeanStat.meanLickPerRec150to180 = [...
        mean(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLick150to180))),...
        mean(mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLick150to180)))];
    behAlignedMeanStat.stdLickPerRec150to180 = [...
        std(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLick150to180),2))/...
            sqrt(size(behAlignedMean.meanLickPerRecNonStimGood,1)),...
        std(mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLick150to180),2))/...
            sqrt(size(behAlignedMean.meanLickPerRecNonStimBad,1))];% added on 6/7/2022
        
    behAlignedMeanStat.pRSLickTracePerRec150to180 = ...
        ranksum(reshape(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLick150to180),[],1),...
        reshape(behAlignedMean.lickTraceNonStimBadPerRec(:,indLick150to180),[],1));
    
    behAlignedMeanStat.pRSMeanLickMeanPerRec150to180 = ...
        ranksum(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLick150to180),2),...
        mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLick150to180),2));
            
    behAlignedMeanStat.pRSMeanLickTracePerRec150to180 = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLick150to180),2),...
        mean(behAlignedMean.lickTraceNonStimBadPerRec(:,indLick150to180),2));
        
    %% distance after 180
    indLickAfter180 = find(spaceStepsLick >= 1800 & spaceStepsLick < 2100);
    behAlignedMeanStat.indLickAfter180 = indLickAfter180;
    behAlignedMeanStat.meanLickPerRecAfter180 = [...
        mean(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLickAfter180))),...
        mean(mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLickAfter180)))];
    behAlignedMeanStat.stdLickPerRecAfter180 = [...
        std(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLickAfter180),2))/...
            sqrt(size(behAlignedMean.meanLickPerRecNonStimGood,1)),...
        std(mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLickAfter180),2))/...
            sqrt(size(behAlignedMean.meanLickPerRecNonStimBad,1))];% added on 6/7/2022
        
    behAlignedMeanStat.pRSLickTracePerRecAfter180 = ...
        ranksum(reshape(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLickAfter180),[],1),...
        reshape(behAlignedMean.lickTraceNonStimBadPerRec(:,indLickAfter180),[],1));
    
    behAlignedMeanStat.pRSMeanLickMeanPerRecAfter180 = ...
        ranksum(mean(behAlignedMean.meanLickPerRecNonStimGood(:,indLickAfter180),2),...
        mean(behAlignedMean.meanLickPerRecNonStimBad(:,indLickAfter180),2));
            
    behAlignedMeanStat.pRSMeanLickTracePerRecAfter180 = ...
        ranksum(mean(behAlignedMean.lickTraceNonStimGoodPerRec(:,indLickAfter180),2),...
        mean(behAlignedMean.lickTraceNonStimBadPerRec(:,indLickAfter180),2));
    
    %% total mean
    behAlignedMeanStat.meanSpeedPerRec = [...
        mean(behAlignedMean.meanSpeedPerRecNonStimGood(:)),...
        mean(behAlignedMean.meanSpeedPerRecNonStimBad(:))];
    behAlignedMeanStat.stdSpeedPerRec = [...
        std(mean(behAlignedMean.meanSpeedPerRecNonStimGood,2))/...
            sqrt(size(behAlignedMean.meanSpeedPerRecNonStimGood,1)),...
        std(mean(behAlignedMean.meanSpeedPerRecNonStimGood,2))/...
            sqrt(size(behAlignedMean.meanSpeedPerRecNonStimGood,1))];% added on 6/7/2022
        
    behAlignedMeanStat.pRSSpeedTracePerRec = ...
        ranksum(behAlignedMean.speedTraceNonStimGoodPerRec(:),...
        behAlignedMean.speedTraceNonStimBadPerRec(:));
    
    behAlignedMeanStat.pRSMeanSpeedMeanPerRec = ...
        ranksum(mean(behAlignedMean.meanSpeedPerRecNonStimGood,2),...
        mean(behAlignedMean.meanSpeedPerRecNonStimBad,2));
    
    behAlignedMeanStat.pRSMeanSpeedTracePerRec = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimGoodPerRec,2),...
        mean(behAlignedMean.speedTraceNonStimBadPerRec,2));
    
    %% distance 30 to 100
    indSpeed30to100 = find(spaceStepsSpeed >= 300 & spaceStepsSpeed < 1000);
    behAlignedMeanStat.indSpeed30to100 = indSpeed30to100;
    behAlignedMeanStat.meanSpeedPerRec30to100 = [...
        mean(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeed30to100))),...
        mean(mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,indSpeed30to100)))];
    behAlignedMeanStat.stdSpeedPerRec30to100 = [...
        std(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeed30to100),2))/...
            sqrt(size(behAlignedMean.meanSpeedPerRecNonStimGood,1)),...
        std(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeed30to100),2))/...
            sqrt(size(behAlignedMean.meanSpeedPerRecNonStimGood,1))];% added on 6/7/2022
    
    behAlignedMeanStat.pRSSpeedTracePerRec30to100 = ...
        ranksum(reshape(behAlignedMean.speedTraceNonStimGoodPerRec(:,indSpeed30to100),[],1),...
        reshape(behAlignedMean.speedTraceNonStimBadPerRec(:,indSpeed30to100),[],1));
    
    behAlignedMeanStat.pRSMeanSpeedMeanPerRec30to100 = ...
        ranksum(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeed30to100),2),...
        mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,indSpeed30to100),2));
    
    behAlignedMeanStat.pRSMeanSpeedTracePerRec30to100 = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimGoodPerRec(:,indSpeed30to100),2),...
        mean(behAlignedMean.speedTraceNonStimBadPerRec(:,indSpeed30to100),2));
    
    %% distance > 100
    indSpeedAfter100 = find(spaceStepsSpeed >= 1000);
    behAlignedMeanStat.indSpeedAfter100 = indSpeedAfter100;
    behAlignedMeanStat.meanSpeedPerRecAfter100 = [...
        mean(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeedAfter100))),...
        mean(mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,indSpeedAfter100)))];
    behAlignedMeanStat.stdSpeedPerRecAfter100 = [...
        std(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeedAfter100),2))/...
            sqrt(size(behAlignedMean.meanSpeedPerRecNonStimGood,1)),...
        std(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeedAfter100),2))/...
            sqrt(size(behAlignedMean.meanSpeedPerRecNonStimGood,1))];% added on 6/7/2022
    
    behAlignedMeanStat.pRSSpeedTracePerRecAfter100 = ...
        ranksum(reshape(behAlignedMean.speedTraceNonStimGoodPerRec(:,indSpeedAfter100),[],1),...
        reshape(behAlignedMean.speedTraceNonStimBadPerRec(:,indSpeedAfter100),[],1));
    
    behAlignedMeanStat.pRSMeanSpeedMeanPerRecAfter100 = ...
        ranksum(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,indSpeedAfter100),2),...
        mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,indSpeedAfter100),2));
    
    behAlignedMeanStat.pRSMeanSpeedTracePerRecAfter100 = ...
        ranksum(mean(behAlignedMean.speedTraceNonStimGoodPerRec(:,indSpeedAfter100),2),...
        mean(behAlignedMean.speedTraceNonStimBadPerRec(:,indSpeedAfter100),2));
    
end
