function plotBehMeanALNoCue(pathAnal,behAL,behNoCue,behMeanStat)
% compare behavior of no cue and AL sessions
% this function is called by PyrBehALNoCue.m
    
    
    % total licks
    plotStat(mean(behAL.meanLickPerRec(:,behMeanStat.indLickAfter30),2)',...
        mean(behNoCue.meanLickPerRec(:,behMeanStat.indLickAfter30),2)',...
        behMeanStat.meanLickPerRec,behMeanStat.stdLickPerRec,...
        behMeanStat.pRSMeanLickMean,...
        [],'No. licks',[],'meanLickPerRecALVsNoCueBar',...
        pathAnal);
   
    % distance 30 to 100 cm
    plotStat(mean(behAL.meanLickPerRec(:,behMeanStat.indLick30to100),2)',...
        mean(behNoCue.meanLickPerRec(:,behMeanStat.indLick30to100),2)',...
        behMeanStat.meanLickPerRec30to100,behMeanStat.stdLickPerRec30to100,...
        behMeanStat.pRSMeanLickMean30to100,...
        [],'No. licks (30-100 cm)',[],'meanLickPerRecALVsNoCue30to100Bar',...
        pathAnal);
    
    % distance 100 to 140 cm
    plotStat(mean(behAL.meanLickPerRec(:,behMeanStat.indLick100to140),2)',...
        mean(behNoCue.meanLickPerRec(:,behMeanStat.indLick100to140),2)',...
        behMeanStat.meanLickPerRec100to140,behMeanStat.stdLickPerRec100to140,...
        behMeanStat.pRSMeanLickMean100to140,...
        [],'No. licks (100-140 cm)',[],'meanLickPerRecALVsNoCue100to140Bar',...
        pathAnal);
    
    % distance 100 to 180 cm
    plotStat(mean(behAL.meanLickPerRec(:,behMeanStat.indLick100to180),2)',...
        mean(behNoCue.meanLickPerRec(:,behMeanStat.indLick100to180),2)',...
        behMeanStat.meanLickPerRec100to180,behMeanStat.stdLickPerRec100to180,...
        behMeanStat.pRSMeanLickMean100to180,...
        [],'No. licks (100-180 cm)',[],'meanLickPerRecALVsNoCue100to180Bar',...
        pathAnal);
        
    % distance 140 to 180 cm
    plotStat(mean(behAL.meanLickPerRec(:,behMeanStat.indLick140to180),2)',...
        mean(behNoCue.meanLickPerRec(:,behMeanStat.indLick140to180),2)',...
        behMeanStat.meanLickPerRec140to180,behMeanStat.stdLickPerRec140to180,...
        behMeanStat.pRSMeanLickMean140to180,...
        [],'No. licks (140-180 cm)',[],'meanLickPerRecALVsNoCue140to180Bar',...
        pathAnal);
   
    % distance after 180 cm
    plotStat(mean(behAL.meanLickPerRec(:,behMeanStat.indLickAfter180),2)',...
        mean(behNoCue.meanLickPerRec(:,behMeanStat.indLickAfter180),2)',...
        behMeanStat.meanLickPerRecAfter180,behMeanStat.stdLickPerRecAfter180,...
        behMeanStat.pRSMeanLickMeanAfter180,...
        [],'No. licks (>=180 cm)',[],'meanLickPerRecALVsNoCueAfter180Bar',...
        pathAnal);
    
    % mean speed
    plotStat(mean(behAL.meanSpeedPerRec,2)'/10,...
        mean(behNoCue.meanSpeedPerRec,2)'/10,...
        behMeanStat.meanSpeedPerRec,behMeanStat.stdSpeedPerRec,...
        behMeanStat.pRSMeanSpeedMean,...
        [],'Speed (cm/s)',[],'meanSpeedPerRecALVsNoCueBar',...
        pathAnal);
   
    % distance 0 to 30 cm
    plotStat(mean(behAL.meanSpeedPerRec(:,behMeanStat.indSpeed0to30),2)'/10,...
        mean(behNoCue.meanSpeedPerRec(:,behMeanStat.indSpeed0to30),2)'/10,...
        behMeanStat.meanSpeedPerRec0to30,behMeanStat.stdSpeedPerRec0to30,...
        behMeanStat.pRSMeanSpeedMean0to30,...
        [],'Speed (cm/s) (0-30 cm)',[],'meanSpeedPerRecALVsNoCue0to30Bar',...
        pathAnal);
   
    % distance 30 to 100 cm
    plotStat(mean(behAL.meanSpeedPerRec(:,behMeanStat.indSpeed30to100),2)'/10,...
        mean(behNoCue.meanSpeedPerRec(:,behMeanStat.indSpeed30to100),2)'/10,...
        behMeanStat.meanSpeedPerRec30to100,behMeanStat.stdSpeedPerRec30to100,...
        behMeanStat.pRSMeanSpeedMean30to100,...
        [],'Speed (cm/s) (30-100 cm)',[],'meanSpeedPerRecALVsNoCue30to100Bar',...
        pathAnal);
   
    % distance after 100 cm
    plotStat(mean(behAL.meanSpeedPerRec(:,behMeanStat.indSpeedAfter100),2)'/10,...
        mean(behNoCue.meanSpeedPerRec(:,behMeanStat.indSpeedAfter100),2)'/10,...
        behMeanStat.meanSpeedPerRecAfter100,behMeanStat.stdSpeedPerRecAfter100,...
        behMeanStat.pRSMeanSpeedMeanAfter100,...
        [],'Speed (cm/s) (>100 cm)',[],'meanSpeedPerRecALVsNoCueAfter100Bar',...
        pathAnal);
   
    
end