function plotBehTimeAlignedMeanGoodBadBar(pathAnal,behAlignedMean,behAlignedMeanStat,colorSel)
% compare behavior of good vs bad trials (bar plots)
% this function is called by PyrBehAlignedAllRec.m
    
   
    %  bef 4 sec
    plotStat(mean(behAlignedMean.meanLickPerRecNonStimGood(:,behAlignedMeanStat.indLickBef4s),2)',...
        mean(behAlignedMean.meanLickPerRecNonStimBad(:,behAlignedMeanStat.indLickBef4s),2)',...
        behAlignedMeanStat.meanLickPerRec,behAlignedMeanStat.stdLickPerRec,...
        behAlignedMeanStat.pRSMeanLickMeanPerRec,...
        [],'No. licks (Bef 4s)',[],'meanLickPerRecGoodVsBadBef4sBar',...
        pathAnal);
    
    %  bef 2 sec
    plotStat(mean(behAlignedMean.meanLickPerRecNonStimGood(:,behAlignedMeanStat.indLickBef2s),2)',...
        mean(behAlignedMean.meanLickPerRecNonStimBad(:,behAlignedMeanStat.indLickBef2s),2)',...
        behAlignedMeanStat.meanLickPerRecBef2s,behAlignedMeanStat.stdLickPerRecBef2s,...
        behAlignedMeanStat.pRSMeanLickMeanPerRecBef2s,...
        [],'No. licks (Bef 2s)',[],'meanLickPerRecGoodVsBadBef2sBar',...
        pathAnal);

    %  bef 1 sec
    plotStat(mean(behAlignedMean.meanLickPerRecNonStimGood(:,behAlignedMeanStat.indLickBef1s),2)',...
        mean(behAlignedMean.meanLickPerRecNonStimBad(:,behAlignedMeanStat.indLickBef1s),2)',...
        behAlignedMeanStat.meanLickPerRecBef1s,behAlignedMeanStat.stdLickPerRecBef1s,...
        behAlignedMeanStat.pRSMeanLickMeanPerRecBef1s,...
        [],'No. licks (Bef 1s)',[],'meanLickPerRecGoodVsBadBef1sBar',...
        pathAnal);

    %  between 1 to 2s
    plotStat(mean(behAlignedMean.meanLickPerRecNonStimGood(:,behAlignedMeanStat.indLick1to2s),2)',...
        mean(behAlignedMean.meanLickPerRecNonStimBad(:,behAlignedMeanStat.indLick1to2s),2)',...
        behAlignedMeanStat.meanLickPerRec1to2s,behAlignedMeanStat.stdLickPerRec1to2s,...
        behAlignedMeanStat.pRSMeanLickMeanPerRec1to2s,...
        [],'No. licks (1to2s)',[],'meanLickPerRecGoodVsBad1to2sBar',...
        pathAnal);

    %  between 2 to 3s
    plotStat(mean(behAlignedMean.meanLickPerRecNonStimGood(:,behAlignedMeanStat.indLick2to3s),2)',...
        mean(behAlignedMean.meanLickPerRecNonStimBad(:,behAlignedMeanStat.indLick2to3s),2)',...
        behAlignedMeanStat.meanLickPerRec2to3s,behAlignedMeanStat.stdLickPerRec2to3s,...
        behAlignedMeanStat.pRSMeanLickMeanPerRec2to3s,...
        [],'No. licks (2to3s)',[],'meanLickPerRecGoodVsBad2to3sBar',...
        pathAnal);

    %  between 3 to 4s
    plotStat(mean(behAlignedMean.meanLickPerRecNonStimGood(:,behAlignedMeanStat.indLick3to4s),2)',...
        mean(behAlignedMean.meanLickPerRecNonStimBad(:,behAlignedMeanStat.indLick3to4s),2)',...
        behAlignedMeanStat.meanLickPerRec3to4s,behAlignedMeanStat.stdLickPerRec3to4s,...
        behAlignedMeanStat.pRSMeanLickMeanPerRec3to4s,...
        [],'No. licks (3to4s)',[],'meanLickPerRecGoodVsBad3to4sBar',...
        pathAnal);
    
   
    % mean speed bef 4s
    plotStat(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,behAlignedMeanStat.indSpeedBef4s),2)'/10,...
        mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,behAlignedMeanStat.indSpeedBef4s),2)'/10,...
        behAlignedMeanStat.meanSpeedPerRec,behAlignedMeanStat.stdSpeedPerRec,...
        behAlignedMeanStat.pRSMeanSpeedMeanPerRec,...
        [],'Speed (cm/s, Bef 4s)',[],'meanSpeedPerRecGoodVsBadBar',...
        pathAnal);
    
    % Bef 2s
    plotStat(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,behAlignedMeanStat.indSpeedBef2s),2)'/10,...
        mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,behAlignedMeanStat.indSpeedBef2s),2)'/10,...
        behAlignedMeanStat.meanSpeedPerRecBef2s,behAlignedMeanStat.stdSpeedPerRecBef2s,...
        behAlignedMeanStat.pRSMeanSpeedMeanPerRecBef2s,...
        [],'Speed (cm/s) (Bef 2s)',[],'meanSpeedPerRecGoodVsBadBef2sBar',...
        pathAnal);
   
    % Bef 1s
    plotStat(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,behAlignedMeanStat.indSpeedBef1s),2)'/10,...
        mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,behAlignedMeanStat.indSpeedBef1s),2)'/10,...
        behAlignedMeanStat.meanSpeedPerRecBef1s,behAlignedMeanStat.stdSpeedPerRecBef1s,...
        behAlignedMeanStat.pRSMeanSpeedMeanPerRecBef1s,...
        [],'Speed (cm/s) (Bef 1s)',[],'meanSpeedPerRecGoodVsBadBef1sBar',...
        pathAnal);
   
    % Between 1 to 2 s
    plotStat(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,behAlignedMeanStat.indSpeed1to2s),2)'/10,...
        mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,behAlignedMeanStat.indSpeed1to2s),2)'/10,...
        behAlignedMeanStat.meanSpeedPerRec1to2s,behAlignedMeanStat.stdSpeedPerRec1to2s,...
        behAlignedMeanStat.pRSMeanSpeedMeanPerRec1to2s,...
        [],'Speed (cm/s) (1-2s)',[],'meanSpeedPerRecGoodVsBad1to2sBar',...
        pathAnal);

    % Between 2 to 3 s
    plotStat(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,behAlignedMeanStat.indSpeed2to3s),2)'/10,...
        mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,behAlignedMeanStat.indSpeed2to3s),2)'/10,...
        behAlignedMeanStat.meanSpeedPerRec2to3s,behAlignedMeanStat.stdSpeedPerRec2to3s,...
        behAlignedMeanStat.pRSMeanSpeedMeanPerRec2to3s,...
        [],'Speed (cm/s) (2-3s)',[],'meanSpeedPerRecGoodVsBad2to3sBar',...
        pathAnal);
   
    % Between 3 to 4 s
    plotStat(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,behAlignedMeanStat.indSpeed3to4s),2)'/10,...
        mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,behAlignedMeanStat.indSpeed3to4s),2)'/10,...
        behAlignedMeanStat.meanSpeedPerRec3to4s,behAlignedMeanStat.stdSpeedPerRec3to4s,...
        behAlignedMeanStat.pRSMeanSpeedMeanPerRec3to4s,...
        [],'Speed (cm/s) (3-4s)',[],'meanSpeedPerRecGoodVsBad3to4sBar',...
        pathAnal);
end