function plotBehTimeAlignedMean(pathAnal,behAlignedMean,behAlignedMeanStat,colorSel)
% compare behavior of recordings with and without fields
% this function is called by PyrBehAlignedAllRec.m

    % mean licks before 4 sec
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,behAlignedMeanStat.indLickBef4s),[],1)',...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLickBef4s),[],1)',...
        'No. licks (good trials)','meanLickNonStimGoodPerRecFieldVsNoFieldBox',...
        pathAnal,[-0.1 0.5],behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecField,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,behAlignedMeanStat.indLickBef4s),[],1)',...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,behAlignedMeanStat.indLickBef4s),[],1)',...
        'No. licks (bad trials)','meanLickNonStimBadPerRecFieldVsNoFieldBox',...
        pathAnal,[-0.1 0.5],behAlignedMeanStat.pRSMeanLickNonStimBadPerRecField,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimPerRecField(:,behAlignedMeanStat.indLickBef4s),2)',...
        mean(behAlignedMean.lickTraceNonStimPerRecNoField(:,behAlignedMeanStat.indLickBef4s),2)',...
        'No. licks (non-stim trials)','lickTraceNonStimPerRecFieldVsNoFieldBox',...
        pathAnal,[-0.1 0.5],behAlignedMeanStat.pRSLickTraceNonStimMeanPerRecField,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,behAlignedMeanStat.indLickBef4s),2)',...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLickBef4s),2)',...
        'No. licks (good trials)','lickTraceNonStimGoodPerRecFieldVsNoFieldBox',...
        pathAnal,[-0.1 0.5],behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecField,colorSel,[{'F'} {'NoF'}]);
    
    % mean licks before 1 sec
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,behAlignedMeanStat.indLickBef1s),[],1)',...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLickBef1s),[],1)',...
        'No. licks (good trials, bef 1s)','meanLickNonStimGoodPerRecFieldVsNoFieldBef1sBox',...
        pathAnal,[-0.1 0.2],behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecFieldBef1s,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,behAlignedMeanStat.indLickBef1s),[],1)',...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,behAlignedMeanStat.indLickBef1s),[],1)',...
        'No. licks (bad trials, bef 1s)','meanLickNonStimBadPerRecFieldVsNoFieldBef1sBox',...
        pathAnal,[-0.1 0.2],behAlignedMeanStat.pRSMeanLickNonStimBadPerRecFieldBef1s,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimPerRecField(:,behAlignedMeanStat.indLickBef1s),2)',...
        mean(behAlignedMean.lickTraceNonStimPerRecNoField(:,behAlignedMeanStat.indLickBef1s),2)',...
        'No. licks (non-stim trials, bef 1s)','lickTraceNonStimPerRecFieldVsNoFieldBef1sBox',...
        pathAnal,[-0.1 0.2],behAlignedMeanStat.pRSLickTraceNonStimMeanPerRecFieldBef1s,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,behAlignedMeanStat.indLickBef1s),2)',...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLickBef1s),2)',...
        'No. licks (good trials, bef 1s)','lickTraceNonStimGoodPerRecFieldVsNoFieldBef1sBox',...
        pathAnal,[-0.1 0.2],behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecFieldBef1s,colorSel,[{'F'} {'NoF'}]);
    
    % mean licks between 1-2 sec
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,behAlignedMeanStat.indLick1to2s),[],1)',...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLick1to2s),[],1)',...
        'No. licks (good trials, 1-2s)','meanLickNonStimGoodPerRecFieldVsNoField1to2sBox',...
        pathAnal,[-0.1 0.4],behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecField1to2s,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,behAlignedMeanStat.indLick1to2s),[],1)',...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,behAlignedMeanStat.indLick1to2s),[],1)',...
        'No. licks (bad trials, 1-2s)','meanLickNonStimBadPerRecFieldVsNoField1to2sBox',...
        pathAnal,[-0.1 0.4],behAlignedMeanStat.pRSMeanLickNonStimBadPerRecField1to2s,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimPerRecField(:,behAlignedMeanStat.indLick1to2s),2)',...
        mean(behAlignedMean.lickTraceNonStimPerRecNoField(:,behAlignedMeanStat.indLick1to2s),2)',...
        'No. licks (non-stim trials, 1-2s)','lickTraceNonStimPerRecFieldVsNoField1to2sBox',...
        pathAnal,[-0.1 0.4],behAlignedMeanStat.pRSLickTraceNonStimMeanPerRecField1to2s,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,behAlignedMeanStat.indLick1to2s),2)',...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLick1to2s),2)',...
        'No. licks (good trials, 1-2s)','lickTraceNonStimGoodPerRecFieldVsNoField1to2sBox',...
        pathAnal,[-0.1 0.4],behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecField1to2s,colorSel,[{'F'} {'NoF'}]);
    
    % mean licks between 2-3 sec
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,behAlignedMeanStat.indLick2to3s),[],1)',...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLick2to3s),[],1)',...
        'No. licks (good trials, 2-3s)','meanLickNonStimGoodPerRecFieldVsNoField2to3sBox',...
        pathAnal,[-0.1 0.8],behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecField2to3s,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,behAlignedMeanStat.indLick2to3s),[],1)',...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,behAlignedMeanStat.indLick2to3s),[],1)',...
        'No. licks (bad trials, 2-3s)','meanLickNonStimBadPerRecFieldVsNoField2to3sBox',...
        pathAnal,[-0.1 0.8],behAlignedMeanStat.pRSMeanLickNonStimBadPerRecField2to3s,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimPerRecField(:,behAlignedMeanStat.indLick2to3s),2)',...
        mean(behAlignedMean.lickTraceNonStimPerRecNoField(:,behAlignedMeanStat.indLick2to3s),2)',...
        'No. licks (non-stim trials, 2-3s)','lickTraceNonStimPerRecFieldVsNoField2to3sBox',...
        pathAnal,[-0.1 0.9],behAlignedMeanStat.pRSLickTraceNonStimMeanPerRecField2to3s,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,behAlignedMeanStat.indLick2to3s),2)',...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLick2to3s),2)',...
        'No. licks (good trials, 2-3s)','lickTraceNonStimGoodPerRecFieldVsNoField2to3sBox',...
        pathAnal,[-0.1 0.9],behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecField2to3s,colorSel,[{'F'} {'NoF'}]);
    
    % mean licks between 3-4 sec
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,behAlignedMeanStat.indLick3to4s),[],1)',...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLick3to4s),[],1)',...
        'No. licks (good trials, 3-4s)','meanLickNonStimGoodPerRecFieldVsNoField3to4sBox',...
        pathAnal,[-0.1 1.5],behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecField3to4s,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,behAlignedMeanStat.indLick3to4s),[],1)',...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,behAlignedMeanStat.indLick3to4s),[],1)',...
        'No. licks (bad trials, 3-4s)','meanLickNonStimBadPerRecFieldVsNoField3to4sBox',...
        pathAnal,[-0.1 1.5],behAlignedMeanStat.pRSMeanLickNonStimBadPerRecField3to4s,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimPerRecField(:,behAlignedMeanStat.indLick3to4s),2)',...
        mean(behAlignedMean.lickTraceNonStimPerRecNoField(:,behAlignedMeanStat.indLick3to4s),2)',...
        'No. licks (non-stim trials, 3-4s)','lickTraceNonStimPerRecFieldVsNoField3to4sBox',...
        pathAnal,[-0.1 1.5],behAlignedMeanStat.pRSLickTraceNonStimMeanPerRecField3to4s,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,behAlignedMeanStat.indLick3to4s),2)',...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLick3to4s),2)',...
        'No. licks (good trials, 3-4s)','lickTraceNonStimGoodPerRecFieldVsNoField3to4sBox',...
        pathAnal,[-0.1 1.5],behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecField3to4s,colorSel,[{'F'} {'NoF'}]);
    
    % speed before 4 sec
    
    plotBoxPlot(reshape(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,behAlignedMeanStat.indSpeedBef4s),[],1)'/10,...
        reshape(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,behAlignedMeanStat.indSpeedBef4s),[],1)'/10,...
        'Speed (good trials, bef 4s)','meanSpeedNonStimGoodPerRecFieldVsNoFieldBox',...
        pathAnal,[10 70],behAlignedMeanStat.pRSMeanSpeedNonStimGoodPerRecField,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(reshape(behAlignedMean.meanSpeedNonStimBadPerRecField(:,behAlignedMeanStat.indSpeedBef4s),[],1)'/10,...
        reshape(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:,behAlignedMeanStat.indSpeedBef4s),[],1)'/10,...
        'Speed (bad trials, bef 4s)','meanSpeedNonStimBadPerRecFieldVsNoFieldBox',...
        pathAnal,[10 70],behAlignedMeanStat.pRSMeanSpeedNonStimBadPerRecField,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.speedTraceNonStimPerRecField(:,behAlignedMeanStat.indSpeedBef4s),2)'/10,...
        mean(behAlignedMean.speedTraceNonStimPerRecNoField(:,behAlignedMeanStat.indSpeedBef4s),2)'/10,...
        'Speed (non-stim trials, bef 4s)','speedTraceNonStimPerRecFieldVsNoFieldBox',...
        pathAnal,[10 80],behAlignedMeanStat.pRSSpeedTraceNonStimMeanPerRecField,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.speedTraceNonStimGoodPerRecField(:,behAlignedMeanStat.indSpeedBef4s),2)'/10,...
        mean(behAlignedMean.speedTraceNonStimGoodPerRecNoField(:,behAlignedMeanStat.indSpeedBef4s),2)'/10,...
        'Speed (good trials, bef 4s)','speedTraceNonStimGoodPerRecFieldVsNoFieldBox',...
        pathAnal,[10 80],behAlignedMeanStat.pRSSpeedTraceNonStimGoodMeanPerRecField,colorSel,[{'F'} {'NoF'}]);
    
    
    % speed before 1 sec
    
    plotBoxPlot(reshape(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,behAlignedMeanStat.indSpeedBef1s),[],1)'/10,...
        reshape(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,behAlignedMeanStat.indSpeedBef1s),[],1)'/10,...
        'Speed (good trials, bef 1s)','meanSpeedNonStimGoodPerRecFieldVsNoFieldBef1sBox',...
        pathAnal,[10 70],behAlignedMeanStat.pRSMeanSpeedNonStimGoodPerRecFieldBef1s,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(reshape(behAlignedMean.meanSpeedNonStimBadPerRecField(:,behAlignedMeanStat.indSpeedBef1s),[],1)'/10,...
        reshape(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:,behAlignedMeanStat.indSpeedBef1s),[],1)'/10,...
        'Speed (bad trials, bef 1s','meanSpeedNonStimBadPerRecFieldVsNoFieldBef1sBox',...
        pathAnal,[10 70],behAlignedMeanStat.pRSMeanSpeedNonStimBadPerRecFieldBef1s,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.speedTraceNonStimPerRecField(:,behAlignedMeanStat.indSpeedBef1s),2)'/10,...
        mean(behAlignedMean.speedTraceNonStimPerRecNoField(:,behAlignedMeanStat.indSpeedBef1s),2)'/10,...
        'Speed (non-stim trials, bef 1s)','speedTraceNonStimPerRecFieldVsNoFieldBef1sBox',...
        pathAnal,[10 80],behAlignedMeanStat.pRSSpeedTraceNonStimMeanPerRecFieldBef1s,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.speedTraceNonStimGoodPerRecField(:,behAlignedMeanStat.indSpeedBef1s),2)'/10,...
        mean(behAlignedMean.speedTraceNonStimGoodPerRecNoField(:,behAlignedMeanStat.indSpeedBef1s),2)'/10,...
        'Speed (good trials, bef 1s)','speedTraceNonStimGoodPerRecFieldVsNoFieldBef1sBox',...
        pathAnal,[10 80],behAlignedMeanStat.pRSSpeedTraceNonStimGoodMeanPerRecFieldBef1s,colorSel,[{'F'} {'NoF'}]);
    
    % speed between 1-2 sec
    
    plotBoxPlot(reshape(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,behAlignedMeanStat.indSpeed1to2s),[],1)'/10,...
        reshape(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,behAlignedMeanStat.indSpeed1to2s),[],1)'/10,...
        'Speed (good trials, 1-2s)','meanSpeedNonStimGoodPerRecFieldVsNoField1to2sBox',...
        pathAnal,[10 70],behAlignedMeanStat.pRSMeanSpeedNonStimGoodPerRecField1to2s,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(reshape(behAlignedMean.meanSpeedNonStimBadPerRecField(:,behAlignedMeanStat.indSpeed1to2s),[],1)'/10,...
        reshape(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:,behAlignedMeanStat.indSpeed1to2s),[],1)'/10,...
        'Speed (bad trials, 1-2s)','meanSpeedNonStimBadPerRecFieldVsNoField1to2sBox',...
        pathAnal,[10 70],behAlignedMeanStat.pRSMeanSpeedNonStimBadPerRecField1to2s,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.speedTraceNonStimPerRecField(:,behAlignedMeanStat.indSpeed1to2s),2)'/10,...
        mean(behAlignedMean.speedTraceNonStimPerRecNoField(:,behAlignedMeanStat.indSpeed1to2s),2)'/10,...
        'Speed (non-stim trials, 1-2s)','speedTraceNonStimPerRecFieldVsNoField1to2sBox',...
        pathAnal,[10 70],behAlignedMeanStat.pRSSpeedTraceNonStimMeanPerRecField1to2s,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.speedTraceNonStimGoodPerRecField(:,behAlignedMeanStat.indSpeed1to2s),2)'/10,...
        mean(behAlignedMean.speedTraceNonStimGoodPerRecNoField(:,behAlignedMeanStat.indSpeed1to2s),2)'/10,...
        'Speed (good trials, 1-2s)','speedTraceNonStimGoodPerRecFieldVsNoField1to2sBox',...
        pathAnal,[10 70],behAlignedMeanStat.pRSSpeedTraceNonStimGoodMeanPerRecField1to2s,colorSel,[{'F'} {'NoF'}]);

    % speed between 2-3 sec
    
    plotBoxPlot(reshape(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,behAlignedMeanStat.indSpeed2to3s),[],1)'/10,...
        reshape(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,behAlignedMeanStat.indSpeed2to3s),[],1)'/10,...
        'Speed (good trials, 2-3s)','meanSpeedNonStimGoodPerRecFieldVsNoField2to3sBox',...
        pathAnal,[10 70],behAlignedMeanStat.pRSMeanSpeedNonStimGoodPerRecField2to3s,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(reshape(behAlignedMean.meanSpeedNonStimBadPerRecField(:,behAlignedMeanStat.indSpeed2to3s),[],1)'/10,...
        reshape(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:,behAlignedMeanStat.indSpeed2to3s),[],1)'/10,...
        'Speed (bad trials, 2-3s)','meanSpeedNonStimBadPerRecFieldVsNoField2to3sBox',...
        pathAnal,[10 70],behAlignedMeanStat.pRSMeanSpeedNonStimBadPerRecField2to3s,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.speedTraceNonStimPerRecField(:,behAlignedMeanStat.indSpeed2to3s),2)'/10,...
        mean(behAlignedMean.speedTraceNonStimPerRecNoField(:,behAlignedMeanStat.indSpeed2to3s),2)'/10,...
        'Speed (non-stim trials, 2-3s)','speedTraceNonStimPerRecFieldVsNoField2to3sBox',...
        pathAnal,[10 70],behAlignedMeanStat.pRSSpeedTraceNonStimMeanPerRecField2to3s,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.speedTraceNonStimGoodPerRecField(:,behAlignedMeanStat.indSpeed2to3s),2)'/10,...
        mean(behAlignedMean.speedTraceNonStimGoodPerRecNoField(:,behAlignedMeanStat.indSpeed2to3s),2)'/10,...
        'Speed (good trials, 2-3s)','speedTraceNonStimGoodPerRecFieldVsNoField2to3sBox',...
        pathAnal,[10 70],behAlignedMeanStat.pRSSpeedTraceNonStimGoodMeanPerRecField2to3s,colorSel,[{'F'} {'NoF'}]);

    % speed between 3-4 sec
    
    plotBoxPlot(reshape(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,behAlignedMeanStat.indSpeed3to4s),[],1)'/10,...
        reshape(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,behAlignedMeanStat.indSpeed3to4s),[],1)'/10,...
        'Speed (good trials, 3-4s)','meanSpeedNonStimGoodPerRecFieldVsNoField3to4sBox',...
        pathAnal,[10 70],behAlignedMeanStat.pRSMeanSpeedNonStimGoodPerRecField3to4s,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(reshape(behAlignedMean.meanSpeedNonStimBadPerRecField(:,behAlignedMeanStat.indSpeed3to4s),[],1)'/10,...
        reshape(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:,behAlignedMeanStat.indSpeed3to4s),[],1)'/10,...
        'Speed (bad trials, 3-4s)','meanSpeedNonStimBadPerRecFieldVsNoField3to4sBox',...
        pathAnal,[10 70],behAlignedMeanStat.pRSMeanSpeedNonStimBadPerRecField3to4s,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.speedTraceNonStimPerRecField(:,behAlignedMeanStat.indSpeed3to4s),2)'/10,...
        mean(behAlignedMean.speedTraceNonStimPerRecNoField(:,behAlignedMeanStat.indSpeed3to4s),2)'/10,...
        'Speed (non-stim trials, 3-4s)','speedTraceNonStimPerRecFieldVsNoField3to4sBox',...
        pathAnal,[10 70],behAlignedMeanStat.pRSSpeedTraceNonStimMeanPerRecField3to4s,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.speedTraceNonStimGoodPerRecField(:,behAlignedMeanStat.indSpeed3to4s),2)'/10,...
        mean(behAlignedMean.speedTraceNonStimGoodPerRecNoField(:,behAlignedMeanStat.indSpeed3to4s),2)'/10,...
        'Speed (good trials, 3-4s)','speedTraceNonStimGoodPerRecFieldVsNoField3to4sBox',...
        pathAnal,[10 70],behAlignedMeanStat.pRSSpeedTraceNonStimGoodMeanPerRecField3to4s,colorSel,[{'F'} {'NoF'}]);
end
