function plotBehMeanALNoCueTime(pathAnal,behAL,behNoCue,behMeanStat)
% compare behavior of no cue and AL sessions
% this function is called by PyrBehALNoCue.m
    
    
    % total licks
    plotStat(mean(behAL.meanLickPerRec(:,behMeanStat.indLickBef4s),2)',...
        mean(behNoCue.meanLickPerRec(:,behMeanStat.indLickBef4s),2)',...
        behMeanStat.meanLickPerRec,behMeanStat.stdLickPerRec,...
        behMeanStat.pRSMeanLickMean,...
        [],'No. licks',[],'meanLickPerRecALVsNoCueBar',...
        pathAnal);
   
    % before 2 sec
    plotStat(mean(behAL.meanLickPerRec(:,behMeanStat.indLickBef2s),2)',...
        mean(behNoCue.meanLickPerRec(:,behMeanStat.indLickBef2s),2)',...
        behMeanStat.meanLickPerRecBef2s,behMeanStat.stdLickPerRecBef2s,...
        behMeanStat.pRSMeanLickMeanBef2s,...
        [],'No. licks (Bef 2s)',[],'meanLickPerRecALVsNoCueBef2sBar',...
        pathAnal);
    
    % before 1 sec
    plotStat(mean(behAL.meanLickPerRec(:,behMeanStat.indLickBef1s),2)',...
        mean(behNoCue.meanLickPerRec(:,behMeanStat.indLickBef1s),2)',...
        behMeanStat.meanLickPerRecBef1s,behMeanStat.stdLickPerRecBef1s,...
        behMeanStat.pRSMeanLickMeanBef1s,...
        [],'No. licks (Bef 1s)',[],'meanLickPerRecALVsNoCueBef1sBar',...
        pathAnal);
    
    % between 1 to 2 s
    plotStat(mean(behAL.meanLickPerRec(:,behMeanStat.indLick1to2s),2)',...
        mean(behNoCue.meanLickPerRec(:,behMeanStat.indLick1to2s),2)',...
        behMeanStat.meanLickPerRec1to2s,behMeanStat.stdLickPerRec1to2s,...
        behMeanStat.pRSMeanLickMean1to2s,...
        [],'No. licks (1to2s)',[],'meanLickPerRecALVsNoCue1to2sBar',...
        pathAnal);
        
    % between 2 to 3 s
    plotStat(mean(behAL.meanLickPerRec(:,behMeanStat.indLick2to3s),2)',...
        mean(behNoCue.meanLickPerRec(:,behMeanStat.indLick2to3s),2)',...
        behMeanStat.meanLickPerRec2to3s,behMeanStat.stdLickPerRec2to3s,...
        behMeanStat.pRSMeanLickMean2to3s,...
        [],'No. licks (2to3s)',[],'meanLickPerRecALVsNoCue2to3sBar',...
        pathAnal);
   
    % between 3 to 4 s
    plotStat(mean(behAL.meanLickPerRec(:,behMeanStat.indLick3to4s),2)',...
        mean(behNoCue.meanLickPerRec(:,behMeanStat.indLick3to4s),2)',...
        behMeanStat.meanLickPerRec3to4s,behMeanStat.stdLickPerRec3to4s,...
        behMeanStat.pRSMeanLickMean3to4s,...
        [],'No. licks (3to4s)',[],'meanLickPerRecALVsNoCue3to4sBar',...
        pathAnal);
    
    % mean speed
    plotStat(mean(behAL.meanSpeedPerRec(:,behMeanStat.indSpeedBef4s),2)'/10,...
        mean(behNoCue.meanSpeedPerRec(:,behMeanStat.indSpeedBef4s),2)'/10,...
        behMeanStat.meanSpeedPerRecBef4s,behMeanStat.stdSpeedPerRecBef4s,...
        behMeanStat.pRSMeanSpeedMeanBef4s,...
        [],'Speed (cm/s)',[],'meanSpeedPerRecALVsNoCueBar',...
        pathAnal);
   
    % before 2 sec
    plotStat(mean(behAL.meanSpeedPerRec(:,behMeanStat.indSpeedBef2s),2)'/10,...
        mean(behNoCue.meanSpeedPerRec(:,behMeanStat.indSpeedBef2s),2)'/10,...
        behMeanStat.meanSpeedPerRecBef2s,behMeanStat.stdSpeedPerRecBef2s,...
        behMeanStat.pRSMeanSpeedMeanBef2s,...
        [],'Speed (cm/s) (Bef 2s)',[],'meanSpeedPerRecALVsNoCueBef2sBar',...
        pathAnal);
   
    % before 1 sec
    plotStat(mean(behAL.meanSpeedPerRec(:,behMeanStat.indSpeedBef1s),2)'/10,...
        mean(behNoCue.meanSpeedPerRec(:,behMeanStat.indSpeedBef1s),2)'/10,...
        behMeanStat.meanSpeedPerRecBef1s,behMeanStat.stdSpeedPerRecBef1s,...
        behMeanStat.pRSMeanSpeedMeanBef1s,...
        [],'Speed (cm/s) (Bef 1s)',[],'meanSpeedPerRecALVsNoCueBef1sBar',...
        pathAnal);
   
    % between 1-2 sec
    plotStat(mean(behAL.meanSpeedPerRec(:,behMeanStat.indSpeed1to2s),2)'/10,...
        mean(behNoCue.meanSpeedPerRec(:,behMeanStat.indSpeed1to2s),2)'/10,...
        behMeanStat.meanSpeedPerRec1to2s,behMeanStat.stdSpeedPerRec1to2s,...
        behMeanStat.pRSMeanSpeedMean1to2s,...
        [],'Speed (cm/s) (1to2s)',[],'meanSpeedPerRecALVsNoCue1to2sBar',...
        pathAnal);
   
    % between 2-3 sec
    plotStat(mean(behAL.meanSpeedPerRec(:,behMeanStat.indSpeed2to3s),2)'/10,...
        mean(behNoCue.meanSpeedPerRec(:,behMeanStat.indSpeed2to3s),2)'/10,...
        behMeanStat.meanSpeedPerRec2to3s,behMeanStat.stdSpeedPerRec2to3s,...
        behMeanStat.pRSMeanSpeedMean2to3s,...
        [],'Speed (cm/s) (2to3s)',[],'meanSpeedPerRecALVsNoCue2to3sBar',...
        pathAnal);
    
    % between 3-4 sec
    plotStat(mean(behAL.meanSpeedPerRec(:,behMeanStat.indSpeed3to4s),2)'/10,...
        mean(behNoCue.meanSpeedPerRec(:,behMeanStat.indSpeed3to4s),2)'/10,...
        behMeanStat.meanSpeedPerRec3to4s,behMeanStat.stdSpeedPerRec3to4s,...
        behMeanStat.pRSMeanSpeedMean3to4s,...
        [],'Speed (cm/s) (3to4s)',[],'meanSpeedPerRecALVsNoCue3to4sBar',...
        pathAnal);
   
end