function plotBehAlignedMean(pathAnal,behAlignedMean,behAlignedMeanStat,colorSel)
% compare behavior of recordings with and without fields
% this function is called by PyrBehAlignedAllRec.m

    % total licks
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimPerRecField(:,behAlignedMeanStat.indLickAfter30),[],1)',...
        reshape(behAlignedMean.meanLickNonStimPerRecNoField(:,behAlignedMeanStat.indLickAfter30),[],1)',...
        'No. licks (non-stim trials)','meanLickNonStimPerRecFieldVsNoFieldBox',...
        pathAnal,[-0.1 0.5],behAlignedMeanStat.pRSMeanLickNonStimPerRecField,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,behAlignedMeanStat.indLickAfter30),[],1)',...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLickAfter30),[],1)',...
        'No. licks (good trials)','meanLickNonStimGoodPerRecFieldVsNoFieldBox',...
        pathAnal,[-0.1 0.5],behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecField,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,behAlignedMeanStat.indLickAfter30),[],1)',...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,behAlignedMeanStat.indLickAfter30),[],1)',...
        'No. licks (bad trials)','meanLickNonStimBadPerRecFieldVsNoFieldBox',...
        pathAnal,[-0.1 0.5],behAlignedMeanStat.pRSMeanLickNonStimBadPerRecField,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimPerRecField(:,behAlignedMeanStat.indLickAfter30),2)',...
        mean(behAlignedMean.lickTraceNonStimPerRecNoField(:,behAlignedMeanStat.indLickAfter30),2)',...
        'No. licks (non-stim trials)','lickTraceNonStimPerRecFieldVsNoFieldBox',...
        pathAnal,[-0.1 0.5],behAlignedMeanStat.pRSLickTraceNonStimMeanPerRecField,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,behAlignedMeanStat.indLickAfter30),2)',...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLickAfter30),2)',...
        'No. licks (good trials)','lickTraceNonStimGoodPerRecFieldVsNoFieldBox',...
        pathAnal,[-0.1 0.5],behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecField,colorSel,[{'F'} {'NoF'}]);
    
    % distance 30 to 100 cm
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimPerRecField(:,behAlignedMeanStat.indLick30to100),[],1)',...
        reshape(behAlignedMean.meanLickNonStimPerRecNoField(:,behAlignedMeanStat.indLick30to100),[],1)',...
        'No. licks (non-stim trials, 30-100 cm)','meanLickNonStimPerRecFieldVsNoField30to100Box',...
        pathAnal,[-0.1 0.2],behAlignedMeanStat.pRSMeanLickNonStimPerRecField30to100,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,behAlignedMeanStat.indLick30to100),[],1)',...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLick30to100),[],1)',...
        'No. licks (good trials, 30-100 cm)','meanLickNonStimGoodPerRecFieldVsNoField30to100Box',...
        pathAnal,[-0.1 0.2],behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecField30to100,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,behAlignedMeanStat.indLick30to100),[],1)',...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,behAlignedMeanStat.indLick30to100),[],1)',...
        'No. licks (bad trials, 30-100 cm)','meanLickNonStimBadPerRecFieldVsNoField30to100Box',...
        pathAnal,[-0.1 0.2],behAlignedMeanStat.pRSMeanLickNonStimBadPerRecField30to100,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimPerRecField(:,behAlignedMeanStat.indLick30to100),2)',...
        mean(behAlignedMean.lickTraceNonStimPerRecNoField(:,behAlignedMeanStat.indLick30to100),2)',...
        'No. licks (non-stim trials, 30-100 cm)','lickTraceNonStimPerRecFieldVsNoField30to100Box',...
        pathAnal,[-0.1 0.2],behAlignedMeanStat.pRSLickTraceNonStimMeanPerRecField30to100,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,behAlignedMeanStat.indLick30to100),2)',...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLick30to100),2)',...
        'No. licks (good trials, 30-100 cm)','lickTraceNonStimGoodPerRecFieldVsNoField30to100Box',...
        pathAnal,[-0.1 0.2],behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecField30to100,colorSel,[{'F'} {'NoF'}]);
    
    % distance 100 to 150 cm
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimPerRecField(:,behAlignedMeanStat.indLick100to150),[],1)',...
        reshape(behAlignedMean.meanLickNonStimPerRecNoField(:,behAlignedMeanStat.indLick100to150),[],1)',...
        'No. licks (non-stim trials, 100-150 cm)','meanLickNonStimPerRecFieldVsNoField100to150Box',...
        pathAnal,[-0.1 0.4],behAlignedMeanStat.pRSMeanLickNonStimPerRecField100to150,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,behAlignedMeanStat.indLick100to150),[],1)',...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLick100to150),[],1)',...
        'No. licks (good trials, 100-150 cm)','meanLickNonStimGoodPerRecFieldVsNoField100to150Box',...
        pathAnal,[-0.1 0.4],behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecField100to150,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,behAlignedMeanStat.indLick100to150),[],1)',...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,behAlignedMeanStat.indLick100to150),[],1)',...
        'No. licks (bad trials, 100-150 cm)','meanLickNonStimBadPerRecFieldVsNoField100to150Box',...
        pathAnal,[-0.1 0.4],behAlignedMeanStat.pRSMeanLickNonStimBadPerRecField100to150,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimPerRecField(:,behAlignedMeanStat.indLick100to150),2)',...
        mean(behAlignedMean.lickTraceNonStimPerRecNoField(:,behAlignedMeanStat.indLick100to150),2)',...
        'No. licks (non-stim trials, 100-150 cm)','lickTraceNonStimPerRecFieldVsNoField100to150Box',...
        pathAnal,[-0.1 0.4],behAlignedMeanStat.pRSLickTraceNonStimMeanPerRecField100to150,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,behAlignedMeanStat.indLick100to150),2)',...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLick100to150),2)',...
        'No. licks (good trials, 100-150 cm)','lickTraceNonStimGoodPerRecFieldVsNoField100to150Box',...
        pathAnal,[-0.1 0.4],behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecField100to150,colorSel,[{'F'} {'NoF'}]);
    
    % distance 150 to 180 cm
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimPerRecField(:,behAlignedMeanStat.indLick150to180),[],1)',...
        reshape(behAlignedMean.meanLickNonStimPerRecNoField(:,behAlignedMeanStat.indLick150to180),[],1)',...
        'No. licks (non-stim trials, 150-180 cm)','meanLickNonStimPerRecFieldVsNoField150to180Box',...
        pathAnal,[-0.1 0.8],behAlignedMeanStat.pRSMeanLickNonStimPerRecField150to180,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,behAlignedMeanStat.indLick150to180),[],1)',...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLick150to180),[],1)',...
        'No. licks (good trials, 150-180 cm)','meanLickNonStimGoodPerRecFieldVsNoField150to180Box',...
        pathAnal,[-0.1 0.8],behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecField150to180,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,behAlignedMeanStat.indLick150to180),[],1)',...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,behAlignedMeanStat.indLick150to180),[],1)',...
        'No. licks (bad trials, 150-180 cm)','meanLickNonStimBadPerRecFieldVsNoField150to180Box',...
        pathAnal,[-0.1 0.8],behAlignedMeanStat.pRSMeanLickNonStimBadPerRecField150to180,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimPerRecField(:,behAlignedMeanStat.indLick150to180),2)',...
        mean(behAlignedMean.lickTraceNonStimPerRecNoField(:,behAlignedMeanStat.indLick150to180),2)',...
        'No. licks (non-stim trials, 150-180 cm)','lickTraceNonStimPerRecFieldVsNoField150to180Box',...
        pathAnal,[-0.1 0.9],behAlignedMeanStat.pRSLickTraceNonStimMeanPerRecField150to180,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,behAlignedMeanStat.indLick150to180),2)',...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLick150to180),2)',...
        'No. licks (good trials, 150-180 cm)','lickTraceNonStimGoodPerRecFieldVsNoField150to180Box',...
        pathAnal,[-0.1 0.9],behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecField150to180,colorSel,[{'F'} {'NoF'}]);
    
    % distance after 180 cm
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimPerRecField(:,behAlignedMeanStat.indLickAfter180),[],1)',...
        reshape(behAlignedMean.meanLickNonStimPerRecNoField(:,behAlignedMeanStat.indLickAfter180),[],1)',...
        'No. licks (non-stim trials, >=180 cm)','meanLickNonStimPerRecFieldVsNoFieldAfter180Box',...
        pathAnal,[-0.1 1.5],behAlignedMeanStat.pRSMeanLickNonStimPerRecFieldAfter180,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimGoodPerRecField(:,behAlignedMeanStat.indLickAfter180),[],1)',...
        reshape(behAlignedMean.meanLickNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLickAfter180),[],1)',...
        'No. licks (good trials, >=180 cm)','meanLickNonStimGoodPerRecFieldVsNoFieldAfter180Box',...
        pathAnal,[-0.1 1.5],behAlignedMeanStat.pRSMeanLickNonStimGoodPerRecFieldAfter180,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(reshape(behAlignedMean.meanLickNonStimBadPerRecField(:,behAlignedMeanStat.indLickAfter180),[],1)',...
        reshape(behAlignedMean.meanLickNonStimBadPerRecNoField(:,behAlignedMeanStat.indLickAfter180),[],1)',...
        'No. licks (bad trials, >=180 cm)','meanLickNonStimBadPerRecFieldVsNoFieldAfter180Box',...
        pathAnal,[-0.1 1.5],behAlignedMeanStat.pRSMeanLickNonStimBadPerRecFieldAfter180,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimPerRecField(:,behAlignedMeanStat.indLickAfter180),2)',...
        mean(behAlignedMean.lickTraceNonStimPerRecNoField(:,behAlignedMeanStat.indLickAfter180),2)',...
        'No. licks (non-stim trials)','lickTraceNonStimPerRecFieldVsNoFieldAfter180Box',...
        pathAnal,[-0.1 1.5],behAlignedMeanStat.pRSLickTraceNonStimMeanPerRecFieldAfter180,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimGoodPerRecField(:,behAlignedMeanStat.indLickAfter180),2)',...
        mean(behAlignedMean.lickTraceNonStimGoodPerRecNoField(:,behAlignedMeanStat.indLickAfter180),2)',...
        'No. licks (good trials)','lickTraceNonStimGoodPerRecFieldVsNoFieldAfter180Box',...
        pathAnal,[-0.1 1.5],behAlignedMeanStat.pRSLickTraceNonStimGoodMeanPerRecFieldAfter180,colorSel,[{'F'} {'NoF'}]);
    
    % mean speed
    plotBoxPlot(behAlignedMean.meanSpeedNonStimPerRecField(:)'/10,...
        behAlignedMean.meanSpeedNonStimPerRecNoField(:)'/10,...
        'Speed (cm/s) non-stim trials','meanSpeedNonStimPerRecFieldVsNoFieldBox',...
        pathAnal,[10 70],behAlignedMeanStat.pRSMeanSpeedNonStimPerRecField,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(behAlignedMean.meanSpeedNonStimGoodPerRecField(:)'/10,...
        behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:)'/10,...
        'Speed (cm/s) good trials','meanSpeedNonStimGoodPerRecFieldVsNoFieldBox',...
        pathAnal,[10 70],behAlignedMeanStat.pRSMeanSpeedNonStimGoodPerRecField,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(behAlignedMean.meanSpeedNonStimBadPerRecField(:)'/10,...
        behAlignedMean.meanSpeedNonStimBadPerRecNoField(:)'/10,...
        'Speed (cm/s) bad trials','meanSpeedNonStimBadPerRecFieldVsNoFieldBox',...
        pathAnal,[0 70],behAlignedMeanStat.pRSMeanSpeedNonStimBadPerRecField,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.speedTraceNonStimPerRecField,2)'/10,...
        mean(behAlignedMean.speedTraceNonStimPerRecNoField,2)'/10,...
        'Speed (cm/s) non-stim trials','speedTraceNonStimPerRecFieldVsNoFieldBox',...
        pathAnal,[0 70],behAlignedMeanStat.pRSSpeedTraceNonStimMeanPerRecField,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.speedTraceNonStimGoodPerRecField,2)'/10,...
        mean(behAlignedMean.speedTraceNonStimGoodPerRecNoField,2)'/10,...
        'Speed (cm/s) good trials','speedTraceNonStimGoodPerRecFieldVsNoFieldBox',...
        pathAnal,[0 70],behAlignedMeanStat.pRSSpeedTraceNonStimGoodMeanPerRecField,colorSel,[{'F'} {'NoF'}]);
    
    % distance 30 to 100 cm
    plotBoxPlot(reshape(behAlignedMean.meanSpeedNonStimPerRecField(:,behAlignedMeanStat.indSpeed30to100),[],1)'/10,...
        reshape(behAlignedMean.meanSpeedNonStimPerRecNoField(:,behAlignedMeanStat.indSpeed30to100),[],1)'/10,...
        'Speed (non-stim trials, 30-100 cm)','meanSpeedNonStimPerRecFieldVsNoField30to100Box',...
        pathAnal,[10 70],behAlignedMeanStat.pRSMeanSpeedNonStimPerRecField30to100,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(reshape(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,behAlignedMeanStat.indSpeed30to100),[],1)'/10,...
        reshape(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,behAlignedMeanStat.indSpeed30to100),[],1)'/10,...
        'Speed (good trials, 30-100 cm)','meanSpeedNonStimGoodPerRecFieldVsNoField30to100Box',...
        pathAnal,[10 70],behAlignedMeanStat.pRSMeanSpeedNonStimGoodPerRecField30to100,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(reshape(behAlignedMean.meanSpeedNonStimBadPerRecField(:,behAlignedMeanStat.indSpeed30to100),[],1)'/10,...
        reshape(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:,behAlignedMeanStat.indSpeed30to100),[],1)'/10,...
        'Speed (bad trials, 30-100 cm)','meanSpeedNonStimBadPerRecFieldVsNoField30to100Box',...
        pathAnal,[10 70],behAlignedMeanStat.pRSMeanSpeedNonStimBadPerRecField30to100,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.speedTraceNonStimPerRecField(:,behAlignedMeanStat.indSpeed30to100),2)'/10,...
        mean(behAlignedMean.speedTraceNonStimPerRecNoField(:,behAlignedMeanStat.indSpeed30to100),2)'/10,...
        'Speed (non-stim trials, 30-100 cm)','speedTraceNonStimPerRecFieldVsNoField30to100Box',...
        pathAnal,[10 80],behAlignedMeanStat.pRSSpeedTraceNonStimMeanPerRecField30to100,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.speedTraceNonStimGoodPerRecField(:,behAlignedMeanStat.indSpeed30to100),2)'/10,...
        mean(behAlignedMean.speedTraceNonStimGoodPerRecNoField(:,behAlignedMeanStat.indSpeed30to100),2)'/10,...
        'Speed (good trials, 30-100 cm)','speedTraceNonStimGoodPerRecFieldVsNoField30to100Box',...
        pathAnal,[10 80],behAlignedMeanStat.pRSSpeedTraceNonStimGoodMeanPerRecField30to100,colorSel,[{'F'} {'NoF'}]);
    
    % distance after 100 cm
    plotBoxPlot(reshape(behAlignedMean.meanSpeedNonStimPerRecField(:,behAlignedMeanStat.indSpeedAfter100),[],1)'/10,...
        reshape(behAlignedMean.meanSpeedNonStimPerRecNoField(:,behAlignedMeanStat.indSpeedAfter100),[],1)'/10,...
        'Speed (non-stim trials, >=100 cm)','meanSpeedNonStimPerRecFieldVsNoFieldAfter100Box',...
        pathAnal,[10 70],behAlignedMeanStat.pRSMeanSpeedNonStimPerRecFieldAfter100,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(reshape(behAlignedMean.meanSpeedNonStimGoodPerRecField(:,behAlignedMeanStat.indSpeedAfter100),[],1)'/10,...
        reshape(behAlignedMean.meanSpeedNonStimGoodPerRecNoField(:,behAlignedMeanStat.indSpeedAfter100),[],1)'/10,...
        'Speed (good trials, >=100 cm)','meanSpeedNonStimGoodPerRecFieldVsNoFieldAfter100Box',...
        pathAnal,[10 70],behAlignedMeanStat.pRSMeanSpeedNonStimGoodPerRecFieldAfter100,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(reshape(behAlignedMean.meanSpeedNonStimBadPerRecField(:,behAlignedMeanStat.indSpeedAfter100),[],1)'/10,...
        reshape(behAlignedMean.meanSpeedNonStimBadPerRecNoField(:,behAlignedMeanStat.indSpeedAfter100),[],1)'/10,...
        'Speed (bad trials, >=100 cm)','meanSpeedNonStimBadPerRecFieldVsNoFieldAfter100Box',...
        pathAnal,[10 70],behAlignedMeanStat.pRSMeanSpeedNonStimBadPerRecFieldAfter100,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.speedTraceNonStimPerRecField(:,behAlignedMeanStat.indSpeedAfter100),2)'/10,...
        mean(behAlignedMean.speedTraceNonStimPerRecNoField(:,behAlignedMeanStat.indSpeedAfter100),2)'/10,...
        'Speed (non-stim trials, >=100 cm)','speedTraceNonStimPerRecFieldVsNoFieldAfter100Box',...
        pathAnal,[10 70],behAlignedMeanStat.pRSSpeedTraceNonStimMeanPerRecFieldAfter100,colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(mean(behAlignedMean.speedTraceNonStimGoodPerRecField(:,behAlignedMeanStat.indSpeedAfter100),2)'/10,...
        mean(behAlignedMean.speedTraceNonStimGoodPerRecNoField(:,behAlignedMeanStat.indSpeedAfter100),2)'/10,...
        'Speed (good trials, >=100 cm)','speedTraceNonStimGoodPerRecFieldVsNoFieldAfter100Box',...
        pathAnal,[10 70],behAlignedMeanStat.pRSSpeedTraceNonStimGoodMeanPerRecFieldAfter100,colorSel,[{'F'} {'NoF'}]);
end
