function plotBehAlignedMeanGoodBad(pathAnal,behAlignedMean,behAlignedMeanStat,colorSel)
% compare behavior of good vs bad trials
% this function is called by PyrBehAlignedAllRec.m
    
    % bef 4 sec
    plotBoxPlot(reshape(behAlignedMean.meanLickPerRecNonStimGood(:,behAlignedMeanStat.indLickBef4s),[],1)',...
        reshape(behAlignedMean.meanLickPerRecNonStimBad(:,behAlignedMeanStat.indLickBef4s),[],1)',...
        'No. licks (Bef 4s)','meanLickPerRecGoodVsBadBef4sBox',...
        pathAnal,[-0.1 0.2],behAlignedMeanStat.pRSMeanLickMeanPerRec,colorSel,[{'Good'} {'Bad'}]);

    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimGoodPerRec(:,behAlignedMeanStat.indLickBef4s),2)',...
        mean(behAlignedMean.lickTraceNonStimBadPerRec(:,behAlignedMeanStat.indLickBef4s),2)',...
        'No. licks (Bef 4s)','lickTracePerRecGoodVsBadBef4sBox',...
        pathAnal,[-0.1 0.2],behAlignedMeanStat.pRSMeanLickTracePerRec,colorSel,[{'Good'} {'Bad'}]);
    
    % bef 2 sec
    plotBoxPlot(reshape(behAlignedMean.meanLickPerRecNonStimGood(:,behAlignedMeanStat.indLickBef2s),[],1)',...
        reshape(behAlignedMean.meanLickPerRecNonStimBad(:,behAlignedMeanStat.indLickBef2s),[],1)',...
        'No. licks (Bef 2s)','meanLickPerRecGoodVsBadBef2sBox',...
        pathAnal,[-0.1 0.2],behAlignedMeanStat.pRSMeanLickMeanPerRecBef2s,colorSel,[{'Good'} {'Bad'}]);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimGoodPerRec(:,behAlignedMeanStat.indLickBef2s),2)',...
        mean(behAlignedMean.lickTraceNonStimBadPerRec(:,behAlignedMeanStat.indLickBef2s),2)',...
        'No. licks (Bef 2s)','lickTracePerRecGoodVsBadBef2sBox',...
        pathAnal,[-0.1 0.2],behAlignedMeanStat.pRSMeanLickTracePerRecBef2s,colorSel,[{'Good'} {'Bad'}]);
        
    % bef 1 sec
    plotBoxPlot(reshape(behAlignedMean.meanLickPerRecNonStimGood(:,behAlignedMeanStat.indLickBef1s),[],1)',...
        reshape(behAlignedMean.meanLickPerRecNonStimBad(:,behAlignedMeanStat.indLickBef1s),[],1)',...
        'No. licks (Bef 1s)','meanLickPerRecGoodVsBadBef1sBox',...
        pathAnal,[-0.1 0.2],behAlignedMeanStat.pRSMeanLickMeanPerRecBef1s,colorSel,[{'Good'} {'Bad'}]);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimGoodPerRec(:,behAlignedMeanStat.indLickBef1s),2)',...
        mean(behAlignedMean.lickTraceNonStimBadPerRec(:,behAlignedMeanStat.indLickBef1s),2)',...
        'No. licks (Bef 1s)','lickTracePerRecGoodVsBadBef1sBox',...
        pathAnal,[-0.1 0.2],behAlignedMeanStat.pRSMeanLickTracePerRecBef1s,colorSel,[{'Good'} {'Bad'}]);
    
    % betwen 1-2 sec
    plotBoxPlot(reshape(behAlignedMean.meanLickPerRecNonStimGood(:,behAlignedMeanStat.indLick1to2s),[],1)',...
        reshape(behAlignedMean.meanLickPerRecNonStimBad(:,behAlignedMeanStat.indLick1to2s),[],1)',...
        'No. licks (1to2s)','meanLickPerRecGoodVsBad1to2sBox',...
        pathAnal,[-0.1 0.4],behAlignedMeanStat.pRSMeanLickMeanPerRec1to2s,colorSel,[{'Good'} {'Bad'}]);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimGoodPerRec(:,behAlignedMeanStat.indLick1to2s),2)',...
        mean(behAlignedMean.lickTraceNonStimBadPerRec(:,behAlignedMeanStat.indLick1to2s),2)',...
        'No. licks (1to2s)','lickTracePerRecGoodVsBad1to2sBox',...
        pathAnal,[-0.1 0.4],behAlignedMeanStat.pRSMeanLickTracePerRec1to2s,colorSel,[{'Good'} {'Bad'}]);
    
    % between 2-3 sec
    plotBoxPlot(reshape(behAlignedMean.meanLickPerRecNonStimGood(:,behAlignedMeanStat.indLick2to3s),[],1)',...
        reshape(behAlignedMean.meanLickPerRecNonStimBad(:,behAlignedMeanStat.indLick2to3s),[],1)',...
        'No. licks (2to3s)','meanLickPerRecGoodVsBad2to3sBox',...
        pathAnal,[-0.1 0.85],behAlignedMeanStat.pRSMeanLickMeanPerRec2to3s,colorSel,[{'Good'} {'Bad'}]);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimGoodPerRec(:,behAlignedMeanStat.indLick2to3s),2)',...
        mean(behAlignedMean.lickTraceNonStimBadPerRec(:,behAlignedMeanStat.indLick2to3s),2)',...
        'No. licks (2to3s)','lickTracePerRecGoodVsBad2to3sBox',...
        pathAnal,[-0.1 0.85],behAlignedMeanStat.pRSMeanLickTracePerRec2to3s,colorSel,[{'Good'} {'Bad'}]);
    
    % between 3-4 sec
    plotBoxPlot(reshape(behAlignedMean.meanLickPerRecNonStimGood(:,behAlignedMeanStat.indLick3to4s),[],1)',...
        reshape(behAlignedMean.meanLickPerRecNonStimBad(:,behAlignedMeanStat.indLick3to4s),[],1)',...
        'No. licks (3to4s)','meanLickPerRecGoodVsBad3to4sBox',...
        pathAnal,[-0.1 1.2],behAlignedMeanStat.pRSMeanLickMeanPerRec3to4s,colorSel,[{'Good'} {'Bad'}]);
    
    plotBoxPlot(mean(behAlignedMean.lickTraceNonStimGoodPerRec(:,behAlignedMeanStat.indLick3to4s),2)',...
        mean(behAlignedMean.lickTraceNonStimBadPerRec(:,behAlignedMeanStat.indLick3to4s),2)',...
        'No. licks (3to4s)','lickTracePerRecGoodVsBad3to4sBox',...
        pathAnal,[-0.1 1.1],behAlignedMeanStat.pRSMeanLickTracePerRec3to4s,colorSel,[{'Good'} {'Bad'}]);
   
    % mean speed bef 4s
    plotBoxPlot(reshape(behAlignedMean.meanSpeedPerRecNonStimGood(:,behAlignedMeanStat.indSpeedBef4s),[],1)'/10,...
        reshape(behAlignedMean.meanSpeedPerRecNonStimBad(:,behAlignedMeanStat.indSpeedBef4s),[],1)'/10,...
        'Speed (cm/s, Bef 4s)','meanSpeedPerRecGoodVsBadBox',...
        pathAnal,[0 80],behAlignedMeanStat.pRSMeanSpeedMeanPerRec,colorSel,[{'Good'} {'Bad'}]);
   
    plotBoxPlot(mean(behAlignedMean.speedTraceNonStimGoodPerRec(:,behAlignedMeanStat.indSpeedBef4s),2)'/10,...
        mean(behAlignedMean.speedTraceNonStimBadPerRec(:,behAlignedMeanStat.indSpeedBef4s),2)'/10,...
        'Speed (cm/s, Bef 4s)','speedTracePerRecGoodVsBadBox',...
        pathAnal,[0 80],behAlignedMeanStat.pRSMeanSpeedTracePerRec,colorSel,[{'Good'} {'Bad'}]);
    
    % bef 2s
    plotBoxPlot(reshape(behAlignedMean.meanSpeedPerRecNonStimGood(:,behAlignedMeanStat.indSpeedBef2s),[],1)'/10,...
        reshape(behAlignedMean.meanSpeedPerRecNonStimBad(:,behAlignedMeanStat.indSpeedBef2s),[],1)'/10,...
        'Speed (cm/s) (Bef 2s)','meanSpeedPerRecGoodVsBadBef2sBox',...
        pathAnal,[10 90],behAlignedMeanStat.pRSMeanSpeedMeanPerRecBef2s,colorSel,[{'Good'} {'Bad'}]);
   
    plotBoxPlot(mean(behAlignedMean.speedTraceNonStimGoodPerRec(:,behAlignedMeanStat.indSpeedBef2s),2)'/10,...
        mean(behAlignedMean.speedTraceNonStimBadPerRec(:,behAlignedMeanStat.indSpeedBef2s),2)'/10,...
        'Speed (cm/s) (Bef 2s)','speedTracePerRecGoodVsBadBef2sBox',...
        pathAnal,[10 90],behAlignedMeanStat.pRSMeanSpeedTracePerRecBef2s,colorSel,[{'Good'} {'Bad'}]);
    
    % bef 1s
    plotBoxPlot(reshape(behAlignedMean.meanSpeedPerRecNonStimGood(:,behAlignedMeanStat.indSpeedBef1s),[],1)'/10,...
        reshape(behAlignedMean.meanSpeedPerRecNonStimBad(:,behAlignedMeanStat.indSpeedBef1s),[],1)'/10,...
        'Speed (cm/s) (Bef 1s)','meanSpeedPerRecGoodVsBadBef1sBox',...
        pathAnal,[10 90],behAlignedMeanStat.pRSMeanSpeedMeanPerRecBef1s,colorSel,[{'Good'} {'Bad'}]);
   
    plotBoxPlot(mean(behAlignedMean.speedTraceNonStimGoodPerRec(:,behAlignedMeanStat.indSpeedBef1s),2)'/10,...
        mean(behAlignedMean.speedTraceNonStimBadPerRec(:,behAlignedMeanStat.indSpeedBef1s),2)'/10,...
        'Speed (cm/s) (Bef 1s)','speedTracePerRecGoodVsBadBef1sBox',...
        pathAnal,[10 90],behAlignedMeanStat.pRSMeanSpeedTracePerRecBef1s,colorSel,[{'Good'} {'Bad'}]);
    
    % between 1-2s
    plotBoxPlot(reshape(behAlignedMean.meanSpeedPerRecNonStimGood(:,behAlignedMeanStat.indSpeed1to2s),[],1)'/10,...
        reshape(behAlignedMean.meanSpeedPerRecNonStimBad(:,behAlignedMeanStat.indSpeed1to2s),[],1)'/10,...
        'Speed (cm/s) (1to2s)','meanSpeedPerRecGoodVsBad1to2sBox',...
        pathAnal,[10 80],behAlignedMeanStat.pRSMeanSpeedMeanPerRec1to2s,colorSel,[{'Good'} {'Bad'}]);
   
    plotBoxPlot(mean(behAlignedMean.speedTraceNonStimGoodPerRec(:,behAlignedMeanStat.indSpeed1to2s),2)'/10,...
        mean(behAlignedMean.speedTraceNonStimBadPerRec(:,behAlignedMeanStat.indSpeed1to2s),2)'/10,...
        'Speed (cm/s) (1to2s)','speedTracePerRecGoodVsBad1to2sBox',...
        pathAnal,[10 80],behAlignedMeanStat.pRSMeanSpeedTracePerRec1to2s,colorSel,[{'Good'} {'Bad'}]);

    % between 2-3s
    plotBoxPlot(reshape(behAlignedMean.meanSpeedPerRecNonStimGood(:,behAlignedMeanStat.indSpeed2to3s),[],1)'/10,...
        reshape(behAlignedMean.meanSpeedPerRecNonStimBad(:,behAlignedMeanStat.indSpeed2to3s),[],1)'/10,...
        'Speed (cm/s) (2to3s)','meanSpeedPerRecGoodVsBad2to3sBox',...
        pathAnal,[10 80],behAlignedMeanStat.pRSMeanSpeedMeanPerRec2to3s,colorSel,[{'Good'} {'Bad'}]);
   
    plotBoxPlot(mean(behAlignedMean.speedTraceNonStimGoodPerRec(:,behAlignedMeanStat.indSpeed2to3s),2)'/10,...
        mean(behAlignedMean.speedTraceNonStimBadPerRec(:,behAlignedMeanStat.indSpeed2to3s),2)'/10,...
        'Speed (cm/s) (2to3s)','speedTracePerRecGoodVsBad2to3sBox',...
        pathAnal,[10 80],behAlignedMeanStat.pRSMeanSpeedTracePerRec2to3s,colorSel,[{'Good'} {'Bad'}]);

    % between 3-4s
    plotBoxPlot(reshape(behAlignedMean.meanSpeedPerRecNonStimGood(:,behAlignedMeanStat.indSpeed3to4s),[],1)'/10,...
        reshape(behAlignedMean.meanSpeedPerRecNonStimBad(:,behAlignedMeanStat.indSpeed3to4s),[],1)'/10,...
        'Speed (cm/s) (3to4s)','meanSpeedPerRecGoodVsBad3to4sBox',...
        pathAnal,[10 80],behAlignedMeanStat.pRSMeanSpeedMeanPerRec3to4s,colorSel,[{'Good'} {'Bad'}]);
   
    plotBoxPlot(mean(behAlignedMean.speedTraceNonStimGoodPerRec(:,behAlignedMeanStat.indSpeed3to4s),2)'/10,...
        mean(behAlignedMean.speedTraceNonStimBadPerRec(:,behAlignedMeanStat.indSpeed3to4s),2)'/10,...
        'Speed (cm/s) (3to4s)','speedTracePerRecGoodVsBad3to4sBox',...
        pathAnal,[10 80],behAlignedMeanStat.pRSMeanSpeedTracePerRec3to4s,colorSel,[{'Good'} {'Bad'}]);
    
end