function plotBehAlignedMeanGoodBadBar(pathAnal,behAlignedMean,behAlignedMeanStat,colorSel)
% compare behavior of good vs bad trials (bar plots)
% this function is called by PyrBehAlignedAllRec.m
    
    % perc rewarded
    plotStat(behAlignedMean.percRewardedNonStimGood,...
        behAlignedMean.percRewardedNonStimBad,...
        behAlignedMeanStat.meanPercRewardedNonStim,behAlignedMeanStat.stdPercRewardedNonStim,...
        behAlignedMeanStat.pRSMeanPercRewardedNonStim,...
        [],'Perc rewarded',[],'meanPercRewardedNonStimPerRecGoodVsBadBar',...
        pathAnal);
    
    % total stop time
    plotStat(behAlignedMean.meanTotStopLenTPerRecNonStimGood,...
        behAlignedMean.meanTotStopLenTPerRecNonStimBad,...
        behAlignedMeanStat.meanTotStopLenTPerRec,behAlignedMeanStat.stdTotStopLenTPerRec,...
        behAlignedMeanStat.pRSMeanTotStopLenTPerRec,...
        [],'Total stop time (s)',[],'meanTotStopLenTPerRecGoodVsBadBar',...
        pathAnal);
    
    % total licks
    plotStat(mean(behAlignedMean.meanLickPerRecNonStimGood(:,behAlignedMeanStat.indLickAfter30),2)',...
        mean(behAlignedMean.meanLickPerRecNonStimBad(:,behAlignedMeanStat.indLickAfter30),2)',...
        behAlignedMeanStat.meanLickPerRec,behAlignedMeanStat.stdLickPerRec,...
        behAlignedMeanStat.pRSMeanLickMeanPerRec,...
        [],'No. licks',[],'meanLickPerRecGoodVsBadBar',...
        pathAnal);
   
    % distance 30 to 100 cm
    plotStat(mean(behAlignedMean.meanLickPerRecNonStimGood(:,behAlignedMeanStat.indLick30to100),2)',...
        mean(behAlignedMean.meanLickPerRecNonStimBad(:,behAlignedMeanStat.indLick30to100),2)',...
        behAlignedMeanStat.meanLickPerRec30to100,behAlignedMeanStat.stdLickPerRec30to100,...
        behAlignedMeanStat.pRSMeanLickMeanPerRec30to100,...
        [],'No. licks (30-100 cm)',[],'meanLickPerRecGoodVsBad30to100Bar',...
        pathAnal);
    
    % distance 100 to 150 cm
    plotStat(mean(behAlignedMean.meanLickPerRecNonStimGood(:,behAlignedMeanStat.indLick100to150),2)',...
        mean(behAlignedMean.meanLickPerRecNonStimBad(:,behAlignedMeanStat.indLick100to150),2)',...
        behAlignedMeanStat.meanLickPerRec100to150,behAlignedMeanStat.stdLickPerRec100to150,...
        behAlignedMeanStat.pRSMeanLickMeanPerRec100to150,...
        [],'No. licks (100-150 cm)',[],'meanLickPerRecGoodVsBad100to150Bar',...
        pathAnal);
        
    % distance 150 to 180 cm
    plotStat(mean(behAlignedMean.meanLickPerRecNonStimGood(:,behAlignedMeanStat.indLick150to180),2)',...
        mean(behAlignedMean.meanLickPerRecNonStimBad(:,behAlignedMeanStat.indLick150to180),2)',...
        behAlignedMeanStat.meanLickPerRec150to180,behAlignedMeanStat.stdLickPerRec150to180,...
        behAlignedMeanStat.pRSMeanLickMeanPerRec150to180,...
        [],'No. licks (150-180 cm)',[],'meanLickPerRecGoodVsBad150to180Bar',...
        pathAnal);
   
    % distance after 180 cm
    plotStat(mean(behAlignedMean.meanLickPerRecNonStimGood(:,behAlignedMeanStat.indLickAfter180),2)',...
        mean(behAlignedMean.meanLickPerRecNonStimBad(:,behAlignedMeanStat.indLickAfter180),2)',...
        behAlignedMeanStat.meanLickPerRecAfter180,behAlignedMeanStat.stdLickPerRecAfter180,...
        behAlignedMeanStat.pRSMeanLickMeanPerRecAfter180,...
        [],'No. licks (>=180 cm)',[],'meanLickPerRecGoodVsBadAfter180Bar',...
        pathAnal);
    
    % mean speed
    plotStat(mean(behAlignedMean.meanSpeedPerRecNonStimGood,2)'/10,...
        mean(behAlignedMean.meanSpeedPerRecNonStimBad,2)'/10,...
        behAlignedMeanStat.meanSpeedPerRec,behAlignedMeanStat.stdSpeedPerRec,...
        behAlignedMeanStat.pRSMeanSpeedMeanPerRec,...
        [],'Speed (cm/s)',[],'meanSpeedPerRecGoodVsBadBar',...
        pathAnal);
   
    % distance 30 to 100 cm
    plotStat(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,behAlignedMeanStat.indSpeed30to100),2)'/10,...
        mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,behAlignedMeanStat.indSpeed30to100),2)'/10,...
        behAlignedMeanStat.meanSpeedPerRec30to100,behAlignedMeanStat.stdSpeedPerRec30to100,...
        behAlignedMeanStat.pRSMeanSpeedMeanPerRec30to100,...
        [],'Speed (cm/s) (30-100 cm)',[],'meanSpeedPerRecGoodVsBad30to100Bar',...
        pathAnal);
   
    % distance after 100 cm
    plotStat(mean(behAlignedMean.meanSpeedPerRecNonStimGood(:,behAlignedMeanStat.indSpeedAfter100),2)'/10,...
        mean(behAlignedMean.meanSpeedPerRecNonStimBad(:,behAlignedMeanStat.indSpeedAfter100),2)'/10,...
        behAlignedMeanStat.meanSpeedPerRecAfter100,behAlignedMeanStat.stdSpeedPerRecAfter100,...
        behAlignedMeanStat.pRSMeanSpeedMeanPerRecAfter100,...
        [],'Speed (cm/s) (>100 cm)',[],'meanSpeedPerRecGoodVsBadAfter100Bar',...
        pathAnal);
   
end