function plotIntNeuRiseDownTagged(pathAnal,timeStepRun,...
            InitAll,IntRise,IntDown,FRProfileMean,FRProfileMeanInt,FRProfileMeanIntStat,colorSel,xlabels)

    for i = 1:max(InitAll.idxC2Int)
        idxCTmp = InitAll.idxC2Int == i;
        if(length(IntRise.idxRise{i}) ~= 0)
            %% added on 2/3/2023
            %% order pyramidal neurons with field based on the peak firing rate after 0
            plotIndFRProfile(timeStepRun,...
                    InitAll.avgFRProfileNormInt(idxCTmp,:),['FR (Hz)  C' num2str(i)],...
                    ['Int_IndFRProfileNormFRPeakAftRunNeuC' num2str(i)],...
                    pathAnal,[],5,[],[])

           
            %% order pyramidal neurons with field based on before and after run FR ratio  
            plotIndFRProfile(timeStepRun,...
                    InitAll.avgFRProfileNormInt(idxCTmp,:),['FR (Hz)  C' num2str(i)],...
                    ['Int_IndFRProfileNormFR0to1VsBefRunNeuC' num2str(i)],...
                    pathAnal,[],4,FRProfileMean.indFRBefRun,...
                    FRProfileMean.indFR0to1) % ordered based on -1to0 to 0to1 mean ratio

            
            %%
            %% average profile good vs bad trials
            plotAvgFRProfileCmp(timeStepRun,...
                    InitAll.avgFRProfileInt(IntRise.idxRise{i},:),...
                    InitAll.avgFRProfileBadInt(IntRise.idxRiseBadBad{i},:),...
                    ['FR IntRise Good/Bad C' num2str(i)],...
                    ['Int_FRProfileIntRiseGoodBadC' num2str(i)],...
                    pathAnal,[0 45],xlabels)

    %         plotAvgFRProfileCmp(timeStepRun,...
    %                 InitAll.avgFRProfile(IntDown.idxDown{i},:),...
    %                 InitAll.avgFRProfileBad(IntDown.idxDownBadBad{i},:),...
    %                 ['FR IntDown Good/Bad C' num2str(i)],...
    %                 ['Int_FRProfileIntDownGoodBadC' num2str(i)],...
    %                 pathAnal,[],xlabels)

            plotAvgFRProfileCmp(timeStepRun,...
                    InitAll.avgFRProfileNormInt(IntRise.idxRise{i},:),...
                    InitAll.avgFRProfileNormBadInt(IntRise.idxRiseBadBad{i},:),...
                    ['FR Norm IntRise Good/Bad C' num2str(i)],...
                    ['Int_FRProfileNormIntRiseGoodBadC' num2str(i)],...
                    pathAnal,[0 1],xlabels)

    %         plotAvgFRProfileCmp(timeStepRun,...
    %                 InitAll.avgFRProfileNormInt(IntDown.idxDown{i},:),...
    %                 InitAll.avgFRProfileNormBadInt(IntDown.idxDownBadBad{i},:),...
    %                 ['FR Norm IntDown Good/Bad C' num2str(i)],...
    %                 ['Int_FRProfileNormIntDownGoodBadC' num2str(i)],...
    %                 pathAnal,[],xlabels)

            %% FR Change before run vs 0to1s
            if(~isempty(FRProfileMeanIntStat.RiseGoodBad{i}))
                barPlotWithStat1(1:2,...
                        [mean(FRProfileMeanInt.Rise{i}.percChangeBefRunVs0to1),...
                        mean(FRProfileMeanInt.RiseBad{i}.percChangeBefRunVs0to1)],...
                        [std(FRProfileMeanInt.Rise{i}.percChangeBefRunVs0to1)...
                            /sqrt(length(FRProfileMeanInt.Rise{i}.percChangeBefRunVs0to1)),...
                        std(FRProfileMeanInt.RiseBad{i}.percChangeBefRunVs0to1)...
                            /sqrt(length(FRProfileMeanInt.RiseBad{i}.percChangeBefRunVs0to1))],...
                        [],...
                        ['average FR change BefRun/0to1s G/B Rise C' num2str(i)],...
                        '', FRProfileMeanIntStat.RiseGoodBad{i}.pRSPercChangeBefRunVs0to1All,...
                        ['Int_FRChangeBefRun-0to1RiseGoodBadC' num2str(i)],...
                        pathAnal,colorSel,xlabels,[0 2.5]);

    %         barPlotWithStat1(1:2,...
    %                 [mean(FRProfileMeanInt.Down{i}.percChangeBefRunVs0to1),...
    %                 mean(FRProfileMeanInt.DownBad{i}.percChangeBefRunVs0to1)],...
    %                 [std(FRProfileMeanInt.Down{i}.percChangeBefRunVs0to1)...
    %                     /sqrt(length(FRProfileMeanInt.Down{i}.percChangeBefRunVs0to1)),...
    %                 std(FRProfileMeanInt.DownBad{i}.percChangeBefRunVs0to1)...
    %                     /sqrt(length(FRProfileMeanInt.DownBad{i}.percChangeBefRunVs0to1))],...
    %                 [],...
    %                 ['average FR change BefRun/0to1s G/B Down C' num2str(i)],...
    %                 '', FRProfileMeanIntStat.DownGoodBad{i}.pRSPercChangeBefRunVs0to1All,...
    %                 ['Int_FRChangeBefRun-0to1DownGoodBadC' num2str(i)],...
    %                 pathAnal,colorSel,xlabels);

                %% FR rel Change before run vs 0to1s
                indBadNonNan = ~isnan(FRProfileMeanInt.RiseBad{i}.relChangeBefRunVs0to1);
                barPlotWithStat1(1:2,...
                        [mean(FRProfileMeanInt.Rise{i}.relChangeBefRunVs0to1),...
                        mean(FRProfileMeanInt.RiseBad{i}.relChangeBefRunVs0to1(indBadNonNan))],...
                        [std(FRProfileMeanInt.Rise{i}.relChangeBefRunVs0to1)...
                            /sqrt(length(FRProfileMeanInt.Rise{i}.relChangeBefRunVs0to1)),...
                        std(FRProfileMeanInt.RiseBad{i}.relChangeBefRunVs0to1(indBadNonNan))...
                            /sqrt(length(FRProfileMeanInt.RiseBad{i}.relChangeBefRunVs0to1(indBadNonNan)))],...
                        [],...
                        ['rel. FR change BefRun/0to1s G/B Rise C' num2str(i)],...
                        '', FRProfileMeanIntStat.RiseGoodBad{i}.pRSRelChangeBefRunVs0to1All,...
                        ['Int_RelFRChangeBefRun-0to1RiseGoodBadC' num2str(i)],...
                        pathAnal,colorSel,xlabels,[-0.65 0.65]);

    %         barPlotWithStat1(1:2,...
    %                 [mean(FRProfileMeanInt.Down{i}.relChangeBefRunVs0to1),...
    %                 mean(FRProfileMeanInt.DownBad{i}.relChangeBefRunVs0to1)],...
    %                 [std(FRProfileMeanInt.Down{i}.relChangeBefRunVs0to1)...
    %                     /sqrt(length(FRProfileMeanInt.Down{i}.relChangeBefRunVs0to1)),...
    %                 std(FRProfileMeanInt.DownBad{i}.relChangeBefRunVs0to1)...
    %                     /sqrt(length(FRProfileMeanInt.DownBad{i}.relChangeBefRunVs0to1))],...
    %                 [],...
    %                 ['rel. FR change BefRun/0to1s G/B Down C' num2str(i)],...
    %                 '', FRProfileMeanIntStat.DownGoodBad{i}.pRSRelChangeBefRunVs0to1All,...
    %                 ['Int_RelFRChangeBefRun-0to1DownGoodBadC' num2str(i)],...
    %                 pathAnal,colorSel,xlabels);

                %% FR between -1 to 4s    
                barPlotWithStat1(1:2,...
                        [mean(FRProfileMeanInt.Rise{i}.meanAvgFRProfileAll),...
                        mean(FRProfileMeanInt.RiseBad{i}.meanAvgFRProfileAll)],...
                        [std(FRProfileMeanInt.Rise{i}.meanAvgFRProfileAll)...
                            /sqrt(length(FRProfileMeanInt.Rise{i}.meanAvgFRProfileAll)),...
                        std(FRProfileMeanInt.RiseBad{i}.meanAvgFRProfileAll)...
                            /sqrt(length(FRProfileMeanInt.RiseBad{i}.meanAvgFRProfileAll))],...
                        [],...
                        ['average FR All G/B Rise C' num2str(i)],...
                        '', FRProfileMeanIntStat.RiseGoodBad{i}.pRSAll,...
                        ['Int_FRAllRiseGoodBadC' num2str(i)],...
                        pathAnal,colorSel,xlabels,[0 50]);

                %% FR before run    
                barPlotWithStat1(1:2,...
                        [mean(FRProfileMeanInt.Rise{i}.meanAvgFRProfileBefRun),...
                        mean(FRProfileMeanInt.RiseBad{i}.meanAvgFRProfileBefRun)],...
                        [std(FRProfileMeanInt.Rise{i}.meanAvgFRProfileBefRun)...
                            /sqrt(length(FRProfileMeanInt.Rise{i}.meanAvgFRProfileBefRun)),...
                        std(FRProfileMeanInt.RiseBad{i}.meanAvgFRProfileBefRun)...
                            /sqrt(length(FRProfileMeanInt.RiseBad{i}.meanAvgFRProfileBefRun))],...
                        [],...
                        ['average FR BefRun G/B Rise C' num2str(i)],...
                        '', FRProfileMeanIntStat.RiseGoodBad{i}.pRSBefRunAll,...
                        ['Int_FRBefRunRiseGoodBadC' num2str(i)],...
                        pathAnal,colorSel,xlabels,[0 50]);

    %         barPlotWithStat1(1:2,...
    %                 [mean(FRProfileMeanInt.Down{i}.meanAvgFRProfileBefRun),...
    %                 mean(FRProfileMeanInt.DownBad{i}.meanAvgFRProfileBefRun)],...
    %                 [std(FRProfileMeanInt.Down{i}.meanAvgFRProfileBefRun)...
    %                     /sqrt(length(FRProfileMeanInt.Down{i}.meanAvgFRProfileBefRun)),...
    %                 std(FRProfileMeanInt.DownBad{i}.meanAvgFRProfileBefRun)...
    %                     /sqrt(length(FRProfileMeanInt.DownBad{i}.meanAvgFRProfileBefRun))],...
    %                 [],...
    %                 ['average FR BefRun G/B Down C' num2str(i)],...
    %                 '', FRProfileMeanIntStat.DownGoodBad{i}.pRSBefRunAll,...
    %                 ['Int_FRBefRunDownGoodBadC' num2str(i)],...
    %                 pathAnal,colorSel,xlabels,[0 30]);

                %% FR 0 to 1s
                barPlotWithStat1(1:2,...
                        [mean(FRProfileMeanInt.Rise{i}.meanAvgFRProfile0to1),...
                        mean(FRProfileMeanInt.RiseBad{i}.meanAvgFRProfile0to1)],...
                        [std(FRProfileMeanInt.Rise{i}.meanAvgFRProfile0to1)...
                            /sqrt(length(FRProfileMeanInt.Rise{i}.meanAvgFRProfile0to1)),...
                        std(FRProfileMeanInt.RiseBad{i}.meanAvgFRProfile0to1)...
                            /sqrt(length(FRProfileMeanInt.RiseBad{i}.meanAvgFRProfile0to1))],...
                        [],...
                        ['average FR 0to1s G/B Rise C' num2str(i)],...
                        '', FRProfileMeanIntStat.RiseGoodBad{i}.pRS0to1All,...
                        ['Int_FR0to1sRiseGoodBadC' num2str(i)],...
                        pathAnal,colorSel,xlabels,[0 50]);

    %         barPlotWithStat1(1:2,...
    %                 [mean(FRProfileMeanInt.Down{i}.meanAvgFRProfile0to1),...
    %                 mean(FRProfileMeanInt.DownBad{i}.meanAvgFRProfile0to1)],...
    %                 [std(FRProfileMeanInt.Down{i}.meanAvgFRProfile0to1)...
    %                     /sqrt(length(FRProfileMeanInt.Down{i}.meanAvgFRProfile0to1)),...
    %                 std(FRProfileMeanInt.DownBad{i}.meanAvgFRProfile0to1)...
    %                     /sqrt(length(FRProfileMeanInt.DownBad{i}.meanAvgFRProfile0to1))],...
    %                 [],...
    %                 ['average FR 0to1s G/B Down C' num2str(i)],...
    %                 '', FRProfileMeanIntStat.DownGoodBad{i}.pRS0to1All,...
    %                 ['Int_FR0to1sDownGoodBadC' num2str(i)],...
    %                 pathAnal,colorSel,xlabels,[0 30]);
            end
        end
    end
end