function plotPyrNeuRiseDownSigALNoCuePercNeu(pathAnal,PyrRiseAL1,PyrDownAL1,PyrOtherAL1,...
    PyrRiseNoCue1,PyrDownNoCue1,PyrOtherNoCue1,FRProfileMeanPyrStat1,colorSel,xlabels)

    barPlotWithStat1(1:2,...
            [mean(PyrRiseNoCue1.percNeuPerRec),...
            mean(PyrRiseAL1.percNeuPerRec)],...
            [std(PyrRiseNoCue1.percNeuPerRec)...
                /sqrt(length(PyrRiseNoCue1.percNeuPerRec)),...
            std(PyrRiseAL1.percNeuPerRec)...
                /sqrt(length(PyrRiseAL1.percNeuPerRec))],...
            [],...
            ['Perc. neuron per rec. NoCue/AL Rise'],...
            '', FRProfileMeanPyrStat1.RiseALNoCue.pRSPercNeuPerRec,...
            ['Pyr_PercNeuRisePerRecNoCueAL'],...
            pathAnal,colorSel,xlabels);
        
    barPlotWithStat1(1:2,...
            [mean(PyrDownNoCue1.percNeuPerRec),...
            mean(PyrDownAL1.percNeuPerRec)],...
            [std(PyrDownNoCue1.percNeuPerRec)...
                /sqrt(length(PyrDownNoCue1.percNeuPerRec)),...
            std(PyrDownAL1.percNeuPerRec)...
                /sqrt(length(PyrDownAL1.percNeuPerRec))],...
            [],...
            ['Perc. neuron per rec. NoCue/AL Down'],...
            '', FRProfileMeanPyrStat1.DownALNoCue.pRSPercNeuPerRec,...
            ['Pyr_PercNeuDownPerRecNoCueAL'],...
            pathAnal,colorSel,xlabels);
        
    barPlotWithStat1(1:2,...
            [mean(PyrOtherNoCue1.percNeuPerRec),...
            mean(PyrOtherAL1.percNeuPerRec)],...
            [std(PyrOtherNoCue1.percNeuPerRec)...
                /sqrt(length(PyrOtherNoCue1.percNeuPerRec)),...
            std(PyrOtherAL1.percNeuPerRec)...
                /sqrt(length(PyrOtherAL1.percNeuPerRec))],...
            [],...
            ['Perc. neuron per rec. NoCue/AL Other'],...
            '', FRProfileMeanPyrStat1.OtherALNoCue.pRSPercNeuPerRec,...
            ['Pyr_PercNeuOtherPerRecNoCueAL'],...
            pathAnal,colorSel,xlabels);
        