function plotPyrNeuRiseDownNoCueVsAL(pathAnal,timeStepRun,...
            InitAllAL,InitAllNoCue,PyrRiseAL,PyrRiseNoCue,PyrDownAL,PyrDownNoCue,...
            PyrOtherAL,PyrOtherNoCue,FRProfileMeanPyrAL,FRProfileMeanPyrNoCue,...
            FRProfileMeanPyrStat,colorSel,xlabels)

    
    %% average profile No cue vs AL
    plotAvgFRProfileCmp(timeStepRun,...
            InitAllNoCue.avgFRProfile(PyrRiseNoCue.idxRise,:),...
            InitAllAL.avgFRProfile(PyrRiseAL.idxRise,:),...
            ['FR PyrRise NoCue/AL'],...
            ['Pyr_FRProfilePyrRiseNoCueAL'],...
            pathAnal,[0 2.6],xlabels)
        
    plotAvgFRProfileCmp(timeStepRun,...
            InitAllNoCue.avgFRProfile(PyrDownNoCue.idxDown,:),...
            InitAllAL.avgFRProfile(PyrDownAL.idxDown,:),...
            ['FR PyrDown NoCue/AL'],...
            ['Pyr_FRProfilePyrDownNoCueAL'],...
            pathAnal,[0 2.6],xlabels)
        
    % add on 7/9/2022
    plotAvgFRProfileCmp(timeStepRun,...
            InitAllNoCue.avgFRProfile(PyrOtherNoCue.idxOther,:),...
            InitAllAL.avgFRProfile(PyrOtherAL.idxOther,:),...
            ['FR PyrOther NoCue/AL'],...
            ['Pyr_FRProfilePyrOtherNoCueAL'],...
            pathAnal,[0 2.6],xlabels)
        
    plotAvgFRProfileCmp(timeStepRun,...
            InitAllNoCue.avgFRProfileNorm(PyrRiseNoCue.idxRise,:),...
            InitAllAL.avgFRProfileNorm(PyrRiseAL.idxRise,:),...
            ['FR Norm PyrRise NoCue/AL'],...
            ['Pyr_FRProfileNormPyrRiseNoCueAL'],...
            pathAnal,[0 0.6],xlabels)
        
    plotAvgFRProfileCmp(timeStepRun,...
            InitAllNoCue.avgFRProfileNorm(PyrDownNoCue.idxDown,:),...
            InitAllAL.avgFRProfileNorm(PyrDownAL.idxDown,:),...
            ['FR Norm PyrDown NoCue/AL'],...
            ['Pyr_FRProfileNormPyrDownNoCueAL'],...
            pathAnal,[0 0.6],xlabels)

    % add on 7/9/2022
    plotAvgFRProfileCmp(timeStepRun,...
            InitAllNoCue.avgFRProfileNorm(PyrOtherNoCue.idxOther,:),...
            InitAllAL.avgFRProfileNorm(PyrOtherAL.idxOther,:),...
            ['FR Norm PyrOther NoCue/AL'],...
            ['Pyr_FRProfileNormPyrOtherNoCueAL'],...
            pathAnal,[0 0.6],xlabels)
        
    %% FR Change before run vs 0to1s
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyrNoCue.Rise.percChangeBefRunVs0to1),...
            mean(FRProfileMeanPyrAL.Rise.percChangeBefRunVs0to1)],...
            [std(FRProfileMeanPyrNoCue.Rise.percChangeBefRunVs0to1)...
                /sqrt(length(FRProfileMeanPyrNoCue.Rise.percChangeBefRunVs0to1)),...
            std(FRProfileMeanPyrAL.Rise.percChangeBefRunVs0to1)...
                /sqrt(length(FRProfileMeanPyrAL.Rise.percChangeBefRunVs0to1))],...
            [],...
            ['average FR change BefRun/0to1s NoCue/AL Rise'],...
            '', FRProfileMeanPyrStat.RiseALNoCue.pRSPercChangeBefRunVs0to1All,...
            ['Pyr_FRChangeBefRun-0to1RiseNoCueAL'],...
            pathAnal,colorSel,xlabels);
        
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyrNoCue.Down.percChangeBefRunVs0to1),...
            mean(FRProfileMeanPyrAL.Down.percChangeBefRunVs0to1)],...
            [std(FRProfileMeanPyrNoCue.Down.percChangeBefRunVs0to1)...
                /sqrt(length(FRProfileMeanPyrNoCue.Down.percChangeBefRunVs0to1)),...
            std(FRProfileMeanPyrAL.Down.percChangeBefRunVs0to1)...
                /sqrt(length(FRProfileMeanPyrAL.Down.percChangeBefRunVs0to1))],...
            [],...
            ['average FR change BefRun/0to1s NoCue/AL Down'],...
            '', FRProfileMeanPyrStat.DownALNoCue.pRSPercChangeBefRunVs0to1All,...
            ['Pyr_FRChangeBefRun-0to1DownNoCueAL'],...
            pathAnal,colorSel,xlabels);
        
    % add on 7/9/2022
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyrNoCue.Other.percChangeBefRunVs0to1),...
            mean(FRProfileMeanPyrAL.Other.percChangeBefRunVs0to1)],...
            [std(FRProfileMeanPyrNoCue.Other.percChangeBefRunVs0to1)...
                /sqrt(length(FRProfileMeanPyrNoCue.Other.percChangeBefRunVs0to1)),...
            std(FRProfileMeanPyrAL.Other.percChangeBefRunVs0to1)...
                /sqrt(length(FRProfileMeanPyrAL.Other.percChangeBefRunVs0to1))],...
            [],...
            ['average FR change BefRun/0to1s NoCue/AL Other'],...
            '', FRProfileMeanPyrStat.OtherALNoCue.pRSPercChangeBefRunVs0to1All,...
            ['Pyr_FRChangeBefRun-0to1OtherNoCueAL'],...
            pathAnal,colorSel,xlabels);
   
    %% FR rel Change before run vs 0to1s
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyrNoCue.Rise.relChangeBefRunVs0to1),...
            mean(FRProfileMeanPyrAL.Rise.relChangeBefRunVs0to1)],...
            [std(FRProfileMeanPyrNoCue.Rise.relChangeBefRunVs0to1)...
                /sqrt(length(FRProfileMeanPyrNoCue.Rise.relChangeBefRunVs0to1)),...
            std(FRProfileMeanPyrAL.Rise.relChangeBefRunVs0to1)...
                /sqrt(length(FRProfileMeanPyrAL.Rise.relChangeBefRunVs0to1))],...
            [],...
            ['rel. FR change BefRun/0to1s NoCue/AL Rise'],...
            '', FRProfileMeanPyrStat.RiseALNoCue.pRSRelChangeBefRunVs0to1All,...
            ['Pyr_RelFRChangeBefRun-0to1RiseNoCueAL'],...
            pathAnal,colorSel,xlabels,[-0.65 0.65]);
        
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyrNoCue.Down.relChangeBefRunVs0to1),...
            mean(FRProfileMeanPyrAL.Down.relChangeBefRunVs0to1)],...
            [std(FRProfileMeanPyrNoCue.Down.relChangeBefRunVs0to1)...
                /sqrt(length(FRProfileMeanPyrNoCue.Down.relChangeBefRunVs0to1)),...
            std(FRProfileMeanPyrAL.Down.relChangeBefRunVs0to1)...
                /sqrt(length(FRProfileMeanPyrAL.Down.relChangeBefRunVs0to1))],...
            [],...
            ['rel. FR change BefRun/0to1s NoCue/AL Down'],...
            '', FRProfileMeanPyrStat.DownALNoCue.pRSRelChangeBefRunVs0to1All,...
            ['Pyr_RelFRChangeBefRun-0to1DownNoCueAL'],...
            pathAnal,colorSel,xlabels,[-0.65 0.65]);
        
    % add on 7/9/2022
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyrNoCue.Other.relChangeBefRunVs0to1),...
            mean(FRProfileMeanPyrAL.Other.relChangeBefRunVs0to1)],...
            [std(FRProfileMeanPyrNoCue.Other.relChangeBefRunVs0to1)...
                /sqrt(length(FRProfileMeanPyrNoCue.Other.relChangeBefRunVs0to1)),...
            std(FRProfileMeanPyrAL.Other.relChangeBefRunVs0to1)...
                /sqrt(length(FRProfileMeanPyrAL.Other.relChangeBefRunVs0to1))],...
            [],...
            ['rel. FR change BefRun/0to1s NoCue/AL Other'],...
            '', FRProfileMeanPyrStat.OtherALNoCue.pRSRelChangeBefRunVs0to1All,...
            ['Pyr_RelFRChangeBefRun-0to1OtherNoCueAL'],...
            pathAnal,colorSel,xlabels,[-0.65 0.65]);
   
    %% FR between -1 to 4s    
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyrNoCue.Rise.meanAvgFRProfileAll),...
            mean(FRProfileMeanPyrAL.Rise.meanAvgFRProfileAll)],...
            [std(FRProfileMeanPyrNoCue.Rise.meanAvgFRProfileAll)...
                /sqrt(length(FRProfileMeanPyrNoCue.Rise.meanAvgFRProfileAll)),...
            std(FRProfileMeanPyrAL.Rise.meanAvgFRProfileAll)...
                /sqrt(length(FRProfileMeanPyrAL.Rise.meanAvgFRProfileAll))],...
            [],...
            ['average FR All NoCue/AL Rise'],...
            '', FRProfileMeanPyrStat.RiseALNoCue.pRSAll,...
            ['Pyr_FRAllRiseNoCueAL'],...
            pathAnal,colorSel,xlabels,[0 3.1]);
        
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyrNoCue.Down.meanAvgFRProfileAll),...
            mean(FRProfileMeanPyrAL.Down.meanAvgFRProfileAll)],...
            [std(FRProfileMeanPyrNoCue.Down.meanAvgFRProfileAll)...
                /sqrt(length(FRProfileMeanPyrNoCue.Down.meanAvgFRProfileAll)),...
            std(FRProfileMeanPyrAL.Down.meanAvgFRProfileAll)...
                /sqrt(length(FRProfileMeanPyrAL.Down.meanAvgFRProfileAll))],...
            [],...
            ['average FR All NoCue/AL Down'],...
            '', FRProfileMeanPyrStat.DownALNoCue.pRSAll,...
            ['Pyr_FRAllDownNoCueAL'],...
            pathAnal,colorSel,xlabels,[0 3.1]);
        
    % add on 7/9/2022
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyrNoCue.Other.meanAvgFRProfileAll),...
            mean(FRProfileMeanPyrAL.Other.meanAvgFRProfileAll)],...
            [std(FRProfileMeanPyrNoCue.Other.meanAvgFRProfileAll)...
                /sqrt(length(FRProfileMeanPyrNoCue.Other.meanAvgFRProfileAll)),...
            std(FRProfileMeanPyrAL.Other.meanAvgFRProfileAll)...
                /sqrt(length(FRProfileMeanPyrAL.Other.meanAvgFRProfileAll))],...
            [],...
            ['average FR All NoCue/AL Other'],...
            '', FRProfileMeanPyrStat.OtherALNoCue.pRSAll,...
            ['Pyr_FRAllOtherNoCueAL'],...
            pathAnal,colorSel,xlabels,[0 3.1]);
        
    %% FR before run    
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyrNoCue.Rise.meanAvgFRProfileBefRun),...
            mean(FRProfileMeanPyrAL.Rise.meanAvgFRProfileBefRun)],...
            [std(FRProfileMeanPyrNoCue.Rise.meanAvgFRProfileBefRun)...
                /sqrt(length(FRProfileMeanPyrNoCue.Rise.meanAvgFRProfileBefRun)),...
            std(FRProfileMeanPyrAL.Rise.meanAvgFRProfileBefRun)...
                /sqrt(length(FRProfileMeanPyrAL.Rise.meanAvgFRProfileBefRun))],...
            [],...
            ['average FR BefRun NoCue/AL Rise'],...
            '', FRProfileMeanPyrStat.RiseALNoCue.pRSBefRunAll,...
            ['Pyr_FRBefRunRiseNoCueAL'],...
            pathAnal,colorSel,xlabels,[0 3.1]);
        
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyrNoCue.Down.meanAvgFRProfileBefRun),...
            mean(FRProfileMeanPyrAL.Down.meanAvgFRProfileBefRun)],...
            [std(FRProfileMeanPyrNoCue.Down.meanAvgFRProfileBefRun)...
                /sqrt(length(FRProfileMeanPyrNoCue.Down.meanAvgFRProfileBefRun)),...
            std(FRProfileMeanPyrAL.Down.meanAvgFRProfileBefRun)...
                /sqrt(length(FRProfileMeanPyrAL.Down.meanAvgFRProfileBefRun))],...
            [],...
            ['average FR BefRun NoCue/AL Down'],...
            '', FRProfileMeanPyrStat.DownALNoCue.pRSBefRunAll,...
            ['Pyr_FRBefRunDownNoCueAL'],...
            pathAnal,colorSel,xlabels,[0 3.1]);
        
    % add on 7/9/2022
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyrNoCue.Other.meanAvgFRProfileBefRun),...
            mean(FRProfileMeanPyrAL.Other.meanAvgFRProfileBefRun)],...
            [std(FRProfileMeanPyrNoCue.Other.meanAvgFRProfileBefRun)...
                /sqrt(length(FRProfileMeanPyrNoCue.Other.meanAvgFRProfileBefRun)),...
            std(FRProfileMeanPyrAL.Other.meanAvgFRProfileBefRun)...
                /sqrt(length(FRProfileMeanPyrAL.Other.meanAvgFRProfileBefRun))],...
            [],...
            ['average FR BefRun NoCue/AL Other'],...
            '', FRProfileMeanPyrStat.OtherALNoCue.pRSBefRunAll,...
            ['Pyr_FRBefRunOtherNoCueAL'],...
            pathAnal,colorSel,xlabels,[0 3.1]);
    
    %% FR 0 to 1s
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyrNoCue.Rise.meanAvgFRProfile0to1),...
            mean(FRProfileMeanPyrAL.Rise.meanAvgFRProfile0to1)],...
            [std(FRProfileMeanPyrNoCue.Rise.meanAvgFRProfile0to1)...
                /sqrt(length(FRProfileMeanPyrNoCue.Rise.meanAvgFRProfile0to1)),...
            std(FRProfileMeanPyrAL.Rise.meanAvgFRProfile0to1)...
                /sqrt(length(FRProfileMeanPyrAL.Rise.meanAvgFRProfile0to1))],...
            [],...
            ['average FR 0to1s NoCue/AL Rise'],...
            '', FRProfileMeanPyrStat.RiseALNoCue.pRS0to1All,...
            ['Pyr_FR0to1sRiseNoCueAL'],...
            pathAnal,colorSel,xlabels,[0 3.1]);
        
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyrNoCue.Down.meanAvgFRProfile0to1),...
            mean(FRProfileMeanPyrAL.Down.meanAvgFRProfile0to1)],...
            [std(FRProfileMeanPyrNoCue.Down.meanAvgFRProfile0to1)...
                /sqrt(length(FRProfileMeanPyrNoCue.Down.meanAvgFRProfile0to1)),...
            std(FRProfileMeanPyrAL.Down.meanAvgFRProfile0to1)...
                /sqrt(length(FRProfileMeanPyrAL.Down.meanAvgFRProfile0to1))],...
            [],...
            ['average FR 0to1s NoCue/AL Down'],...
            '', FRProfileMeanPyrStat.DownALNoCue.pRS0to1All,...
            ['Pyr_FR0to1sDownNoCueAL'],...
            pathAnal,colorSel,xlabels,[0 3.1]);
        
    % add on 7/9/2022
    barPlotWithStat1(1:2,...
            [mean(FRProfileMeanPyrNoCue.Other.meanAvgFRProfile0to1),...
            mean(FRProfileMeanPyrAL.Other.meanAvgFRProfile0to1)],...
            [std(FRProfileMeanPyrNoCue.Other.meanAvgFRProfile0to1)...
                /sqrt(length(FRProfileMeanPyrNoCue.Other.meanAvgFRProfile0to1)),...
            std(FRProfileMeanPyrAL.Other.meanAvgFRProfile0to1)...
                /sqrt(length(FRProfileMeanPyrAL.Other.meanAvgFRProfile0to1))],...
            [],...
            ['average FR 0to1s NoCue/AL Other'],...
            '', FRProfileMeanPyrStat.OtherALNoCue.pRS0to1All,...
            ['Pyr_FR0to1sOtherNoCueAL'],...
            pathAnal,colorSel,xlabels,[0 3.1]);
end