function plotPyrNeuRiseDownSigFNoFPercNeu(pathAnal,PyrRiseF1,PyrDownF1,PyrOtherF1,...
    PyrRiseNoF1,PyrDownNoF1,PyrOtherNoF1,FRProfileMeanPyrStat,colorSel,xlabels)

    barPlotWithStat1(1:2,...
            [mean(PyrRiseNoF1.percNeuPerRec),...
            mean(PyrRiseF1.percNeuPerRec)],...
            [std(PyrRiseNoF1.percNeuPerRec)...
                /sqrt(length(PyrRiseNoF1.percNeuPerRec)),...
            std(PyrRiseF1.percNeuPerRec)...
                /sqrt(length(PyrRiseF1.percNeuPerRec))],...
            [],...
            ['Perc. neuron per rec. NoF/F Rise'],...
            '', FRProfileMeanPyrStat.Rise.pRSPercNeuPerRec,...
            ['Pyr_PercNeuRisePerRecFNoF'],...
            pathAnal,colorSel,xlabels);
        
    barPlotWithStat1(1:2,...
            [mean(PyrDownNoF1.percNeuPerRec),...
            mean(PyrDownF1.percNeuPerRec)],...
            [std(PyrDownNoF1.percNeuPerRec)...
                /sqrt(length(PyrDownNoF1.percNeuPerRec)),...
            std(PyrDownF1.percNeuPerRec)...
                /sqrt(length(PyrDownF1.percNeuPerRec))],...
            [],...
            ['Perc. neuron per rec. NoF/F Down'],...
            '', FRProfileMeanPyrStat.Down.pRSPercNeuPerRec,...
            ['Pyr_PercNeuDownPerRecFNoF'],...
            pathAnal,colorSel,xlabels);
        
    barPlotWithStat1(1:2,...
            [mean(PyrOtherNoF1.percNeuPerRec),...
            mean(PyrOtherF1.percNeuPerRec)],...
            [std(PyrOtherNoF1.percNeuPerRec)...
                /sqrt(length(PyrOtherNoF1.percNeuPerRec)),...
            std(PyrOtherF1.percNeuPerRec)...
                /sqrt(length(PyrOtherF1.percNeuPerRec))],...
            [],...
            ['Perc. neuron per rec. NoF/F Other'],...
            '', FRProfileMeanPyrStat.Other.pRSPercNeuPerRec,...
            ['Pyr_PercNeuOtherPerRecFNoF'],...
            pathAnal,colorSel,xlabels);
        