function plotClusterPCA(pathAnal,autoCorrIntAll,autoCorrIntTag)
%% plot the clustering results in PCA space
% This function is called by InterneuronPropAllRec

    plotCompCPCA(autoCorrIntAll.scorekm11(:,1),autoCorrIntAll.scorekm12(:,1),...
        autoCorrIntAll.scorekm12(:,2),'PC1','PC2','PC3',autoCorrIntAll.idxC1,...
        'PCA space 1');
    fileName1 = [pathAnal 'Interneuron_PCAClustersAng12'];
    saveas(gcf,fileName1);
    print('-painters', '-dpdf', fileName1, '-r600')
        
    plotCompCPCA(autoCorrIntAll.scorekm21(:,1),autoCorrIntAll.scorekm22(:,1),...
        autoCorrIntAll.scorekm22(:,2),'PC1','PC2','PC3',autoCorrIntAll.idxC2,...
        'PCA space 2');
    fileName1 = [pathAnal 'Interneuron_PCAClustersAng21'];
    saveas(gcf,fileName1);
    print('-painters', '-dpdf', fileName1, '-r600')
    
    plotCompCPCA(autoCorrIntAll.scorekm31(:,1),autoCorrIntAll.scorekm32(:,1),...
        autoCorrIntAll.scorekm32(:,2),'PC1','PC2','PC3',autoCorrIntAll.idxC3,...
        'PCA space 3');
    fileName1 = [pathAnal 'Interneuron_PCAClustersAng31'];
    saveas(gcf,fileName1);
    print('-painters', '-dpdf', fileName1, '-r600')
    
    idxTagPV = autoCorrIntTag.cellType == 1;
    plotCompCPCATagC5(autoCorrIntAll.scorekm11(:,1),autoCorrIntAll.scorekm12(:,1),...
        autoCorrIntAll.scorekm12(:,2),...
        autoCorrIntTag.scorekm11(idxTagPV,1),autoCorrIntTag.scorekm12(idxTagPV,1),...
        autoCorrIntTag.scorekm12(idxTagPV,2),'PC1','PC2','PC3',autoCorrIntAll.idxC1,...
        'PCA space PV 1');
    fileName1 = [pathAnal 'Interneuron_PCAClustersScoreKm11TagPV'];
    saveas(gcf,fileName1);
    print('-painters', '-dpdf', fileName1, '-r600')
    
    idxTagSST = autoCorrIntTag.cellType == 2;
    plotCompCPCATagC5(autoCorrIntAll.scorekm11(:,1),autoCorrIntAll.scorekm12(:,1),...
        autoCorrIntAll.scorekm12(:,2),...
        autoCorrIntTag.scorekm11(idxTagSST,1),autoCorrIntTag.scorekm12(idxTagSST,1),...
        autoCorrIntTag.scorekm12(idxTagSST,2),'PC1','PC2','PC3',autoCorrIntAll.idxC1,...
        'PCA space SST 1');
    fileName1 = [pathAnal 'Interneuron_PCAClustersScoreKm11TagSST'];
    saveas(gcf,fileName1);
    print('-painters', '-dpdf', fileName1, '-r600')
    
    plotCompCPCATagC5(autoCorrIntAll.scorekm21(:,1),autoCorrIntAll.scorekm22(:,1),...
        autoCorrIntAll.scorekm22(:,2),...
        autoCorrIntTag.scorekm21(idxTagPV,1),autoCorrIntTag.scorekm22(idxTagPV,1),...
        autoCorrIntTag.scorekm22(idxTagPV,2),'PC1','PC2','PC3',autoCorrIntAll.idxC2,...
        'PCA space PV 2');
    fileName1 = [pathAnal 'Interneuron_PCAClustersScoreKm21TagPV'];
    saveas(gcf,fileName1);
    print('-painters', '-dpdf', fileName1, '-r600')
    
    plotCompCPCATagC5(autoCorrIntAll.scorekm21(:,1),autoCorrIntAll.scorekm22(:,1),...
        autoCorrIntAll.scorekm22(:,2),...
        autoCorrIntTag.scorekm21(idxTagSST,1),autoCorrIntTag.scorekm22(idxTagSST,1),...
        autoCorrIntTag.scorekm22(idxTagSST,2),'PC1','PC2','PC3',autoCorrIntAll.idxC2,...
        'PCA space SST 2');
    fileName1 = [pathAnal 'Interneuron_PCAClustersScoreKm21TagSST'];
    saveas(gcf,fileName1);
    print('-painters', '-dpdf', fileName1, '-r600')
    
    plotCompCPCATagC5(autoCorrIntAll.scorekm31(:,1),autoCorrIntAll.scorekm32(:,1),...
        autoCorrIntAll.scorekm32(:,2),...
        autoCorrIntTag.scorekm31(idxTagPV,1),autoCorrIntTag.scorekm32(idxTagPV,1),...
        autoCorrIntTag.scorekm32(idxTagPV,2),'PC1','PC2','PC3',autoCorrIntAll.idxC3,...
        'PCA space PV 3');
    fileName1 = [pathAnal 'Interneuron_PCAClustersScoreKm31TagPV'];
    saveas(gcf,fileName1);
    print('-painters', '-dpdf', fileName1, '-r600')
    
    plotCompCPCATagC5(autoCorrIntAll.scorekm31(:,1),autoCorrIntAll.scorekm32(:,1),...
        autoCorrIntAll.scorekm32(:,2),...
        autoCorrIntTag.scorekm31(idxTagSST,1),autoCorrIntTag.scorekm32(idxTagSST,1),...
        autoCorrIntTag.scorekm32(idxTagSST,2),'PC1','PC2','PC3',autoCorrIntAll.idxC3,...
        'PCA space SST 3');
    fileName1 = [pathAnal 'Interneuron_PCAClustersScoreKm31TagSST'];
    saveas(gcf,fileName1);
    print('-painters', '-dpdf', fileName1, '-r600')
    
    