function InterneuronModAllRec(onlyRun,task)

    methodKMean = 2;

    RecordingListPyrInt;  % include all the early NoCue (no blackout), PL and AL (up to A057)
    pathAnal0 = 'Z:\Yingxue\Draft\PV\Interneuron\';
    if(task == 1) % including all the neurons
        pathAnal = 'Z:\Yingxue\Draft\PV\Interneuron\';
    elseif(task == 2) % including AL and PL neurons
        pathAnal = 'Z:\Yingxue\Draft\PV\InterneuronALPL\';
    else % AL neurons only
        pathAnal = 'Z:\Yingxue\Draft\PV\InterneuronAL\';
    end
    
    load([pathAnal0 'autoCorrIntAllRec.mat']);
    
%     figure
%     for i = 1:max(idxC)
%         indCurC = idxC == i;
%         h = plot(phaseMeanDire(indCurC),phaseDiff(indCurC),'o');
%         set(gca,'XLim',[0 2*pi],'YLim',[0 300])
%         pause;
%     end

    modInt = InterneuronModAllRecByType(modIntNoCue,modIntAL,modIntPL,...
        autoCorrIntNoCue,autoCorrIntAL,autoCorrIntPL,autoCorrIntAll,task);

    modIntStatsField = modIntStatsFieldRec(modInt,autoCorrIntAll);
    
    save([pathAnal 'autoCorrIntAllRec_km' num2str(methodKMean) '.mat'],'modInt','modIntStatsField');
    
    %% compare cluster 1, recordings with fields vs. without
    colorSel = 1;
    cluster = 2;
    plotClusterFieldVsNoFieldRec(pathAnal,modInt,modIntStatsField,cluster,colorSel);
    
    %% compare cluster 2, recordings with fields vs. without
    colorSel = 6;
    cluster = 3;
    plotClusterFieldVsNoFieldRec(pathAnal,modInt,modIntStatsField,cluster,colorSel);
    
    colorSel = 4;
    cluster = 4;
    plotClusterFieldVsNoFieldRec(pathAnal,modInt,modIntStatsField,cluster,colorSel);
    
    colorSel = 2;
    cluster = 5;
    plotClusterFieldVsNoFieldRec(pathAnal,modInt,modIntStatsField,cluster,colorSel);
    
%     indCurCField = idxC == cluster & nNeuWithField >= 2;
%     indCurCNoField = idxC == cluster & nNeuWithField < 1;
%     plotBoxPlot(phaseMeanDire(indCurCField),...
%         phaseMeanDire(indCurCNoField),'Mean theta phase',['Int_ThetaMeanC' num2str(cluster) 'Field-NoFieldBox'],...
%         pathAnal,[0 pi],modIntStatsField.pWWPhaseMeanDire(cluster),colorSel);
%     
%     plotBoxPlot(thetaModHist(indCurCField),...
%         thetaModHist(indCurCNoField),'Theta modulation',['Int_ThetaModHistC' num2str(cluster) 'Field-NoFieldBox'],...
%         pathAnal,[0 1.2],modIntStatsField.pRSThetaModHist(cluster),colorSel);
%     
%     plotBoxPlot(fractBurst(indCurCField),...
%         fractBurst(indCurCNoField),'Fract. burst',['Int_FractBurstC' num2str(cluster) 'Field-NoFieldBox'],...
%         pathAnal,[-0.1 0.4],modIntStatsField.pRSFractBurst(cluster),colorSel);
%     
%     nonZeroF = numSpPerBurstMean(indCurCField);
%     nonZeroF = nonZeroF(nonZeroF > 0);
%     nonZeroNoF = numSpPerBurstMean(indCurCNoField);
%     nonZeroNoF = nonZeroNoF(nonZeroNoF > 0);
%     plotBoxPlot(nonZeroF,...
%         nonZeroNoF,'Burst length',['Int_NumSpPerBurstMeanC' num2str(cluster) 'Field-NoFieldBox'],...
%         pathAnal,[1 4],modIntStatsField.pRSNumSpPerBurstMean(cluster),colorSel);
%     
%     plotBoxPlot(nonBurstMeanDire(indCurCField),...
%         nonBurstMeanDire(indCurCNoField),'Non-burst phase',['Int_NonBurstMeanDireC' num2str(cluster) 'Field-NoFieldBox'],...
%         pathAnal,[0 pi],modIntStatsField.pWWNonBurstMeanDire(cluster),colorSel);
%     
%     plotBoxPlot(burstMeanDire(indCurCField),...
%         burstMeanDire(indCurCNoField),'Burst phase',['Int_BurstMeanDireC' num2str(cluster) 'Field-NoFieldBox'],...
%         pathAnal,[0 2*pi],modIntStatsField.pWWBurstMeanDire(cluster),colorSel);
%     
%     plotPolarPlot(phaseMeanDire(indCurCField),...
%         phaseMeanDire(indCurCNoField),'Mean theta phase',...
%         ['Int_ThetaMeanC' num2str(cluster) 'Field-NoFieldPolar'],pathAnal,modIntStatsField.pWWPhaseMeanDire(cluster),colorSel);
%     
%     plotPolarPlot(phaseMeanDire(idxC == cluster),...
%         [],'Mean theta phase',...
%         ['Int_ThetaMeanCPolar' num2str(cluster)],pathAnal,1,colorSel);
%     
%     plotPolarPlot(burstMeanDire(idxC == cluster),...
%         [],'Burst phase',...
%         ['Int_BurstMeanDireCPolar' num2str(cluster)],pathAnal,1,colorSel);
%     
%     plotPolarPlot(maxPhaseArr(indCurCField)/180*pi,...
%         maxPhaseArr(indCurCNoField)/180*pi,'Max theta phase',['Int_MaxPhaseC' num2str(cluster) 'Field-NoFieldPolar'],...
%         pathAnal,modIntStatsField.pWWMaxPhase(cluster),colorSel);
%     
%     plotPolarPlot(minPhaseArr(indCurCField)/180*pi,...
%         minPhaseArr(indCurCNoField)/180*pi,'Min theta phase',['Int_MinPhaseC' num2str(cluster) 'Field-NoFieldPolar'],...
%         pathAnal,modIntStatsField.pWWMinPhase(cluster),colorSel);
%     
%     plotPolarPlot(burstMeanDire(indCurCField),...
%         burstMeanDire(indCurCNoField),'Burst phase',['Int_BurstMeanDireC' num2str(cluster) 'Field-NoFieldPolar'],...
%         pathAnal,modIntStatsField.pWWBurstMeanDire(cluster),colorSel);
    
%     %% compare cluster 4, recordings with fields vs. without
%     colorSel = 4;
%     cluster = 1;
%     indCurCField = idxC == cluster & nNeuWithField >= 2;
%     indCurCNoField = idxC == cluster & nNeuWithField < 1;
%     plotBoxPlot(phaseMeanDire(indCurCField),...
%         phaseMeanDire(indCurCNoField),'Mean theta phase',['Int_ThetaMeanC' num2str(cluster) 'Field-NoFieldBox'],...
%         pathAnal,[0 pi],modIntStatsField.pWWPhaseMeanDire(cluster),colorSel);
%     
%     plotBoxPlot(thetaModHist(indCurCField),...
%         thetaModHist(indCurCNoField),'Theta modulation',['Int_ThetaModHistC' num2str(cluster) 'Field-NoFieldBox'],...
%         pathAnal,[0 1.2],modIntStatsField.pRSThetaModHist(cluster),colorSel);
%     
%     plotBoxPlot(fractBurst(indCurCField),...
%         fractBurst(indCurCNoField),'Fract. burst',['Int_FractBurstC' num2str(cluster) 'Field-NoFieldBox'],...
%         pathAnal,[-0.1 0.2],modIntStatsField.pRSFractBurst(cluster),colorSel);
%     
%     nonZeroF = numSpPerBurstMean(indCurCField);
%     nonZeroF = nonZeroF(nonZeroF > 0);
%     nonZeroNoF = numSpPerBurstMean(indCurCNoField);
%     nonZeroNoF = nonZeroNoF(nonZeroNoF > 0);
%     plotBoxPlot(nonZeroF,...
%         nonZeroNoF,'Burst length',['Int_NumSpPerBurstMeanC' num2str(cluster) 'Field-NoFieldBox'],...
%         pathAnal,[1 4],modIntStatsField.pRSNumSpPerBurstMean(cluster),colorSel);
%     
%     plotBoxPlot(nonBurstMeanDire(indCurCField),...
%         nonBurstMeanDire(indCurCNoField),'Non-burst phase',['Int_NonBurstMeanDireC' num2str(cluster) 'Field-NoFieldBox'],...
%         pathAnal,[0 pi],modIntStatsField.pWWNonBurstMeanDire(cluster),colorSel);
%     
%     plotBoxPlot(burstMeanDire(indCurCField),...
%         burstMeanDire(indCurCNoField),'Burst phase',['Int_BurstMeanDireC' num2str(cluster) 'Field-NoFieldBox'],...
%         pathAnal,[0 2*pi],modIntStatsField.pWWBurstMeanDire(cluster),colorSel);
%     
%     plotPolarPlot(phaseMeanDire(indCurCField),...
%         phaseMeanDire(indCurCNoField),'Mean theta phase',...
%         ['Int_ThetaMeanC' num2str(cluster) 'Field-NoFieldPolar'],pathAnal,modIntStatsField.pWWPhaseMeanDire(cluster),colorSel);
%     
%     plotPolarPlot(maxPhaseArr(indCurCField)/180*pi,...
%         maxPhaseArr(indCurCNoField)/180*pi,'Max theta phase',['Int_MaxPhaseC' num2str(cluster) 'Field-NoFieldPolar'],...
%         pathAnal,modIntStatsField.pWWMaxPhase(cluster),colorSel);
%     
%     plotPolarPlot(minPhaseArr(indCurCField)/180*pi,...
%         minPhaseArr(indCurCNoField)/180*pi,'Min theta phase',['Int_MinPhaseC' num2str(cluster) 'Field-NoFieldPolar'],...
%         pathAnal,modIntStatsField.pWWMinPhase(cluster),colorSel);
%     
%     plotPolarPlot(burstMeanDire(indCurCField),...
%         burstMeanDire(indCurCNoField),'Burst phase',['Int_BurstMeanDireC' num2str(cluster) 'Field-NoFieldPolar'],...
%         pathAnal,modIntStatsField.pWWBurstMeanDire(cluster),colorSel);
    
%     %% compare cluster 6, recordings with fields vs. without
%     colorSel = 2;
%     cluster = 3;
%     indCurCField = idxC == cluster & nNeuWithField >= 2;
%     indCurCNoField = idxC == cluster & nNeuWithField < 1;
%     plotBoxPlot(phaseMeanDire(indCurCField),...
%         phaseMeanDire(indCurCNoField),'Mean theta phase',['Int_ThetaMeanC' num2str(cluster) 'Field-NoFieldBox'],...
%         pathAnal,[0 pi*2],modIntStatsField.pWWPhaseMeanDire(cluster),colorSel);
%     
%     plotBoxPlot(thetaModHist(indCurCField),...
%         thetaModHist(indCurCNoField),'Theta modulation',['Int_ThetaModHistC' num2str(cluster) 'Field-NoFieldBox'],...
%         pathAnal,[0 1.2],modIntStatsField.pRSThetaModHist(cluster),colorSel);
%     
%     plotBoxPlot(fractBurst(indCurCField),...
%         fractBurst(indCurCNoField),'Fract. burst',['Int_FractBurstC' num2str(cluster) 'Field-NoFieldBox'],...
%         pathAnal,[-0.1 0.2],modIntStatsField.pRSFractBurst(cluster),colorSel);
%     
%     nonZeroF = numSpPerBurstMean(indCurCField);
%     nonZeroF = nonZeroF(nonZeroF > 0);
%     nonZeroNoF = numSpPerBurstMean(indCurCNoField);
%     nonZeroNoF = nonZeroNoF(nonZeroNoF > 0);
%     plotBoxPlot(nonZeroF,...
%         nonZeroNoF,'Burst length',['Int_NumSpPerBurstMeanC' num2str(cluster) 'Field-NoFieldBox'],...
%         pathAnal,[1 4],modIntStatsField.pRSNumSpPerBurstMean(cluster),colorSel);
%     
%     plotBoxPlot(nonBurstMeanDire(indCurCField),...
%         nonBurstMeanDire(indCurCNoField),'Non-burst phase',['Int_NonBurstMeanDireC' num2str(cluster) 'Field-NoFieldBox'],...
%         pathAnal,[0 pi*2],modIntStatsField.pWWNonBurstMeanDire(cluster),colorSel);
%     
%     plotBoxPlot(burstMeanDire(indCurCField),...
%         burstMeanDire(indCurCNoField),'Burst phase',['Int_BurstMeanDireC' num2str(cluster) 'Field-NoFieldBox'],...
%         pathAnal,[0 2*pi],modIntStatsField.pWWBurstMeanDire(cluster),colorSel);
%     
%     plotPolarPlot(phaseMeanDire(indCurCField),...
%         phaseMeanDire(indCurCNoField),'Mean theta phase',...
%         ['Int_ThetaMeanC' num2str(cluster) 'Field-NoFieldPolar'],pathAnal,modIntStatsField.pWWPhaseMeanDire(cluster),colorSel);
%     
%     plotPolarPlot(maxPhaseArr(indCurCField)/180*pi,...
%         maxPhaseArr(indCurCNoField)/180*pi,'Max theta phase',['Int_MaxPhaseC' num2str(cluster) 'Field-NoFieldPolar'],...
%         pathAnal,modIntStatsField.pWWMaxPhase(cluster),colorSel);
%     
%     plotPolarPlot(minPhaseArr(indCurCField)/180*pi,...
%         minPhaseArr(indCurCNoField)/180*pi,'Min theta phase',['Int_MinPhaseC' num2str(cluster) 'Field-NoFieldPolar'],...
%         pathAnal,modIntStatsField.pWWMinPhase(cluster),colorSel);
%     
%     plotPolarPlot(burstMeanDire(indCurCField),...
%         burstMeanDire(indCurCNoField),'Burst phase',['Int_BurstMeanDireC' num2str(cluster) 'Field-NoFieldPolar'],...
%         pathAnal,modIntStatsField.pWWBurstMeanDire(cluster),colorSel);
%     
    %%
%     plotClustersFieldsPhase(pathAnal,burstMeanDire,phaseMeanDire,...
%         idxC,indField,...
%         'Burst mean direction','Theta phase mean direction','All tasks',...
%         'Interneuron_BurstMeanVsThetaMean');
%     
%     plotClustersFields(pathAnal,thetaModHist,phaseMeanDire,...
%         idxC,indField,...
%         'Theta modulation (hist)','Theta phase mean direction','All tasks',...
%         'Interneuron_ThetaModHistVsThetaMean');
%     
%     plotClustersFields(pathAnal,thetaModHistH,phaseMeanDireH,...
%         idxC,indField,...
%         'Theta modulation (hist hilbert)','Theta phase mean direction (hilbert)','All tasks',...
%         'Interneuron_ThetaModHistHVsThetaMean');
%    
%     plotClustersFields(pathAnal,burstMeanDire,fractBurst,...
%         idxC,indField,...
%         'Burst mean direction','Fract burst','All tasks',...
%         'Interneuron_BurstMeanVsFractBurst');
%     
% %     plotClustersFields(pathAnal,phaseMeanDire,thetaModFreq3,...
% %         idxC,indField,...
% %         'Theta phase mean direction','Theta modulation freq. (Hz)','All tasks',...
% %         'Interneuron_ThetaMeanVsModFreq');
%     
%     plotClustersFields(pathAnal,phaseMeanDire,phaseDiff,...
%         idxC,indField,...
%         'Theta phase mean direction','Max-min theta phase','All tasks',...
%         'Interneuron_ThetaMeanVsPhaseDiff');
%     
%     plotClustersFields(pathAnal,phaseMeanDire,minPhaseArr,...
%         idxC,indField,...
%         'Theta phase mean direction','Min theta phase','All tasks',...
%         'Interneuron_ThetaMeanVsMinPhase');
%     
%     plotClustersFields(pathAnal,phaseMeanDire,thetaAsym3,...
%         idxC,indField,...
%         'Theta phase mean direction','Theta asymmetry','All tasks',...
%         'Interneuron_ThetaMeanVsThetaAsym');
%     
%     plotClustersFieldsPhase(pathAnal,burstMeanDire,nonBurstMeanDire,...
%         idxC,indField,...
%         'Burst mean direction','Nonburst mean direction','All tasks',...
%         'Interneuron_BurstMeanVsNonBurstMean');
%     
%     plotClustersFields(pathAnal,thetaModFreq3,thetaAsym3,...
%         idxC,indField,...
%         'Theta modulation freq. (Hz)','Theta asymmetry','All tasks',...
%         'Interneuron_ModFreqVsThetaAsym');

end

function plotClustersFieldsPhase(pathAnal,x,y,idx,indField,xl,yl,ti,fileN)
    plotClusters(x(indField),y(indField),...
        idx(indField),xl,yl,[ti ' - field']);
    plot([0 2*pi],[0 2*pi],'k-')
    
    fileName1 = [pathAnal fileN 'Field'];
    saveas(gcf,fileName1);
    print('-painters', '-dpdf', fileName1, '-r600')
    
    plotClusters(x(~indField),y(~indField),...
        idx(~indField),xl,yl,[ti ' - no field']);
    plot([0 2*pi],[0 2*pi],'k-')
    
    fileName1 = [pathAnal fileN 'NoField'];
    saveas(gcf,fileName1);
    print('-painters', '-dpdf', fileName1, '-r600')
end

function plotClustersFields(pathAnal,x,y,idx,indField,xl,yl,ti,fileN)
    plotClusters(x(indField),y(indField),...
        idx(indField),xl,yl,[ti ' - field']);
    
    fileName1 = [pathAnal fileN 'Field'];
    saveas(gcf,fileName1);
    print('-painters', '-dpdf', fileName1, '-r600')
    
    plotClusters(x(~indField),y(~indField),...
        idx(~indField),xl,yl,[ti ' - no field']);
    
    fileName1 = [pathAnal fileN 'NoField'];
    saveas(gcf,fileName1);
    print('-painters', '-dpdf', fileName1, '-r600')
end
