function plotClusterFieldVsNoFieldRec(pathAnal,modInt,modIntStatsField,cluster,colorSel)
%% compare interneurons in recordings with vs without fields
% this function is called by InterneuronModAllRec.m

    indCurCField = modInt.idxC == cluster & modInt.nNeuWithField >= 2;
    indCurCNoField = modInt.idxC == cluster & modInt.nNeuWithField < 1;
    plotBoxPlot(modInt.phaseMeanDire(indCurCField),...
        modInt.phaseMeanDire(indCurCNoField),['Mean theta phase C' num2str(cluster)],...
        ['Int_ThetaMeanC' num2str(cluster) 'Field-NoFieldBox'],...
        pathAnal,[0 2*pi],modIntStatsField.pWWPhaseMeanDire(cluster),colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(modInt.maxPhaseArr(indCurCField)/180*pi,...
        modInt.maxPhaseArr(indCurCNoField)/180*pi,['Max theta phase C' num2str(cluster)],...
        ['Int_ThetaMaxC' num2str(cluster) 'Field-NoFieldBox'],...
        pathAnal,[0 2*pi],modIntStatsField.pWWMaxPhase(cluster),colorSel,[{'F'} {'NoF'}]);
  
    minPhaseField = modInt.minPhaseArr(indCurCField)/180*pi;
    minPhaseNoField = modInt.minPhaseArr(indCurCNoField)/180*pi;
    minPhaseField(minPhaseField > pi) = minPhaseField(minPhaseField > pi) - 2*pi;
    minPhaseNoField(minPhaseNoField > pi) = minPhaseNoField(minPhaseNoField > pi) - 2*pi;
    plotBoxPlot(minPhaseField,...
        minPhaseNoField,['Min theta phase C' num2str(cluster)],...
        ['Int_ThetaMinC' num2str(cluster) 'Field-NoFieldBox'],...
        pathAnal,[-pi pi],modIntStatsField.pWWMinPhase(cluster),colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(modInt.fractBurst(indCurCField),...
        modInt.fractBurst(indCurCNoField),['Fract. burst C' num2str(cluster)],...
        ['Int_FractBurstC' num2str(cluster) 'Field-NoFieldBox'],...
        pathAnal,[-0.1 0.6],modIntStatsField.pRSFractBurst(cluster),colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(modInt.thetaModHist(indCurCField),...
        modInt.thetaModHist(indCurCNoField),['Theta modulation C' num2str(cluster)],...
        ['Int_ThetaModHistC' num2str(cluster) 'Field-NoFieldBox'],...
        pathAnal,[0 1.2],modIntStatsField.pRSThetaModHist(cluster),colorSel,[{'F'} {'NoF'}]);
    
    nonZeroF = modInt.numSpPerBurstMean(indCurCField);
    nonZeroF = nonZeroF(nonZeroF > 0);
    nonZeroNoF = modInt.numSpPerBurstMean(indCurCNoField);
    nonZeroNoF = nonZeroNoF(nonZeroNoF > 0);
    plotBoxPlot(nonZeroF,...
        nonZeroNoF,['Burst length C' num2str(cluster)],...
        ['Int_NumSpPerBurstMeanC' num2str(cluster) 'Field-NoFieldBox'],...
        pathAnal,[1 4],modIntStatsField.pRSNumSpPerBurstMean(cluster),colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(modInt.burstMeanDire(indCurCField),...
        modInt.burstMeanDire(indCurCNoField),['Burst phase C' num2str(cluster)],...
        ['Int_BurstMeanDireC' num2str(cluster) 'Field-NoFieldBox'],...
        pathAnal,[0 2*pi],modIntStatsField.pWWBurstMeanDire(cluster),colorSel,[{'F'} {'NoF'}]);
    
    plotBoxPlot(modInt.nonBurstMeanDire(indCurCField),...
        modInt.nonBurstMeanDire(indCurCNoField),['Non-burst phase C' num2str(cluster)],...
        ['Int_NonBurstMeanDireC' num2str(cluster) 'Field-NoFieldBox'],...
        pathAnal,[1 5],modIntStatsField.pWWNonBurstMeanDire(cluster),colorSel,[{'F'} {'NoF'}]);
    
    plotPolarPlot(modInt.phaseMeanDire(modInt.idxC == cluster),...
        [],['Mean theta phase C' num2str(cluster)],...
        ['Int_ThetaMeanCPolar' num2str(cluster)],pathAnal,1);
    
    plotPolarPlot(modInt.burstMeanDire(modInt.idxC == cluster),...
        [],['Burst phase C' num2str(cluster)],...
        ['Int_BurstMeanDireCPolar' num2str(cluster)],pathAnal,1);
    
    plotPolarPlot(modInt.phaseMeanDire(indCurCField),...
        modInt.phaseMeanDire(indCurCNoField),['Mean theta phase C' num2str(cluster)],...
        ['Int_ThetaMeanC1' num2str(cluster) 'Field-NoFieldPolar'],...
        pathAnal,modIntStatsField.pWWPhaseMeanDire(cluster));
    
    plotPolarPlot(modInt.maxPhaseArr(indCurCField)/180*pi,...
        modInt.maxPhaseArr(indCurCNoField)/180*pi,['Max theta phase C' num2str(cluster)],...
        ['Int_MaxPhaseC' num2str(cluster) 'Field-NoFieldPolar'],...
        pathAnal,modIntStatsField.pWWMaxPhase(cluster));
    
    plotPolarPlot(modInt.minPhaseArr(indCurCField)/180*pi,...
        modInt.minPhaseArr(indCurCNoField)/180*pi,['Min theta phase C' num2str(cluster)],...
        ['Int_MinPhaseC' num2str(cluster) 'Field-NoFieldPolar'],...
        pathAnal,modIntStatsField.pWWMinPhase(cluster));
    
    plotPolarPlot(modInt.burstMeanDire(indCurCField),...
        modInt.burstMeanDire(indCurCNoField),['Burst phase C' num2str(cluster)],...
        ['Int_BurstMeanDireC' num2str(cluster) 'Field-NoFieldPolar'],...
        pathAnal,modIntStatsField.pKBurstMeanDire(cluster));