function plotCmpIntSegProfile(pathAnal,modInt1,FRProfileMean,FRProfileMeanStatC,colorSel)

    % compare each segment of avgFRProfile
    for i = 1:max(modInt1.idxC)    
        FRBLArr = modInt1.avgFRProfile(modInt1.idxC == i,FRProfileMean.indFRBaseline);
        FR0to1Arr = modInt1.avgFRProfile(modInt1.idxC == i,FRProfileMean.indFR0to1);
        plotBoxPlot(FR0to1Arr(:),FRBLArr(:),...
            ['C' num2str(i) ' average FR (Hz) All BL vs 0to1s All'],...
            ['Int_FRMeanC' num2str(i) 'BL-0to1BoxAll'],...
            pathAnal,[],FRProfileMeanStatC.pRS0to1VsBL(i),colorSel,[{'baseline'} {'0to1s'}]);
        
        FRBefRunArr = modInt1.avgFRProfile(modInt1.idxC == i,FRProfileMean.indFRBefRun);
        plotBoxPlot(FRBLArr(:),FRBefRunArr(:),...
            ['C' num2str(i) ' average FR (Hz) All BL vs BefRun All'],...
            ['Int_FRMeanC' num2str(i) 'BL-BefRunBoxAll'],...
            pathAnal,[],FRProfileMeanStatC.pRSBefRunVsBL(i),colorSel,[{'baseline'} {'befRun'}]);
         
        plotBoxPlot(FRBefRunArr(:),FR0to1Arr(:),...
            ['C' num2str(i) ' average FR (Hz) All BefRun vs 0to1s All'],...
            ['Int_FRMeanC' num2str(i) 'BefRun-0to1BoxAll'],...
            pathAnal,[],FRProfileMeanStatC.pRS0to1VsBefRun(i),colorSel,[{'befRun'} {'0to1s'} ]);
         
    end