function plotCmpIntMeanSegRatioProfileGoodBad(pathAnal,modInt1,FRProfileMeanGood,FRProfileMeanBad,FRProfileMeanStatC,colorSel)

    % compare the mean ratio of a pair of segments of avgFRProfile (Good vs. bad)
    for i = 1:max(modInt1.idxC)   
        x = FRProfileMeanGood.meanAvgFRProfileBaseline;
        x1 = FRProfileMeanBad.meanAvgFRProfileBaseline;
        y = FRProfileMeanGood.meanAvgFRProfile0to1;
        y1 = FRProfileMeanBad.meanAvgFRProfile0to1;
        barPlotWithStat3(1:2, [mean(y./x),mean(y1./x1)],...
            [std(y./x)/sqrt(length(x)),std(y1./x1)/sqrt(length(x1))],...
            y./x, y1./x1,['C' num2str(i) ' average mFR (Hz) change 0to1s/BL Good/Bad'],...
            [],FRProfileMeanStatC.pRSPercChange0to1VsBL(i),...
            ['Int_FRChangeMeanC' num2str(i) 'BL-0to1GoodBadTrBar'],...
            pathAnal,colorSel,[{'Good'} {'Bad'}]);
        
        x = FRProfileMeanGood.meanAvgFRProfileBaseline;
        x1 = FRProfileMeanBad.meanAvgFRProfileBaseline;
        y = FRProfileMeanGood.meanAvgFRProfileBefRun;
        y1 = FRProfileMeanBad.meanAvgFRProfileBefRun;
        barPlotWithStat3(1:2, [mean(y./x),mean(y1./x1)],...
            [std(y./x)/sqrt(length(x)),std(y1./x1)/sqrt(length(x1))],...
            y./x, y1./x1,['C' num2str(i) ' average mFR (Hz) change BefRun/BL  F/NoF'],...
            [],FRProfileMeanStatC.pRSPercChangeBefRunVsBL(i),...
            ['Int_FRChangeMeanC' num2str(i) 'BL-BefRunGoodBadTrBar'],...
            pathAnal,colorSel,[{'Good'} {'Bad'}]);
 
        x = FRProfileMeanGood.meanAvgFRProfileBefRun;
        x1 = FRProfileMeanBad.meanAvgFRProfileBefRun;
        y = FRProfileMeanGood.meanAvgFRProfile0to1;
        y1 = FRProfileMeanBad.meanAvgFRProfile0to1;
        barPlotWithStat3(1:2, [mean(y./x),mean(y1./x1)],...
            [std(y./x)/sqrt(length(x)),std(y1./x1)/sqrt(length(x1))],...
            y./x, y1./x1,['C' num2str(i) ' average mFR (Hz) change 0to1s/BefRun Good/Bad'],...
            [],FRProfileMeanStatC.pRSPercChange0to1VsBefRun(i),...
            ['Int_FRChangeMeanC' num2str(i) 'BefRun-0to1GoodBadTrBar'],...
            pathAnal,colorSel,[{'Good'} {'Bad'}]);
    end