function plotCmpIntMeanSegProfileGoodBad(pathAnal,modInt1,FRProfileMeanGood,FRProfileMeanBad,FRProfileMeanStatC,colorSel)

    % compare the mean of each segment of avgFRProfile (good vs. bad)
    for i = 1:max(modInt1.idxC)   
        x = FRProfileMeanGood.meanAvgFRProfileBaseline(modInt1.idxCGood == i);
        y = FRProfileMeanBad.meanAvgFRProfileBaseline(modInt1.idxCBad == i);
        barPlotWithStat3(1:2, [mean(x),mean(y)],...
            [std(x)/sqrt(length(x)),std(y)/sqrt(length(y))],...
            x, y,['C' num2str(i) ' average mFR (Hz) BL Good/Bad'],...
            [],FRProfileMeanStatC.pRSBL(i),...
            ['Int_FRMeanC' num2str(i) 'BLGoodBadTrBar'],...
            pathAnal,colorSel,[{'Good'} {'Bad'}]);
        
        x = FRProfileMeanGood.meanAvgFRProfileBefRun(modInt1.idxCGood == i);
        y = FRProfileMeanBad.meanAvgFRProfileBefRun(modInt1.idxCBad == i);
        barPlotWithStat3(1:2, [mean(x),mean(y)],...
            [std(x)/sqrt(length(x)),std(y)/sqrt(length(y))],...
            x, y,['C' num2str(i) ' average mFR (Hz) BefRun Good/Bad'],...
            [],FRProfileMeanStatC.pRSBefRun(i),...
            ['Int_FRMeanC' num2str(i) 'BefRunGoodBadTrBar'],...
            pathAnal,colorSel,[{'Good'} {'Bad'}]);
        
        x = FRProfileMeanGood.meanAvgFRProfile0to1(modInt1.idxCGood == i);
        y = FRProfileMeanBad.meanAvgFRProfile0to1(modInt1.idxCBad == i);
        barPlotWithStat3(1:2, [mean(x),mean(y)],...
            [std(x)/sqrt(length(x)),std(y)/sqrt(length(y))],...
            x, y,['C' num2str(i) ' average mFR (Hz) 0to1s Good/Bad'],...
            [],FRProfileMeanStatC.pRS0to1(i),...
            ['Int_FRMeanC' num2str(i) '0to1sGoodBadTrBar'],...
            pathAnal,colorSel,[{'Good'} {'Bad'}]);   
    end