function plotIntInitFieldRecPerClu(pathAnal,modInt1NoCue,modInt1)
%% plotting the firing profile for field vs non-field recordings for each cluster

    ind = find(modInt1NoCue.timeStepRun == -1.5);
    
    % firing profile field vs. non-field
    for i = 1:max(modInt1.idxC)
        plotAvgFRProfile(modInt1NoCue.timeStepRun(ind:end),...
            modInt1.avgFRProfile(modInt1.idxC == i,ind:end),['C' num2str(i) ' FR (Hz)'],...
            ['Int_FRProfileSecC' num2str(i)],...
            pathAnal,[])
        
        indCurCField = modInt1.idxC == i & modInt1.nNeuWithField > 1;
        indCurCNoField = modInt1.idxC == i & modInt1.nNeuWithField < 1;
        plotAvgFRProfileCmp(modInt1NoCue.timeStepRun(ind:end),...
            modInt1.avgFRProfile(indCurCField,ind:end),...
            modInt1.avgFRProfile(indCurCNoField,ind:end),...
            ['C' num2str(i) ' FR (Hz) F vs. NoF'],...
            ['Int_FRProfileCFieldNoField' num2str(i)],...
            pathAnal,[],[])
        
        plotAvgFRProfileCmp(modInt1NoCue.timeStepRun(ind:end),...
            modInt1.avgFRProfileNorm(indCurCField,ind:end),...
            modInt1.avgFRProfileNorm(indCurCNoField,ind:end),...
            ['C' num2str(i) ' Norm FR (Hz) F vs. NoF'],...
            ['Int_FRProfileNormCFieldNoField' num2str(i)],...
            pathAnal,[],[])
    end
    
    % firing profile field vs. non-field after aligning to run onset
    for i = 1:max(modInt1.idxC)        
        indCurCField = modInt1.idxC == i & modInt1.nNeuWithFieldAligned > 1;
        indCurCNoField = modInt1.idxC == i & modInt1.nNeuWithFieldAligned < 1;
        plotAvgFRProfileCmp(modInt1NoCue.timeStepRun(ind:end),...
            modInt1.avgFRProfile(indCurCField,ind:end),...
            modInt1.avgFRProfile(indCurCNoField,ind:end),...
            ['C' num2str(i) ' FR (Hz) F vs. NoF'],...
            ['Int_FRProfileAlignedCFieldNoField' num2str(i)],...
            pathAnal,[],[])
        
        plotAvgFRProfileCmp(modInt1NoCue.timeStepRun(ind:end),...
            modInt1.avgFRProfileNorm(indCurCField,ind:end),...
            modInt1.avgFRProfileNorm(indCurCNoField,ind:end),...
            ['C' num2str(i) ' Norm FR (Hz) F vs. NoF'],...
            ['Int_FRProfileAlignedNormCFieldNoField' num2str(i)],...
            pathAnal,[],[])
    end