function plotIntIndProfilePerClu(pathAnal,modInt1NoCue,modInt1,autoCorrIntTag,FRProfileMean)

    ind = find(modInt1NoCue.timeStepRun == -1.5);

    % firing profile of individual neurons ordered
    for i = 1:max(modInt1.idxC)
        plotIndFRProfile(modInt1NoCue.timeStepRun(ind:end),...
            modInt1.avgFRProfileNorm(modInt1.idxC == i,ind:end),['C' num2str(i) ' FR (Hz)'],...
            ['Int_IndFRProfileNormCPeak' num2str(i)],...
            pathAnal,[],1,[],[]) % ordered based on peak time
        
%         plotIndFRProfile(modInt1NoCue.timeStepRun,...
%             avgFRProfileNorm(idxC == i,:),['C' num2str(i) ' FR (Hz)'],...
%             ['Int_IndFRProfileNormCFR0to1' num2str(i)],...
%             pathAnal,[],2,FRProfileMean.indFR0to1,[]) % ordered based on 0to1 mean
%         
%         plotIndFRProfile(modInt1NoCue.timeStepRun,...
%             avgFRProfileNorm(idxC == i,:),['C' num2str(i) ' FR (Hz)'],...
%             ['Int_IndFRProfileNormCFRBefRun' num2str(i)],...
%             pathAnal,[],3,FRProfileMean.indFRBefRun,[]) % ordered based on -1to0 mean
%         
        plotIndFRProfile(modInt1NoCue.timeStepRun,...
            modInt1.avgFRProfileNorm(modInt1.idxC == i,:),['C' num2str(i) ' FR (Hz)'],...
            ['Int_IndFRProfileNormCFR0to1VsBefRun' num2str(i)],...
            pathAnal,[],4,FRProfileMean.indFRBefRun,FRProfileMean.indFR0to1) % ordered based on -1to0 to 0to1 mean ratio
        
        idxTmp = find(autoCorrIntTag.idxC2 == i & autoCorrIntTag.cellType == 1);
        taskTag = autoCorrIntTag.task(idxTmp);
        recTag = autoCorrIntTag.indRec(idxTmp);
        neuTag = autoCorrIntTag.indNeu(idxTmp);
        idxTag = [];        
        for j = 1:length(idxTmp)
            idxTagTmp = find(modInt1.task == taskTag(j) & modInt1.indRec == recTag(j) &...
                modInt1.indNeu == neuTag(j));
            idxTag = [idxTag idxTagTmp];
        end
        disp(['No tagged PV neurons in C' num2str(i) ' is: ' num2str(length(idxTmp)) ...
            '; No tagged neurons included here is :' num2str(length(idxTag))]);
        plotIndFRProfile(modInt1NoCue.timeStepRun,...
            modInt1.avgFRProfileNorm(idxTag,:),['C' num2str(i) ' FR (Hz) Tagged PV'],...
            ['Int_IndFRProfileNormCFR0to1VsBefRunTagPV' num2str(i)],...
            pathAnal,[],4,FRProfileMean.indFRBefRun,FRProfileMean.indFR0to1) % tagged cells ordered based on -1to0 to 0to1 mean ratio
         
        idxTmp = find(autoCorrIntTag.idxC2 == i & autoCorrIntTag.cellType == 2);
        taskTag = autoCorrIntTag.task(idxTmp);
        recTag = autoCorrIntTag.indRec(idxTmp);
        neuTag = autoCorrIntTag.indNeu(idxTmp);
        idxTag = [];
        for j = 1:length(idxTmp)
            idxTagTmp = find(modInt1.task == taskTag(j) & modInt1.indRec == recTag(j) &...
                modInt1.indNeu == neuTag(j));
            idxTag = [idxTag idxTagTmp];
        end
        disp(['No tagged SST neurons in C' num2str(i) ' is: ' num2str(length(idxTmp)) ...
            '; No tagged neurons included here is :' num2str(length(idxTag))]);
        plotIndFRProfile(modInt1NoCue.timeStepRun,...
            modInt1.avgFRProfileNorm(idxTag,:),['C' num2str(i) ' FR (Hz)  Tagged SST'],...
            ['Int_IndFRProfileNormCFR0to1VsBefRunTagSST' num2str(i)],...
            pathAnal,[],4,FRProfileMean.indFRBefRun,FRProfileMean.indFR0to1) % tagged cells ordered based on -1to0 to 0to1 mean ratio
        
%         plotAvgFRProfile(modInt1NoCue.timeStepRun,...
%             avgFRProfile(idxC == i,:),['C' num2str(i) ' FR (Hz)'],...
%             ['Int_FRProfileC' num2str(i)],...
%             pathAnal,[])
        
    end