function plotCmpIntSegProfileField(pathAnal,modInt1,FRProfileMean,FRProfileMeanStatC,colorSel)

    % compare each segment of avgFRProfile (field vs. no field)
    for i = 1:max(modInt1.idxC) 
        indCurCField = modInt1.idxC == i & modInt1.nNeuWithField > 1;
        indCurCNoField = modInt1.idxC == i & modInt1.nNeuWithField < 1;
        FRBLArrF = modInt1.avgFRProfile(indCurCField,FRProfileMean.indFRBaseline);
        FRBLArrNoF = modInt1.avgFRProfile(indCurCNoField,FRProfileMean.indFRBaseline);
        FR0to1ArrF = modInt1.avgFRProfile(indCurCField,FRProfileMean.indFR0to1);
        FR0to1ArrNoF = modInt1.avgFRProfile(indCurCNoField,FRProfileMean.indFR0to1);
        plotBoxPlot((FR0to1ArrF(:)./FRBLArrF(:))',...
            (FR0to1ArrNoF(:)./FRBLArrNoF(:))',...
            ['C' num2str(i) ' average FR change 0-1s/BL F/NoF'],...
            ['Int_FRChangeC' num2str(i) '0to1-BLFieldNoFieldBox'],...
            pathAnal,[0 3],FRProfileMeanStatC.pRSPercChange0to1VsBLFieldVsNoField(i),...
            colorSel,[{'F'} {'NoF'}]);
        
        FRBefRunArrF = modInt1.avgFRProfile(indCurCField,FRProfileMean.indFRBefRun);
        FRBefRunArrNoF = modInt1.avgFRProfile(indCurCNoField,FRProfileMean.indFRBefRun);
        plotBoxPlot((FRBefRunArrF(:)./FRBLArrF(:))',...
            (FRBefRunArrNoF(:)./FRBLArrNoF(:))',...
            ['C' num2str(i) ' average FR change BefRun/BL F/NoF'],...
            ['Int_FRChangeC' num2str(i) 'BefRun-BLFieldNoFieldBox'],...
            pathAnal,[0 2],FRProfileMeanStatC.pRSPercChangeBefRunVsBLFieldVsNoField(i),...
            colorSel,[{'F'} {'NoF'}]);
        
        plotBoxPlot((FR0to1ArrF(:)./FRBefRunArrF(:))',...
            (FR0to1ArrNoF(:)./FRBefRunArrNoF(:))',...
            ['C' num2str(i) ' average FR change 0-1s/BefRun F/NoF'],...
            ['Int_FRChangeC' num2str(i) '0to1-BefRunFieldNoFieldBox'],...
            pathAnal,[0 3.5],FRProfileMeanStatC.pRSPercChange0to1VsBefRunFieldVsNoField(i),...
            colorSel,[{'F'} {'NoF'}]);

    end