function plotIntInitGoodBadTrPerClu(pathAnal,modInt1NoCue,modInt1,autoCorrIntTag)
%% plot the firing rate profile for good vs bad trials

    ind = find(modInt1NoCue.timeStepRun == -1.5);
    
    % firing profile good vs. bad trials
    for i = 1:max(modInt1.idxC)        
        plotAvgFRProfileCmp(modInt1NoCue.timeStepRun(ind:end),...
            modInt1.avgFRProfile(modInt1.idxC == i,ind:end),...
            modInt1.avgFRProfileBad(modInt1.idxCBad == i,ind:end),...
            ['C' num2str(i) ' FR (Hz) Good vs. Bad'],...
            ['Int_FRProfileCGoodVsBad' num2str(i)],...
            pathAnal,[],[])
        
        plotAvgFRProfileCmp(modInt1NoCue.timeStepRun(ind:end),...
            modInt1.avgFRProfileNorm(modInt1.idxC == i,ind:end),...
            modInt1.avgFRProfileNormBad(modInt1.idxCBad == i,ind:end),...
            ['C' num2str(i) ' Norm FR Good vs. Bad'],...
            ['Int_FRProfileNormCGoodVsBad' num2str(i)],...
            pathAnal,[],[])
    end
    
    % firing profile good vs. bad trials for tagged cells
    for i = 1:max(modInt1.idxC)        
        idxTmp = find(autoCorrIntTag.idxC2 == i & autoCorrIntTag.cellType == 1);
        taskTag = autoCorrIntTag.task(idxTmp);
        recTag = autoCorrIntTag.indRec(idxTmp);
        neuTag = autoCorrIntTag.indNeu(idxTmp);
        idxTag = [];        
        for j = 1:length(idxTmp)
            idxTagTmp = find(modInt1.task == taskTag(j) & modInt1.indRec == recTag(j) ...
                & modInt1.indNeu == neuTag(j));
            idxTag = [idxTag idxTagTmp];
        end
        idxTagBad = []; 
        for j = 1:length(idxTmp)
            idxTagTmp = find(modInt1.taskBad == taskTag(j) & modInt1.indRecBad == recTag(j)...
                & modInt1.indNeuBad == neuTag(j));
            idxTagBad = [idxTagBad idxTagTmp];
        end
        plotAvgFRProfileCmp(modInt1NoCue.timeStepRun(ind:end),...
            modInt1.avgFRProfile(idxTag,ind:end),...
            modInt1.avgFRProfileBad(idxTagBad,ind:end),...
            ['C' num2str(i) ' FR (Hz) Good vs. Bad Tagged PV'],...
            ['Int_FRProfileCGoodVsBadTaggedPV' num2str(i)],...
            pathAnal,[],[])
        
        plotAvgFRProfileCmp(modInt1NoCue.timeStepRun(ind:end),...
            modInt1.avgFRProfileNorm(idxTag,ind:end),modInt1.avgFRProfileNormBad(idxTagBad,ind:end),...
            ['C' num2str(i) ' Norm FR Good vs. Bad Tagged PV'],...
            ['Int_FRProfileNormCGoodVsBadTaggedPV' num2str(i)],...
            pathAnal,[],[])
        
        idxTmp = find(autoCorrIntTag.idxC2 == i & autoCorrIntTag.cellType == 2);
        taskTag = autoCorrIntTag.task(idxTmp);
        recTag = autoCorrIntTag.indRec(idxTmp);
        neuTag = autoCorrIntTag.indNeu(idxTmp);
        idxTag = [];        
        for j = 1:length(idxTmp)
            idxTagTmp = find(modInt1.task == taskTag(j) & modInt1.indRec == recTag(j) & ...
                modInt1.indNeu == neuTag(j));
            idxTag = [idxTag idxTagTmp];
        end
        idxTagBad = []; 
        for j = 1:length(idxTmp)
            idxTagTmp = find(modInt1.taskBad == taskTag(j) & modInt1.indRecBad == recTag(j) & ...
                modInt1.indNeuBad == neuTag(j));
            idxTagBad = [idxTagBad idxTagTmp];
        end
        plotAvgFRProfileCmp(modInt1NoCue.timeStepRun(ind:end),...
            modInt1.avgFRProfile(idxTag,ind:end),...
            modInt1.avgFRProfileBad(idxTagBad,ind:end),...
            ['C' num2str(i) ' FR (Hz) Good vs. Bad Tagged SST'],...
            ['Int_FRProfileCGoodVsBadTaggedSST' num2str(i)],...
            pathAnal,[],[])
        
        plotAvgFRProfileCmp(modInt1NoCue.timeStepRun(ind:end),...
            modInt1.avgFRProfileNorm(idxTag,ind:end),modInt1.avgFRProfileNormBad(idxTagBad,ind:end),...
            ['C' num2str(i) ' Norm FR Good vs. Bad Tagged SST'],...
            ['Int_FRProfileNormCGoodVsBadTaggedSST' num2str(i)],...
            pathAnal,[],[])
    end