function plotCmpIntSegProfileGoodBad(pathAnal,modInt1,FRProfileMean,FRProfileMeanStatCGoodBad,colorSel)

    % FR good vs bad trials
    for i = 1:max(modInt1.idxC) 
        FRBLArrG = modInt1.avgFRProfile(modInt1.idxC == i,FRProfileMean.indFRBaseline);
        FRBLArrB = modInt1.avgFRProfileBad(modInt1.idxCBad == i,FRProfileMean.indFRBaseline); 
        plotBoxPlot(FRBLArrG(:)',FRBLArrB(:)',...
            ['C' num2str(i) ' average FR BL Good/Bad'],...
            ['Int_FRC' num2str(i) 'BLGoodBadTrBox'],...
            pathAnal,[],FRProfileMeanStatCGoodBad.pRSBL(i),colorSel,[{'Good'} {'Bad'}]);
        
        FRBefRunArrG = modInt1.avgFRProfile(modInt1.idxC == i,FRProfileMean.indFRBefRun);
        FRBefRunArrB = modInt1.avgFRProfileBad(modInt1.idxCBad == i,FRProfileMean.indFRBefRun);
        plotBoxPlot(FRBefRunArrG(:)',FRBefRunArrB(:)',...
            ['C' num2str(i) ' average FR BefRun Good/Bad'],...
            ['Int_FRC' num2str(i) 'BefRunGoodBadTrdBox'],...
            pathAnal,[],FRProfileMeanStatCGoodBad.pRSBefRun(i),colorSel,[{'Good'} {'Bad'}]);
        
        FR0to1ArrG = modInt1.avgFRProfile(modInt1.idxC == i,FRProfileMean.indFR0to1);
        FR0to1ArrB = modInt1.avgFRProfileBad(modInt1.idxCBad == i,FRProfileMean.indFR0to1);
        plotBoxPlot(FR0to1ArrG(:)',FR0to1ArrB(:)',...
            ['C' num2str(i) ' average FR 0-1s Good/Bad'],...
            ['Int_FRC' num2str(i) '0to1GoodBadTrBox'],...
            pathAnal,[],FRProfileMeanStatCGoodBad.pRS0to1(i),colorSel,[{'Good'} {'Bad'}]);
    end