function plotCmpIntMeanSegProfile(pathAnal,modInt1,FRProfileMean,FRProfileMeanStatC,colorSel)

    % compare the mean of each segment of avgFRProfile
    for i = 1:max(modInt1.idxC)    
        x = FRProfileMean.meanAvgFRProfileBaseline(modInt1.idxC == i);
        y = FRProfileMean.meanAvgFRProfile0to1(modInt1.idxC == i);
        barPlotWithStat2(1:2, [mean(x),mean(y)],...
            [std(x)/sqrt(length(x)),std(y)/sqrt(length(y))],...
            [x y],['C' num2str(i) ' average FR (Hz) BL vs 0to1s'],...
            [],FRProfileMeanStatC.pRS0to1VsBL(i),['Int_FRMeanC' num2str(i) 'BL-0to1Box'],...
            pathAnal,colorSel,[{'baseline'} {'0to1s'}]);
        
        x = FRProfileMean.meanAvgFRProfileBaseline(modInt1.idxC == i);
        y = FRProfileMean.meanAvgFRProfileBefRun(modInt1.idxC == i);
        barPlotWithStat2(1:2, [mean(x),mean(y)],...
            [std(x)/sqrt(length(x)),std(y)/sqrt(length(y))],...
            [x y],['C' num2str(i) ' average FR (Hz) BL vs BefRun'],...
            [],FRProfileMeanStatC.pRSBefRunVsBL(i),['Int_FRMeanC' num2str(i) 'BL-BefRunBox'],...
            pathAnal,colorSel,[{'baseline'} {'BefRun'}]);
        
%         x = FRProfileMean.meanAvgFRProfileBaseline(modInt1.idxC == i);
%         y = FRProfileMean.meanAvgFRProfile1to5(modInt1.idxC == i);
%         barPlotWithStat2(1:2, [mean(x),mean(y)],...
%             [std(x)/sqrt(length(x)),std(y)/sqrt(length(y))],...
%             [x y],['C' num2str(i) ' average FR (Hz) BL vs 1to5s'],...
%             [],FRProfileMeanStatC.pRS1to5VsBL(i),['Int_FRMeanC' num2str(i) 'BL-1to5Box'],...
%             pathAnal,colorSel,[{'baseline'} {'1to5s'}]);
%         
%         x = FRProfileMean.meanAvgFRProfileBefRun(modInt1.idxC == i);
%         y = FRProfileMean.meanAvgFRProfile1to5(modInt1.idxC == i);
%         barPlotWithStat2(1:2, [mean(x),mean(y)],...
%             [std(x)/sqrt(length(x)),std(y)/sqrt(length(y))],...
%             [x y],['C' num2str(i) ' average FR (Hz) BefRun vs 1to5s'],...
%             [],FRProfileMeanStatC.pRS1to5VsBefRun(i),['Int_FRMeanC' num2str(i) 'BefRun-1to5Box'],...
%             pathAnal,colorSel,[{'befRun'} {'1to5s'}]);
  
        x = FRProfileMean.meanAvgFRProfileBefRun(modInt1.idxC == i);
        y = FRProfileMean.meanAvgFRProfile0to1(modInt1.idxC == i);
        barPlotWithStat2(1:2, [mean(x),mean(y)],...
            [std(x)/sqrt(length(x)),std(y)/sqrt(length(y))],...
            [x y],['C' num2str(i) ' average FR (Hz) BefRun vs 0to1s'],...
            [],FRProfileMeanStatC.pRS0to1VsBefRun(i),['Int_FRMeanC' num2str(i) 'BefRun-0to1Box'],...
            pathAnal,colorSel,[{'befRun'} {'0to1s'}]);
       
%         x = FRProfileMean.meanAvgFRProfile0to1(modInt1.idxC == i);
%         y = FRProfileMean.meanAvgFRProfile1to5(modInt1.idxC == i);
%         barPlotWithStat2(1:2, [mean(x),mean(y)],...
%             [std(x)/sqrt(length(x)),std(y)/sqrt(length(y))],...
%             [x y],['C' num2str(i) ' average FR (Hz) 0to1s vs 1to5s'],...
%             [],FRProfileMeanStatC.pRS1to5Vs0to1(i),['Int_FRMeanC' num2str(i) '0to1-1to5Box'],...
%             pathAnal,colorSel,[{'0to1s'} {'1to5s'}]);      
    end