function plotCmpIntSegRatioProfileGoodBad(pathAnal,modInt1,FRProfileMean,FRProfileMeanStatCGoodBad,colorSel)

    % FR change good vs bad trials
    for i = 1:max(modInt1.idxC) 
        FRBLArrG = modInt1.avgFRProfile(modInt1.idxC == i,FRProfileMean.indFRBaseline);
        FRBLArrB = modInt1.avgFRProfileBad(modInt1.idxCBad == i,FRProfileMean.indFRBaseline); 
        FR0to1ArrG = modInt1.avgFRProfile(modInt1.idxC == i,FRProfileMean.indFR0to1);
        FR0to1ArrB = modInt1.avgFRProfileBad(modInt1.idxCBad == i,FRProfileMean.indFR0to1);
        plotBoxPlot(FR0to1ArrG(:)'./FRBLArrG(:)',...
            FR0to1ArrB(:)'./FRBLArrB(:)',...
            ['C' num2str(i) ' average FR change 0-1s/BL Good/Bad'],...
            ['Int_FRChangeC' num2str(i) '0to1-BLGoodBadTrBox'],...
            pathAnal,[0 3],FRProfileMeanStatCGoodBad.pRSPercChange0to1VsBL(i),...
            colorSel,[{'Good'} {'Bad'}]);
        
        FRBefRunArrG = modInt1.avgFRProfile(modInt1.idxC == i,FRProfileMean.indFRBefRun);
        FRBefRunArrB = modInt1.avgFRProfileBad(modInt1.idxCBad == i,FRProfileMean.indFRBefRun);
        plotBoxPlot(FRBefRunArrG(:)'./FRBLArrG(:)',...
            FRBefRunArrB(:)'./FRBLArrB(:)',...
            ['C' num2str(i) ' average FR change BefRun/BL Good/Bad'],...
            ['Int_FRChangeC' num2str(i) 'BefRun-BLGoodBadTrBox'],...
            pathAnal,[0 2],FRProfileMeanStatCGoodBad.pRSPercChangeBefRunVsBL(i),...
            colorSel,[{'Good'} {'Bad'}]);
        
        plotBoxPlot(FR0to1ArrG(:)'./FRBefRunArrG(:)',...
            FR0to1ArrB(:)'./FRBefRunArrB(:)',...
            ['C' num2str(i) ' average FR change 0-1s/BefRun Good/Bad'],...
            ['Int_FRChangeC' num2str(i) '0to1-BefRunGoodBadTrBox'],...
            pathAnal,[0 3.5],FRProfileMeanStatCGoodBad.pRSPercChange0to1VsBefRun(i),...
            colorSel,[{'Good'} {'Bad'}]);
    end